//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;
typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int32_t _isctype(uint32_t c, int32_t mask);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t deregister_tm_clones(void);
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args);
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags);
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags);
int64_t frame_dummy(void);
void function_1070(int64_t * d);
void function_1080(void);
int32_t function_1090(int32_t c, struct _IO_FILE * stream);
int64_t * function_10a0(int64_t delta);
void function_10b0(int32_t status);
int64_t function_271d(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2728(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2733(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_273e(void);
int64_t function_2745(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int32_t libmin_printf(char * fmt, ...);
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...);
int64_t libmin_strlen(char * str);
void libmin_success(void);
void libtarg_fail(int32_t code);
void libtarg_putc(char c);
char * libtarg_sbrk(int64_t inc);
void libtarg_success(void);
void lu_decomposition(float64_t (*A)[5], float64_t (*L)[5], float64_t (*U)[5]);
int64_t my_modf_isra_0(int64_t a1);
void print_matrix(char * name, float64_t (*mat)[5]);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = -0x102c00000e89; // 0x30a0
int64_t g2 = -0x117c00000fd9; // 0x31f0
int64_t g3 = -0x12cc00001129; // 0x3340
int32_t g4 = 0; // 0x400
int64_t g5 = 0x20002000200020; // 0x5022
struct _IO_FILE * g7 = NULL; // 0x5230
char g8 = 0; // 0x5238
int32_t g9;
int64_t * g6 = &g5; // 0x5228

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g9;
    }
    // 0x1016
    return result;
}

// Address range: 0x1070 - 0x107b
void function_1070(int64_t * d) {
    // 0x1070
    __cxa_finalize(d);
}

// Address range: 0x1080 - 0x108b
void function_1080(void) {
    // 0x1080
    __stack_chk_fail();
}

// Address range: 0x1090 - 0x109b
int32_t function_1090(int32_t c, struct _IO_FILE * stream) {
    // 0x1090
    return fputc(c, stream);
}

// Address range: 0x10a0 - 0x10ab
int64_t * function_10a0(int64_t delta) {
    // 0x10a0
    return sbrk(delta);
}

// Address range: 0x10b0 - 0x10bb
void function_10b0(int32_t status) {
    // 0x10b0
    exit(status);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/lu-decomp/lu-decomp.c
// Address range: 0x10c0 - 0x1270
// Line range:    41 - 68
int main() {
    int128_t v1 = __asm_movsd(-0x4010000000000000); // 0x10d5
    int128_t v2 = __asm_movsd(0x4000000000000000); // 0x10dd
    __readfsqword(40);
    int64_t v3 = __asm_movsd_1(v2); // bp-648, 0x110b
    __asm_movsd_1(v1);
    __asm_movsd_1(v1);
    __asm_movsd_1(v2);
    __asm_movsd_1(v1);
    __asm_movsd_1(v1);
    __asm_movsd_1(v2);
    __asm_movsd_1(v1);
    __asm_movsd_1(v1);
    __asm_movsd_1(v2);
    __asm_movsd_1(v1);
    __asm_movsd_1(v1);
    __asm_movsd_1(v2);
    int64_t v4; // bp-440, 0x10c0
    __asm_rep_stosq_memset((char *)&v4, 0, 25);
    int64_t v5; // bp-232, 0x10c0
    __asm_rep_stosq_memset((char *)&v5, 0, 25);
    lu_decomposition((float64_t (*)[5])&v3, (float64_t (*)[5])&v4, (float64_t (*)[5])&v5);
    print_matrix("A", (float64_t (*)[5])&v3);
    print_matrix("L", (float64_t (*)[5])&v4);
    print_matrix("U", (float64_t (*)[5])&v5);
    libmin_success();
    // UNREACHABLE
}

// Address range: 0x1270 - 0x1296
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1270
    int64_t v1; // 0x1270
    __libc_start_main(0x10c0, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x12a0 - 0x12c9
int64_t deregister_tm_clones(void) {
    // 0x12a0
    return (int64_t)&g7;
}

// Address range: 0x12d0 - 0x1309
int64_t register_tm_clones(void) {
    // 0x12d0
    return 0;
}

// Address range: 0x1310 - 0x1349
int64_t __do_global_dtors_aux(void) {
    // 0x1310
    if (g8 != 0) {
        // 0x1348
        int64_t result; // 0x1310
        return result;
    }
    // 0x131d
    if (*(int64_t *)0x4ff8 != 0) {
        // 0x132b
        __cxa_finalize((int64_t *)*(int64_t *)0x5008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1337
    g8 = 1;
    return result2;
}

// Address range: 0x1350 - 0x1359
int64_t frame_dummy(void) {
    // 0x1350
    return register_tm_clones();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/lu-decomp/lu-decomp.c
// Address range: 0x1360 - 0x13dc
// Line range:    6 - 14
void print_matrix(char * name, float64_t (*mat)[5]) {
    int64_t v1 = (int64_t)mat;
    libmin_printf("%s =\n", name);
    int64_t v2 = v1 + 40; // 0x1394
    int64_t v3 = v2 - 40;
    int64_t v4 = v3 + 8; // 0x13a9
    libmin_printf("%8.4f ", (float64_t)(int64_t)__asm_movsd(*(int64_t *)v3));
    while (v4 != v2) {
        // 0x139d
        v3 = v4;
        v4 = v3 + 8;
        libmin_printf("%8.4f ", (float64_t)(int64_t)__asm_movsd(*(int64_t *)v3));
    }
    // 0x13b7
    libmin_printf("\n");
    v2 = v3 + 48;
    while (v3 != v1 + 192) {
        // 0x1399
        v3 = v2 - 40;
        v4 = v3 + 8;
        libmin_printf("%8.4f ", (float64_t)(int64_t)__asm_movsd(*(int64_t *)v3));
        while (v4 != v2) {
            // 0x139d
            v3 = v4;
            v4 = v3 + 8;
            libmin_printf("%8.4f ", (float64_t)(int64_t)__asm_movsd(*(int64_t *)v3));
        }
        // 0x13b7
        libmin_printf("\n");
        v2 = v3 + 48;
    }
    // 0x13ca
    libmin_printf("\n");
}

// From module:   /home/jad/asm-to-asm/bringup-bench/lu-decomp/lu-decomp.c
// Address range: 0x13e0 - 0x1510
// Line range:    17 - 30
void lu_decomposition(float64_t (*A)[5], float64_t (*L)[5], float64_t (*U)[5]) {
    // 0x13e0
    int128_t v1; // 0x13e0
    int128_t v2 = v1;
    int64_t v3 = (int64_t)U;
    int64_t v4 = (int64_t)L;
    int64_t v5 = (int64_t)A;
    int128_t v6 = __asm_movsd(0x3ff0000000000000); // 0x13e6
    int128_t v7 = __asm_pxor(v2, v2); // 0x13f9
    int64_t v8 = 0; // 0x1410
    int64_t v9 = 0; // 0x1410
    int64_t v10 = 0;
    int64_t v11 = v9 + v4; // 0x1418
    int64_t v12 = 8 * v10;
    int128_t v13 = __asm_movapd(v7); // 0x143e
    int64_t v14; // 0x13e0
    int128_t v15; // 0x144a
    int64_t v16; // 0x1453
    int128_t v17; // 0x145b
    if (v10 != 0) {
        // 0x1440
        v17 = __asm_movapd(v7);
        v16 = 0;
        v14 = v12 + v3;
        v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
        v16++;
        v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
        v14 += 40;
        v13 = v17;
        while (v16 != v10) {
            // 0x144a
            v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
            v16++;
            v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
            v14 += 40;
            v13 = v17;
        }
    }
    int64_t v18 = v12 + v9;
    int128_t v19 = __asm_movsd(*(int64_t *)(v18 + v5)); // 0x1463
    *(int64_t *)(v18 + v3) = __asm_movsd_1(__asm_subsd(v19, v13));
    int64_t v20 = v12 + 8; // 0x147b
    while (v12 != 32) {
        // 0x1437
        v12 = v20;
        v13 = __asm_movapd(v7);
        if (v10 != 0) {
            // 0x1440
            v17 = __asm_movapd(v7);
            v16 = 0;
            v14 = v12 + v3;
            v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
            v16++;
            v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
            v14 += 40;
            v13 = v17;
            while (v16 != v10) {
                // 0x144a
                v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
                v16++;
                v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
                v14 += 40;
                v13 = v17;
            }
        }
        // 0x1463
        v18 = v12 + v9;
        v19 = __asm_movsd(*(int64_t *)(v18 + v5));
        *(int64_t *)(v18 + v3) = __asm_movsd_1(__asm_subsd(v19, v13));
        v20 = v12 + 8;
    }
    int64_t v21 = (int64_t)L; // 0x147d
    int64_t v22 = (int64_t)U;
    int64_t * v23 = (int64_t *)(v8 + v3);
    int64_t * v24 = (int64_t *)(v8 + v4);
    int64_t v25 = v8;
    int64_t v26; // 0x13e0
    int128_t v27; // 0x148a
    int128_t v28; // 0x14bd
    int128_t v29; // 0x149d
    int64_t v30; // 0x14a6
    int128_t v31; // 0x14ae
    int128_t v32; // 0x13e0
    // 0x1508
    *v24 = __asm_movsd_1(v6);
    int64_t v33 = v10 + 1; // 0x14cc
    int64_t v34 = v25 + 40; // 0x14d8
    int64_t v35 = v33 & 0xffffffff; // 0x14d8
    while ((int32_t)v33 != 5) {
        // 0x1485
        v25 = v34;
        if (v35 == v10) {
            // 0x1508
            *v24 = __asm_movsd_1(v6);
        } else {
            // 0x148a
            v27 = __asm_movapd(v7);
            v32 = v27;
            if (v10 != 0) {
                // 0x1492
                v31 = v27;
                v30 = 0;
                v26 = v22;
                v29 = __asm_movsd(*(int64_t *)(v25 + v21 + 8 * v30));
                v30++;
                v31 = __asm_addsd(v31, __asm_mulsd(v29, *(int64_t *)v26));
                v26 += 40;
                v32 = v31;
                while (v30 != v10) {
                    // 0x149d
                    v29 = __asm_movsd(*(int64_t *)(v25 + v21 + 8 * v30));
                    v30++;
                    v31 = __asm_addsd(v31, __asm_mulsd(v29, *(int64_t *)v26));
                    v26 += 40;
                    v32 = v31;
                }
            }
            // 0x14b6
            v28 = __asm_subsd(__asm_movsd(*(int64_t *)(v25 + v5)), v32);
            *(int64_t *)(v25 + v4) = __asm_movsd_1(__asm_divsd(v28, *v23));
        }
        // 0x14cc
        v33 = v35 + 1;
        v34 = v25 + 40;
        v35 = v33 & 0xffffffff;
    }
    int64_t v36 = v10 + 1; // 0x1430
    float64_t (*v37)[5] = (float64_t (*)[5])(v21 - 8); // 0x14f2
    float64_t (*v38)[5] = (float64_t (*)[5])(v22 + 8); // 0x14f2
    v8 += 48;
    v9 += 40;
    while (v36 != 5) {
        // 0x1415
        v10 = v36;
        v11 = v9 + v4;
        v12 = 8 * v10;
        v13 = __asm_movapd(v7);
        if (v10 != 0) {
            // 0x1440
            v17 = __asm_movapd(v7);
            v16 = 0;
            v14 = v12 + v3;
            v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
            v16++;
            v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
            v14 += 40;
            v13 = v17;
            while (v16 != v10) {
                // 0x144a
                v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
                v16++;
                v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
                v14 += 40;
                v13 = v17;
            }
        }
        // 0x1463
        v18 = v12 + v9;
        v19 = __asm_movsd(*(int64_t *)(v18 + v5));
        *(int64_t *)(v18 + v3) = __asm_movsd_1(__asm_subsd(v19, v13));
        v20 = v12 + 8;
        while (v12 != 32) {
            // 0x1437
            v12 = v20;
            v13 = __asm_movapd(v7);
            if (v10 != 0) {
                // 0x1440
                v17 = __asm_movapd(v7);
                v16 = 0;
                v14 = v12 + v3;
                v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
                v16++;
                v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
                v14 += 40;
                v13 = v17;
                while (v16 != v10) {
                    // 0x144a
                    v15 = __asm_movsd(*(int64_t *)(v11 + 8 * v16));
                    v16++;
                    v17 = __asm_addsd(v17, __asm_mulsd(v15, *(int64_t *)v14));
                    v14 += 40;
                    v13 = v17;
                }
            }
            // 0x1463
            v18 = v12 + v9;
            v19 = __asm_movsd(*(int64_t *)(v18 + v5));
            *(int64_t *)(v18 + v3) = __asm_movsd_1(__asm_subsd(v19, v13));
            v20 = v12 + 8;
        }
        // 0x147d
        v21 = (int64_t)v37;
        v22 = (int64_t)v38;
        v23 = (int64_t *)(v8 + v3);
        v24 = (int64_t *)(v8 + v4);
        v25 = v8;
        // 0x1508
        *v24 = __asm_movsd_1(v6);
        // 0x14cc
        v33 = v10 + 1;
        v34 = v25 + 40;
        v35 = v33 & 0xffffffff;
        while ((int32_t)v33 != 5) {
            // 0x1485
            v25 = v34;
            if (v35 == v10) {
                // 0x1508
                *v24 = __asm_movsd_1(v6);
            } else {
                // 0x148a
                v27 = __asm_movapd(v7);
                v32 = v27;
                if (v10 != 0) {
                    // 0x1492
                    v31 = v27;
                    v30 = 0;
                    v26 = v22;
                    v29 = __asm_movsd(*(int64_t *)(v25 + v21 + 8 * v30));
                    v30++;
                    v31 = __asm_addsd(v31, __asm_mulsd(v29, *(int64_t *)v26));
                    v26 += 40;
                    v32 = v31;
                    while (v30 != v10) {
                        // 0x149d
                        v29 = __asm_movsd(*(int64_t *)(v25 + v21 + 8 * v30));
                        v30++;
                        v31 = __asm_addsd(v31, __asm_mulsd(v29, *(int64_t *)v26));
                        v26 += 40;
                        v32 = v31;
                    }
                }
                // 0x14b6
                v28 = __asm_subsd(__asm_movsd(*(int64_t *)(v25 + v5)), v32);
                *(int64_t *)(v25 + v4) = __asm_movsd_1(__asm_divsd(v28, *v23));
            }
            // 0x14cc
            v33 = v35 + 1;
            v34 = v25 + 40;
            v35 = v33 & 0xffffffff;
        }
        // 0x14da
        v36 = v10 + 1;
        v37 = (float64_t (*)[5])(v21 - 8);
        v38 = (float64_t (*)[5])(v22 + 8);
        v8 += 48;
        v9 += 40;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1510 - 0x1521
// Line range:    124 - 127
void libtarg_success(void) {
    // 0x1510
    exit(0);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1530 - 0x153f
// Line range:    162 - 165
void libtarg_fail(int32_t code) {
    // 0x1530
    exit(code);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1540 - 0x1554
// Line range:    188 - 191
void libtarg_putc(char c) {
    // 0x1540
    fputc((int32_t)c, g7);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1560 - 0x1569
// Line range:    230 - 236
char * libtarg_sbrk(int64_t inc) {
    // 0x1560
    return (char *)sbrk(inc);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1570 - 0x17b8
// Line range:    426 - 483
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags) {
    int64_t v1 = flags; // 0x157f
    int64_t v2 = value; // 0x159f
    int64_t v3 = 0; // 0x159f
    int32_t v4 = 0; // 0x159f
    if ((flags & 64) == 0) {
        if (value < 0) {
            // 0x1780
            v2 = -value;
            v3 = 45;
            v4 = -1;
        } else {
            // 0x15aa
            v2 = value;
            v3 = 43;
            v4 = -1;
            if ((v1 & 2) == 0) {
                uint32_t v5 = 8 * flags & 32; // 0x17a3
                v2 = value;
                v3 = v5;
                v4 = v5 != 0;
            }
        }
    }
    int64_t v6 = (int64_t)currlen;
    int64_t v7 = (int64_t)buffer;
    uint32_t v8 = max > 0 ? max : 0; // 0x1597
    uint64_t v9 = (int64_t)base; // 0x15d2
    int64_t v10; // bp-89, 0x1570
    int64_t v11 = &v10; // 0x15d5
    int64_t v12 = (v1 & 32) == 0 ? (int64_t)"0123456789abcdef" : (int64_t)"0123456789ABCDEF"; // 0x15ed
    uint64_t v13 = v2; // 0x15f1
    int64_t v14 = 1;
    *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
    int32_t v15 = v14;
    int32_t v16 = v15 - 19; // 0x1618
    int64_t v17 = v14 + 1; // 0x1624
    while (v13 >= v9 == (v16 == 0 || v16 < 0 != (18 - v15 & v15) < 0)) {
        // 0x15f8
        v13 /= v9;
        v14 = v17;
        *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
        v15 = v14;
        v16 = v15 - 19;
        v17 = v14 + 1;
    }
    int64_t v18 = v15 == 20 ? 19 : v14 & 0xffffffff; // 0x1636
    int32_t v19 = v18; // 0x163a
    int32_t v20 = v8 - v19; // 0x163a
    int64_t v21 = 0x100000000 * v18 >> 32; // 0x1640
    int64_t v22; // bp-48, 0x1570
    int64_t v23 = (int64_t)&v22 - 40 + v21; // 0x1647
    *(char *)v23 = 0;
    uint32_t v24 = min - (int32_t)(v20 < 0 == (v20 & v19) < 0 ? (int64_t)v8 : v18) + v4; // 0x1653
    uint32_t v25 = v20 > 0 ? v20 : 0; // 0x1659
    int64_t v26 = v25; // 0x1659
    int64_t v27 = v24 >= 0 ? (int64_t)v24 : 0; // 0x1665
    int64_t v28; // 0x1570
    int64_t v29; // 0x1570
    int64_t v30; // 0x1570
    if ((v1 & 16) == 0) {
        if (flags % 2 != 0) {
            // 0x1760
            v29 = v6;
            v30 = -v27 & 0xffffffff;
            v28 = v26;
        } else {
            // 0x1724
            v29 = v6;
            v30 = v27;
            v28 = v26;
            if (v24 >= 1) {
                if (v6 < maxlen) {
                    // 0x1735
                    *(char *)(v6 + v7) = 32;
                }
                int64_t v31 = v6 + 1; // 0x173c
                *currlen = v31;
                uint32_t v32 = (int32_t)v27 - 1; // 0x1743
                int64_t v33 = v32; // 0x1746
                while (v32 != 0) {
                    int64_t v34 = v31;
                    int64_t v35 = v34; // 0x1733
                    if (v34 < maxlen) {
                        // 0x1735
                        *(char *)(v34 + v7) = 32;
                        v35 = v6;
                    }
                    // 0x173c
                    v31 = v35 + 1;
                    *currlen = v31;
                    v32 = (int32_t)v33 - 1;
                    v33 = v32;
                }
                int32_t v36 = v27; // 0x1748
                v29 = v31;
                v30 = v27 - (v36 >= 0 == (v36 != 0) ? v27 : 1) & 0xffffffff;
                v28 = v26;
            }
        }
    } else {
        int32_t v37 = v27; // 0x1676
        int32_t v38 = v25 - v37; // 0x1676
        v29 = v6;
        v30 = 0;
        v28 = v38 < 0 == (v38 & v37) < 0 ? v26 : v27;
    }
    int64_t v39 = v29; // 0x1682
    if (v3 != 0) {
        int64_t v40 = v29; // 0x1687
        if (v29 < maxlen) {
            // 0x1770
            *(char *)(v29 + v7) = (char)v3;
            v40 = v6;
        }
        // 0x168d
        v39 = v40 + 1;
        *currlen = v39;
    }
    int64_t v41 = v39; // 0x1697
    uint32_t v42 = v28; // 0x1697
    if ((int32_t)v28 != 0) {
        int64_t v43 = v39; // 0x1703
        if (v39 < maxlen) {
            // 0x1705
            *(char *)(v39 + v7) = 48;
            v43 = v6;
        }
        int64_t v44 = v43 + 1; // 0x170c
        *currlen = v44;
        v41 = v44;
        while (v42 != 0) {
            // 0x1700
            v42 = (int64_t)v42;
            int64_t v45 = v44;
            v43 = v45;
            if (v45 < maxlen) {
                // 0x1705
                *(char *)(v45 + v7) = 48;
                v43 = v6;
            }
            // 0x170c
            v44 = v43 + 1;
            *currlen = v44;
            v41 = v44;
        }
    }
    int64_t v46 = v23; // 0x16a8
    v46--;
    int64_t v47 = v41; // 0x16b3
    if (v41 < maxlen) {
        // 0x16b5
        *(char *)(v41 + v7) = *(char *)v46;
        v47 = v6;
    }
    int64_t v48 = v47 + 1; // 0x16c0
    *currlen = v48;
    while (v21 + v11 - (v18 + 0xffffffff & 0xffffffff) != v46) {
        int64_t v49 = v48;
        v46--;
        v47 = v49;
        if (v49 < maxlen) {
            // 0x16b5
            *(char *)(v49 + v7) = *(char *)v46;
            v47 = v6;
        }
        // 0x16c0
        v48 = v47 + 1;
        *currlen = v48;
    }
    // 0x16d0
    if (v30 == 0) {
        // 0x16f0
        return;
    }
    uint32_t v50 = v30; // 0x16d2
    int64_t v51 = v48; // 0x16db
    if (v48 < maxlen) {
        // 0x16dd
        *(char *)(v48 + v7) = 32;
        v51 = v6;
    }
    int64_t v52 = v51 + 1; // 0x16e4
    *currlen = v52;
    while (v50 != 0) {
        // 0x16d8
        v50 = (int64_t)v50;
        int64_t v53 = v52;
        v51 = v53;
        if (v53 < maxlen) {
            // 0x16dd
            *(char *)(v53 + v7) = 32;
            v51 = v6;
        }
        // 0x16e4
        v52 = v51 + 1;
        *currlen = v52;
    }
}

// Address range: 0x17c0 - 0x1873
int64_t my_modf_isra_0(int64_t a1) {
    // 0x17c0
    int128_t v1; // 0x17c0
    int128_t v2 = __asm_movapd(v1); // 0x17c1
    int128_t v3 = __asm_movsd(0x3ff0000000000000); // 0x17ce
    int128_t v4 = __asm_movsd(0x3fb999999999999a); // 0x17d6
    int128_t v5 = __asm_movsd(0x4024000000000000); // 0x17de
    int128_t v6 = __asm_movapd(v3); // 0x17e6
    int64_t v7; // bp-8, 0x17c0
    bool v8 = &v7 < (int64_t *)32; // 0x17ea
    int64_t result2 = 0;
    int128_t v9 = v6;
    int128_t v10; // 0x17c0
    int128_t v11 = v10;
    int128_t v12 = v2;
    int64_t v13 = __asm_cvttsd2si_4(v12); // 0x1800
    __asm_pxor(v11, v11);
    int128_t v14 = __asm_addsd(__asm_movapd(v12), v3); // 0x180d
    int128_t v15 = __asm_cvtsi2sd(v13); // 0x1811
    __asm_comisd(v14, v15);
    while (v8) {
        int64_t v16 = result2 + 1; // 0x17f4
        int64_t result = v16 & 0xffffffff; // 0x17f4
        uint32_t v17 = (int32_t)v16; // 0x17fb
        v8 = v17 < 100;
        int128_t v18 = __asm_mulsd_2(v12, v4); // 0x17fe
        int128_t v19 = __asm_mulsd_2(v9, v5); // 0x17fe
        if (v17 == 100) {
            // 0x1838
            *(int64_t *)a1 = 0;
            return result;
        }
        result2 = result;
        v9 = v19;
        v11 = v15;
        v12 = v18;
        v13 = __asm_cvttsd2si_4(v12);
        __asm_pxor(v11, v11);
        v14 = __asm_addsd(__asm_movapd(v12), v3);
        v15 = __asm_cvtsi2sd(v13);
        __asm_comisd(v14, v15);
    }
    // 0x181c
    __asm_comisd(v15, __asm_subsd(__asm_movapd(v12), v3));
    if (result2 == 0) {
        // 0x182e
        *(int64_t *)a1 = __asm_movsd_1(v15);
        return result2;
    }
    int128_t v20 = __asm_mulsd_2(v15, v9); // 0x1845
    __asm_subsd(v1, v20);
    int64_t v21 = __asm_movsd_1(v20); // 0x1852
    int64_t v22; // bp-16, 0x17c0
    int64_t result3 = my_modf_isra_0((int64_t)&v22); // 0x1858
    *(int64_t *)a1 = __asm_movsd_1(__asm_addsd_3(__asm_movsd(v21), v22));
    return result3;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1880 - 0x1e00
// Line range:    586 - 525
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags) {
    char iconvert[311]; // bp-704, 0x1880
    char v1[311]; // 0x1880
    char v2[311]; // 0x1de8
    char v3[311]; // 0x1d22
    char v4[311]; // 0x1983
    char v5[311]; // 0x1cfc
    // 0x1880
    int128_t v6; // 0x1880
    int128_t v7 = v6;
    int128_t v8 = v6;
    int128_t v9 = v6;
    int3_t v10; // 0x1880
    int3_t v11 = v10 - 1;
    float80_t v12; // 0x1880
    __frontend_reg_store_fpr(v11, v12);
    int32_t v13 = 6; // 0x18a5
    int64_t v14 = 6; // 0x18a5
    if (max >= 0) {
        int32_t v15 = max - 16; // 0x18b1
        v14 = v15 == 0 | v15 < 0 != (15 - max & max) < 0 ? (int64_t)max : 16;
        v13 = max;
    }
    uint64_t v16 = (int64_t)flags;
    int3_t v17 = v10 - 2; // 0x18b8
    __frontend_reg_store_fpr(v17, 0.0L);
    float80_t v18 = __frontend_reg_load_fpr(v17); // 0x18ba
    float80_t v19 = __frontend_reg_load_fpr(v11); // 0x18ba
    float80_t v20 = __frontend_reg_load_fpr(v11);
    int32_t v21; // 0x1880
    int32_t v22; // 0x1880
    float64_t v23; // bp-744, 0x1880
    int128_t v24; // 0x1880
    if (v18 > v19) {
        // 0x1d30
        __frontend_reg_store_fpr(v11, -v20);
        float64_t v25 = __frontend_reg_load_fpr(v11); // 0x1d3a
        v23 = v25;
        v22 = 45;
        v21 = 1;
        v24 = __asm_movsd((int64_t)v25);
    } else {
        float64_t v26 = v20; // 0x18c2
        v23 = v26;
        int128_t v27 = __asm_movsd((int64_t)v26); // 0x18c5
        v22 = 43;
        v21 = 1;
        v24 = v27;
        if ((v16 & 2) == 0) {
            int32_t v28 = 8 * flags & 32; // 0x18dd
            v22 = v28;
            v21 = v28 != 0;
            v24 = v27;
        }
    }
    // 0x18ee
    __asm_movapd(v24);
    float64_t fracpart; // bp-712, 0x1880
    int64_t v29 = &fracpart; // 0x18f8
    my_modf_isra_0(v29);
    bool v30; // 0x1880
    bool v31; // 0x1880
    int128_t v32; // 0x1880
    int128_t v33; // 0x1880
    int128_t v34; // 0x1880
    bool v35; // 0x1880
    bool v36; // 0x1880
    if (v13 == 0) {
        int128_t v37 = __asm_movsd((int64_t)fracpart); // 0x1d94
        int128_t v38 = __asm_subsd(v24, v37); // 0x1d9a
        int64_t v39 = __asm_cvttsd2si_4(v38); // 0x1d9f
        v23 = __asm_movsd_1(v38);
        __frontend_reg_store_fpr(v11, (float80_t)v39);
        __frontend_reg_store_fpr(v11, (float80_t)v23 - __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v17, 0.5L);
        float80_t v40 = __frontend_reg_load_fpr(v17); // 0x1dbc
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v40);
        float80_t v41 = __frontend_reg_load_fpr(v17); // 0x1dbe
        float80_t v42 = __frontend_reg_load_fpr(v11); // 0x1dbe
        bool v43 = false; // 0x1dbe
        bool v44 = false; // 0x1dbe
        bool v45 = false; // 0x1dbe
        if (v41 <= v42) {
            v43 = true;
            v44 = false;
            v45 = false;
            if (v41 >= v42) {
                v43 = v41 != v42;
                v44 = v41 != v42;
                v45 = true;
            }
        }
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
        bool v46 = true; // 0x1dc2
        bool v47 = v44; // 0x1dc2
        bool v48 = v45; // 0x1dc2
        int64_t v49 = v39; // 0x1dc2
        if (!v43) {
            // 0x1dc4
            v49 = v39 + 1;
            v46 = v39 == -1;
            v47 = llvm_ctpop_i8((char)v49) % 2 == 0;
            v48 = v49 == 0;
        }
        // 0x1dc8
        __asm_pxor(v7, v7);
        int128_t v50 = __asm_movsd(0x3ff0000000000000); // 0x1dcd
        int128_t v51 = __asm_cvtsi2sd(v49); // 0x1dd5
        v23 = __asm_movsd_1(v51);
        __asm_comisd(v51, v50);
        __frontend_reg_store_fpr(v11, (float80_t)v23);
        int64_t v52 = __asm_movsd_1(v51); // 0x1de8
        v2[0] = v52;
        iconvert = v2;
        if (v46) {
            // 0x19b0
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v47;
            v35 = v48;
            v32 = v37;
            v34 = v51;
            goto lab_0x19b8;
        } else {
            int128_t v53 = __asm_addsd(v37, v50); // 0x1df5
            __frontend_reg_store_fpr(v17, 1.0L);
            v31 = v47;
            v36 = v48;
            v33 = v53;
            goto lab_0x1ceb;
        }
    } else {
        // 0x1909
        __frontend_reg_store_fpr(v11, 1.0L);
        __frontend_reg_store_fpr(v17, 10.0L);
        int64_t v54 = v14 & 0xffffffff; // 0x1911
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
        uint32_t v55 = (int32_t)v54 - 1; // 0x191a
        int64_t v56 = v55; // 0x191d
        while (v55 != 0) {
            // 0x1918
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
            v55 = (int32_t)v56 - 1;
            v56 = v55;
        }
        float80_t v57 = __frontend_reg_load_fpr(v17); // 0x191f
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v57);
        int128_t v58 = __asm_movsd((int64_t)fracpart); // 0x1925
        v23 = __asm_movsd_1(__asm_subsd(v24, v58));
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) * (float80_t)v23);
        int3_t v59 = v10 - 3;
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        float80_t v60 = __frontend_reg_load_fpr(v59); // 0x194c
        v23 = v60;
        __frontend_reg_store_fpr(v59, v60);
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) - __frontend_reg_load_fpr(v59));
        __frontend_reg_store_fpr(v59, (float80_t)*(float32_t *)0x34ac);
        float80_t v61 = __frontend_reg_load_fpr(v59); // 0x195e
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v61);
        float80_t v62 = __frontend_reg_load_fpr(v59); // 0x1960
        float80_t v63 = __frontend_reg_load_fpr(v17); // 0x1960
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
        if (v62 < v63) {
            // 0x1d10
            __asm_pxor(v9, v9);
            int128_t v64 = __asm_cvtsi2sd((int64_t)v23); // 0x1d14
            int64_t v65 = __asm_movsd_1(v64); // 0x1d1a
            v23 = v65;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v65);
            int64_t v66 = __asm_movsd_1(v64); // 0x1d22
            v3[0] = v66;
            v1 = v3;
        } else {
            // 0x196a
            __asm_pxor(v9, v9);
            int128_t v67 = __asm_cvtsi2sd((int64_t)v23 + 1); // 0x1976
            int64_t v68 = __asm_movsd_1(v67); // 0x197b
            v23 = v68;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v68);
            int64_t v69 = __asm_movsd_1(v67); // 0x1983
            v4[0] = v69;
            v1 = v4;
        }
        // 0x1989
        iconvert = v1;
        __frontend_reg_store_fpr(v59, 1.0L);
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
        uint32_t v70 = (int32_t)v54 - 1; // 0x1992
        int64_t v71 = v70; // 0x1995
        while (v70 != 0) {
            // 0x1990
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            v70 = (int32_t)v71 - 1;
            v71 = v70;
        }
        float80_t v72 = __frontend_reg_load_fpr(v59); // 0x1997
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v72);
        float80_t v73 = __frontend_reg_load_fpr(v59); // 0x1999
        float80_t v74 = __frontend_reg_load_fpr(v17); // 0x1999
        bool v75 = false; // 0x1999
        bool v76 = false; // 0x1999
        bool v77 = false; // 0x1999
        if (v73 <= v74) {
            v75 = true;
            v76 = false;
            v77 = false;
            if (v73 >= v74) {
                v75 = v73 != v74;
                v76 = v73 != v74;
                v77 = true;
            }
        }
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v59));
        if (!v75) {
            int128_t v78 = __asm_addsd_3(v58, 0x3ff0000000000000); // 0x1cd0
            __frontend_reg_store_fpr(v59, 1.0L);
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            uint32_t v79 = (int32_t)v54 - 1; // 0x1ce2
            int64_t v80 = v79; // 0x1ce5
            while (v79 != 0) {
                // 0x1ce0
                __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
                v79 = (int32_t)v80 - 1;
                v80 = v79;
            }
            unsigned char v81 = llvm_ctpop_i8((char)v79); // 0x1ce2
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v59));
            float80_t v82 = __frontend_reg_load_fpr(v17); // 0x1ce9
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
            __frontend_reg_store_fpr(v11, v82);
            v31 = v81 % 2 == 0;
            v36 = true;
            v33 = v78;
            goto lab_0x1ceb;
        } else {
            // 0x19a3
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v76;
            v35 = v77;
            v32 = v58;
            v34 = __asm_movsd(*(int64_t *)&iconvert);
            goto lab_0x19b8;
        }
    }
  lab_0x19b8:;
    int64_t v83 = (int64_t)currlen;
    int64_t v84 = (int64_t)buffer;
    int64_t v85 = &v23; // 0x1890
    int64_t v86; // bp-697, 0x1880
    int64_t v87 = &v86; // 0x19bd
    int128_t v88 = __asm_pxor(v8, v8); // 0x19c2
    int128_t v89 = __asm_movsd(0x3fb999999999999a); // 0x19c7
    int128_t v90 = __asm_movsd(0x3fa999999999999a); // 0x19d0
    int128_t v91 = __asm_movsd(0x4024000000000000); // 0x19e0
    bool v92 = v30; // 0x19e9
    bool v93 = v35; // 0x19e9
    int64_t v94 = 1;
    int128_t v95 = __asm_movapd(__asm_mulsd_2(v32, v89)); // 0x1a0c
    my_modf_isra_0(v29);
    int128_t v96 = __asm_movsd((int64_t)fracpart); // 0x1a16
    int128_t v97 = __asm_subsd(v95, v96); // 0x1a1c
    __asm_ucomisd(v96, v88);
    int32_t v98 = __asm_cvttsd2si(__asm_mulsd_2(__asm_addsd(v97, v90), v91)); // 0x1a30
    char v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef"); // 0x1a37
    *(char *)(v94 + v87) = v99;
    bool v100; // 0x1880
    int64_t v101; // 0x1880
    bool v102; // 0x1880
    while (v92 || !v93) {
        int64_t v103 = v94 - 311; // 0x19f4
        unsigned char v104 = llvm_ctpop_i8((char)v103); // 0x19f4
        v92 = v104 % 2 == 0;
        v93 = false;
        v100 = v104 % 2 == 0;
        v102 = true;
        v101 = 310;
        if (v103 == 0) {
            goto lab_0x1a53;
        }
        v94++;
        v95 = __asm_movapd(__asm_mulsd_2(v96, v89));
        my_modf_isra_0(v29);
        v96 = __asm_movsd((int64_t)fracpart);
        v97 = __asm_subsd(v95, v96);
        __asm_ucomisd(v96, v88);
        v98 = __asm_cvttsd2si(__asm_mulsd_2(__asm_addsd(v97, v90), v91));
        v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef");
        *(char *)(v94 + v87) = v99;
    }
    int32_t v105 = (int32_t)v94 - 311; // 0x1a44
    v100 = llvm_ctpop_i8((char)v105) % 2 == 0;
    v102 = v105 == 0;
    v101 = v105 == 0 ? 310 : v94 & 0xffffffff;
  lab_0x1a53:
    // 0x1a53
    __asm_ucomisd(v34, v88);
    int64_t v106 = 0x100000000 * v101 >> 32; // 0x1a58
    v23 = v106;
    int64_t v107 = v85 + 48; // 0x1a5f
    *(char *)(v106 + v107) = 0;
    int64_t v108 = v14; // 0x1a64
    int64_t v109 = 0; // 0x1a64
    if (v100 || !v102) {
        bool v110 = v100; // 0x1a7e
        bool v111 = v102; // 0x1a7e
        int64_t v112 = 1;
        int128_t v113 = __asm_mulsd_2(v34, v89); // 0x1a91
        __asm_movapd(v113);
        int128_t v114 = __asm_movapd(v113); // 0x1a9e
        my_modf_isra_0((int64_t)&iconvert);
        int128_t v115 = __asm_movsd(*(int64_t *)&iconvert); // 0x1aa8
        int128_t v116 = __asm_subsd(v114, v115); // 0x1ab1
        __asm_ucomisd(v115, v88);
        int32_t v117 = __asm_cvttsd2si(__asm_mulsd_2(__asm_addsd(v116, v90), v91)); // 0x1ac5
        char v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef"); // 0x1acc
        int64_t v119; // bp-377, 0x1880
        *(char *)(v112 + (int64_t)&v119) = v118;
        while (v110 || !v111) {
            int64_t v120 = v112 - 311; // 0x1a84
            v110 = llvm_ctpop_i8((char)v120) % 2 == 0;
            v111 = false;
            if (v120 == 0) {
                goto lab_0x1d78;
            }
            v112++;
            v113 = __asm_mulsd_2(v115, v89);
            __asm_movapd(v113);
            v114 = __asm_movapd(v113);
            my_modf_isra_0((int64_t)&iconvert);
            v115 = __asm_movsd(*(int64_t *)&iconvert);
            v116 = __asm_subsd(v114, v115);
            __asm_ucomisd(v115, v88);
            v117 = __asm_cvttsd2si(__asm_mulsd_2(__asm_addsd(v116, v90), v91));
            v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef");
            *(char *)(v112 + (int64_t)&v119) = v118;
        }
        if ((int32_t)v112 == 311) {
          lab_0x1d78:
            // 0x1d78
            v108 = v14 + 0xfffffeca;
            v109 = 310;
        } else {
            // 0x1ae5
            v108 = v14 - v112;
            v109 = v112 & 0xffffffff;
        }
    }
    int64_t v121 = (0x100000000 * v109 >> 32) + v85;
    int64_t v122 = v121 + 368; // 0x1af5
    *(char *)v122 = 0;
    int32_t v123 = -1 - (int32_t)v14 + (int32_t)(float32_t)(float64_t)(int64_t)min - v21 - (int32_t)v101; // 0x1b0d
    int64_t v124 = v123 >= 0 ? (int64_t)v123 : 0; // 0x1b12
    int64_t v125; // 0x1880
    int64_t v126; // 0x1880
    int64_t v127; // 0x1880
    int64_t v128; // 0x1880
    int64_t v129; // 0x1880
    int64_t v130; // 0x1880
    if (v16 % 2 == 0) {
        if ((v16 & 16) == 0) {
            // 0x1c90
            v129 = v83;
            v125 = v124;
            if (v123 >= 1) {
                if (v83 < maxlen) {
                    // 0x1ca5
                    *(char *)(v83 + v84) = 32;
                }
                int64_t v131 = v83 + 1; // 0x1cac
                *currlen = v131;
                uint32_t v132 = (int32_t)v124 - 1; // 0x1cb3
                int64_t v133 = v132; // 0x1cb7
                while (v132 != 0) {
                    int64_t v134 = v131;
                    int64_t v135 = v134; // 0x1ca3
                    if (v134 < maxlen) {
                        // 0x1ca5
                        *(char *)(v134 + v84) = 32;
                        v135 = v83;
                    }
                    // 0x1cac
                    v131 = v135 + 1;
                    *currlen = v131;
                    v132 = (int32_t)v133 - 1;
                    v133 = v132;
                }
                int32_t v136 = v124; // 0x1cb9
                v129 = v131;
                v125 = v124 - (v136 >= 0 == (v136 != 0) ? v124 : 1) & 0xffffffff;
            }
            goto lab_0x1b23;
        } else {
            // 0x1c4e
            v129 = v83;
            v125 = v124;
            if (v123 < 1) {
                goto lab_0x1b23;
            } else {
                // 0x1c57
                v130 = v83;
                v126 = v124;
                if (v22 != 0) {
                    // 0x1d61
                    v128 = v83;
                    v127 = v124;
                    if (v83 < maxlen) {
                        // 0x1d6a
                        *(char *)(v83 + v84) = (char)v22;
                        v128 = v83;
                        v127 = v124;
                    }
                    goto lab_0x1c74;
                } else {
                    goto lab_0x1c68;
                }
            }
        }
    } else {
        // 0x1b20
        v129 = v83;
        v125 = -v124 & 0xffffffff;
        goto lab_0x1b23;
    }
  lab_0x1ceb:
    // 0x1ceb
    __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) - __frontend_reg_load_fpr(v17));
    fracpart = __asm_movsd_1(v33);
    float64_t v137 = __frontend_reg_load_fpr(v11); // 0x1cf3
    v23 = v137;
    int128_t v138 = __asm_movsd((int64_t)v137); // 0x1cf6
    int64_t v139 = __asm_movsd_1(v138); // 0x1cfc
    v5[0] = v139;
    iconvert = v5;
    v30 = v31;
    v35 = v36;
    v32 = v33;
    v34 = v138;
    goto lab_0x19b8;
  lab_0x1b23:;
    int64_t v140 = v129; // 0x1b29
    int64_t v141 = v125; // 0x1b29
    if (v22 != 0) {
        int64_t v142 = v129; // 0x1b2e
        if (v129 < maxlen) {
            // 0x1b30
            *(char *)(v129 + v84) = (char)v22;
            v142 = v83;
        }
        int64_t v143 = v142 + 1; // 0x1b36
        *currlen = v143;
        v140 = v143;
        v141 = v125;
    }
    goto lab_0x1b3d;
  lab_0x1b3d:;
    int64_t v144 = v107 + (int64_t)v23 - 1;
    int64_t v145; // 0x1880
    if (v140 < maxlen) {
        // 0x1b55
        *(char *)(v145 + v84) = *(char *)v144;
    }
    int64_t v146 = v140 + 1; // 0x1b60
    *currlen = v146;
    int64_t v147 = v146; // 0x1b6e
    int64_t v148 = v144; // 0x1b6e
    while (v87 - (v101 + 0xffffffff & 0xffffffff) + (int64_t)v23 != v144) {
        // 0x1b50
        v144 = v148 - 1;
        if (v147 < maxlen) {
            // 0x1b55
            *(char *)(v145 + v84) = *(char *)v144;
        }
        // 0x1b60
        v146 = v147 + 1;
        *currlen = v146;
        v147 = v146;
        v148 = v144;
    }
    if (v13 != 0) {
        int64_t v149 = v146; // 0x1b78
        if (v146 < maxlen) {
            // 0x1b7a
            *(char *)(v146 + v84) = 46;
            v149 = v83;
        }
        int64_t v150 = v149 + 1; // 0x1b81
        *currlen = v150;
        int64_t v151 = v150; // 0x1b8a
        if ((int32_t)v108 >= 1) {
            int64_t v152 = v151;
            int64_t v153 = v152; // 0x1b93
            if (v152 < maxlen) {
                // 0x1b95
                *(char *)(v152 + v84) = 48;
                v153 = v83;
            }
            int64_t v154 = v153 + 1; // 0x1b9c
            *currlen = v154;
            uint32_t v155 = (int32_t)(v108 & 0xffffffff) - 1; // 0x1ba3
            int64_t v156 = v155; // 0x1ba6
            while (v155 != 0) {
                // 0x1b90
                v152 = v154;
                v153 = v152;
                if (v152 < maxlen) {
                    // 0x1b95
                    *(char *)(v152 + v84) = 48;
                    v153 = v83;
                }
                // 0x1b9c
                v154 = v153 + 1;
                *currlen = v154;
                v155 = (int32_t)v156 - 1;
                v156 = v155;
            }
        }
        if (v109 != 0) {
            int64_t v157 = v122 - 1;
            if (v83 < maxlen) {
                // 0x1bcd
                *(char *)(v83 + v84) = *(char *)v157;
            }
            int64_t v158 = v83 + 1; // 0x1bd8
            *currlen = v158;
            int64_t v159 = v157; // 0x1be6
            while (367 - (v109 + 0xffffffff & 0xffffffff) + v121 != v157) {
                int64_t v160 = v158;
                v157 = v159 - 1;
                int64_t v161 = v160; // 0x1bcb
                if (v160 < maxlen) {
                    // 0x1bcd
                    *(char *)(v160 + v84) = *(char *)v157;
                    v161 = v83;
                }
                // 0x1bd8
                v158 = v161 + 1;
                *currlen = v158;
                v159 = v157;
            }
        }
    }
    // 0x1be8
    if ((int32_t)v141 == 0) {
        // 0x1c09
        return;
    }
    if (v83 < maxlen) {
        // 0x1bf5
        *(char *)(v83 + v84) = 32;
    }
    int64_t v162 = v83 + 1; // 0x1bfc
    *currlen = v162;
    uint32_t v163 = (int32_t)v141 + 1; // 0x1c03
    int64_t v164 = v163; // 0x1c07
    while (v163 != 0) {
        int64_t v165 = v162;
        int64_t v166 = v165; // 0x1bf3
        if (v165 < maxlen) {
            // 0x1bf5
            *(char *)(v165 + v84) = 32;
            v166 = v83;
        }
        // 0x1bfc
        v162 = v166 + 1;
        *currlen = v162;
        v163 = (int32_t)v164 + 1;
        v164 = v163;
    }
  lab_0x1c68:;
    int64_t v167 = v126;
    int64_t v168 = v130;
    v128 = v168;
    v127 = v167;
    if (v168 < maxlen) {
        // 0x1c6d
        *(char *)(v168 + v84) = 48;
        v128 = v83;
        v127 = v167;
    }
    goto lab_0x1c74;
  lab_0x1c74:;
    int64_t v169 = v128 + 1; // 0x1c74
    *currlen = v169;
    uint32_t v170 = (int32_t)v127 - 1; // 0x1c7b
    int64_t v171 = v170; // 0x1c7b
    v140 = v169;
    v141 = v171;
    v130 = v169;
    v126 = v171;
    if (v170 != 0) {
        goto lab_0x1c68;
    } else {
        goto lab_0x1b3d;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1e00 - 0x271d
// Line range:    130 - 290
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args) {
    // 0x1e00
    int64_t v1; // 0x1e00
    uint64_t v2 = v1;
    int64_t v3 = (int64_t)buffer;
    int64_t v4 = (int64_t)format + 1; // 0x1e13
    int64_t v5 = v4; // 0x1e13
    int64_t result2 = 0; // 0x1e29
    int64_t v6; // 0x1e00
    int64_t v7; // 0x1e00
    int64_t v8; // 0x1e00
    int64_t v9; // 0x1e00
    char v10; // 0x1e00
    int64_t v11; // 0x1e00
    int64_t v12; // 0x1e00
    if ((char)v2 != 0) {
        int64_t v13 = (int64_t)args;
        int64_t * v14 = (int64_t *)(v13 + 8);
        v6 = v4;
        v7 = v2 % 256;
        v12 = 0;
        while (true) {
          lab_0x1e7e:;
            char v15 = v7; // 0x1e85
            int64_t v16 = v6; // 0x1e88
            char v17 = v15; // 0x1e88
            int64_t v18 = v12; // 0x1e88
            int64_t v19 = v6; // 0x1e88
            int64_t v20 = v12; // 0x1e88
            if (v15 != 37) {
                while (true) {
                  lab_0x1e8a:;
                    uint64_t v21 = v18;
                    int64_t v22 = v16; // 0x1e8d
                    if (v21 < maxlen) {
                        // 0x1e8f
                        *(char *)(v21 + v3) = v17;
                        v22 = v5;
                    }
                    char v23 = *(char *)v22; // 0x1e93
                    int64_t v24 = v22 + 1; // 0x1e96
                    v5 = v24;
                    int64_t v25 = v21 + 1; // 0x1e9a
                    result2 = v25;
                    v16 = v24;
                    v17 = v23;
                    v18 = v25;
                    v19 = v24;
                    v20 = v25;
                    switch (v23) {
                        case 0: {
                            goto lab_0x1e30_3;
                        }
                        case 37: {
                            goto lab_0x1ea9;
                        }
                        default: {
                            goto lab_0x1e8a;
                        }
                    }
                }
            }
          lab_0x1ea9:
            // 0x1ea9
            v11 = v20;
            unsigned char v26 = *(char *)v19; // 0x1eb3
            result2 = v11;
            if (v26 == 0) {
                // break -> 0x1e30
                break;
            }
            int64_t v27 = v26; // 0x1eb3
            int64_t result = v27; // 0x1ecb
            if (v26 < 49) {
                // 0x1e43
                return result;
            }
            int64_t v28 = v19 + 1; // 0x1ebe
            int64_t v29 = (int64_t)g6; // 0x1eda
            v5 = 0;
            int64_t v30 = v27; // 0x1eea
            int64_t v31 = v28; // 0x1eea
            int32_t v32 = 0; // 0x1eea
            int64_t v33 = v27; // 0x1eea
            int64_t v34 = v28; // 0x1eea
            if ((*(char *)(2 * v27 + v29) & 4) != 0) {
                int64_t v35 = 0xffffffd0 + (0x100000000000000 * v30 >> 56); // 0x1ef6
                int64_t v36 = v35 & 0xffffffff; // 0x1ef6
                v5 = v36;
                unsigned char v37 = *(char *)v31; // 0x1efa
                result2 = v11;
                if (v37 == 0) {
                    // break (via goto) -> 0x1e30
                    goto lab_0x1e30_3;
                }
                int64_t v38 = v31 + 1; // 0x1ef2
                int64_t v39 = v37; // 0x1efa
                v31 = v38;
                while ((*(char *)(2 * v39 + v29) & 4) != 0) {
                    // 0x1eec
                    v35 = 10 * v36 + 0xffffffd0 + (0x100000000000000 * v39 >> 56);
                    v36 = v35 & 0xffffffff;
                    v5 = v36;
                    v37 = *(char *)v31;
                    result2 = v11;
                    if (v37 == 0) {
                        // break (via goto) -> 0x1e30
                        goto lab_0x1e30_3;
                    }
                    // 0x1f06
                    v38 = v31 + 1;
                    v39 = v37;
                    v31 = v38;
                }
                // 0x1f12
                v32 = v35;
                v33 = v39;
                v34 = v38;
            }
            int64_t v40 = v34;
            int64_t v41 = v33; // 0x1f14
            int64_t v42 = v40; // 0x1f14
            if (v33 == 42) {
                uint32_t v43 = v32; // 0x2448
                if (v43 < 48) {
                    // 0x244f
                    v5 = *(int64_t *)(v13 + 16) + (int64_t)v43;
                    *args = v43 + 8;
                } else {
                    int64_t v44 = *v14; // 0x24a3
                    v5 = v44;
                    *v14 = v44 + 8;
                }
                unsigned char v45 = *(char *)v40; // 0x245a
                result2 = v11;
                if (v45 == 0) {
                    // break -> 0x1e30
                    break;
                }
                // 0x246c
                v41 = v45;
                v42 = v40 + 1;
            }
            int64_t v46 = v42;
            int64_t v47 = v41; // 0x1f22
            int64_t v48 = v46; // 0x1f22
            if ((char)v41 == 46) {
                char v49 = *(char *)v46; // 0x1fd8
                result2 = v11;
                if (v49 == 0) {
                    // break -> 0x1e30
                    break;
                }
                int64_t v50 = v46;
                unsigned char v51 = v49;
                int64_t v52 = v50 + 1;
                int64_t v53 = v51;
                while ((*(char *)(2 * v53 + v29) & 4) != 0) {
                    char v54 = *(char *)v52; // 0x200c
                    result2 = v11;
                    if (v54 == 0) {
                        // break (via goto) -> 0x1e30
                        goto lab_0x1e30_3;
                    }
                    v50 = v52;
                    v51 = v54;
                    v52 = v50 + 1;
                    v53 = v51;
                }
                // 0x2390
                v47 = v53;
                v48 = v52;
                if (v51 == 42) {
                    uint32_t v55 = *(int32_t *)&v5; // 0x2398
                    if (v55 < 48) {
                        // 0x23a3
                        *args = v55 + 8;
                    } else {
                        // 0x2474
                        *v14 = *v14 + 8;
                    }
                    unsigned char v56 = *(char *)v52; // 0x23ae
                    result2 = v11;
                    if (v56 == 0) {
                        // break -> 0x1e30
                        break;
                    }
                    // 0x23c1
                    v47 = v56;
                    v48 = v50 + 2;
                }
            }
            int64_t v57 = v48;
            int64_t v58 = v47;
            switch ((char)v58) {
                case 104: {
                    char v59 = *(char *)v57; // 0x242e
                    v10 = v59;
                    v9 = v57 + 1;
                    if (v59 == 0) {
                        // break -> 0x1e30
                        break;
                    }
                    goto lab_0x23e6;
                }
                case 108: {
                    char v60 = *(char *)v57; // 0x23c9
                    int64_t v61 = v57 + 1;
                    result2 = v11;
                    v10 = v60;
                    v9 = v61;
                    switch (v60) {
                        case 108: {
                            char v62 = *(char *)v61; // 0x2485
                            v10 = v62;
                            v9 = v57 + 2;
                            if (v62 == 0) {
                                // break -> 0x1e30
                                break;
                            }
                            goto lab_0x23e6;
                        }
                        case 0: {
                            goto lab_0x1e30_3;
                        }
                        default: {
                            goto lab_0x23e6;
                        }
                    }
                }
                case 76: {
                    unsigned char v63 = *(char *)v57; // 0x23ff
                    if (v63 == 0) {
                        // break -> 0x1e30
                        break;
                    }
                    int64_t v64 = (int64_t)v63 + 0xffffffdb; // 0x240b
                    v8 = v57 + 1;
                    if ((char)v64 < 84) {
                        int32_t v65 = *(int32_t *)((4 * v64 & 1020) + (int64_t)&g3); // 0x2424
                        return (int64_t)v65 + (int64_t)&g3;
                    }
                    goto lab_0x2073;
                }
                default: {
                    // 0x1f40
                    v8 = v57;
                    if ((char)(v58 + 0xffffffdb) < 84) {
                        // 0x1f4b
                        int64_t v66; // 0x1f40
                        int32_t v67 = *(int32_t *)((4 * v66 & 1020) + (int64_t)&g1); // 0x1f55
                        return (int64_t)v67 + (int64_t)&g1;
                    }
                    goto lab_0x2073;
                }
            }
        }
    }
  lab_0x1e30_3:
    // 0x1e30
    if (maxlen == 0) {
        // 0x1e43
        return result2;
    }
    uint64_t v68 = maxlen - 1;
    if (v68 > result2) {
        // 0x1e3e
        *(char *)(result2 + v3) = 0;
        // 0x1e43
        return result2;
    }
    // 0x1e58
    *(char *)(v68 + v3) = 0;
    return result2;
  lab_0x2073:;
    unsigned char v69 = *(char *)v8; // 0x2073
    int64_t v70 = v8 + 1; // 0x2077
    v5 = v70;
    result2 = v11;
    v6 = v70;
    v7 = v69;
    v12 = v11;
    if (v69 == 0) {
        // break -> 0x1e30
        goto lab_0x1e30_3;
    }
    goto lab_0x1e7e;
  lab_0x23e6:;
    int64_t v71 = (int64_t)v10 + 0xffffffdb; // 0x23e6
    v8 = v9;
    if ((char)v71 < 84) {
        int32_t v72 = *(int32_t *)((4 * v71 & 1020) + (int64_t)&g2); // 0x23f4
        return (int64_t)v72 + (int64_t)&g2;
    }
    goto lab_0x2073;
}

// Address range: 0x271d - 0x2728
int64_t function_271d(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x271d
    int64_t v1; // 0x271d
    return v1 & 0xffffffff;
}

// Address range: 0x2728 - 0x2733
int64_t function_2728(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2728
    int64_t v1; // 0x2728
    return v1 & 0xffffffff;
}

// Address range: 0x2733 - 0x273e
int64_t function_2733(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2733
    int64_t v1; // 0x2733
    return v1 & 0xffffffff;
}

// Address range: 0x273e - 0x2745
int64_t function_273e(void) {
    // 0x273e
    int64_t v1; // 0x273e
    return v1 & 0xffffffff;
}

// Address range: 0x2745 - 0x2750
int64_t function_2745(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2745
    int64_t v1; // 0x2745
    return v1 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2750 - 0x285c
// Line range:    751 - 769
int32_t libmin_printf(char * fmt, ...) {
    // 0x2750
    int64_t v1; // 0x2750
    if ((char)v1 != 0) {
        // 0x278c
        int128_t v2; // 0x2750
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 8; // bp-1248, 0x27f6
    char v4; // bp-1224, 0x2750
    dopr(&v4, (int64_t)&g4, fmt, (int32_t *)&v3);
    if (v4 == 0) {
        // 0x2850
        return 0;
    }
    int64_t v5 = &v4;
    libtarg_putc(v4);
    int64_t v6 = v5 + 1; // 0x2839
    char v7 = *(char *)v6; // 0x2839
    while (v7 != 0) {
        // 0x2830
        v5 = v6;
        libtarg_putc(v7);
        v6 = v5 + 1;
        v7 = *(char *)v6;
    }
    // 0x2846
    int64_t v8; // bp+1225, 0x2750
    return v5 + (int64_t)&v8;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2860 - 0x290b
// Line range:    772 - 782
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...) {
    // 0x2860
    int64_t v1; // 0x2860
    if ((char)v1 != 0) {
        // 0x2886
        int128_t v2; // 0x2860
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 24; // bp-224, 0x28da
    dopr(s, size, fmt, (int32_t *)&v3);
    *(char *)((int64_t)s - 1 + size) = 0;
    return libmin_strlen(s);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_strlen.c
// Address range: 0x2910 - 0x293b
// Line range:    5 - 15
int64_t libmin_strlen(char * str) {
    int64_t v1 = (int64_t)str;
    if (str == NULL || (char)v1 == 0) {
        // 0x2938
        return 0;
    }
    int64_t v2 = v1; // 0x2917
    v2++;
    while (*(char *)v2 != 0) {
        // 0x2928
        v2++;
    }
    // 0x2931
    return v2 - v1;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_success.c
// Address range: 0x2940 - 0x2949
// Line range:    5 - 7
void libmin_success(void) {
    // 0x2940
    libtarg_success();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_ctype.c
// Address range: 0x2950 - 0x2972
// Line range:    140 - 146
int32_t _isctype(uint32_t c, int32_t mask) {
    int32_t result = 0; // 0x295f
    if (c < 256) {
        uint16_t v1 = *(int16_t *)((0x100000000 * (int64_t)c >> 31) + (int64_t)g6); // 0x296b
        result = (int32_t)v1 & mask;
    }
    // 0x2971
    return result;
}

// Address range: 0x2974 - 0x2981
int64_t _fini(void) {
    // 0x2974
    int64_t result; // 0x2974
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 33

