//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;
typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int32_t _isctype(uint32_t c, int32_t mask);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t deregister_tm_clones(void);
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args);
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags);
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags);
int64_t frame_dummy(void);
void function_1070(int64_t * d);
void function_1080(void);
int32_t function_1090(int32_t c, struct _IO_FILE * stream);
int64_t * function_10a0(int64_t delta);
void function_10b0(int32_t status);
int64_t function_27dd(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_27e8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_27f3(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_27fe(void);
int64_t function_2805(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
float64_t libmin_fabs(float64_t x);
float32_t libmin_fabsf(float32_t x);
void libmin_fail(uint32_t code);
int32_t libmin_printf(char * fmt, ...);
int32_t libmin_rand(void);
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...);
float64_t libmin_sqrt(float64_t x);
int64_t libmin_srand(void);
int64_t libmin_strlen(char * str);
void libmin_success(void);
void libtarg_fail(int32_t code);
void libtarg_putc(char c);
char * libtarg_sbrk(int64_t inc);
void libtarg_success(void);
int128_t line_distance(void);
int64_t my_modf_isra_0(int64_t a1);
void ransac_line_fitting(int32_t * points, uint32_t numPoints, float64_t * best_m, float64_t * best_b, int32_t * best_inlier_count);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = -0xfbc00000e19; // 0x30f0
int64_t g2 = -0x110c00000f69; // 0x3240
int64_t g3 = -0x125c000010b9; // 0x3390
int64_t g4 = -0x66f74f2100000000; // 0x3530
int32_t * g5 = (int32_t *)0x1000000004; // 0x38c
int32_t * g6 = (int32_t *)0x100000010; // 0x390
int32_t g7 = 0; // 0x400
int64_t g8 = 0x20002000200020; // 0x5022
struct _IO_FILE * g10 = NULL; // 0x5240
char g11 = 0; // 0x5248
int64_t g12 = 0; // 0x55ec
int32_t g13 = 0; // 0x5890
int32_t g14 = 0; // 0x5c1c
int64_t g15 = 0; // 0x5c20
int32_t mt[625]; // 0x5260
int32_t mt_initialized = 0; // 0x5c24
int32_t mti = 625; // 0x5010
int32_t g16;
int64_t * g9 = &g8; // 0x5228

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g16;
    }
    // 0x1016
    return result;
}

// Address range: 0x1070 - 0x107b
void function_1070(int64_t * d) {
    // 0x1070
    __cxa_finalize(d);
}

// Address range: 0x1080 - 0x108b
void function_1080(void) {
    // 0x1080
    __stack_chk_fail();
}

// Address range: 0x1090 - 0x109b
int32_t function_1090(int32_t c, struct _IO_FILE * stream) {
    // 0x1090
    return fputc(c, stream);
}

// Address range: 0x10a0 - 0x10ab
int64_t * function_10a0(int64_t delta) {
    // 0x10a0
    return sbrk(delta);
}

// Address range: 0x10b0 - 0x10bb
void function_10b0(int32_t status) {
    // 0x10b0
    exit(status);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ransac/ransac.c
// Address range: 0x10c0 - 0x1280
// Line range:    68 - 101
int main() {
    // 0x10c0
    __readfsqword(40);
    libmin_srand();
    int64_t v1 = 0; // 0x10f6
    int64_t v2; // bp-1640, 0x10c0
    int64_t v3 = &v2; // 0x10f6
    int128_t v4; // 0x10c0
    int128_t v5 = v4;
    int128_t v6; // 0x10c0
    int128_t v7 = v6;
    __asm_pxor(v7, v7);
    int128_t v8 = __asm_divsd(__asm_cvtsi2sd((int32_t)v1), 0x4049000000000000); // 0x110c
    int64_t v9 = v1 + 1; // 0x1114
    int64_t v10 = __asm_movsd(__asm_mulsd(v8, 0x4049000000000000)); // 0x111f
    uint32_t v11 = libmin_rand(); // 0x1125
    __asm_pxor(v5, v5);
    int128_t v12 = __asm_movsd_1(v10); // 0x112e
    int128_t v13 = __asm_subsd(__asm_divsd(__asm_cvtsi2sd_2((int64_t)v11), 0x41dfffffffc00000), 0x3fe0000000000000); // 0x1143
    *(int64_t *)v3 = __asm_movsd(v12);
    int128_t v14 = __asm_addsd_3(__asm_addsd(v12, v12), 0x3ff0000000000000); // 0x1156
    int128_t v15 = __asm_addsd(__asm_addsd(v13, v13), v14); // 0x1162
    *(int64_t *)(v3 + 8) = __asm_movsd(v15);
    v1 = v9 & 0xffffffff;
    v3 += 16;
    while ((int32_t)v9 != 50) {
        // 0x1100
        v5 = v15;
        v7 = v14;
        __asm_pxor(v7, v7);
        v8 = __asm_divsd(__asm_cvtsi2sd((int32_t)v1), 0x4049000000000000);
        v9 = v1 + 1;
        v10 = __asm_movsd(__asm_mulsd(v8, 0x4049000000000000));
        v11 = libmin_rand();
        __asm_pxor(v5, v5);
        v12 = __asm_movsd_1(v10);
        v13 = __asm_subsd(__asm_divsd(__asm_cvtsi2sd_2((int64_t)v11), 0x41dfffffffc00000), 0x3fe0000000000000);
        *(int64_t *)v3 = __asm_movsd(v12);
        v14 = __asm_addsd_3(__asm_addsd(v12, v12), 0x3ff0000000000000);
        v15 = __asm_addsd(__asm_addsd(v13, v13), v14);
        *(int64_t *)(v3 + 8) = __asm_movsd(v15);
        v1 = v9 & 0xffffffff;
        v3 += 16;
    }
    // 0x1172
    int64_t v16; // bp-840, 0x10c0
    int64_t v17 = &v16;
    int128_t v18 = v14;
    uint32_t v19 = libmin_rand(); // 0x1188
    __asm_pxor(v18, v18);
    int64_t v20 = v17 + 16; // 0x1191
    int128_t v21 = __asm_mulsd(__asm_divsd(__asm_cvtsi2sd_2((int64_t)v19), 0x41dfffffffc00000), 0x4049000000000000); // 0x11a4
    *(int64_t *)v17 = __asm_movsd(v21);
    uint32_t v22 = libmin_rand(); // 0x11b3
    __asm_pxor(v21, v21);
    int128_t v23 = __asm_mulsd(__asm_divsd(__asm_cvtsi2sd_2((int64_t)v22), 0x41dfffffffc00000), 0x4059000000000000); // 0x11cb
    *(int64_t *)(v17 + 8) = __asm_movsd(v23);
    int64_t v24; // bp-40, 0x10c0
    while (v20 != (int64_t)&v24) {
        // 0x1188
        v17 = v20;
        v18 = v23;
        v19 = libmin_rand();
        __asm_pxor(v18, v18);
        v20 = v17 + 16;
        v21 = __asm_mulsd(__asm_divsd(__asm_cvtsi2sd_2((int64_t)v19), 0x41dfffffffc00000), 0x4049000000000000);
        *(int64_t *)v17 = __asm_movsd(v21);
        v22 = libmin_rand();
        __asm_pxor(v21, v21);
        v23 = __asm_mulsd(__asm_divsd(__asm_cvtsi2sd_2((int64_t)v22), 0x41dfffffffc00000), 0x4059000000000000);
        *(int64_t *)(v17 + 8) = __asm_movsd(v23);
    }
    int32_t v25 = 0; // bp-1660, 0x11f6
    float64_t best_b = 0.0; // bp-1656, 0x11fe
    int64_t points = 0; // bp-1648, 0x1207
    ransac_line_fitting((int32_t *)&v2, 100, &best_b, (float64_t *)&points, &v25);
    int128_t v26 = __asm_movsd_1(points); // 0x1215
    libmin_printf("RANSAC estimated line: y = %f * x + %f\n", (float64_t)(int64_t)__asm_movsd_1((int64_t)best_b), (float64_t)(int64_t)v26);
    libmin_printf("Number of inliers: %d / %d\n", (int64_t)v25, 100);
    libmin_success();
    // UNREACHABLE
}

// Address range: 0x1280 - 0x12a6
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1280
    int64_t v1; // 0x1280
    __libc_start_main(0x10c0, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x12b0 - 0x12d9
int64_t deregister_tm_clones(void) {
    // 0x12b0
    return 0x5230;
}

// Address range: 0x12e0 - 0x1319
int64_t register_tm_clones(void) {
    // 0x12e0
    return 0;
}

// Address range: 0x1320 - 0x1359
int64_t __do_global_dtors_aux(void) {
    // 0x1320
    if (g11 != 0) {
        // 0x1358
        int64_t result; // 0x1320
        return result;
    }
    // 0x132d
    if (*(int64_t *)0x4ff8 != 0) {
        // 0x133b
        __cxa_finalize((int64_t *)*(int64_t *)0x5008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1347
    g11 = 1;
    return result2;
}

// Address range: 0x1360 - 0x1369
int64_t frame_dummy(void) {
    // 0x1360
    return register_tm_clones();
}

// Address range: 0x1370 - 0x13c1
int128_t line_distance(void) {
    // 0x1370
    int128_t v1; // 0x1370
    int128_t v2 = __asm_mulsd_6(v1, v1); // 0x1374
    int64_t v3 = __asm_movsd(v1); // 0x137c
    int128_t v4 = __asm_subsd_4(v2, v1); // 0x1382
    float64_t v5 = libmin_fabs((float64_t)(int64_t)__asm_addsd(v4, v1)); // 0x138a
    int128_t v6 = __asm_movsd_1(v3); // 0x138f
    int64_t v7 = __asm_movsd((int128_t)(int32_t)(float32_t)v5); // 0x1395
    int128_t v8 = __asm_addsd_3(__asm_mulsd_6(v6, v6), 0x3ff0000000000000); // 0x139e
    float64_t v9 = libmin_sqrt((float64_t)(int64_t)__asm_movapd(v8)); // 0x13aa
    return __asm_movapd(__asm_divsd_5(__asm_movsd_1(v7), (int128_t)(int32_t)(float32_t)v9));
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ransac/ransac.c
// Address range: 0x13d0 - 0x1581
// Line range:    32 - 54
void ransac_line_fitting(int32_t * points, uint32_t numPoints, float64_t * best_m, float64_t * best_b, int32_t * best_inlier_count) {
    int64_t v1 = (int64_t)points;
    *best_inlier_count = 0;
    for (int32_t i = 500; i > 0; i--) {
        int32_t v2 = libmin_rand() % numPoints;
        uint32_t v3 = libmin_rand() % numPoints;
        while (v2 == v3) {
            // 0x1420
            v3 = libmin_rand() % numPoints;
        }
        uint64_t v4 = 0x100000000 * (int64_t)v3 >> 28; // 0x1434
        int64_t v5 = 16 * (int64_t)v2 + v1; // 0x1438
        uint64_t v6 = v4 + v1; // 0x143b
        int128_t v7 = __asm_movsd_1(*(int64_t *)v5); // 0x143e
        int128_t v8 = __asm_movsd_1(*(int64_t *)(v5 + 8)); // 0x1443
        int128_t v9 = __asm_movsd_1(*(int64_t *)v6); // 0x1448
        int64_t v10 = *(int64_t *)(v6 + 8); // 0x144c
        int64_t v11 = __asm_movsd(v8); // 0x1450
        int128_t v12 = __asm_subsd_4(v9, v7); // 0x1456
        int64_t v13 = __asm_movsd(v7); // 0x145a
        int128_t v14 = __asm_movapd(v12); // 0x1460
        int64_t v15 = __asm_movsd(v12); // 0x1464
        float64_t v16 = libmin_fabs((float64_t)(int64_t)v14); // 0x146a
        __asm_comisd(__asm_movsd_1(0x3eb0c6f7a0b5ed8d), (int128_t)(int32_t)(float32_t)v16);
        if (v6 < v4 || v6 == 0) {
            int128_t v17 = __asm_movsd_1(v11); // 0x1498
            int128_t v18 = __asm_movq(v10); // 0x149e
            int128_t v19 = __asm_movsd_1(v15); // 0x14a3
            int128_t v20 = __asm_movsd_1(v13); // 0x14a9
            int128_t v21 = __asm_divsd_5(__asm_subsd_4(v18, v17), v19); // 0x14b3
            int128_t v22 = __asm_mulsd_6(v20, v21); // 0x14b7
            int64_t v23 = __asm_movsd(v21); // 0x14bb
            int64_t v24 = __asm_movsd(__asm_subsd_4(v17, v22)); // 0x14c5
            if (numPoints >= 1) {
                int64_t v25 = __asm_movsd(__asm_mulsd_6(__asm_movapd(v21), v21)); // 0x14e0
                int64_t v26 = v1; // 0x14e6
                int128_t v27 = __asm_mulsd(__asm_movsd_1(v23), *(int64_t *)v26); // 0x14f6
                int128_t v28 = __asm_addsd_3(__asm_subsd(v27, *(int64_t *)(v26 + 8)), v24); // 0x1501
                int64_t v29 = __asm_movsd((int128_t)(int32_t)(float32_t)libmin_fabs((float64_t)(int64_t)v28)); // 0x150c
                int128_t v30 = __asm_movsd_1(0x3ff0000000000000); // 0x1512
                float64_t v31 = libmin_sqrt((float64_t)(int64_t)__asm_addsd_3(v30, v25)); // 0x1520
                int128_t v32 = __asm_movsd_1(v29); // 0x1525
                int128_t v33 = __asm_movsd_1(0x3ff0000000000000); // 0x152b
                __asm_comisd(v33, __asm_divsd_5(v32, (int128_t)(int32_t)(float32_t)v31));
                v26 += 16;
                while (v1 + 16 + 16 * (int64_t)(numPoints - 1) != v26) {
                    // 0x14f0
                    v27 = __asm_mulsd(__asm_movsd_1(v23), *(int64_t *)v26);
                    v28 = __asm_addsd_3(__asm_subsd(v27, *(int64_t *)(v26 + 8)), v24);
                    v29 = __asm_movsd((int128_t)(int32_t)(float32_t)libmin_fabs((float64_t)(int64_t)v28));
                    v30 = __asm_movsd_1(0x3ff0000000000000);
                    v31 = libmin_sqrt((float64_t)(int64_t)__asm_addsd_3(v30, v25));
                    v32 = __asm_movsd_1(v29);
                    v33 = __asm_movsd_1(0x3ff0000000000000);
                    __asm_comisd(v33, __asm_divsd_5(v32, (int128_t)(int32_t)(float32_t)v31));
                    v26 += 16;
                }
            }
            int64_t v34; // 0x13d0
            if ((int32_t)v34 < 0) {
                int128_t v35 = __asm_movsd_1(v23); // 0x1558
                int128_t v36 = __asm_movsd_1(v24); // 0x155e
                *best_inlier_count = 0;
                *best_m = (float64_t)__asm_movsd(v35);
                *best_b = (float64_t)__asm_movsd(v36);
            }
        }
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1590 - 0x15a1
// Line range:    124 - 127
void libtarg_success(void) {
    // 0x1590
    exit(0);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x15b0 - 0x15bf
// Line range:    162 - 165
void libtarg_fail(int32_t code) {
    // 0x15b0
    exit(code);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x15c0 - 0x15d4
// Line range:    188 - 191
void libtarg_putc(char c) {
    // 0x15c0
    fputc((int32_t)c, g10);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x15e0 - 0x15e9
// Line range:    230 - 236
char * libtarg_sbrk(int64_t inc) {
    // 0x15e0
    return (char *)sbrk(inc);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fabs.c
// Address range: 0x15f0 - 0x1604
// Line range:    5 - 10
float64_t libmin_fabs(float64_t x) {
    int64_t v1 = __asm_movq_7((int128_t)(int32_t)(float32_t)x); // 0x15f4
    return (int64_t)__asm_movq(v1 & 0x7fffffffffffffff);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fabs.c
// Address range: 0x1610 - 0x1622
// Line range:    13 - 18
float32_t libmin_fabsf(float32_t x) {
    uint32_t v1 = __asm_movd((int128_t)(int32_t)x); // 0x1614
    return (int32_t)__asm_movd_8(v1 % 0x80000000);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1630 - 0x1878
// Line range:    426 - 483
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags) {
    int64_t v1 = flags; // 0x163f
    int64_t v2 = value; // 0x165f
    int64_t v3 = 0; // 0x165f
    int32_t v4 = 0; // 0x165f
    if ((flags & 64) == 0) {
        if (value < 0) {
            // 0x1840
            v2 = -value;
            v3 = 45;
            v4 = -1;
        } else {
            // 0x166a
            v2 = value;
            v3 = 43;
            v4 = -1;
            if ((v1 & 2) == 0) {
                uint32_t v5 = 8 * flags & 32; // 0x1863
                v2 = value;
                v3 = v5;
                v4 = v5 != 0;
            }
        }
    }
    int64_t v6 = (int64_t)currlen;
    int64_t v7 = (int64_t)buffer;
    uint32_t v8 = max > 0 ? max : 0; // 0x1657
    uint64_t v9 = (int64_t)base; // 0x1692
    int64_t v10; // bp-89, 0x1630
    int64_t v11 = &v10; // 0x1695
    int64_t v12 = (v1 & 32) == 0 ? (int64_t)"0123456789abcdef" : (int64_t)"0123456789ABCDEF"; // 0x16ad
    uint64_t v13 = v2; // 0x16b1
    int64_t v14 = 1;
    *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
    int32_t v15 = v14;
    int32_t v16 = v15 - 19; // 0x16d8
    int64_t v17 = v14 + 1; // 0x16e4
    while (v13 >= v9 == (v16 == 0 || v16 < 0 != (18 - v15 & v15) < 0)) {
        // 0x16b8
        v13 /= v9;
        v14 = v17;
        *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
        v15 = v14;
        v16 = v15 - 19;
        v17 = v14 + 1;
    }
    int64_t v18 = v15 == 20 ? 19 : v14 & 0xffffffff; // 0x16f6
    int32_t v19 = v18; // 0x16fa
    int32_t v20 = v8 - v19; // 0x16fa
    int64_t v21 = 0x100000000 * v18 >> 32; // 0x1700
    int64_t v22; // bp-48, 0x1630
    int64_t v23 = (int64_t)&v22 - 40 + v21; // 0x1707
    *(char *)v23 = 0;
    uint32_t v24 = min - (int32_t)(v20 < 0 == (v20 & v19) < 0 ? (int64_t)v8 : v18) + v4; // 0x1713
    uint32_t v25 = v20 > 0 ? v20 : 0; // 0x1719
    int64_t v26 = v25; // 0x1719
    int64_t v27 = v24 >= 0 ? (int64_t)v24 : 0; // 0x1725
    int64_t v28; // 0x1630
    int64_t v29; // 0x1630
    int64_t v30; // 0x1630
    if ((v1 & 16) == 0) {
        if (flags % 2 != 0) {
            // 0x1820
            v29 = v6;
            v30 = -v27 & 0xffffffff;
            v28 = v26;
        } else {
            // 0x17e4
            v29 = v6;
            v30 = v27;
            v28 = v26;
            if (v24 >= 1) {
                if (v6 < maxlen) {
                    // 0x17f5
                    *(char *)(v6 + v7) = 32;
                }
                int64_t v31 = v6 + 1; // 0x17fc
                *currlen = v31;
                uint32_t v32 = (int32_t)v27 - 1; // 0x1803
                int64_t v33 = v32; // 0x1806
                while (v32 != 0) {
                    int64_t v34 = v31;
                    int64_t v35 = v34; // 0x17f3
                    if (v34 < maxlen) {
                        // 0x17f5
                        *(char *)(v34 + v7) = 32;
                        v35 = v6;
                    }
                    // 0x17fc
                    v31 = v35 + 1;
                    *currlen = v31;
                    v32 = (int32_t)v33 - 1;
                    v33 = v32;
                }
                int32_t v36 = v27; // 0x1808
                v29 = v31;
                v30 = v27 - (v36 >= 0 == (v36 != 0) ? v27 : 1) & 0xffffffff;
                v28 = v26;
            }
        }
    } else {
        int32_t v37 = v27; // 0x1736
        int32_t v38 = v25 - v37; // 0x1736
        v29 = v6;
        v30 = 0;
        v28 = v38 < 0 == (v38 & v37) < 0 ? v26 : v27;
    }
    int64_t v39 = v29; // 0x1742
    if (v3 != 0) {
        int64_t v40 = v29; // 0x1747
        if (v29 < maxlen) {
            // 0x1830
            *(char *)(v29 + v7) = (char)v3;
            v40 = v6;
        }
        // 0x174d
        v39 = v40 + 1;
        *currlen = v39;
    }
    int64_t v41 = v39; // 0x1757
    uint32_t v42 = v28; // 0x1757
    if ((int32_t)v28 != 0) {
        int64_t v43 = v39; // 0x17c3
        if (v39 < maxlen) {
            // 0x17c5
            *(char *)(v39 + v7) = 48;
            v43 = v6;
        }
        int64_t v44 = v43 + 1; // 0x17cc
        *currlen = v44;
        v41 = v44;
        while (v42 != 0) {
            // 0x17c0
            v42 = (int64_t)v42;
            int64_t v45 = v44;
            v43 = v45;
            if (v45 < maxlen) {
                // 0x17c5
                *(char *)(v45 + v7) = 48;
                v43 = v6;
            }
            // 0x17cc
            v44 = v43 + 1;
            *currlen = v44;
            v41 = v44;
        }
    }
    int64_t v46 = v23; // 0x1768
    v46--;
    int64_t v47 = v41; // 0x1773
    if (v41 < maxlen) {
        // 0x1775
        *(char *)(v41 + v7) = *(char *)v46;
        v47 = v6;
    }
    int64_t v48 = v47 + 1; // 0x1780
    *currlen = v48;
    while (v21 + v11 - (v18 + 0xffffffff & 0xffffffff) != v46) {
        int64_t v49 = v48;
        v46--;
        v47 = v49;
        if (v49 < maxlen) {
            // 0x1775
            *(char *)(v49 + v7) = *(char *)v46;
            v47 = v6;
        }
        // 0x1780
        v48 = v47 + 1;
        *currlen = v48;
    }
    // 0x1790
    if (v30 == 0) {
        // 0x17b0
        return;
    }
    uint32_t v50 = v30; // 0x1792
    int64_t v51 = v48; // 0x179b
    if (v48 < maxlen) {
        // 0x179d
        *(char *)(v48 + v7) = 32;
        v51 = v6;
    }
    int64_t v52 = v51 + 1; // 0x17a4
    *currlen = v52;
    while (v50 != 0) {
        // 0x1798
        v50 = (int64_t)v50;
        int64_t v53 = v52;
        v51 = v53;
        if (v53 < maxlen) {
            // 0x179d
            *(char *)(v53 + v7) = 32;
            v51 = v6;
        }
        // 0x17a4
        v52 = v51 + 1;
        *currlen = v52;
    }
}

// Address range: 0x1880 - 0x1933
int64_t my_modf_isra_0(int64_t a1) {
    // 0x1880
    int128_t v1; // 0x1880
    int128_t v2 = __asm_movapd(v1); // 0x1881
    int128_t v3 = __asm_movsd_1(0x3ff0000000000000); // 0x188e
    int128_t v4 = __asm_movsd_1(0x3fb999999999999a); // 0x1896
    int128_t v5 = __asm_movsd_1(0x4024000000000000); // 0x189e
    int128_t v6 = __asm_movapd(v3); // 0x18a6
    int64_t v7; // bp-8, 0x1880
    bool v8 = &v7 < (int64_t *)32; // 0x18aa
    int64_t result2 = 0;
    int128_t v9 = v6;
    int128_t v10; // 0x1880
    int128_t v11 = v10;
    int128_t v12 = v2;
    int64_t v13 = __asm_cvttsd2si_9(v12); // 0x18c0
    __asm_pxor(v11, v11);
    int128_t v14 = __asm_addsd(__asm_movapd(v12), v3); // 0x18cd
    int128_t v15 = __asm_cvtsi2sd_2(v13); // 0x18d1
    __asm_comisd(v14, v15);
    while (v8) {
        int64_t v16 = result2 + 1; // 0x18b4
        int64_t result = v16 & 0xffffffff; // 0x18b4
        uint32_t v17 = (int32_t)v16; // 0x18bb
        v8 = v17 < 100;
        int128_t v18 = __asm_mulsd_6(v12, v4); // 0x18be
        int128_t v19 = __asm_mulsd_6(v9, v5); // 0x18be
        if (v17 == 100) {
            // 0x18f8
            *(int64_t *)a1 = 0;
            return result;
        }
        result2 = result;
        v9 = v19;
        v11 = v15;
        v12 = v18;
        v13 = __asm_cvttsd2si_9(v12);
        __asm_pxor(v11, v11);
        v14 = __asm_addsd(__asm_movapd(v12), v3);
        v15 = __asm_cvtsi2sd_2(v13);
        __asm_comisd(v14, v15);
    }
    // 0x18dc
    __asm_comisd(v15, __asm_subsd_4(__asm_movapd(v12), v3));
    if (result2 == 0) {
        // 0x18ee
        *(int64_t *)a1 = __asm_movsd(v15);
        return result2;
    }
    int128_t v20 = __asm_mulsd_6(v15, v9); // 0x1905
    __asm_subsd_4(v1, v20);
    int64_t v21 = __asm_movsd(v20); // 0x1912
    int64_t v22; // bp-16, 0x1880
    int64_t result3 = my_modf_isra_0((int64_t)&v22); // 0x1918
    *(int64_t *)a1 = __asm_movsd(__asm_addsd_3(__asm_movsd_1(v21), v22));
    return result3;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1940 - 0x1ec0
// Line range:    586 - 525
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags) {
    char iconvert[311]; // bp-704, 0x1940
    char v1[311]; // 0x1940
    char v2[311]; // 0x1ea8
    char v3[311]; // 0x1de2
    char v4[311]; // 0x1a43
    char v5[311]; // 0x1dbc
    // 0x1940
    int128_t v6; // 0x1940
    int128_t v7 = v6;
    int128_t v8 = v6;
    int128_t v9 = v6;
    int3_t v10; // 0x1940
    int3_t v11 = v10 - 1;
    float80_t v12; // 0x1940
    __frontend_reg_store_fpr(v11, v12);
    int32_t v13 = 6; // 0x1965
    int64_t v14 = 6; // 0x1965
    if (max >= 0) {
        int32_t v15 = max - 16; // 0x1971
        v14 = v15 == 0 | v15 < 0 != (15 - max & max) < 0 ? (int64_t)max : 16;
        v13 = max;
    }
    uint64_t v16 = (int64_t)flags;
    int3_t v17 = v10 - 2; // 0x1978
    __frontend_reg_store_fpr(v17, 0.0L);
    float80_t v18 = __frontend_reg_load_fpr(v17); // 0x197a
    float80_t v19 = __frontend_reg_load_fpr(v11); // 0x197a
    float80_t v20 = __frontend_reg_load_fpr(v11);
    int32_t v21; // 0x1940
    int32_t v22; // 0x1940
    float64_t v23; // bp-744, 0x1940
    int128_t v24; // 0x1940
    if (v18 > v19) {
        // 0x1df0
        __frontend_reg_store_fpr(v11, -v20);
        float64_t v25 = __frontend_reg_load_fpr(v11); // 0x1dfa
        v23 = v25;
        v22 = 45;
        v21 = 1;
        v24 = __asm_movsd_1((int64_t)v25);
    } else {
        float64_t v26 = v20; // 0x1982
        v23 = v26;
        int128_t v27 = __asm_movsd_1((int64_t)v26); // 0x1985
        v22 = 43;
        v21 = 1;
        v24 = v27;
        if ((v16 & 2) == 0) {
            int32_t v28 = 8 * flags & 32; // 0x199d
            v22 = v28;
            v21 = v28 != 0;
            v24 = v27;
        }
    }
    // 0x19ae
    __asm_movapd(v24);
    float64_t fracpart; // bp-712, 0x1940
    int64_t v29 = &fracpart; // 0x19b8
    my_modf_isra_0(v29);
    bool v30; // 0x1940
    bool v31; // 0x1940
    int128_t v32; // 0x1940
    int128_t v33; // 0x1940
    int128_t v34; // 0x1940
    bool v35; // 0x1940
    bool v36; // 0x1940
    if (v13 == 0) {
        int128_t v37 = __asm_movsd_1((int64_t)fracpart); // 0x1e54
        int128_t v38 = __asm_subsd_4(v24, v37); // 0x1e5a
        int64_t v39 = __asm_cvttsd2si_9(v38); // 0x1e5f
        v23 = __asm_movsd(v38);
        __frontend_reg_store_fpr(v11, (float80_t)v39);
        __frontend_reg_store_fpr(v11, (float80_t)v23 - __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v17, 0.5L);
        float80_t v40 = __frontend_reg_load_fpr(v17); // 0x1e7c
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v40);
        float80_t v41 = __frontend_reg_load_fpr(v17); // 0x1e7e
        float80_t v42 = __frontend_reg_load_fpr(v11); // 0x1e7e
        bool v43 = false; // 0x1e7e
        bool v44 = false; // 0x1e7e
        bool v45 = false; // 0x1e7e
        if (v41 <= v42) {
            v43 = true;
            v44 = false;
            v45 = false;
            if (v41 >= v42) {
                v43 = v41 != v42;
                v44 = v41 != v42;
                v45 = true;
            }
        }
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
        bool v46 = true; // 0x1e82
        bool v47 = v44; // 0x1e82
        bool v48 = v45; // 0x1e82
        int64_t v49 = v39; // 0x1e82
        if (!v43) {
            // 0x1e84
            v49 = v39 + 1;
            v46 = v39 == -1;
            v47 = llvm_ctpop_i8((char)v49) % 2 == 0;
            v48 = v49 == 0;
        }
        // 0x1e88
        __asm_pxor(v7, v7);
        int128_t v50 = __asm_movsd_1(0x3ff0000000000000); // 0x1e8d
        int128_t v51 = __asm_cvtsi2sd_2(v49); // 0x1e95
        v23 = __asm_movsd(v51);
        __asm_comisd(v51, v50);
        __frontend_reg_store_fpr(v11, (float80_t)v23);
        int64_t v52 = __asm_movsd(v51); // 0x1ea8
        v2[0] = v52;
        iconvert = v2;
        if (v46) {
            // 0x1a70
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v47;
            v35 = v48;
            v32 = v37;
            v34 = v51;
            goto lab_0x1a78;
        } else {
            int128_t v53 = __asm_addsd(v37, v50); // 0x1eb5
            __frontend_reg_store_fpr(v17, 1.0L);
            v31 = v47;
            v36 = v48;
            v33 = v53;
            goto lab_0x1dab;
        }
    } else {
        // 0x19c9
        __frontend_reg_store_fpr(v11, 1.0L);
        __frontend_reg_store_fpr(v17, 10.0L);
        int64_t v54 = v14 & 0xffffffff; // 0x19d1
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
        uint32_t v55 = (int32_t)v54 - 1; // 0x19da
        int64_t v56 = v55; // 0x19dd
        while (v55 != 0) {
            // 0x19d8
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
            v55 = (int32_t)v56 - 1;
            v56 = v55;
        }
        float80_t v57 = __frontend_reg_load_fpr(v17); // 0x19df
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v57);
        int128_t v58 = __asm_movsd_1((int64_t)fracpart); // 0x19e5
        v23 = __asm_movsd(__asm_subsd_4(v24, v58));
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) * (float80_t)v23);
        int3_t v59 = v10 - 3;
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        float80_t v60 = __frontend_reg_load_fpr(v59); // 0x1a0c
        v23 = v60;
        __frontend_reg_store_fpr(v59, v60);
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) - __frontend_reg_load_fpr(v59));
        __frontend_reg_store_fpr(v59, 0.5L);
        float80_t v61 = __frontend_reg_load_fpr(v59); // 0x1a1e
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v61);
        float80_t v62 = __frontend_reg_load_fpr(v59); // 0x1a20
        float80_t v63 = __frontend_reg_load_fpr(v17); // 0x1a20
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
        if (v62 < v63) {
            // 0x1dd0
            __asm_pxor(v9, v9);
            int128_t v64 = __asm_cvtsi2sd_2((int64_t)v23); // 0x1dd4
            int64_t v65 = __asm_movsd(v64); // 0x1dda
            v23 = v65;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v65);
            int64_t v66 = __asm_movsd(v64); // 0x1de2
            v3[0] = v66;
            v1 = v3;
        } else {
            // 0x1a2a
            __asm_pxor(v9, v9);
            int128_t v67 = __asm_cvtsi2sd_2((int64_t)v23 + 1); // 0x1a36
            int64_t v68 = __asm_movsd(v67); // 0x1a3b
            v23 = v68;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v68);
            int64_t v69 = __asm_movsd(v67); // 0x1a43
            v4[0] = v69;
            v1 = v4;
        }
        // 0x1a49
        iconvert = v1;
        __frontend_reg_store_fpr(v59, 1.0L);
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
        uint32_t v70 = (int32_t)v54 - 1; // 0x1a52
        int64_t v71 = v70; // 0x1a55
        while (v70 != 0) {
            // 0x1a50
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            v70 = (int32_t)v71 - 1;
            v71 = v70;
        }
        float80_t v72 = __frontend_reg_load_fpr(v59); // 0x1a57
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v72);
        float80_t v73 = __frontend_reg_load_fpr(v59); // 0x1a59
        float80_t v74 = __frontend_reg_load_fpr(v17); // 0x1a59
        bool v75 = false; // 0x1a59
        bool v76 = false; // 0x1a59
        bool v77 = false; // 0x1a59
        if (v73 <= v74) {
            v75 = true;
            v76 = false;
            v77 = false;
            if (v73 >= v74) {
                v75 = v73 != v74;
                v76 = v73 != v74;
                v77 = true;
            }
        }
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v59));
        if (!v75) {
            int128_t v78 = __asm_addsd_3(v58, 0x3ff0000000000000); // 0x1d90
            __frontend_reg_store_fpr(v59, 1.0L);
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            uint32_t v79 = (int32_t)v54 - 1; // 0x1da2
            int64_t v80 = v79; // 0x1da5
            while (v79 != 0) {
                // 0x1da0
                __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
                v79 = (int32_t)v80 - 1;
                v80 = v79;
            }
            unsigned char v81 = llvm_ctpop_i8((char)v79); // 0x1da2
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v59));
            float80_t v82 = __frontend_reg_load_fpr(v17); // 0x1da9
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
            __frontend_reg_store_fpr(v11, v82);
            v31 = v81 % 2 == 0;
            v36 = true;
            v33 = v78;
            goto lab_0x1dab;
        } else {
            // 0x1a63
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v76;
            v35 = v77;
            v32 = v58;
            v34 = __asm_movsd_1(*(int64_t *)&iconvert);
            goto lab_0x1a78;
        }
    }
  lab_0x1a78:;
    int64_t v83 = (int64_t)currlen;
    int64_t v84 = (int64_t)buffer;
    int64_t v85 = &v23; // 0x1950
    int64_t v86; // bp-697, 0x1940
    int64_t v87 = &v86; // 0x1a7d
    int128_t v88 = __asm_pxor(v8, v8); // 0x1a82
    int128_t v89 = __asm_movsd_1(0x3fb999999999999a); // 0x1a87
    int128_t v90 = __asm_movsd_1(0x3fa999999999999a); // 0x1a90
    int128_t v91 = __asm_movsd_1(0x4024000000000000); // 0x1aa0
    bool v92 = v30; // 0x1aa9
    bool v93 = v35; // 0x1aa9
    int64_t v94 = 1;
    int128_t v95 = __asm_movapd(__asm_mulsd_6(v32, v89)); // 0x1acc
    my_modf_isra_0(v29);
    int128_t v96 = __asm_movsd_1((int64_t)fracpart); // 0x1ad6
    int128_t v97 = __asm_subsd_4(v95, v96); // 0x1adc
    __asm_ucomisd(v96, v88);
    int32_t v98 = __asm_cvttsd2si(__asm_mulsd_6(__asm_addsd(v97, v90), v91)); // 0x1af0
    char v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef"); // 0x1af7
    *(char *)(v94 + v87) = v99;
    bool v100; // 0x1940
    int64_t v101; // 0x1940
    bool v102; // 0x1940
    while (v92 || !v93) {
        int64_t v103 = v94 - 311; // 0x1ab4
        unsigned char v104 = llvm_ctpop_i8((char)v103); // 0x1ab4
        v92 = v104 % 2 == 0;
        v93 = false;
        v100 = v104 % 2 == 0;
        v102 = true;
        v101 = 310;
        if (v103 == 0) {
            goto lab_0x1b13;
        }
        v94++;
        v95 = __asm_movapd(__asm_mulsd_6(v96, v89));
        my_modf_isra_0(v29);
        v96 = __asm_movsd_1((int64_t)fracpart);
        v97 = __asm_subsd_4(v95, v96);
        __asm_ucomisd(v96, v88);
        v98 = __asm_cvttsd2si(__asm_mulsd_6(__asm_addsd(v97, v90), v91));
        v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef");
        *(char *)(v94 + v87) = v99;
    }
    int32_t v105 = (int32_t)v94 - 311; // 0x1b04
    v100 = llvm_ctpop_i8((char)v105) % 2 == 0;
    v102 = v105 == 0;
    v101 = v105 == 0 ? 310 : v94 & 0xffffffff;
  lab_0x1b13:
    // 0x1b13
    __asm_ucomisd(v34, v88);
    int64_t v106 = 0x100000000 * v101 >> 32; // 0x1b18
    v23 = v106;
    int64_t v107 = v85 + 48; // 0x1b1f
    *(char *)(v106 + v107) = 0;
    int64_t v108 = v14; // 0x1b24
    int64_t v109 = 0; // 0x1b24
    if (v100 || !v102) {
        bool v110 = v100; // 0x1b3e
        bool v111 = v102; // 0x1b3e
        int64_t v112 = 1;
        int128_t v113 = __asm_mulsd_6(v34, v89); // 0x1b51
        __asm_movapd(v113);
        int128_t v114 = __asm_movapd(v113); // 0x1b5e
        my_modf_isra_0((int64_t)&iconvert);
        int128_t v115 = __asm_movsd_1(*(int64_t *)&iconvert); // 0x1b68
        int128_t v116 = __asm_subsd_4(v114, v115); // 0x1b71
        __asm_ucomisd(v115, v88);
        int32_t v117 = __asm_cvttsd2si(__asm_mulsd_6(__asm_addsd(v116, v90), v91)); // 0x1b85
        char v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef"); // 0x1b8c
        int64_t v119; // bp-377, 0x1940
        *(char *)(v112 + (int64_t)&v119) = v118;
        while (v110 || !v111) {
            int64_t v120 = v112 - 311; // 0x1b44
            v110 = llvm_ctpop_i8((char)v120) % 2 == 0;
            v111 = false;
            if (v120 == 0) {
                goto lab_0x1e38;
            }
            v112++;
            v113 = __asm_mulsd_6(v115, v89);
            __asm_movapd(v113);
            v114 = __asm_movapd(v113);
            my_modf_isra_0((int64_t)&iconvert);
            v115 = __asm_movsd_1(*(int64_t *)&iconvert);
            v116 = __asm_subsd_4(v114, v115);
            __asm_ucomisd(v115, v88);
            v117 = __asm_cvttsd2si(__asm_mulsd_6(__asm_addsd(v116, v90), v91));
            v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef");
            *(char *)(v112 + (int64_t)&v119) = v118;
        }
        if ((int32_t)v112 == 311) {
          lab_0x1e38:
            // 0x1e38
            v108 = v14 + 0xfffffeca;
            v109 = 310;
        } else {
            // 0x1ba5
            v108 = v14 - v112;
            v109 = v112 & 0xffffffff;
        }
    }
    int64_t v121 = (0x100000000 * v109 >> 32) + v85;
    int64_t v122 = v121 + 368; // 0x1bb5
    *(char *)v122 = 0;
    int32_t v123 = -1 - (int32_t)v14 + (int32_t)(float32_t)(float64_t)(int64_t)min - v21 - (int32_t)v101; // 0x1bcd
    int64_t v124 = v123 >= 0 ? (int64_t)v123 : 0; // 0x1bd2
    int64_t v125; // 0x1940
    int64_t v126; // 0x1940
    int64_t v127; // 0x1940
    int64_t v128; // 0x1940
    int64_t v129; // 0x1940
    int64_t v130; // 0x1940
    if (v16 % 2 == 0) {
        if ((v16 & 16) == 0) {
            // 0x1d50
            v129 = v83;
            v125 = v124;
            if (v123 >= 1) {
                if (v83 < maxlen) {
                    // 0x1d65
                    *(char *)(v83 + v84) = 32;
                }
                int64_t v131 = v83 + 1; // 0x1d6c
                *currlen = v131;
                uint32_t v132 = (int32_t)v124 - 1; // 0x1d73
                int64_t v133 = v132; // 0x1d77
                while (v132 != 0) {
                    int64_t v134 = v131;
                    int64_t v135 = v134; // 0x1d63
                    if (v134 < maxlen) {
                        // 0x1d65
                        *(char *)(v134 + v84) = 32;
                        v135 = v83;
                    }
                    // 0x1d6c
                    v131 = v135 + 1;
                    *currlen = v131;
                    v132 = (int32_t)v133 - 1;
                    v133 = v132;
                }
                int32_t v136 = v124; // 0x1d79
                v129 = v131;
                v125 = v124 - (v136 >= 0 == (v136 != 0) ? v124 : 1) & 0xffffffff;
            }
            goto lab_0x1be3;
        } else {
            // 0x1d0e
            v129 = v83;
            v125 = v124;
            if (v123 < 1) {
                goto lab_0x1be3;
            } else {
                // 0x1d17
                v130 = v83;
                v126 = v124;
                if (v22 != 0) {
                    // 0x1e21
                    v128 = v83;
                    v127 = v124;
                    if (v83 < maxlen) {
                        // 0x1e2a
                        *(char *)(v83 + v84) = (char)v22;
                        v128 = v83;
                        v127 = v124;
                    }
                    goto lab_0x1d34;
                } else {
                    goto lab_0x1d28;
                }
            }
        }
    } else {
        // 0x1be0
        v129 = v83;
        v125 = -v124 & 0xffffffff;
        goto lab_0x1be3;
    }
  lab_0x1dab:
    // 0x1dab
    __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) - __frontend_reg_load_fpr(v17));
    fracpart = __asm_movsd(v33);
    float64_t v137 = __frontend_reg_load_fpr(v11); // 0x1db3
    v23 = v137;
    int128_t v138 = __asm_movsd_1((int64_t)v137); // 0x1db6
    int64_t v139 = __asm_movsd(v138); // 0x1dbc
    v5[0] = v139;
    iconvert = v5;
    v30 = v31;
    v35 = v36;
    v32 = v33;
    v34 = v138;
    goto lab_0x1a78;
  lab_0x1be3:;
    int64_t v140 = v129; // 0x1be9
    int64_t v141 = v125; // 0x1be9
    if (v22 != 0) {
        int64_t v142 = v129; // 0x1bee
        if (v129 < maxlen) {
            // 0x1bf0
            *(char *)(v129 + v84) = (char)v22;
            v142 = v83;
        }
        int64_t v143 = v142 + 1; // 0x1bf6
        *currlen = v143;
        v140 = v143;
        v141 = v125;
    }
    goto lab_0x1bfd;
  lab_0x1bfd:;
    int64_t v144 = v107 + (int64_t)v23 - 1;
    int64_t v145; // 0x1940
    if (v140 < maxlen) {
        // 0x1c15
        *(char *)(v145 + v84) = *(char *)v144;
    }
    int64_t v146 = v140 + 1; // 0x1c20
    *currlen = v146;
    int64_t v147 = v146; // 0x1c2e
    int64_t v148 = v144; // 0x1c2e
    while (v87 - (v101 + 0xffffffff & 0xffffffff) + (int64_t)v23 != v144) {
        // 0x1c10
        v144 = v148 - 1;
        if (v147 < maxlen) {
            // 0x1c15
            *(char *)(v145 + v84) = *(char *)v144;
        }
        // 0x1c20
        v146 = v147 + 1;
        *currlen = v146;
        v147 = v146;
        v148 = v144;
    }
    if (v13 != 0) {
        int64_t v149 = v146; // 0x1c38
        if (v146 < maxlen) {
            // 0x1c3a
            *(char *)(v146 + v84) = 46;
            v149 = v83;
        }
        int64_t v150 = v149 + 1; // 0x1c41
        *currlen = v150;
        int64_t v151 = v150; // 0x1c4a
        if ((int32_t)v108 >= 1) {
            int64_t v152 = v151;
            int64_t v153 = v152; // 0x1c53
            if (v152 < maxlen) {
                // 0x1c55
                *(char *)(v152 + v84) = 48;
                v153 = v83;
            }
            int64_t v154 = v153 + 1; // 0x1c5c
            *currlen = v154;
            uint32_t v155 = (int32_t)(v108 & 0xffffffff) - 1; // 0x1c63
            int64_t v156 = v155; // 0x1c66
            while (v155 != 0) {
                // 0x1c50
                v152 = v154;
                v153 = v152;
                if (v152 < maxlen) {
                    // 0x1c55
                    *(char *)(v152 + v84) = 48;
                    v153 = v83;
                }
                // 0x1c5c
                v154 = v153 + 1;
                *currlen = v154;
                v155 = (int32_t)v156 - 1;
                v156 = v155;
            }
        }
        if (v109 != 0) {
            int64_t v157 = v122 - 1;
            if (v83 < maxlen) {
                // 0x1c8d
                *(char *)(v83 + v84) = *(char *)v157;
            }
            int64_t v158 = v83 + 1; // 0x1c98
            *currlen = v158;
            int64_t v159 = v157; // 0x1ca6
            while (367 - (v109 + 0xffffffff & 0xffffffff) + v121 != v157) {
                int64_t v160 = v158;
                v157 = v159 - 1;
                int64_t v161 = v160; // 0x1c8b
                if (v160 < maxlen) {
                    // 0x1c8d
                    *(char *)(v160 + v84) = *(char *)v157;
                    v161 = v83;
                }
                // 0x1c98
                v158 = v161 + 1;
                *currlen = v158;
                v159 = v157;
            }
        }
    }
    // 0x1ca8
    if ((int32_t)v141 == 0) {
        // 0x1cc9
        return;
    }
    if (v83 < maxlen) {
        // 0x1cb5
        *(char *)(v83 + v84) = 32;
    }
    int64_t v162 = v83 + 1; // 0x1cbc
    *currlen = v162;
    uint32_t v163 = (int32_t)v141 + 1; // 0x1cc3
    int64_t v164 = v163; // 0x1cc7
    while (v163 != 0) {
        int64_t v165 = v162;
        int64_t v166 = v165; // 0x1cb3
        if (v165 < maxlen) {
            // 0x1cb5
            *(char *)(v165 + v84) = 32;
            v166 = v83;
        }
        // 0x1cbc
        v162 = v166 + 1;
        *currlen = v162;
        v163 = (int32_t)v164 + 1;
        v164 = v163;
    }
  lab_0x1d28:;
    int64_t v167 = v126;
    int64_t v168 = v130;
    v128 = v168;
    v127 = v167;
    if (v168 < maxlen) {
        // 0x1d2d
        *(char *)(v168 + v84) = 48;
        v128 = v83;
        v127 = v167;
    }
    goto lab_0x1d34;
  lab_0x1d34:;
    int64_t v169 = v128 + 1; // 0x1d34
    *currlen = v169;
    uint32_t v170 = (int32_t)v127 - 1; // 0x1d3b
    int64_t v171 = v170; // 0x1d3b
    v140 = v169;
    v141 = v171;
    v130 = v169;
    v126 = v171;
    if (v170 != 0) {
        goto lab_0x1d28;
    } else {
        goto lab_0x1bfd;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1ec0 - 0x27dd
// Line range:    130 - 290
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args) {
    // 0x1ec0
    int64_t v1; // 0x1ec0
    uint64_t v2 = v1;
    int64_t v3 = (int64_t)buffer;
    int64_t v4 = (int64_t)format + 1; // 0x1ed3
    int64_t v5 = v4; // 0x1ed3
    int64_t result2 = 0; // 0x1ee9
    int64_t v6; // 0x1ec0
    int64_t v7; // 0x1ec0
    int64_t v8; // 0x1ec0
    int64_t v9; // 0x1ec0
    char v10; // 0x1ec0
    int64_t v11; // 0x1ec0
    int64_t v12; // 0x1ec0
    if ((char)v2 != 0) {
        int64_t v13 = (int64_t)args;
        int64_t * v14 = (int64_t *)(v13 + 8);
        v6 = v4;
        v7 = v2 % 256;
        v12 = 0;
        while (true) {
          lab_0x1f3e:;
            char v15 = v7; // 0x1f45
            int64_t v16 = v6; // 0x1f48
            char v17 = v15; // 0x1f48
            int64_t v18 = v12; // 0x1f48
            int64_t v19 = v6; // 0x1f48
            int64_t v20 = v12; // 0x1f48
            if (v15 != 37) {
                while (true) {
                  lab_0x1f4a:;
                    uint64_t v21 = v18;
                    int64_t v22 = v16; // 0x1f4d
                    if (v21 < maxlen) {
                        // 0x1f4f
                        *(char *)(v21 + v3) = v17;
                        v22 = v5;
                    }
                    char v23 = *(char *)v22; // 0x1f53
                    int64_t v24 = v22 + 1; // 0x1f56
                    v5 = v24;
                    int64_t v25 = v21 + 1; // 0x1f5a
                    result2 = v25;
                    v16 = v24;
                    v17 = v23;
                    v18 = v25;
                    v19 = v24;
                    v20 = v25;
                    switch (v23) {
                        case 0: {
                            goto lab_0x1ef0_3;
                        }
                        case 37: {
                            goto lab_0x1f69;
                        }
                        default: {
                            goto lab_0x1f4a;
                        }
                    }
                }
            }
          lab_0x1f69:
            // 0x1f69
            v11 = v20;
            unsigned char v26 = *(char *)v19; // 0x1f73
            result2 = v11;
            if (v26 == 0) {
                // break -> 0x1ef0
                break;
            }
            int64_t v27 = v26; // 0x1f73
            int64_t result = v27; // 0x1f8b
            if (v26 < 49) {
                // 0x1f03
                return result;
            }
            int64_t v28 = v19 + 1; // 0x1f7e
            int64_t v29 = (int64_t)g9; // 0x1f9a
            v5 = 0;
            int64_t v30 = v27; // 0x1faa
            int64_t v31 = v28; // 0x1faa
            int32_t v32 = 0; // 0x1faa
            int64_t v33 = v27; // 0x1faa
            int64_t v34 = v28; // 0x1faa
            if ((*(char *)(2 * v27 + v29) & 4) != 0) {
                int64_t v35 = 0xffffffd0 + (0x100000000000000 * v30 >> 56); // 0x1fb6
                int64_t v36 = v35 & 0xffffffff; // 0x1fb6
                v5 = v36;
                unsigned char v37 = *(char *)v31; // 0x1fba
                result2 = v11;
                if (v37 == 0) {
                    // break (via goto) -> 0x1ef0
                    goto lab_0x1ef0_3;
                }
                int64_t v38 = v31 + 1; // 0x1fb2
                int64_t v39 = v37; // 0x1fba
                v31 = v38;
                while ((*(char *)(2 * v39 + v29) & 4) != 0) {
                    // 0x1fac
                    v35 = 10 * v36 + 0xffffffd0 + (0x100000000000000 * v39 >> 56);
                    v36 = v35 & 0xffffffff;
                    v5 = v36;
                    v37 = *(char *)v31;
                    result2 = v11;
                    if (v37 == 0) {
                        // break (via goto) -> 0x1ef0
                        goto lab_0x1ef0_3;
                    }
                    // 0x1fc6
                    v38 = v31 + 1;
                    v39 = v37;
                    v31 = v38;
                }
                // 0x1fd2
                v32 = v35;
                v33 = v39;
                v34 = v38;
            }
            int64_t v40 = v34;
            int64_t v41 = v33; // 0x1fd4
            int64_t v42 = v40; // 0x1fd4
            if (v33 == 42) {
                uint32_t v43 = v32; // 0x2508
                if (v43 < 48) {
                    // 0x250f
                    v5 = *(int64_t *)(v13 + 16) + (int64_t)v43;
                    *args = v43 + 8;
                } else {
                    int64_t v44 = *v14; // 0x2563
                    v5 = v44;
                    *v14 = v44 + 8;
                }
                unsigned char v45 = *(char *)v40; // 0x251a
                result2 = v11;
                if (v45 == 0) {
                    // break -> 0x1ef0
                    break;
                }
                // 0x252c
                v41 = v45;
                v42 = v40 + 1;
            }
            int64_t v46 = v42;
            int64_t v47 = v41; // 0x1fe2
            int64_t v48 = v46; // 0x1fe2
            if ((char)v41 == 46) {
                char v49 = *(char *)v46; // 0x2098
                result2 = v11;
                if (v49 == 0) {
                    // break -> 0x1ef0
                    break;
                }
                int64_t v50 = v46;
                unsigned char v51 = v49;
                int64_t v52 = v50 + 1;
                int64_t v53 = v51;
                while ((*(char *)(2 * v53 + v29) & 4) != 0) {
                    char v54 = *(char *)v52; // 0x20cc
                    result2 = v11;
                    if (v54 == 0) {
                        // break (via goto) -> 0x1ef0
                        goto lab_0x1ef0_3;
                    }
                    v50 = v52;
                    v51 = v54;
                    v52 = v50 + 1;
                    v53 = v51;
                }
                // 0x2450
                v47 = v53;
                v48 = v52;
                if (v51 == 42) {
                    uint32_t v55 = *(int32_t *)&v5; // 0x2458
                    if (v55 < 48) {
                        // 0x2463
                        *args = v55 + 8;
                    } else {
                        // 0x2534
                        *v14 = *v14 + 8;
                    }
                    unsigned char v56 = *(char *)v52; // 0x246e
                    result2 = v11;
                    if (v56 == 0) {
                        // break -> 0x1ef0
                        break;
                    }
                    // 0x2481
                    v47 = v56;
                    v48 = v50 + 2;
                }
            }
            int64_t v57 = v48;
            int64_t v58 = v47;
            switch ((char)v58) {
                case 104: {
                    char v59 = *(char *)v57; // 0x24ee
                    v10 = v59;
                    v9 = v57 + 1;
                    if (v59 == 0) {
                        // break -> 0x1ef0
                        break;
                    }
                    goto lab_0x24a6;
                }
                case 108: {
                    char v60 = *(char *)v57; // 0x2489
                    int64_t v61 = v57 + 1;
                    result2 = v11;
                    v10 = v60;
                    v9 = v61;
                    switch (v60) {
                        case 108: {
                            char v62 = *(char *)v61; // 0x2545
                            v10 = v62;
                            v9 = v57 + 2;
                            if (v62 == 0) {
                                // break -> 0x1ef0
                                break;
                            }
                            goto lab_0x24a6;
                        }
                        case 0: {
                            goto lab_0x1ef0_3;
                        }
                        default: {
                            goto lab_0x24a6;
                        }
                    }
                }
                case 76: {
                    unsigned char v63 = *(char *)v57; // 0x24bf
                    if (v63 == 0) {
                        // break -> 0x1ef0
                        break;
                    }
                    int64_t v64 = (int64_t)v63 + 0xffffffdb; // 0x24cb
                    v8 = v57 + 1;
                    if ((char)v64 < 84) {
                        int32_t v65 = *(int32_t *)((4 * v64 & 1020) + (int64_t)&g3); // 0x24e4
                        return (int64_t)v65 + (int64_t)&g3;
                    }
                    goto lab_0x2133;
                }
                default: {
                    // 0x2000
                    v8 = v57;
                    if ((char)(v58 + 0xffffffdb) < 84) {
                        // 0x200b
                        int64_t v66; // 0x2000
                        int32_t v67 = *(int32_t *)((4 * v66 & 1020) + (int64_t)&g1); // 0x2015
                        return (int64_t)v67 + (int64_t)&g1;
                    }
                    goto lab_0x2133;
                }
            }
        }
    }
  lab_0x1ef0_3:
    // 0x1ef0
    if (maxlen == 0) {
        // 0x1f03
        return result2;
    }
    uint64_t v68 = maxlen - 1;
    if (v68 > result2) {
        // 0x1efe
        *(char *)(result2 + v3) = 0;
        // 0x1f03
        return result2;
    }
    // 0x1f18
    *(char *)(v68 + v3) = 0;
    return result2;
  lab_0x2133:;
    unsigned char v69 = *(char *)v8; // 0x2133
    int64_t v70 = v8 + 1; // 0x2137
    v5 = v70;
    result2 = v11;
    v6 = v70;
    v7 = v69;
    v12 = v11;
    if (v69 == 0) {
        // break -> 0x1ef0
        goto lab_0x1ef0_3;
    }
    goto lab_0x1f3e;
  lab_0x24a6:;
    int64_t v71 = (int64_t)v10 + 0xffffffdb; // 0x24a6
    v8 = v9;
    if ((char)v71 < 84) {
        int32_t v72 = *(int32_t *)((4 * v71 & 1020) + (int64_t)&g2); // 0x24b4
        return (int64_t)v72 + (int64_t)&g2;
    }
    goto lab_0x2133;
}

// Address range: 0x27dd - 0x27e8
int64_t function_27dd(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x27dd
    int64_t v1; // 0x27dd
    return v1 & 0xffffffff;
}

// Address range: 0x27e8 - 0x27f3
int64_t function_27e8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x27e8
    int64_t v1; // 0x27e8
    return v1 & 0xffffffff;
}

// Address range: 0x27f3 - 0x27fe
int64_t function_27f3(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x27f3
    int64_t v1; // 0x27f3
    return v1 & 0xffffffff;
}

// Address range: 0x27fe - 0x2805
int64_t function_27fe(void) {
    // 0x27fe
    int64_t v1; // 0x27fe
    return v1 & 0xffffffff;
}

// Address range: 0x2805 - 0x2810
int64_t function_2805(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2805
    int64_t v1; // 0x2805
    return v1 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2810 - 0x291c
// Line range:    751 - 769
int32_t libmin_printf(char * fmt, ...) {
    // 0x2810
    int64_t v1; // 0x2810
    if ((char)v1 != 0) {
        // 0x284c
        int128_t v2; // 0x2810
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 8; // bp-1248, 0x28b6
    char v4; // bp-1224, 0x2810
    dopr(&v4, (int64_t)&g7, fmt, (int32_t *)&v3);
    if (v4 == 0) {
        // 0x2910
        return 0;
    }
    int64_t v5 = &v4;
    libtarg_putc(v4);
    int64_t v6 = v5 + 1; // 0x28f9
    char v7 = *(char *)v6; // 0x28f9
    while (v7 != 0) {
        // 0x28f0
        v5 = v6;
        libtarg_putc(v7);
        v6 = v5 + 1;
        v7 = *(char *)v6;
    }
    // 0x2906
    int64_t v8; // bp+1225, 0x2810
    return v5 + (int64_t)&v8;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2920 - 0x29cb
// Line range:    772 - 782
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...) {
    // 0x2920
    int64_t v1; // 0x2920
    if ((char)v1 != 0) {
        // 0x2946
        int128_t v2; // 0x2920
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 24; // bp-224, 0x299a
    dopr(s, size, fmt, (int32_t *)&v3);
    *(char *)((int64_t)s - 1 + size) = 0;
    return libmin_strlen(s);
}

// Address range: 0x29d0 - 0x2a23
int64_t libmin_srand(void) {
    // 0x29d0
    mt_initialized = 1;
    int64_t v1 = (int64_t)&mt;
    int64_t v2 = v1 + 4; // 0x29f9
    int64_t v3; // 0x29d0
    int64_t v4 = 0x10dcd * v3 + 1; // 0x29fd
    int64_t v5 = 0x10dcd * v4; // 0x2a02
    *(int32_t *)v1 = (int32_t)v4 / 0x10000 | (int32_t)v3 & -0x10000;
    v3 = v5 + 1 & 0xffffffff;
    while (v2 != (int64_t)&g15) {
        // 0x29f0
        v1 = v2;
        v2 = v1 + 4;
        v4 = 0x10dcd * v3 + 1;
        v5 = 0x10dcd * v4;
        *(int32_t *)v1 = (int32_t)v4 / 0x10000 | (int32_t)v3 & -0x10000;
        v3 = v5 + 1 & 0xffffffff;
    }
    // 0x2a18
    mti = 624;
    return v5 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_rand.c
// Address range: 0x2a30 - 0x2bd5
// Line range:    42 - 30
int32_t libmin_rand(void) {
    // 0x2a30
    if (mt_initialized == 0) {
        // 0x2b68
        libmin_printf("ERROR: rng is not initialized, call mysrand()!\n");
        libmin_fail(1);
        // UNREACHABLE
    }
    int32_t v1 = mti; // 0x2a46
    int32_t v2; // 0x2a30
    int32_t v3; // 0x2a30
    if (v1 > 623) {
        if (v1 == 625) {
            // 0x2b85
            mt_initialized = 1;
            int64_t v4 = 0x1105; // 0x2ba2
            int64_t v5 = (int64_t)&mt;
            int64_t v6 = v5 + 4; // 0x2bb1
            int64_t v7 = 0x10dcd * v4 + 1; // 0x2bb5
            *(int32_t *)v5 = (int32_t)v7 / 0x10000 | (int32_t)v4 & -0x10000;
            v4 = 0x10dcd * v7 + 1 & 0xffffffff;
            while (v6 != (int64_t)&g15) {
                // 0x2ba8
                v5 = v6;
                v6 = v5 + 4;
                v7 = 0x10dcd * v4 + 1;
                *(int32_t *)v5 = (int32_t)v7 / 0x10000 | (int32_t)v4 & -0x10000;
                v4 = 0x10dcd * v7 + 1 & 0xffffffff;
            }
        }
        int64_t v8 = (int64_t)&mt;
        int32_t * v9 = (int32_t *)v8; // 0x2ac0
        int64_t v10 = v8 + 4; // 0x2ac2
        int32_t v11 = *(int32_t *)v10; // 0x2ac2
        int32_t v12 = *(int32_t *)(v8 + 1588); // 0x2add
        int32_t v13 = *(int32_t *)((int64_t)(4 * v11 & 4) | (int64_t)&g4); // 0x2ae3
        *v9 = v13 ^ v12 ^ (v11 & 0x7ffffffe | *v9 & -0x80000000) / 2;
        int64_t v14 = (int64_t)&mt; // 0x2aec
        while (v10 != (int64_t)&g12) {
            // 0x2ac0
            v8 = v10;
            v9 = (int32_t *)v8;
            v10 = v8 + 4;
            v11 = *(int32_t *)v10;
            v12 = *(int32_t *)(v8 + 1588);
            v13 = *(int32_t *)((int64_t)(4 * v11 & 4) | (int64_t)&g4);
            *v9 = v13 ^ v12 ^ (v11 & 0x7ffffffe | *v9 & -0x80000000) / 2;
            v14 = (int64_t)&mt;
        }
        int32_t v15 = *(int32_t *)(v14 + (int64_t)&g5); // 0x2af8
        int32_t v16 = *(int32_t *)(v14 + (int64_t)&g6); // 0x2afe
        int64_t v17 = v14 + 4; // 0x2b04
        int32_t v18 = *(int32_t *)v14; // 0x2b1c
        int32_t v19 = *(int32_t *)((int64_t)(4 * v16 & 4) | (int64_t)&g4); // 0x2b1f
        *(int32_t *)(v14 + 908) = v19 ^ v18 ^ (v16 & 0x7ffffffe | v15 & -0x80000000) / 2;
        v14 = v17;
        while (v17 != (int64_t)&g13) {
            // 0x2af8
            v15 = *(int32_t *)(v14 + (int64_t)&g5);
            v16 = *(int32_t *)(v14 + (int64_t)&g6);
            v17 = v14 + 4;
            v18 = *(int32_t *)v14;
            v19 = *(int32_t *)((int64_t)(4 * v16 & 4) | (int64_t)&g4);
            *(int32_t *)(v14 + 908) = v19 ^ v18 ^ (v16 & 0x7ffffffe | v15 & -0x80000000) / 2;
            v14 = v17;
        }
        int32_t v20 = mt[0]; // 0x2b2d
        int32_t v21 = *(int32_t *)((int64_t)(4 * v20 & 4) | (int64_t)&g4); // 0x2b55
        g14 = v21 ^ g13 ^ (g14 & -0x80000000 | v20 & 0x7ffffffe) / 2;
        v2 = v20;
        v3 = 1;
    } else {
        // 0x2a54
        v2 = *(int32_t *)(4 * (int64_t)v1 + (int64_t)&mt);
        v3 = v1 + 1;
    }
    uint32_t v22 = v2;
    mti = v3;
    int32_t v23 = v22 / 2048 ^ v22; // 0x2a70
    int32_t v24 = 128 * v23 & -0x62d3a980 ^ v23; // 0x2a7c
    uint32_t v25 = 0x8000 * v24 & -0x103a0000 ^ v24; // 0x2a89
    return v25 / 0x40000 ^ v25 % 0x80000000;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_sqrt.c
// Address range: 0x2be0 - 0x2dee
// Line range:    74 - 102
float64_t libmin_sqrt(float64_t x) {
    int128_t v1 = (float32_t)x;
    uint64_t v2 = __asm_movq_7(v1); // 0x2be4
    if (v2 % 0x7ff0000000000001 == 0x7ff0000000000000) {
        // 0x2dc0
        return (int64_t)__asm_addsd(v1, __asm_mulsd_6(__asm_movapd(v1), v1));
    }
    int64_t v3 = v2 / 0x100000000; // 0x2be9
    int32_t v4 = __asm_movd(v1); // 0x2c01
    int64_t v5 = v4; // 0x2c01
    int32_t v6 = v3; // 0x2c05
    int64_t v7; // 0x2be0
    int64_t v8; // 0x2be0
    int64_t v9; // 0x2be0
    int64_t v10; // 0x2be0
    int64_t v11; // 0x2be0
    int64_t v12; // 0x2be0
    int64_t v13; // 0x2be0
    int64_t v14; // 0x2be0
    int64_t v15; // 0x2be0
    int64_t v16; // 0x2be0
    if (v6 < 1) {
        // 0x2cf0
        if ((v4 || (v6 == 0 ? 0 : v6 ^ -0x80000000)) == 0) {
            // 0x2dbc
            return x;
        }
        // 0x2cff
        if (v2 >= 0x100000000) {
            int128_t v17 = __asm_subsd_4(v1, v1); // 0x2dcd
            return (int64_t)__asm_divsd_5(v17, v17);
        }
        int64_t v18 = 0;
        uint64_t v19 = v5;
        int64_t v20 = v18 + 0xffffffeb & 0xffffffff; // 0x2d12
        int64_t v21 = 0x200000 * v19 & 0xffe00000; // 0x2d15
        int64_t v22 = v19 / 2048 % 0x200000; // 0x2d18
        while (v22 == 0) {
            // 0x2d10
            v18 = v20;
            v19 = v21;
            v20 = v18 + 0xffffffeb & 0xffffffff;
            v21 = 0x200000 * v19 & 0xffe00000;
            v22 = v19 / 2048 % 0x200000;
        }
        // 0x2d1f
        v10 = v22;
        v13 = v21;
        v16 = v20;
        if ((int32_t)v19 <= -1) {
            // 0x2d4c
            v7 = v18 + 0xffffffec & 0xffffffff;
            v8 = v21;
            v14 = v21;
            v11 = v22;
            goto lab_dec_label_pc_unknown;
        } else {
            goto lab_0x2d2a;
        }
    } else {
        // 0x2c0d
        v9 = v3;
        v12 = v5;
        v15 = v2 / 0x10000000000000;
        v10 = v3;
        v13 = v5;
        v16 = 0;
        if (v2 < 0x10000000000000) {
            goto lab_0x2d2a;
        } else {
            goto lab_0x2c1a;
        }
    }
  lab_0x2d60:;
    // 0x2d60
    int32_t v23; // 0x2be0
    int32_t v24 = v23; // 0x2d6e
    int64_t v25; // 0x2be0
    int64_t v26 = v25; // 0x2d6e
    int64_t v27; // 0x2be0
    int64_t v28 = v27 + (int64_t)((int32_t)v25 > -1); // 0x2d6e
    goto lab_0x2ce1;
  lab_0x2ce1:;
    int64_t v29 = v26; // 0x2ce5
    int64_t v30 = v28; // 0x2ce5
    int64_t v31; // 0x2be0
    int64_t v32; // 0x2be0
    int64_t v33 = v32 - v27 + (int64_t)(v24 > (int32_t)v31) & 0xffffffff; // 0x2ce5
    goto lab_0x2cb0;
  lab_0x2cb8:;
    // 0x2cb8
    int64_t v40; // 0x2be0
    int64_t v42 = v40;
    int64_t v35; // 0x2be0
    int64_t v43 = 2 * v35; // 0x2cbc
    int64_t v36; // 0x2be0
    int64_t v44 = 2 * v36; // 0x2cc1
    int32_t v45; // 0x2be0
    int32_t v46 = v45 - 1; // 0x2cc4
    int64_t v47 = v43 & 0xfffffffe; // 0x2cc8
    int64_t v48 = v44 & 0xfffffffe; // 0x2cc8
    uint64_t v41; // 0x2be0
    int64_t v49 = v41 / 2; // 0x2cc8
    int64_t v37; // 0x2be0
    int64_t v50 = v37; // 0x2cc8
    int64_t v38; // 0x2be0
    int64_t v51 = v38; // 0x2cc8
    v45 = v46;
    int64_t v52 = v42; // 0x2cc8
    if (v46 == 0) {
        // break -> 0x2d78
        goto lab_0x2d78;
    }
    goto lab_0x2cce;
  lab_0x2cb0:;
    // 0x2cb0
    int64_t v34; // 0x2cce
    v35 = v31 - v34 & 0xffffffff;
    v36 = v33;
    v37 = v30 & 0xffffffff;
    v38 = v29;
    int64_t v39; // 0x2be0
    v40 = v39 + v41 & 0xffffffff;
    goto lab_0x2cb8;
  lab_0x2d2a:;
    int64_t v58 = 0;
    int64_t v59 = v10;
    int64_t v60 = 2 * v59 & 0xfffffffe; // 0x2d30
    int64_t v61 = v58 + 1; // 0x2d34
    while ((v59 & 0x80000) == 0) {
        // 0x2d30
        v58 = v61 & 0xffffffff;
        v59 = v60;
        v60 = 2 * v59 & 0xfffffffe;
        v61 = v58 + 1;
    }
    uint32_t v62 = (int32_t)v61 % 32; // 0x2d47
    uint32_t v63 = (int32_t)v13;
    int64_t v64 = v62 == 0 ? v13 : (int64_t)(v63 << v62);
    uint32_t v65 = (31 - (int32_t)v58) % 32;
    int64_t v66 = v16 - v58 & 0xffffffff; // 0x2d4f
    v7 = v66;
    v8 = v13 & 0xffffffff;
    v14 = v64;
    v11 = v60;
    int64_t v67 = v66; // 0x2be0
    int64_t v68 = v64; // 0x2be0
    int64_t v69 = v60; // 0x2be0
    int64_t v70 = v63 >> v65; // 0x2be0
    if (v65 == 0) {
        goto lab_dec_label_pc_unknown;
    } else {
        goto lab_dec_label_pc_unknown_2;
    }
  lab_0x2c1a:;
    uint64_t v71 = v15;
    int64_t v72 = v12;
    int64_t v73 = v9 % 0x100000 | 0x100000; // 0x2c20
    int64_t v74 = v73; // 0x2c2f
    int64_t v75 = v72; // 0x2c2f
    if (v71 % 2 == 0) {
        // 0x2c31
        v74 = 2 * v73 | (int64_t)(v72 < 0);
        v75 = 2 * v72 & 0xfffffffe;
    }
    int64_t v76 = 0; // 0x2c57
    int64_t v77 = 0;
    uint64_t v78 = 0x200000;
    int64_t v79 = 2 * v74 & 0xfffffffe | (int64_t)(v75 < 0);
    int64_t v80 = v76 + v78; // 0x2c60
    int64_t v81 = v79; // 0x2c65
    int64_t v82 = v77; // 0x2c65
    int64_t v83 = v76; // 0x2c65
    if (v79 >= (v80 & 0xffffffff)) {
        // 0x2c67
        v81 = v79 - v80 & 0xffffffff;
        v82 = v77 + v78 & 0xffffffff;
        v83 = v80 + v78 & 0xffffffff;
    }
    int64_t v84 = v82;
    int64_t v85 = 2 * (2 * v75 & 0xfffffffe) & 0xfffffffc; // 0x2c72
    int64_t v86 = 2 * v81 & 0xfffffffe;
    int32_t v87 = 21; // 0x2c7a
    int64_t v88 = v85; // 0x2c7e
    int64_t v89 = v78 / 2; // 0x2c7e
    v76 = v83;
    int32_t v90 = v87; // 0x2c7e
    v47 = v85;
    v48 = v86;
    v49 = 0x80000000;
    v50 = v83;
    v51 = 0;
    v45 = 32;
    v52 = 0;
    while (v87 != 0) {
        // 0x2c60
        v77 = v84;
        v78 = v89;
        v79 = v86;
        v80 = v76 + v78;
        v81 = v79;
        v82 = v77;
        v83 = v76;
        if (v79 >= (v80 & 0xffffffff)) {
            // 0x2c67
            v81 = v79 - v80 & 0xffffffff;
            v82 = v77 + v78 & 0xffffffff;
            v83 = v80 + v78 & 0xffffffff;
        }
        // 0x2c6e
        v84 = v82;
        v85 = 2 * v88 & 0xfffffffc;
        v86 = 2 * v81 & 0xfffffffe;
        v87 = v90 - 1;
        v88 = v85;
        v89 = v78 / 2;
        v76 = v83;
        v90 = v87;
        v47 = v85;
        v48 = v86;
        v49 = 0x80000000;
        v50 = v83;
        v51 = 0;
        v45 = 32;
        v52 = 0;
    }
    while (true) {
      lab_0x2cce:
        // 0x2cce
        v39 = v52;
        int64_t v53 = v51;
        v27 = v50;
        v41 = v49;
        v32 = v48;
        v31 = v47;
        v34 = v53 + v41;
        if (v32 > v27) {
            int64_t v54 = v34 + v41 & 0xffffffff; // 0x2cd6
            int32_t v55 = v34;
            v24 = v55;
            v26 = v54;
            v28 = v27;
            v23 = v55;
            v25 = v54;
            if (v55 < 0) {
                goto lab_0x2d60;
            } else {
                goto lab_0x2ce1;
            }
        } else {
            // 0x2c90
            v35 = v31;
            v36 = v32;
            v37 = v27;
            v38 = v53;
            v40 = v39;
            if ((int32_t)v32 != (int32_t)v27) {
                goto lab_0x2cb8;
            } else {
                int32_t v56 = v34;
                if (v56 > (int32_t)v31) {
                    goto lab_0x2cb8;
                } else {
                    int64_t v57 = v34 + v41 & 0xffffffff; // 0x2c96
                    v29 = v57;
                    v30 = v27;
                    v33 = 0;
                    v23 = v56;
                    v25 = v57;
                    if (v56 < 0) {
                        goto lab_0x2d60;
                    } else {
                        goto lab_0x2cb0;
                    }
                }
            }
        }
    }
  lab_0x2d78:;
    int64_t v91 = v42; // 0x2d7a
    int64_t v92; // 0x2be0
    int64_t v93; // 0x2d9c
    int128_t v94; // 0x2db6
    if ((int32_t)(v44 || v43) != 0) {
        if ((int32_t)v42 == -1) {
            // 0x2d8c
            v92 = 0;
            uint64_t v95 = v84 + 1 & 0xffffffff;
            v93 = v95 % 2 != 0 ? v92 | 0x80000000 : v92;
            v94 = __asm_movq(0x100000000 * ((0x80000 * v71 + 0xe0080000 & 0xfff00000) + 0x3fe00000 + (int64_t)((int32_t)v95 >> 1)) | v93);
            return (int64_t)v94;
        }
        // 0x2d82
        v91 = v42 + 1 & 0xffffffff;
    }
    // 0x2d8c
    v92 = v91 / 2 % 0x80000000;
    v93 = v84 % 2 != 0 ? v92 | 0x80000000 : v92;
    v94 = __asm_movq(0x100000000 * ((0x80000 * v71 + 0xe0080000 & 0xfff00000) + 0x3fe00000 + (int64_t)((int32_t)v84 >> 1)) | v93);
    return (int64_t)v94;
  lab_dec_label_pc_unknown:
    v67 = v7;
    v68 = v14;
    v69 = v11;
    v70 = v8;
    goto lab_dec_label_pc_unknown_2;
  lab_dec_label_pc_unknown_2:
    v9 = v70 | v69;
    v12 = v68;
    v15 = v67;
    goto lab_0x2c1a;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_strlen.c
// Address range: 0x2df0 - 0x2e1b
// Line range:    5 - 15
int64_t libmin_strlen(char * str) {
    int64_t v1 = (int64_t)str;
    if (str == NULL || (char)v1 == 0) {
        // 0x2e18
        return 0;
    }
    int64_t v2 = v1; // 0x2df7
    v2++;
    while (*(char *)v2 != 0) {
        // 0x2e08
        v2++;
    }
    // 0x2e11
    return v2 - v1;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_success.c
// Address range: 0x2e20 - 0x2e29
// Line range:    5 - 7
void libmin_success(void) {
    // 0x2e20
    libtarg_success();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_ctype.c
// Address range: 0x2e30 - 0x2e52
// Line range:    140 - 146
int32_t _isctype(uint32_t c, int32_t mask) {
    int32_t result = 0; // 0x2e3f
    if (c < 256) {
        uint16_t v1 = *(int16_t *)((0x100000000 * (int64_t)c >> 31) + (int64_t)g9); // 0x2e4b
        result = (int32_t)v1 & mask;
    }
    // 0x2e51
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fail.c
// Address range: 0x2e60 - 0x2e7f
// Line range:    5 - 8
void libmin_fail(uint32_t code) {
    // 0x2e60
    libmin_printf("ERROR: failure with termination code `%d'\n", (int64_t)code);
    libtarg_fail(code);
}

// Address range: 0x2e80 - 0x2e8d
int64_t _fini(void) {
    // 0x2e80
    int64_t result; // 0x2e80
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 39

