//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;
typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int32_t _isctype(uint32_t c, int32_t mask);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t deregister_tm_clones(void);
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args);
int128_t dot_prod(int64_t a1, int64_t a2);
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags);
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags);
int64_t frame_dummy(void);
void function_1070(int64_t * d);
void function_1080(void);
int32_t function_1090(int32_t c, struct _IO_FILE * stream);
int64_t * function_10a0(int64_t delta);
void function_10b0(int32_t status);
int64_t function_2e3d(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2e48(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2e53(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2e5e(void);
int64_t function_2e65(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
float64_t get_angle(int32_t * a, int32_t * b);
int64_t get_cross_matrix(int32_t * a);
float64_t libmin_acos(float64_t x);
float64_t libmin_fabs(float64_t x);
float32_t libmin_fabsf(float32_t x);
void libmin_fail(uint32_t code);
int32_t libmin_printf(char * fmt, ...);
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...);
float64_t libmin_sqrt(float64_t x);
int64_t libmin_strlen(char * str);
void libmin_success(void);
void libtarg_fail(int32_t code);
void libtarg_putc(char c);
char * libtarg_sbrk(int64_t inc);
void libtarg_success(void);
int64_t my_modf_isra_0(int64_t a1);
char * print_vector(int32_t * a, char * name);
int64_t register_tm_clones(void);
int64_t unit_vec(int32_t * a);
int64_t vector_add(int32_t * a, int32_t * b);
int64_t vector_norm(int64_t * a1);
int64_t vector_prod(int32_t * a, int32_t * b);
int64_t vector_sub(int32_t * a, int32_t * b);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x400
int64_t g2 = -0x1a6c000018c9; // 0x4200
int64_t g3 = -0x1bbc00001a19; // 0x4350
int64_t g4 = -0x1d0c00001b69; // 0x44a0
int64_t g5 = 0x20002000200020; // 0x6022
struct _IO_FILE * g7 = NULL; // 0x6240
char g8 = 0; // 0x6248
char * g9; // 0x6260
float64_t pio2_lo = 6.123233995736766e-17; // 0x6010
int32_t g10;
int64_t * g6 = &g5; // 0x6228

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x5fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g10;
    }
    // 0x1016
    return result;
}

// Address range: 0x1070 - 0x107b
void function_1070(int64_t * d) {
    // 0x1070
    __cxa_finalize(d);
}

// Address range: 0x1080 - 0x108b
void function_1080(void) {
    // 0x1080
    __stack_chk_fail();
}

// Address range: 0x1090 - 0x109b
int32_t function_1090(int32_t c, struct _IO_FILE * stream) {
    // 0x1090
    return fputc(c, stream);
}

// Address range: 0x10a0 - 0x10ab
int64_t * function_10a0(int64_t delta) {
    // 0x10a0
    return sbrk(delta);
}

// Address range: 0x10b0 - 0x10bb
void function_10b0(int32_t status) {
    // 0x10b0
    exit(status);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x10c0 - 0x13e0
// Line range:    344 - 350
int main() {
    // 0x10c0
    __readfsqword(40);
    int64_t v1 = 0x3ff0000000000000; // bp-136, 0x1101
    int64_t v2 = 0x3ff0000000000000; // bp-104, 0x1125
    char * v3 = print_vector((int32_t *)&v1, "a"); // 0x1134
    libmin_printf("%s", v3);
    char * v4 = print_vector((int32_t *)&v2, "b"); // 0x1150
    libmin_printf("%s", v4);
    vector_norm(&v1);
    int128_t v5; // 0x10c0
    int64_t v6 = __asm_movsd(v5); // 0x1176
    libmin_printf("|a| = %.4lf\n");
    int128_t v7 = __asm_movsd_1(v6); // 0x1181
    float64_t v8 = libmin_fabs((float64_t)(int64_t)__asm_subsd(v7, 0x400def9db22d0e56)); // 0x118f
    __asm_comisd(__asm_movsd_1(0x3f847ae147ae147b), (int128_t)(int32_t)(float32_t)v8);
    libmin_fail(1);
    // UNREACHABLE
}

// Address range: 0x13e0 - 0x1406
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x13e0
    int64_t v1; // 0x13e0
    __libc_start_main(0x10c0, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1410 - 0x1439
int64_t deregister_tm_clones(void) {
    // 0x1410
    return 0x6230;
}

// Address range: 0x1440 - 0x1479
int64_t register_tm_clones(void) {
    // 0x1440
    return 0;
}

// Address range: 0x1480 - 0x14b9
int64_t __do_global_dtors_aux(void) {
    // 0x1480
    if (g8 != 0) {
        // 0x14b8
        int64_t result; // 0x1480
        return result;
    }
    // 0x148d
    if (*(int64_t *)0x5ff8 != 0) {
        // 0x149b
        __cxa_finalize((int64_t *)*(int64_t *)0x6008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x14a7
    g8 = 1;
    return result2;
}

// Address range: 0x14c0 - 0x14c9
int64_t frame_dummy(void) {
    // 0x14c0
    return register_tm_clones();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x14d0 - 0x1506
// Line range:    129 - 137
int64_t vector_sub(int32_t * a, int32_t * b) {
    int64_t v1 = (int64_t)b;
    int64_t result = (int64_t)a;
    int128_t v2 = __asm_movsd_1(*(int64_t *)(v1 + 8)); // 0x14d4
    int64_t v3; // 0x14d0
    int128_t v4 = __asm_subsd(__asm_movsd_1(v1), v3); // 0x14e0
    int128_t v5 = __asm_movapd(v2); // 0x14e4
    int128_t v6 = __asm_movsd_1(*(int64_t *)(v1 + 16)); // 0x14e8
    int128_t v7 = __asm_subsd(v5, *(int64_t *)(v3 + 8)); // 0x14ed
    int128_t v8 = __asm_subsd(v6, *(int64_t *)(v3 + 16)); // 0x14f2
    *(int64_t *)a = __asm_movsd(v4);
    *(int64_t *)(result + 8) = __asm_movsd(v7);
    *(int64_t *)(result + 16) = __asm_movsd(v8);
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x1510 - 0x1546
// Line range:    147 - 155
int64_t vector_add(int32_t * a, int32_t * b) {
    int64_t v1 = (int64_t)b;
    int64_t result = (int64_t)a;
    int128_t v2 = __asm_movsd_1(*(int64_t *)(v1 + 8)); // 0x1514
    int64_t v3; // 0x1510
    int128_t v4 = __asm_movsd_1(*(int64_t *)(v3 + 8)); // 0x1519
    int128_t v5 = __asm_addsd_2(__asm_movsd_1(v1), v3); // 0x1525
    int128_t v6 = __asm_addsd(v4, v2); // 0x1529
    int128_t v7 = __asm_addsd_2(__asm_movsd_1(*(int64_t *)(v1 + 16)), *(int64_t *)(v3 + 16)); // 0x1532
    *(int64_t *)a = __asm_movsd(v5);
    *(int64_t *)(result + 8) = __asm_movsd(v6);
    *(int64_t *)(result + 16) = __asm_movsd(v7);
    return result;
}

// Address range: 0x1550 - 0x1579
int128_t dot_prod(int64_t a1, int64_t a2) {
    int128_t v1 = __asm_movsd_1(a1); // 0x1554
    int128_t v2 = __asm_movsd_1(*(int64_t *)(a1 + 8)); // 0x1558
    int128_t v3 = __asm_addsd(__asm_mulsd(v2, *(int64_t *)(a2 + 8)), __asm_mulsd(v1, a2)); // 0x1566
    int128_t v4 = __asm_movsd_1(*(int64_t *)(a1 + 16)); // 0x156a
    return __asm_addsd(__asm_mulsd(v4, *(int64_t *)(a2 + 16)), v3);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x1580 - 0x15de
// Line range:    191 - 200
int64_t vector_prod(int32_t * a, int32_t * b) {
    int64_t v1 = (int64_t)b;
    int64_t result = (int64_t)a;
    int128_t v2 = __asm_movsd_1(*(int64_t *)(v1 + 8)); // 0x1584
    int128_t v3 = __asm_movsd_1(*(int64_t *)(v1 + 16)); // 0x1589
    int64_t v4; // 0x1580
    int128_t v5 = __asm_movsd_1(*(int64_t *)(v4 + 16)); // 0x1591
    int128_t v6 = __asm_movsd_1(*(int64_t *)(v4 + 8)); // 0x1596
    int128_t v7 = __asm_movsd_1(v1); // 0x159b
    int128_t v8 = __asm_movsd_1(v4); // 0x159f
    int128_t v9 = __asm_movapd(v2); // 0x15a3
    int128_t v10 = __asm_mulsd_3(__asm_movapd(v3), v6); // 0x15ab
    int128_t v11 = __asm_mulsd_3(v9, v5); // 0x15af
    int128_t v12 = __asm_mulsd_3(v3, v8); // 0x15b3
    int128_t v13 = __asm_mulsd_3(v5, v7); // 0x15b7
    int128_t v14 = __asm_mulsd_3(v6, v7); // 0x15bb
    int128_t v15 = __asm_mulsd_3(v2, v8); // 0x15bf
    int128_t v16 = __asm_subsd_4(v11, v10); // 0x15c3
    int128_t v17 = __asm_subsd_4(v12, v13); // 0x15c7
    *(int64_t *)a = __asm_movsd(v16);
    int128_t v18 = __asm_subsd_4(v14, v15); // 0x15cf
    *(int64_t *)(result + 8) = __asm_movsd(v17);
    *(int64_t *)(result + 16) = __asm_movsd(v18);
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x15e0 - 0x161d
// Line range:    208 - 216
char * print_vector(int32_t * a, char * name) {
    int64_t v1 = (int64_t)a;
    int128_t v2 = __asm_movsd_1(v1); // 0x15ed
    int128_t v3 = __asm_movsd_1(*(int64_t *)(v1 + 16)); // 0x15f4
    int128_t v4 = __asm_movsd_1(*(int64_t *)(v1 + 8)); // 0x15f9
    libmin_snprintf((char *)&g9, 99, "vec(%s) = (%.0lf)i + (%.0lf)j + (%.0lf)k\n", name, (float64_t)(int64_t)v2, (float64_t)(int64_t)v4, (float64_t)(int64_t)v3);
    return (char *)&g9;
}

// Address range: 0x1620 - 0x164f
int64_t vector_norm(int64_t * a1) {
    int64_t v1 = (int64_t)a1;
    int128_t v2 = __asm_movsd_1(v1); // 0x1624
    int128_t v3 = __asm_mulsd_3(__asm_movapd(v2), v2); // 0x162c
    int128_t v4 = __asm_movsd_1(*(int64_t *)(v1 + 8)); // 0x1630
    int128_t v5 = __asm_addsd(v3, __asm_mulsd_3(v4, v4)); // 0x1639
    int128_t v6 = __asm_movsd_1(*(int64_t *)(v1 + 16)); // 0x163d
    int128_t v7 = __asm_addsd(__asm_mulsd_3(v6, v6), v5); // 0x1646
    return libmin_sqrt((float64_t)(int64_t)v7);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x1650 - 0x1716
// Line range:    238 - 252
int64_t unit_vec(int32_t * a) {
    // 0x1650
    int64_t v1; // bp-16, 0x1650
    int64_t v2 = (int64_t)&v1 - 24; // 0x165d
    int64_t v3; // 0x1650
    int128_t v4 = __asm_movsd_1(v3); // 0x1661
    int128_t v5 = __asm_mulsd_3(__asm_movapd(v4), v4); // 0x1669
    int64_t * v6 = (int64_t *)(v3 + 8); // 0x166d
    int128_t v7 = __asm_movsd_1(*v6); // 0x166d
    int128_t v8 = __asm_addsd(v5, __asm_mulsd_3(v7, v7)); // 0x1676
    int64_t * v9 = (int64_t *)(v3 + 16); // 0x167a
    int128_t v10 = __asm_movsd_1(*v9); // 0x167a
    int128_t v11 = __asm_mulsd_3(v10, v10); // 0x167f
    float64_t v12 = libmin_sqrt((float64_t)(int64_t)__asm_addsd(v11, v8)); // 0x1687
    int64_t v13 = __asm_movsd((int128_t)(int32_t)(float32_t)v12); // 0x168c
    int128_t v14 = (float32_t)libmin_fabs(v12); // 0x1692
    int128_t v15 = __asm_movsd_1(0x3e112e0be826d695); // 0x1697
    __asm_comisd(v15, v14);
    int128_t v16; // 0x1650
    int128_t v17; // 0x1650
    int128_t v18; // 0x1650
    if (&v1 < (int64_t *)24 || v2 == 0) {
        unsigned char v19 = llvm_ctpop_i8((char)v2); // 0x165d
        int128_t v20 = __asm_movsd_1(v13); // 0x16a5
        __asm_ucomisd(v20, 0x3ff0000000000000);
        if (v2 != 0 || v19 % 2 == 0) {
            int128_t v21 = __asm_movsd_1(v3); // 0x16e8
            int128_t v22 = __asm_movsd_1(*v6); // 0x16ec
            int128_t v23 = __asm_movsd_1(*v9); // 0x16f1
            int128_t v24 = __asm_divsd(v21, v20); // 0x16f6
            int128_t v25 = __asm_divsd(v22, v20); // 0x16fa
            v16 = v24;
            v17 = __asm_divsd(v23, v20);
            v18 = v25;
        } else {
            int128_t v26 = __asm_pxor(v15, v15); // 0x16b7
            int128_t v27 = __asm_movapd(v26); // 0x16bb
            v16 = __asm_movapd(v26);
            v17 = v26;
            v18 = v27;
        }
    } else {
        int128_t v28 = __asm_pxor(v14, v14); // 0x1708
        int128_t v29 = __asm_movapd(v28); // 0x170c
        int128_t v30 = __asm_movapd(v28); // 0x1710
        v16 = v28;
        v17 = v30;
        v18 = v29;
    }
    int64_t result = (int64_t)a;
    *(int64_t *)a = __asm_movsd(v16);
    *(int64_t *)(result + 8) = __asm_movsd(v18);
    *(int64_t *)(result + 16) = __asm_movsd(v17);
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x1720 - 0x1787
// Line range:    270 - 274
int64_t get_cross_matrix(int32_t * a) {
    int64_t result = (int64_t)a;
    int64_t v1; // 0x1720
    int128_t v2 = __asm_movsd_1(*(int64_t *)(v1 + 16)); // 0x1724
    int128_t v3 = __asm_movsd_1(v1); // 0x1729
    *(int64_t *)a = 0;
    int128_t v4 = __asm_movq_5(-0x8000000000000000); // 0x1737
    int128_t v5 = __asm_movsd_1(*(int64_t *)(v1 + 8)); // 0x173f
    *(int64_t *)(result + 32) = 0;
    int128_t v6 = __asm_movapd(v2); // 0x174c
    *(int64_t *)(result + 24) = __asm_movsd(v2);
    int128_t v7 = __asm_movapd(v3); // 0x1755
    int128_t v8 = __asm_xorpd(v6, v4); // 0x1759
    *(int64_t *)(result + 16) = __asm_movsd(v5);
    int128_t v9 = __asm_xorpd(v7, v4); // 0x1762
    int128_t v10 = __asm_xorpd(v5, v4); // 0x1766
    *(int64_t *)(result + 64) = 0;
    *(int64_t *)(result + 8) = __asm_movsd(v8);
    *(int64_t *)(result + 40) = __asm_movsd(v9);
    *(int64_t *)(result + 48) = __asm_movsd(v10);
    *(int64_t *)(result + 56) = __asm_movsd(v3);
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/vectors-3d/vectors-3d.c
// Address range: 0x1790 - 0x1888
// Line range:    284 - 295
float64_t get_angle(int32_t * a, int32_t * b) {
    int64_t v1 = (int64_t)b;
    int64_t v2 = (int64_t)a;
    int128_t v3 = __asm_movsd_1(v2); // 0x17a0
    int128_t v4 = __asm_mulsd_3(__asm_movapd(v3), v3); // 0x17a8
    int64_t * v5 = (int64_t *)(v2 + 8); // 0x17ac
    int128_t v6 = __asm_movsd_1(*v5); // 0x17ac
    int128_t v7 = __asm_addsd(v4, __asm_mulsd_3(v6, v6)); // 0x17b5
    int64_t * v8 = (int64_t *)(v2 + 16); // 0x17b9
    int128_t v9 = __asm_movsd_1(*v8); // 0x17b9
    int128_t v10 = __asm_addsd(__asm_mulsd_3(v9, v9), v7); // 0x17c2
    int64_t v11 = __asm_movsd((int128_t)(int32_t)(float32_t)libmin_sqrt((float64_t)(int64_t)v10)); // 0x17cb
    int128_t v12 = __asm_movsd_1(v1); // 0x17d0
    int128_t v13 = __asm_mulsd_3(__asm_movapd(v12), v12); // 0x17d8
    int64_t * v14 = (int64_t *)(v1 + 8); // 0x17dc
    int128_t v15 = __asm_movsd_1(*v14); // 0x17dc
    int128_t v16 = __asm_addsd(v13, __asm_mulsd_3(v15, v15)); // 0x17e5
    int64_t * v17 = (int64_t *)(v1 + 16); // 0x17e9
    int128_t v18 = __asm_movsd_1(*v17); // 0x17e9
    int128_t v19 = __asm_addsd(__asm_mulsd_3(v18, v18), v16); // 0x17f2
    int64_t v20 = __asm_movsd((int128_t)(int32_t)(float32_t)libmin_sqrt((float64_t)(int64_t)v19)); // 0x17fb
    float64_t v21 = libmin_fabs((float64_t)(int64_t)__asm_movsd_1(v11)); // 0x1806
    __asm_comisd(__asm_movsd_1(0x3e112e0be826d695), (int128_t)(int32_t)(float32_t)v21);
    int64_t v22; // bp-16, 0x1790
    if (&v22 > (int64_t *)24) {
        // 0x1819
        return (int64_t)__asm_movsd_1(0x7ff8000000000000);
    }
    float64_t v23 = libmin_fabs((float64_t)(int64_t)__asm_movsd_1(v20)); // 0x1836
    __asm_comisd(__asm_movsd_1(0x3e112e0be826d695), (int128_t)(int32_t)(float32_t)v23);
    int128_t v24 = __asm_addsd(__asm_mulsd(__asm_movsd_1(*v5), *v14), __asm_mulsd(__asm_movsd_1(v2), v1)); // 0x185c
    int128_t v25 = __asm_addsd(__asm_mulsd(__asm_movsd_1(*v8), *v17), v24); // 0x186a
    return libmin_acos((float64_t)(int64_t)__asm_divsd(v25, __asm_mulsd(__asm_movsd_1(v20), v11)));
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1890 - 0x18a1
// Line range:    124 - 127
void libtarg_success(void) {
    // 0x1890
    exit(0);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x18b0 - 0x18bf
// Line range:    162 - 165
void libtarg_fail(int32_t code) {
    // 0x18b0
    exit(code);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x18c0 - 0x18d4
// Line range:    188 - 191
void libtarg_putc(char c) {
    // 0x18c0
    fputc((int32_t)c, g7);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x18e0 - 0x18e9
// Line range:    230 - 236
char * libtarg_sbrk(int64_t inc) {
    // 0x18e0
    return (char *)sbrk(inc);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_acos.c
// Address range: 0x18f0 - 0x1c24
// Line range:    58 - 100
float64_t libmin_acos(float64_t x) {
    int128_t v1 = (float32_t)x;
    int32_t v2 = __asm_movq(v1) / 0x100000000;
    uint32_t v3 = v2 % 0x80000000;
    if (v3 >= 0x3ff00000) {
        // 0x190b
        if ((v3 - 0x3ff00000 | (int32_t)__asm_movq(v1)) != 0) {
            int128_t v4 = __asm_subsd_4(v1, v1); // 0x1a58
            return (int64_t)__asm_divsd(v4, v4);
        }
        int128_t v5 = __asm_pxor(v1, v1); // 0x191d
        if (v2 >= 1) {
            // 0x1929
            return (int64_t)v5;
        }
        int128_t v6 = __asm_movsd_1((int64_t)pio2_lo); // 0x1a68
        return (int64_t)__asm_addsd_2(__asm_addsd(v6, v6), 0x400921fb54442d18);
    }
    if (v3 <= 0x3fdfffff) {
        if (v3 <= 0x3c600000) {
            int128_t v7 = __asm_movsd_1((int64_t)pio2_lo); // 0x1942
            return (int64_t)__asm_addsd_2(v7, 0x3ff921fb54442d18);
        }
        int128_t v8 = __asm_movapd(v1); // 0x1a80
        int128_t v9 = __asm_movsd_1(0x3f023de10dfdf709); // 0x1a84
        int128_t v10 = __asm_movsd_1(0x3fb3b8c5b12e9282); // 0x1a8c
        int128_t v11 = __asm_mulsd_3(v8, v1); // 0x1a94
        int128_t v12 = __asm_movsd_1((int64_t)pio2_lo); // 0x1a98
        int128_t v13 = __asm_addsd_2(__asm_mulsd_3(v9, v11), 0x3f49efe07501b288); // 0x1aa4
        int128_t v14 = __asm_subsd(__asm_mulsd_3(v10, v11), 0x3fe6066c1b8d0159); // 0x1ab0
        int128_t v15 = __asm_subsd(__asm_mulsd_3(v13, v11), 0x3fa48228b5688f3b); // 0x1abc
        int128_t v16 = __asm_addsd_2(__asm_mulsd_3(v14, v11), 0x40002ae59c598ac8); // 0x1ac8
        int128_t v17 = __asm_addsd_2(__asm_mulsd_3(v15, v11), 0x3fc9c1550e884455); // 0x1ad4
        int128_t v18 = __asm_subsd(__asm_mulsd_3(v16, v11), 0x40033a271c8a2d4b); // 0x1ae0
        int128_t v19 = __asm_subsd(__asm_mulsd_3(v17, v11), 0x3fd4d61203eb6f7d); // 0x1aec
        int128_t v20 = __asm_addsd_2(__asm_mulsd_3(v18, v11), 0x3ff0000000000000); // 0x1af8
        int128_t v21 = __asm_divsd(__asm_mulsd_3(__asm_addsd_2(__asm_mulsd_3(v19, v11), 0x3fc5555555555555), v11), v20); // 0x1b10
        int128_t v22 = __asm_subsd_4(v12, __asm_mulsd_3(v21, v1)); // 0x1b18
        int128_t v23 = __asm_movapd(v1); // 0x1b1c
        int128_t v24 = __asm_movsd_1(0x3ff921fb54442d18); // 0x1b20
        return (int64_t)__asm_subsd_4(v24, __asm_subsd_4(v23, v22));
    }
    if (v2 < 0) {
        int128_t v25 = __asm_addsd_2(v1, 0x3ff0000000000000); // 0x1b38
        int128_t v26 = __asm_movsd_1(0x3fe0000000000000); // 0x1b40
        int128_t v27 = __asm_movsd_1(0x3f023de10dfdf709); // 0x1b48
        int128_t v28 = __asm_mulsd_3(v26, v25); // 0x1b50
        int128_t v29 = __asm_mulsd_3(v27, v28); // 0x1b54
        int128_t v30 = __asm_movapd(v28); // 0x1b58
        int64_t v31 = __asm_movsd(v28); // 0x1b5c
        int128_t v32 = __asm_subsd(__asm_mulsd_3(__asm_addsd_2(v29, 0x3f49efe07501b288), v28), 0x3fa48228b5688f3b); // 0x1b6d
        int128_t v33 = __asm_addsd_2(__asm_mulsd_3(v32, v28), 0x3fc9c1550e884455); // 0x1b79
        int128_t v34 = __asm_subsd(__asm_mulsd_3(v33, v28), 0x3fd4d61203eb6f7d); // 0x1b85
        int64_t v35 = __asm_movsd(__asm_mulsd_3(__asm_addsd_2(__asm_mulsd_3(v34, v28), 0x3fc5555555555555), v28)); // 0x1b9d
        float64_t v36 = libmin_sqrt((float64_t)(int64_t)v30); // 0x1ba3
        int128_t v37 = __asm_movsd_1(v31); // 0x1ba8
        int128_t v38 = __asm_movsd_1(0x3fb3b8c5b12e9282); // 0x1bad
        int128_t v39 = __asm_movsd_1(v35); // 0x1bb5
        int128_t v40 = __asm_movapd((int128_t)(int32_t)(float32_t)v36); // 0x1bbb
        int128_t v41 = __asm_movsd_1((int64_t)pio2_lo); // 0x1bbf
        int128_t v42 = __asm_mulsd_3(__asm_subsd(__asm_mulsd_3(v38, v37), 0x3fe6066c1b8d0159), v37); // 0x1bd3
        int128_t v43 = __asm_mulsd_3(__asm_addsd_2(v42, 0x40002ae59c598ac8), v37); // 0x1bdf
        int128_t v44 = __asm_mulsd_3(v37, __asm_subsd(v43, 0x40033a271c8a2d4b)); // 0x1beb
        int128_t v45 = __asm_mulsd_3(__asm_movapd(__asm_divsd(v39, __asm_addsd_2(v44, 0x3ff0000000000000))), v40); // 0x1bff
        int128_t v46 = __asm_addsd(__asm_subsd_4(v45, v41), v40); // 0x1c07
        int128_t v47 = __asm_addsd(__asm_movapd(v46), v46); // 0x1c0f
        return (int64_t)__asm_subsd_4(__asm_movsd_1(0x400921fb54442d18), v47);
    }
    int128_t v48 = __asm_mulsd(__asm_subsd_4(__asm_movsd_1(0x3ff0000000000000), v1), 0x3fe0000000000000); // 0x1970
    int128_t v49 = __asm_movapd(v48); // 0x1978
    int64_t v50 = __asm_movsd(v48); // 0x197c
    int128_t v51 = (float32_t)libmin_sqrt((float64_t)(int64_t)v49); // 0x1981
    int128_t v52 = __asm_movsd_1(v50); // 0x1986
    int128_t v53 = __asm_movsd_1(0x3fb3b8c5b12e9282); // 0x198b
    int128_t v54 = __asm_movapd(v51); // 0x199d
    uint64_t v55 = __asm_movq(v51); // 0x19a1
    int128_t v56 = __asm_movsd_1(0x3f023de10dfdf709); // 0x19a6
    int128_t v57 = __asm_mulsd_3(v53, v52); // 0x19ae
    int64_t v58 = v55 < 0xffffffff00000001 ? v55 : v55 + 0xffffffff; // 0x19b2
    int128_t v59 = __asm_mulsd_3(v56, v52); // 0x19b5
    int128_t v60 = __asm_subsd(v57, 0x3fe6066c1b8d0159); // 0x19b9
    int128_t v61 = __asm_movq_5(v58); // 0x19c1
    int128_t v62 = __asm_addsd_2(v59, 0x3f49efe07501b288); // 0x19c6
    int128_t v63 = __asm_mulsd_3(v60, v52); // 0x19ce
    int128_t v64 = __asm_mulsd_3(v62, v52); // 0x19d2
    int128_t v65 = __asm_addsd_2(v63, 0x40002ae59c598ac8); // 0x19d6
    int128_t v66 = __asm_subsd(v64, 0x3fa48228b5688f3b); // 0x19de
    int128_t v67 = __asm_mulsd_3(v65, v52); // 0x19e6
    int128_t v68 = __asm_mulsd_3(v66, v52); // 0x19ea
    int128_t v69 = __asm_subsd(v67, 0x40033a271c8a2d4b); // 0x19ee
    int128_t v70 = __asm_addsd_2(v68, 0x3fc9c1550e884455); // 0x19f6
    int128_t v71 = __asm_mulsd_3(v69, v52); // 0x19fe
    int128_t v72 = __asm_mulsd_3(v70, v52); // 0x1a02
    int128_t v73 = __asm_addsd_2(v71, 0x3ff0000000000000); // 0x1a06
    int128_t v74 = __asm_addsd_2(__asm_mulsd_3(__asm_subsd(v72, 0x3fd4d61203eb6f7d), v52), 0x3fc5555555555555); // 0x1a1a
    int128_t v75 = __asm_divsd(__asm_mulsd_3(v74, v52), v73); // 0x1a2a
    int128_t v76 = __asm_subsd_4(v52, __asm_mulsd_3(__asm_movq_5(v58), v61)); // 0x1a37
    int128_t v77 = __asm_addsd(__asm_addsd(__asm_mulsd_3(v75, v54), __asm_divsd(v76, __asm_addsd(v54, v61))), v61); // 0x1a4b
    return (int64_t)__asm_addsd(v77, v77);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fabs.c
// Address range: 0x1c30 - 0x1c44
// Line range:    5 - 10
float64_t libmin_fabs(float64_t x) {
    int64_t v1 = __asm_movq((int128_t)(int32_t)(float32_t)x); // 0x1c34
    return (int64_t)__asm_movq_5(v1 & 0x7fffffffffffffff);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fabs.c
// Address range: 0x1c50 - 0x1c62
// Line range:    13 - 18
float32_t libmin_fabsf(float32_t x) {
    uint32_t v1 = __asm_movd((int128_t)(int32_t)x); // 0x1c54
    return (int32_t)__asm_movd_6(v1 % 0x80000000);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fail.c
// Address range: 0x1c70 - 0x1c8f
// Line range:    5 - 8
void libmin_fail(uint32_t code) {
    // 0x1c70
    libmin_printf("ERROR: failure with termination code `%d'\n", (int64_t)code);
    libtarg_fail(code);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1c90 - 0x1ed8
// Line range:    426 - 483
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags) {
    int64_t v1 = flags; // 0x1c9f
    int64_t v2 = value; // 0x1cbf
    int64_t v3 = 0; // 0x1cbf
    int32_t v4 = 0; // 0x1cbf
    if ((flags & 64) == 0) {
        if (value < 0) {
            // 0x1ea0
            v2 = -value;
            v3 = 45;
            v4 = -1;
        } else {
            // 0x1cca
            v2 = value;
            v3 = 43;
            v4 = -1;
            if ((v1 & 2) == 0) {
                uint32_t v5 = 8 * flags & 32; // 0x1ec3
                v2 = value;
                v3 = v5;
                v4 = v5 != 0;
            }
        }
    }
    int64_t v6 = (int64_t)currlen;
    int64_t v7 = (int64_t)buffer;
    uint32_t v8 = max > 0 ? max : 0; // 0x1cb7
    uint64_t v9 = (int64_t)base; // 0x1cf2
    int64_t v10; // bp-89, 0x1c90
    int64_t v11 = &v10; // 0x1cf5
    int64_t v12 = (v1 & 32) == 0 ? (int64_t)"0123456789abcdef" : (int64_t)"0123456789ABCDEF"; // 0x1d0d
    uint64_t v13 = v2; // 0x1d11
    int64_t v14 = 1;
    *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
    int32_t v15 = v14;
    int32_t v16 = v15 - 19; // 0x1d38
    int64_t v17 = v14 + 1; // 0x1d44
    while (v13 >= v9 == (v16 == 0 || v16 < 0 != (18 - v15 & v15) < 0)) {
        // 0x1d18
        v13 /= v9;
        v14 = v17;
        *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
        v15 = v14;
        v16 = v15 - 19;
        v17 = v14 + 1;
    }
    int64_t v18 = v15 == 20 ? 19 : v14 & 0xffffffff; // 0x1d56
    int32_t v19 = v18; // 0x1d5a
    int32_t v20 = v8 - v19; // 0x1d5a
    int64_t v21 = 0x100000000 * v18 >> 32; // 0x1d60
    int64_t v22; // bp-48, 0x1c90
    int64_t v23 = (int64_t)&v22 - 40 + v21; // 0x1d67
    *(char *)v23 = 0;
    uint32_t v24 = min - (int32_t)(v20 < 0 == (v20 & v19) < 0 ? (int64_t)v8 : v18) + v4; // 0x1d73
    uint32_t v25 = v20 > 0 ? v20 : 0; // 0x1d79
    int64_t v26 = v25; // 0x1d79
    int64_t v27 = v24 >= 0 ? (int64_t)v24 : 0; // 0x1d85
    int64_t v28; // 0x1c90
    int64_t v29; // 0x1c90
    int64_t v30; // 0x1c90
    if ((v1 & 16) == 0) {
        if (flags % 2 != 0) {
            // 0x1e80
            v29 = v6;
            v30 = -v27 & 0xffffffff;
            v28 = v26;
        } else {
            // 0x1e44
            v29 = v6;
            v30 = v27;
            v28 = v26;
            if (v24 >= 1) {
                if (v6 < maxlen) {
                    // 0x1e55
                    *(char *)(v6 + v7) = 32;
                }
                int64_t v31 = v6 + 1; // 0x1e5c
                *currlen = v31;
                uint32_t v32 = (int32_t)v27 - 1; // 0x1e63
                int64_t v33 = v32; // 0x1e66
                while (v32 != 0) {
                    int64_t v34 = v31;
                    int64_t v35 = v34; // 0x1e53
                    if (v34 < maxlen) {
                        // 0x1e55
                        *(char *)(v34 + v7) = 32;
                        v35 = v6;
                    }
                    // 0x1e5c
                    v31 = v35 + 1;
                    *currlen = v31;
                    v32 = (int32_t)v33 - 1;
                    v33 = v32;
                }
                int32_t v36 = v27; // 0x1e68
                v29 = v31;
                v30 = v27 - (v36 >= 0 == (v36 != 0) ? v27 : 1) & 0xffffffff;
                v28 = v26;
            }
        }
    } else {
        int32_t v37 = v27; // 0x1d96
        int32_t v38 = v25 - v37; // 0x1d96
        v29 = v6;
        v30 = 0;
        v28 = v38 < 0 == (v38 & v37) < 0 ? v26 : v27;
    }
    int64_t v39 = v29; // 0x1da2
    if (v3 != 0) {
        int64_t v40 = v29; // 0x1da7
        if (v29 < maxlen) {
            // 0x1e90
            *(char *)(v29 + v7) = (char)v3;
            v40 = v6;
        }
        // 0x1dad
        v39 = v40 + 1;
        *currlen = v39;
    }
    int64_t v41 = v39; // 0x1db7
    uint32_t v42 = v28; // 0x1db7
    if ((int32_t)v28 != 0) {
        int64_t v43 = v39; // 0x1e23
        if (v39 < maxlen) {
            // 0x1e25
            *(char *)(v39 + v7) = 48;
            v43 = v6;
        }
        int64_t v44 = v43 + 1; // 0x1e2c
        *currlen = v44;
        v41 = v44;
        while (v42 != 0) {
            // 0x1e20
            v42 = (int64_t)v42;
            int64_t v45 = v44;
            v43 = v45;
            if (v45 < maxlen) {
                // 0x1e25
                *(char *)(v45 + v7) = 48;
                v43 = v6;
            }
            // 0x1e2c
            v44 = v43 + 1;
            *currlen = v44;
            v41 = v44;
        }
    }
    int64_t v46 = v23; // 0x1dc8
    v46--;
    int64_t v47 = v41; // 0x1dd3
    if (v41 < maxlen) {
        // 0x1dd5
        *(char *)(v41 + v7) = *(char *)v46;
        v47 = v6;
    }
    int64_t v48 = v47 + 1; // 0x1de0
    *currlen = v48;
    while (v21 + v11 - (v18 + 0xffffffff & 0xffffffff) != v46) {
        int64_t v49 = v48;
        v46--;
        v47 = v49;
        if (v49 < maxlen) {
            // 0x1dd5
            *(char *)(v49 + v7) = *(char *)v46;
            v47 = v6;
        }
        // 0x1de0
        v48 = v47 + 1;
        *currlen = v48;
    }
    // 0x1df0
    if (v30 == 0) {
        // 0x1e10
        return;
    }
    uint32_t v50 = v30; // 0x1df2
    int64_t v51 = v48; // 0x1dfb
    if (v48 < maxlen) {
        // 0x1dfd
        *(char *)(v48 + v7) = 32;
        v51 = v6;
    }
    int64_t v52 = v51 + 1; // 0x1e04
    *currlen = v52;
    while (v50 != 0) {
        // 0x1df8
        v50 = (int64_t)v50;
        int64_t v53 = v52;
        v51 = v53;
        if (v53 < maxlen) {
            // 0x1dfd
            *(char *)(v53 + v7) = 32;
            v51 = v6;
        }
        // 0x1e04
        v52 = v51 + 1;
        *currlen = v52;
    }
}

// Address range: 0x1ee0 - 0x1f93
int64_t my_modf_isra_0(int64_t a1) {
    // 0x1ee0
    int128_t v1; // 0x1ee0
    int128_t v2 = __asm_movapd(v1); // 0x1ee1
    int128_t v3 = __asm_movsd_1(0x3ff0000000000000); // 0x1eee
    int128_t v4 = __asm_movsd_1(0x3fb999999999999a); // 0x1ef6
    int128_t v5 = __asm_movsd_1(0x4024000000000000); // 0x1efe
    int128_t v6 = __asm_movapd(v3); // 0x1f06
    int64_t v7; // bp-8, 0x1ee0
    bool v8 = &v7 < (int64_t *)32; // 0x1f0a
    int64_t result2 = 0;
    int128_t v9 = v6;
    int128_t v10; // 0x1ee0
    int128_t v11 = v10;
    int128_t v12 = v2;
    int64_t v13 = __asm_cvttsd2si_8(v12); // 0x1f20
    __asm_pxor(v11, v11);
    int128_t v14 = __asm_addsd(__asm_movapd(v12), v3); // 0x1f2d
    int128_t v15 = __asm_cvtsi2sd(v13); // 0x1f31
    __asm_comisd(v14, v15);
    while (v8) {
        int64_t v16 = result2 + 1; // 0x1f14
        int64_t result = v16 & 0xffffffff; // 0x1f14
        uint32_t v17 = (int32_t)v16; // 0x1f1b
        v8 = v17 < 100;
        int128_t v18 = __asm_mulsd_3(v12, v4); // 0x1f1e
        int128_t v19 = __asm_mulsd_3(v9, v5); // 0x1f1e
        if (v17 == 100) {
            // 0x1f58
            *(int64_t *)a1 = 0;
            return result;
        }
        result2 = result;
        v9 = v19;
        v11 = v15;
        v12 = v18;
        v13 = __asm_cvttsd2si_8(v12);
        __asm_pxor(v11, v11);
        v14 = __asm_addsd(__asm_movapd(v12), v3);
        v15 = __asm_cvtsi2sd(v13);
        __asm_comisd(v14, v15);
    }
    // 0x1f3c
    __asm_comisd(v15, __asm_subsd_4(__asm_movapd(v12), v3));
    if (result2 == 0) {
        // 0x1f4e
        *(int64_t *)a1 = __asm_movsd(v15);
        return result2;
    }
    int128_t v20 = __asm_mulsd_3(v15, v9); // 0x1f65
    __asm_subsd_4(v1, v20);
    int64_t v21 = __asm_movsd(v20); // 0x1f72
    int64_t v22; // bp-16, 0x1ee0
    int64_t result3 = my_modf_isra_0((int64_t)&v22); // 0x1f78
    *(int64_t *)a1 = __asm_movsd(__asm_addsd_2(__asm_movsd_1(v21), v22));
    return result3;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1fa0 - 0x2520
// Line range:    586 - 525
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags) {
    char iconvert[311]; // bp-704, 0x1fa0
    char v1[311]; // 0x1fa0
    char v2[311]; // 0x2508
    char v3[311]; // 0x2442
    char v4[311]; // 0x20a3
    char v5[311]; // 0x241c
    // 0x1fa0
    int128_t v6; // 0x1fa0
    int128_t v7 = v6;
    int128_t v8 = v6;
    int128_t v9 = v6;
    int3_t v10; // 0x1fa0
    int3_t v11 = v10 - 1;
    float80_t v12; // 0x1fa0
    __frontend_reg_store_fpr(v11, v12);
    int32_t v13 = 6; // 0x1fc5
    int64_t v14 = 6; // 0x1fc5
    if (max >= 0) {
        int32_t v15 = max - 16; // 0x1fd1
        v14 = v15 == 0 | v15 < 0 != (15 - max & max) < 0 ? (int64_t)max : 16;
        v13 = max;
    }
    uint64_t v16 = (int64_t)flags;
    int3_t v17 = v10 - 2; // 0x1fd8
    __frontend_reg_store_fpr(v17, 0.0L);
    float80_t v18 = __frontend_reg_load_fpr(v17); // 0x1fda
    float80_t v19 = __frontend_reg_load_fpr(v11); // 0x1fda
    float80_t v20 = __frontend_reg_load_fpr(v11);
    int32_t v21; // 0x1fa0
    int32_t v22; // 0x1fa0
    float64_t v23; // bp-744, 0x1fa0
    int128_t v24; // 0x1fa0
    if (v18 > v19) {
        // 0x2450
        __frontend_reg_store_fpr(v11, -v20);
        float64_t v25 = __frontend_reg_load_fpr(v11); // 0x245a
        v23 = v25;
        v22 = 45;
        v21 = 1;
        v24 = __asm_movsd_1((int64_t)v25);
    } else {
        float64_t v26 = v20; // 0x1fe2
        v23 = v26;
        int128_t v27 = __asm_movsd_1((int64_t)v26); // 0x1fe5
        v22 = 43;
        v21 = 1;
        v24 = v27;
        if ((v16 & 2) == 0) {
            int32_t v28 = 8 * flags & 32; // 0x1ffd
            v22 = v28;
            v21 = v28 != 0;
            v24 = v27;
        }
    }
    // 0x200e
    __asm_movapd(v24);
    float64_t fracpart; // bp-712, 0x1fa0
    int64_t v29 = &fracpart; // 0x2018
    my_modf_isra_0(v29);
    bool v30; // 0x1fa0
    bool v31; // 0x1fa0
    int128_t v32; // 0x1fa0
    int128_t v33; // 0x1fa0
    int128_t v34; // 0x1fa0
    bool v35; // 0x1fa0
    bool v36; // 0x1fa0
    if (v13 == 0) {
        int128_t v37 = __asm_movsd_1((int64_t)fracpart); // 0x24b4
        int128_t v38 = __asm_subsd_4(v24, v37); // 0x24ba
        int64_t v39 = __asm_cvttsd2si_8(v38); // 0x24bf
        v23 = __asm_movsd(v38);
        __frontend_reg_store_fpr(v11, (float80_t)v39);
        __frontend_reg_store_fpr(v11, (float80_t)v23 - __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v17, 0.5L);
        float80_t v40 = __frontend_reg_load_fpr(v17); // 0x24dc
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v40);
        float80_t v41 = __frontend_reg_load_fpr(v17); // 0x24de
        float80_t v42 = __frontend_reg_load_fpr(v11); // 0x24de
        bool v43 = false; // 0x24de
        bool v44 = false; // 0x24de
        bool v45 = false; // 0x24de
        if (v41 <= v42) {
            v43 = true;
            v44 = false;
            v45 = false;
            if (v41 >= v42) {
                v43 = v41 != v42;
                v44 = v41 != v42;
                v45 = true;
            }
        }
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
        bool v46 = true; // 0x24e2
        bool v47 = v44; // 0x24e2
        bool v48 = v45; // 0x24e2
        int64_t v49 = v39; // 0x24e2
        if (!v43) {
            // 0x24e4
            v49 = v39 + 1;
            v46 = v39 == -1;
            v47 = llvm_ctpop_i8((char)v49) % 2 == 0;
            v48 = v49 == 0;
        }
        // 0x24e8
        __asm_pxor(v7, v7);
        int128_t v50 = __asm_movsd_1(0x3ff0000000000000); // 0x24ed
        int128_t v51 = __asm_cvtsi2sd(v49); // 0x24f5
        v23 = __asm_movsd(v51);
        __asm_comisd(v51, v50);
        __frontend_reg_store_fpr(v11, (float80_t)v23);
        int64_t v52 = __asm_movsd(v51); // 0x2508
        v2[0] = v52;
        iconvert = v2;
        if (v46) {
            // 0x20d0
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v47;
            v35 = v48;
            v32 = v37;
            v34 = v51;
            goto lab_0x20d8;
        } else {
            int128_t v53 = __asm_addsd(v37, v50); // 0x2515
            __frontend_reg_store_fpr(v17, 1.0L);
            v31 = v47;
            v36 = v48;
            v33 = v53;
            goto lab_0x240b;
        }
    } else {
        // 0x2029
        __frontend_reg_store_fpr(v11, 1.0L);
        __frontend_reg_store_fpr(v17, 10.0L);
        int64_t v54 = v14 & 0xffffffff; // 0x2031
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
        uint32_t v55 = (int32_t)v54 - 1; // 0x203a
        int64_t v56 = v55; // 0x203d
        while (v55 != 0) {
            // 0x2038
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
            v55 = (int32_t)v56 - 1;
            v56 = v55;
        }
        float80_t v57 = __frontend_reg_load_fpr(v17); // 0x203f
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v57);
        int128_t v58 = __asm_movsd_1((int64_t)fracpart); // 0x2045
        v23 = __asm_movsd(__asm_subsd_4(v24, v58));
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) * (float80_t)v23);
        int3_t v59 = v10 - 3;
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        float80_t v60 = __frontend_reg_load_fpr(v59); // 0x206c
        v23 = v60;
        __frontend_reg_store_fpr(v59, v60);
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) - __frontend_reg_load_fpr(v59));
        __frontend_reg_store_fpr(v59, (float80_t)*(float32_t *)0x460c);
        float80_t v61 = __frontend_reg_load_fpr(v59); // 0x207e
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v61);
        float80_t v62 = __frontend_reg_load_fpr(v59); // 0x2080
        float80_t v63 = __frontend_reg_load_fpr(v17); // 0x2080
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
        if (v62 < v63) {
            // 0x2430
            __asm_pxor(v9, v9);
            int128_t v64 = __asm_cvtsi2sd((int64_t)v23); // 0x2434
            int64_t v65 = __asm_movsd(v64); // 0x243a
            v23 = v65;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v65);
            int64_t v66 = __asm_movsd(v64); // 0x2442
            v3[0] = v66;
            v1 = v3;
        } else {
            // 0x208a
            __asm_pxor(v9, v9);
            int128_t v67 = __asm_cvtsi2sd((int64_t)v23 + 1); // 0x2096
            int64_t v68 = __asm_movsd(v67); // 0x209b
            v23 = v68;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v68);
            int64_t v69 = __asm_movsd(v67); // 0x20a3
            v4[0] = v69;
            v1 = v4;
        }
        // 0x20a9
        iconvert = v1;
        __frontend_reg_store_fpr(v59, 1.0L);
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
        uint32_t v70 = (int32_t)v54 - 1; // 0x20b2
        int64_t v71 = v70; // 0x20b5
        while (v70 != 0) {
            // 0x20b0
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            v70 = (int32_t)v71 - 1;
            v71 = v70;
        }
        float80_t v72 = __frontend_reg_load_fpr(v59); // 0x20b7
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v72);
        float80_t v73 = __frontend_reg_load_fpr(v59); // 0x20b9
        float80_t v74 = __frontend_reg_load_fpr(v17); // 0x20b9
        bool v75 = false; // 0x20b9
        bool v76 = false; // 0x20b9
        bool v77 = false; // 0x20b9
        if (v73 <= v74) {
            v75 = true;
            v76 = false;
            v77 = false;
            if (v73 >= v74) {
                v75 = v73 != v74;
                v76 = v73 != v74;
                v77 = true;
            }
        }
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v59));
        if (!v75) {
            int128_t v78 = __asm_addsd_2(v58, 0x3ff0000000000000); // 0x23f0
            __frontend_reg_store_fpr(v59, 1.0L);
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            uint32_t v79 = (int32_t)v54 - 1; // 0x2402
            int64_t v80 = v79; // 0x2405
            while (v79 != 0) {
                // 0x2400
                __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
                v79 = (int32_t)v80 - 1;
                v80 = v79;
            }
            unsigned char v81 = llvm_ctpop_i8((char)v79); // 0x2402
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v59));
            float80_t v82 = __frontend_reg_load_fpr(v17); // 0x2409
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
            __frontend_reg_store_fpr(v11, v82);
            v31 = v81 % 2 == 0;
            v36 = true;
            v33 = v78;
            goto lab_0x240b;
        } else {
            // 0x20c3
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v76;
            v35 = v77;
            v32 = v58;
            v34 = __asm_movsd_1(*(int64_t *)&iconvert);
            goto lab_0x20d8;
        }
    }
  lab_0x20d8:;
    int64_t v83 = (int64_t)currlen;
    int64_t v84 = (int64_t)buffer;
    int64_t v85 = &v23; // 0x1fb0
    int64_t v86; // bp-697, 0x1fa0
    int64_t v87 = &v86; // 0x20dd
    int128_t v88 = __asm_pxor(v8, v8); // 0x20e2
    int128_t v89 = __asm_movsd_1(0x3fb999999999999a); // 0x20e7
    int128_t v90 = __asm_movsd_1(0x3fa999999999999a); // 0x20f0
    int128_t v91 = __asm_movsd_1(0x4024000000000000); // 0x2100
    bool v92 = v30; // 0x2109
    bool v93 = v35; // 0x2109
    int64_t v94 = 1;
    int128_t v95 = __asm_movapd(__asm_mulsd_3(v32, v89)); // 0x212c
    my_modf_isra_0(v29);
    int128_t v96 = __asm_movsd_1((int64_t)fracpart); // 0x2136
    int128_t v97 = __asm_subsd_4(v95, v96); // 0x213c
    __asm_ucomisd_7(v96, v88);
    int32_t v98 = __asm_cvttsd2si(__asm_mulsd_3(__asm_addsd(v97, v90), v91)); // 0x2150
    char v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef"); // 0x2157
    *(char *)(v94 + v87) = v99;
    bool v100; // 0x1fa0
    int64_t v101; // 0x1fa0
    bool v102; // 0x1fa0
    while (v92 || !v93) {
        int64_t v103 = v94 - 311; // 0x2114
        unsigned char v104 = llvm_ctpop_i8((char)v103); // 0x2114
        v92 = v104 % 2 == 0;
        v93 = false;
        v100 = v104 % 2 == 0;
        v102 = true;
        v101 = 310;
        if (v103 == 0) {
            goto lab_0x2173;
        }
        v94++;
        v95 = __asm_movapd(__asm_mulsd_3(v96, v89));
        my_modf_isra_0(v29);
        v96 = __asm_movsd_1((int64_t)fracpart);
        v97 = __asm_subsd_4(v95, v96);
        __asm_ucomisd_7(v96, v88);
        v98 = __asm_cvttsd2si(__asm_mulsd_3(__asm_addsd(v97, v90), v91));
        v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef");
        *(char *)(v94 + v87) = v99;
    }
    int32_t v105 = (int32_t)v94 - 311; // 0x2164
    v100 = llvm_ctpop_i8((char)v105) % 2 == 0;
    v102 = v105 == 0;
    v101 = v105 == 0 ? 310 : v94 & 0xffffffff;
  lab_0x2173:
    // 0x2173
    __asm_ucomisd_7(v34, v88);
    int64_t v106 = 0x100000000 * v101 >> 32; // 0x2178
    v23 = v106;
    int64_t v107 = v85 + 48; // 0x217f
    *(char *)(v106 + v107) = 0;
    int64_t v108 = v14; // 0x2184
    int64_t v109 = 0; // 0x2184
    if (v100 || !v102) {
        bool v110 = v100; // 0x219e
        bool v111 = v102; // 0x219e
        int64_t v112 = 1;
        int128_t v113 = __asm_mulsd_3(v34, v89); // 0x21b1
        __asm_movapd(v113);
        int128_t v114 = __asm_movapd(v113); // 0x21be
        my_modf_isra_0((int64_t)&iconvert);
        int128_t v115 = __asm_movsd_1(*(int64_t *)&iconvert); // 0x21c8
        int128_t v116 = __asm_subsd_4(v114, v115); // 0x21d1
        __asm_ucomisd_7(v115, v88);
        int32_t v117 = __asm_cvttsd2si(__asm_mulsd_3(__asm_addsd(v116, v90), v91)); // 0x21e5
        char v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef"); // 0x21ec
        int64_t v119; // bp-377, 0x1fa0
        *(char *)(v112 + (int64_t)&v119) = v118;
        while (v110 || !v111) {
            int64_t v120 = v112 - 311; // 0x21a4
            v110 = llvm_ctpop_i8((char)v120) % 2 == 0;
            v111 = false;
            if (v120 == 0) {
                goto lab_0x2498;
            }
            v112++;
            v113 = __asm_mulsd_3(v115, v89);
            __asm_movapd(v113);
            v114 = __asm_movapd(v113);
            my_modf_isra_0((int64_t)&iconvert);
            v115 = __asm_movsd_1(*(int64_t *)&iconvert);
            v116 = __asm_subsd_4(v114, v115);
            __asm_ucomisd_7(v115, v88);
            v117 = __asm_cvttsd2si(__asm_mulsd_3(__asm_addsd(v116, v90), v91));
            v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef");
            *(char *)(v112 + (int64_t)&v119) = v118;
        }
        if ((int32_t)v112 == 311) {
          lab_0x2498:
            // 0x2498
            v108 = v14 + 0xfffffeca;
            v109 = 310;
        } else {
            // 0x2205
            v108 = v14 - v112;
            v109 = v112 & 0xffffffff;
        }
    }
    int64_t v121 = (0x100000000 * v109 >> 32) + v85;
    int64_t v122 = v121 + 368; // 0x2215
    *(char *)v122 = 0;
    int32_t v123 = -1 - (int32_t)v14 + (int32_t)(float32_t)(float64_t)(int64_t)min - v21 - (int32_t)v101; // 0x222d
    int64_t v124 = v123 >= 0 ? (int64_t)v123 : 0; // 0x2232
    int64_t v125; // 0x1fa0
    int64_t v126; // 0x1fa0
    int64_t v127; // 0x1fa0
    int64_t v128; // 0x1fa0
    int64_t v129; // 0x1fa0
    int64_t v130; // 0x1fa0
    if (v16 % 2 == 0) {
        if ((v16 & 16) == 0) {
            // 0x23b0
            v129 = v83;
            v125 = v124;
            if (v123 >= 1) {
                if (v83 < maxlen) {
                    // 0x23c5
                    *(char *)(v83 + v84) = 32;
                }
                int64_t v131 = v83 + 1; // 0x23cc
                *currlen = v131;
                uint32_t v132 = (int32_t)v124 - 1; // 0x23d3
                int64_t v133 = v132; // 0x23d7
                while (v132 != 0) {
                    int64_t v134 = v131;
                    int64_t v135 = v134; // 0x23c3
                    if (v134 < maxlen) {
                        // 0x23c5
                        *(char *)(v134 + v84) = 32;
                        v135 = v83;
                    }
                    // 0x23cc
                    v131 = v135 + 1;
                    *currlen = v131;
                    v132 = (int32_t)v133 - 1;
                    v133 = v132;
                }
                int32_t v136 = v124; // 0x23d9
                v129 = v131;
                v125 = v124 - (v136 >= 0 == (v136 != 0) ? v124 : 1) & 0xffffffff;
            }
            goto lab_0x2243;
        } else {
            // 0x236e
            v129 = v83;
            v125 = v124;
            if (v123 < 1) {
                goto lab_0x2243;
            } else {
                // 0x2377
                v130 = v83;
                v126 = v124;
                if (v22 != 0) {
                    // 0x2481
                    v128 = v83;
                    v127 = v124;
                    if (v83 < maxlen) {
                        // 0x248a
                        *(char *)(v83 + v84) = (char)v22;
                        v128 = v83;
                        v127 = v124;
                    }
                    goto lab_0x2394;
                } else {
                    goto lab_0x2388;
                }
            }
        }
    } else {
        // 0x2240
        v129 = v83;
        v125 = -v124 & 0xffffffff;
        goto lab_0x2243;
    }
  lab_0x240b:
    // 0x240b
    __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) - __frontend_reg_load_fpr(v17));
    fracpart = __asm_movsd(v33);
    float64_t v137 = __frontend_reg_load_fpr(v11); // 0x2413
    v23 = v137;
    int128_t v138 = __asm_movsd_1((int64_t)v137); // 0x2416
    int64_t v139 = __asm_movsd(v138); // 0x241c
    v5[0] = v139;
    iconvert = v5;
    v30 = v31;
    v35 = v36;
    v32 = v33;
    v34 = v138;
    goto lab_0x20d8;
  lab_0x2243:;
    int64_t v140 = v129; // 0x2249
    int64_t v141 = v125; // 0x2249
    if (v22 != 0) {
        int64_t v142 = v129; // 0x224e
        if (v129 < maxlen) {
            // 0x2250
            *(char *)(v129 + v84) = (char)v22;
            v142 = v83;
        }
        int64_t v143 = v142 + 1; // 0x2256
        *currlen = v143;
        v140 = v143;
        v141 = v125;
    }
    goto lab_0x225d;
  lab_0x225d:;
    int64_t v144 = v107 + (int64_t)v23 - 1;
    int64_t v145; // 0x1fa0
    if (v140 < maxlen) {
        // 0x2275
        *(char *)(v145 + v84) = *(char *)v144;
    }
    int64_t v146 = v140 + 1; // 0x2280
    *currlen = v146;
    int64_t v147 = v146; // 0x228e
    int64_t v148 = v144; // 0x228e
    while (v87 - (v101 + 0xffffffff & 0xffffffff) + (int64_t)v23 != v144) {
        // 0x2270
        v144 = v148 - 1;
        if (v147 < maxlen) {
            // 0x2275
            *(char *)(v145 + v84) = *(char *)v144;
        }
        // 0x2280
        v146 = v147 + 1;
        *currlen = v146;
        v147 = v146;
        v148 = v144;
    }
    if (v13 != 0) {
        int64_t v149 = v146; // 0x2298
        if (v146 < maxlen) {
            // 0x229a
            *(char *)(v146 + v84) = 46;
            v149 = v83;
        }
        int64_t v150 = v149 + 1; // 0x22a1
        *currlen = v150;
        int64_t v151 = v150; // 0x22aa
        if ((int32_t)v108 >= 1) {
            int64_t v152 = v151;
            int64_t v153 = v152; // 0x22b3
            if (v152 < maxlen) {
                // 0x22b5
                *(char *)(v152 + v84) = 48;
                v153 = v83;
            }
            int64_t v154 = v153 + 1; // 0x22bc
            *currlen = v154;
            uint32_t v155 = (int32_t)(v108 & 0xffffffff) - 1; // 0x22c3
            int64_t v156 = v155; // 0x22c6
            while (v155 != 0) {
                // 0x22b0
                v152 = v154;
                v153 = v152;
                if (v152 < maxlen) {
                    // 0x22b5
                    *(char *)(v152 + v84) = 48;
                    v153 = v83;
                }
                // 0x22bc
                v154 = v153 + 1;
                *currlen = v154;
                v155 = (int32_t)v156 - 1;
                v156 = v155;
            }
        }
        if (v109 != 0) {
            int64_t v157 = v122 - 1;
            if (v83 < maxlen) {
                // 0x22ed
                *(char *)(v83 + v84) = *(char *)v157;
            }
            int64_t v158 = v83 + 1; // 0x22f8
            *currlen = v158;
            int64_t v159 = v157; // 0x2306
            while (367 - (v109 + 0xffffffff & 0xffffffff) + v121 != v157) {
                int64_t v160 = v158;
                v157 = v159 - 1;
                int64_t v161 = v160; // 0x22eb
                if (v160 < maxlen) {
                    // 0x22ed
                    *(char *)(v160 + v84) = *(char *)v157;
                    v161 = v83;
                }
                // 0x22f8
                v158 = v161 + 1;
                *currlen = v158;
                v159 = v157;
            }
        }
    }
    // 0x2308
    if ((int32_t)v141 == 0) {
        // 0x2329
        return;
    }
    if (v83 < maxlen) {
        // 0x2315
        *(char *)(v83 + v84) = 32;
    }
    int64_t v162 = v83 + 1; // 0x231c
    *currlen = v162;
    uint32_t v163 = (int32_t)v141 + 1; // 0x2323
    int64_t v164 = v163; // 0x2327
    while (v163 != 0) {
        int64_t v165 = v162;
        int64_t v166 = v165; // 0x2313
        if (v165 < maxlen) {
            // 0x2315
            *(char *)(v165 + v84) = 32;
            v166 = v83;
        }
        // 0x231c
        v162 = v166 + 1;
        *currlen = v162;
        v163 = (int32_t)v164 + 1;
        v164 = v163;
    }
  lab_0x2388:;
    int64_t v167 = v126;
    int64_t v168 = v130;
    v128 = v168;
    v127 = v167;
    if (v168 < maxlen) {
        // 0x238d
        *(char *)(v168 + v84) = 48;
        v128 = v83;
        v127 = v167;
    }
    goto lab_0x2394;
  lab_0x2394:;
    int64_t v169 = v128 + 1; // 0x2394
    *currlen = v169;
    uint32_t v170 = (int32_t)v127 - 1; // 0x239b
    int64_t v171 = v170; // 0x239b
    v140 = v169;
    v141 = v171;
    v130 = v169;
    v126 = v171;
    if (v170 != 0) {
        goto lab_0x2388;
    } else {
        goto lab_0x225d;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2520 - 0x2e3d
// Line range:    130 - 290
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args) {
    // 0x2520
    int64_t v1; // 0x2520
    uint64_t v2 = v1;
    int64_t v3 = (int64_t)buffer;
    int64_t v4 = (int64_t)format + 1; // 0x2533
    int64_t v5 = v4; // 0x2533
    int64_t result2 = 0; // 0x2549
    int64_t v6; // 0x2520
    int64_t v7; // 0x2520
    int64_t v8; // 0x2520
    int64_t v9; // 0x2520
    char v10; // 0x2520
    int64_t v11; // 0x2520
    int64_t v12; // 0x2520
    if ((char)v2 != 0) {
        int64_t v13 = (int64_t)args;
        int64_t * v14 = (int64_t *)(v13 + 8);
        v6 = v4;
        v7 = v2 % 256;
        v12 = 0;
        while (true) {
          lab_0x259e:;
            char v15 = v7; // 0x25a5
            int64_t v16 = v6; // 0x25a8
            char v17 = v15; // 0x25a8
            int64_t v18 = v12; // 0x25a8
            int64_t v19 = v6; // 0x25a8
            int64_t v20 = v12; // 0x25a8
            if (v15 != 37) {
                while (true) {
                  lab_0x25aa:;
                    uint64_t v21 = v18;
                    int64_t v22 = v16; // 0x25ad
                    if (v21 < maxlen) {
                        // 0x25af
                        *(char *)(v21 + v3) = v17;
                        v22 = v5;
                    }
                    char v23 = *(char *)v22; // 0x25b3
                    int64_t v24 = v22 + 1; // 0x25b6
                    v5 = v24;
                    int64_t v25 = v21 + 1; // 0x25ba
                    result2 = v25;
                    v16 = v24;
                    v17 = v23;
                    v18 = v25;
                    v19 = v24;
                    v20 = v25;
                    switch (v23) {
                        case 0: {
                            goto lab_0x2550_3;
                        }
                        case 37: {
                            goto lab_0x25c9;
                        }
                        default: {
                            goto lab_0x25aa;
                        }
                    }
                }
            }
          lab_0x25c9:
            // 0x25c9
            v11 = v20;
            unsigned char v26 = *(char *)v19; // 0x25d3
            result2 = v11;
            if (v26 == 0) {
                // break -> 0x2550
                break;
            }
            int64_t v27 = v26; // 0x25d3
            int64_t result = v27; // 0x25eb
            if (v26 < 49) {
                // 0x2563
                return result;
            }
            int64_t v28 = v19 + 1; // 0x25de
            int64_t v29 = (int64_t)g6; // 0x25fa
            v5 = 0;
            int64_t v30 = v27; // 0x260a
            int64_t v31 = v28; // 0x260a
            int32_t v32 = 0; // 0x260a
            int64_t v33 = v27; // 0x260a
            int64_t v34 = v28; // 0x260a
            if ((*(char *)(2 * v27 + v29) & 4) != 0) {
                int64_t v35 = 0xffffffd0 + (0x100000000000000 * v30 >> 56); // 0x2616
                int64_t v36 = v35 & 0xffffffff; // 0x2616
                v5 = v36;
                unsigned char v37 = *(char *)v31; // 0x261a
                result2 = v11;
                if (v37 == 0) {
                    // break (via goto) -> 0x2550
                    goto lab_0x2550_3;
                }
                int64_t v38 = v31 + 1; // 0x2612
                int64_t v39 = v37; // 0x261a
                v31 = v38;
                while ((*(char *)(2 * v39 + v29) & 4) != 0) {
                    // 0x260c
                    v35 = 10 * v36 + 0xffffffd0 + (0x100000000000000 * v39 >> 56);
                    v36 = v35 & 0xffffffff;
                    v5 = v36;
                    v37 = *(char *)v31;
                    result2 = v11;
                    if (v37 == 0) {
                        // break (via goto) -> 0x2550
                        goto lab_0x2550_3;
                    }
                    // 0x2626
                    v38 = v31 + 1;
                    v39 = v37;
                    v31 = v38;
                }
                // 0x2632
                v32 = v35;
                v33 = v39;
                v34 = v38;
            }
            int64_t v40 = v34;
            int64_t v41 = v33; // 0x2634
            int64_t v42 = v40; // 0x2634
            if (v33 == 42) {
                uint32_t v43 = v32; // 0x2b68
                if (v43 < 48) {
                    // 0x2b6f
                    v5 = *(int64_t *)(v13 + 16) + (int64_t)v43;
                    *args = v43 + 8;
                } else {
                    int64_t v44 = *v14; // 0x2bc3
                    v5 = v44;
                    *v14 = v44 + 8;
                }
                unsigned char v45 = *(char *)v40; // 0x2b7a
                result2 = v11;
                if (v45 == 0) {
                    // break -> 0x2550
                    break;
                }
                // 0x2b8c
                v41 = v45;
                v42 = v40 + 1;
            }
            int64_t v46 = v42;
            int64_t v47 = v41; // 0x2642
            int64_t v48 = v46; // 0x2642
            if ((char)v41 == 46) {
                char v49 = *(char *)v46; // 0x26f8
                result2 = v11;
                if (v49 == 0) {
                    // break -> 0x2550
                    break;
                }
                int64_t v50 = v46;
                unsigned char v51 = v49;
                int64_t v52 = v50 + 1;
                int64_t v53 = v51;
                while ((*(char *)(2 * v53 + v29) & 4) != 0) {
                    char v54 = *(char *)v52; // 0x272c
                    result2 = v11;
                    if (v54 == 0) {
                        // break (via goto) -> 0x2550
                        goto lab_0x2550_3;
                    }
                    v50 = v52;
                    v51 = v54;
                    v52 = v50 + 1;
                    v53 = v51;
                }
                // 0x2ab0
                v47 = v53;
                v48 = v52;
                if (v51 == 42) {
                    uint32_t v55 = *(int32_t *)&v5; // 0x2ab8
                    if (v55 < 48) {
                        // 0x2ac3
                        *args = v55 + 8;
                    } else {
                        // 0x2b94
                        *v14 = *v14 + 8;
                    }
                    unsigned char v56 = *(char *)v52; // 0x2ace
                    result2 = v11;
                    if (v56 == 0) {
                        // break -> 0x2550
                        break;
                    }
                    // 0x2ae1
                    v47 = v56;
                    v48 = v50 + 2;
                }
            }
            int64_t v57 = v48;
            int64_t v58 = v47;
            switch ((char)v58) {
                case 104: {
                    char v59 = *(char *)v57; // 0x2b4e
                    v10 = v59;
                    v9 = v57 + 1;
                    if (v59 == 0) {
                        // break -> 0x2550
                        break;
                    }
                    goto lab_0x2b06;
                }
                case 108: {
                    char v60 = *(char *)v57; // 0x2ae9
                    int64_t v61 = v57 + 1;
                    result2 = v11;
                    v10 = v60;
                    v9 = v61;
                    switch (v60) {
                        case 108: {
                            char v62 = *(char *)v61; // 0x2ba5
                            v10 = v62;
                            v9 = v57 + 2;
                            if (v62 == 0) {
                                // break -> 0x2550
                                break;
                            }
                            goto lab_0x2b06;
                        }
                        case 0: {
                            goto lab_0x2550_3;
                        }
                        default: {
                            goto lab_0x2b06;
                        }
                    }
                }
                case 76: {
                    unsigned char v63 = *(char *)v57; // 0x2b1f
                    if (v63 == 0) {
                        // break -> 0x2550
                        break;
                    }
                    int64_t v64 = (int64_t)v63 + 0xffffffdb; // 0x2b2b
                    v8 = v57 + 1;
                    if ((char)v64 < 84) {
                        int32_t v65 = *(int32_t *)((4 * v64 & 1020) + (int64_t)&g4); // 0x2b44
                        return (int64_t)v65 + (int64_t)&g4;
                    }
                    goto lab_0x2793;
                }
                default: {
                    // 0x2660
                    v8 = v57;
                    if ((char)(v58 + 0xffffffdb) < 84) {
                        // 0x266b
                        int64_t v66; // 0x2660
                        int32_t v67 = *(int32_t *)((4 * v66 & 1020) + (int64_t)&g2); // 0x2675
                        return (int64_t)v67 + (int64_t)&g2;
                    }
                    goto lab_0x2793;
                }
            }
        }
    }
  lab_0x2550_3:
    // 0x2550
    if (maxlen == 0) {
        // 0x2563
        return result2;
    }
    uint64_t v68 = maxlen - 1;
    if (v68 > result2) {
        // 0x255e
        *(char *)(result2 + v3) = 0;
        // 0x2563
        return result2;
    }
    // 0x2578
    *(char *)(v68 + v3) = 0;
    return result2;
  lab_0x2793:;
    unsigned char v69 = *(char *)v8; // 0x2793
    int64_t v70 = v8 + 1; // 0x2797
    v5 = v70;
    result2 = v11;
    v6 = v70;
    v7 = v69;
    v12 = v11;
    if (v69 == 0) {
        // break -> 0x2550
        goto lab_0x2550_3;
    }
    goto lab_0x259e;
  lab_0x2b06:;
    int64_t v71 = (int64_t)v10 + 0xffffffdb; // 0x2b06
    v8 = v9;
    if ((char)v71 < 84) {
        int32_t v72 = *(int32_t *)((4 * v71 & 1020) + (int64_t)&g3); // 0x2b14
        return (int64_t)v72 + (int64_t)&g3;
    }
    goto lab_0x2793;
}

// Address range: 0x2e3d - 0x2e48
int64_t function_2e3d(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2e3d
    int64_t v1; // 0x2e3d
    return v1 & 0xffffffff;
}

// Address range: 0x2e48 - 0x2e53
int64_t function_2e48(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2e48
    int64_t v1; // 0x2e48
    return v1 & 0xffffffff;
}

// Address range: 0x2e53 - 0x2e5e
int64_t function_2e53(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2e53
    int64_t v1; // 0x2e53
    return v1 & 0xffffffff;
}

// Address range: 0x2e5e - 0x2e65
int64_t function_2e5e(void) {
    // 0x2e5e
    int64_t v1; // 0x2e5e
    return v1 & 0xffffffff;
}

// Address range: 0x2e65 - 0x2e70
int64_t function_2e65(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2e65
    int64_t v1; // 0x2e65
    return v1 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2e70 - 0x2f7c
// Line range:    751 - 769
int32_t libmin_printf(char * fmt, ...) {
    // 0x2e70
    int64_t v1; // 0x2e70
    if ((char)v1 != 0) {
        // 0x2eac
        int128_t v2; // 0x2e70
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 8; // bp-1248, 0x2f16
    char v4; // bp-1224, 0x2e70
    dopr(&v4, (int64_t)&g1, fmt, (int32_t *)&v3);
    if (v4 == 0) {
        // 0x2f70
        return 0;
    }
    int64_t v5 = &v4;
    libtarg_putc(v4);
    int64_t v6 = v5 + 1; // 0x2f59
    char v7 = *(char *)v6; // 0x2f59
    while (v7 != 0) {
        // 0x2f50
        v5 = v6;
        libtarg_putc(v7);
        v6 = v5 + 1;
        v7 = *(char *)v6;
    }
    // 0x2f66
    int64_t v8; // bp+1225, 0x2e70
    return v5 + (int64_t)&v8;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2f80 - 0x302b
// Line range:    772 - 782
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...) {
    // 0x2f80
    int64_t v1; // 0x2f80
    if ((char)v1 != 0) {
        // 0x2fa6
        int128_t v2; // 0x2f80
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 24; // bp-224, 0x2ffa
    dopr(s, size, fmt, (int32_t *)&v3);
    *(char *)((int64_t)s - 1 + size) = 0;
    return libmin_strlen(s);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_sqrt.c
// Address range: 0x3030 - 0x323e
// Line range:    74 - 102
float64_t libmin_sqrt(float64_t x) {
    int128_t v1 = (float32_t)x;
    uint64_t v2 = __asm_movq(v1); // 0x3034
    if (v2 % 0x7ff0000000000001 == 0x7ff0000000000000) {
        // 0x3210
        return (int64_t)__asm_addsd(v1, __asm_mulsd_3(__asm_movapd(v1), v1));
    }
    int64_t v3 = v2 / 0x100000000; // 0x3039
    int32_t v4 = __asm_movd(v1); // 0x3051
    int64_t v5 = v4; // 0x3051
    int32_t v6 = v3; // 0x3055
    int64_t v7; // 0x3030
    int64_t v8; // 0x3030
    int64_t v9; // 0x3030
    int64_t v10; // 0x3030
    int64_t v11; // 0x3030
    int64_t v12; // 0x3030
    int64_t v13; // 0x3030
    int64_t v14; // 0x3030
    int64_t v15; // 0x3030
    int64_t v16; // 0x3030
    if (v6 < 1) {
        // 0x3140
        if ((v4 || (v6 == 0 ? 0 : v6 ^ -0x80000000)) == 0) {
            // 0x320c
            return x;
        }
        // 0x314f
        if (v2 >= 0x100000000) {
            int128_t v17 = __asm_subsd_4(v1, v1); // 0x321d
            return (int64_t)__asm_divsd(v17, v17);
        }
        int64_t v18 = 0;
        uint64_t v19 = v5;
        int64_t v20 = v18 + 0xffffffeb & 0xffffffff; // 0x3162
        int64_t v21 = 0x200000 * v19 & 0xffe00000; // 0x3165
        int64_t v22 = v19 / 2048 % 0x200000; // 0x3168
        while (v22 == 0) {
            // 0x3160
            v18 = v20;
            v19 = v21;
            v20 = v18 + 0xffffffeb & 0xffffffff;
            v21 = 0x200000 * v19 & 0xffe00000;
            v22 = v19 / 2048 % 0x200000;
        }
        // 0x316f
        v10 = v22;
        v13 = v21;
        v16 = v20;
        if ((int32_t)v19 <= -1) {
            // 0x319c
            v7 = v18 + 0xffffffec & 0xffffffff;
            v8 = v21;
            v14 = v21;
            v11 = v22;
            goto lab_dec_label_pc_unknown;
        } else {
            goto lab_0x317a;
        }
    } else {
        // 0x305d
        v9 = v3;
        v12 = v5;
        v15 = v2 / 0x10000000000000;
        v10 = v3;
        v13 = v5;
        v16 = 0;
        if (v2 < 0x10000000000000) {
            goto lab_0x317a;
        } else {
            goto lab_0x306a;
        }
    }
  lab_0x31b0:;
    // 0x31b0
    int32_t v23; // 0x3030
    int32_t v24 = v23; // 0x31be
    int64_t v25; // 0x3030
    int64_t v26 = v25; // 0x31be
    int64_t v27; // 0x3030
    int64_t v28 = v27 + (int64_t)((int32_t)v25 > -1); // 0x31be
    goto lab_0x3131;
  lab_0x3131:;
    int64_t v29 = v26; // 0x3135
    int64_t v30 = v28; // 0x3135
    int64_t v31; // 0x3030
    int64_t v32; // 0x3030
    int64_t v33 = v32 - v27 + (int64_t)(v24 > (int32_t)v31) & 0xffffffff; // 0x3135
    goto lab_0x3100;
  lab_0x3108:;
    // 0x3108
    int64_t v40; // 0x3030
    int64_t v42 = v40;
    int64_t v35; // 0x3030
    int64_t v43 = 2 * v35; // 0x310c
    int64_t v36; // 0x3030
    int64_t v44 = 2 * v36; // 0x3111
    int32_t v45; // 0x3030
    int32_t v46 = v45 - 1; // 0x3114
    int64_t v47 = v43 & 0xfffffffe; // 0x3118
    int64_t v48 = v44 & 0xfffffffe; // 0x3118
    uint64_t v41; // 0x3030
    int64_t v49 = v41 / 2; // 0x3118
    int64_t v37; // 0x3030
    int64_t v50 = v37; // 0x3118
    int64_t v38; // 0x3030
    int64_t v51 = v38; // 0x3118
    v45 = v46;
    int64_t v52 = v42; // 0x3118
    if (v46 == 0) {
        // break -> 0x31c8
        goto lab_0x31c8;
    }
    goto lab_0x311e;
  lab_0x3100:;
    // 0x3100
    int64_t v34; // 0x311e
    v35 = v31 - v34 & 0xffffffff;
    v36 = v33;
    v37 = v30 & 0xffffffff;
    v38 = v29;
    int64_t v39; // 0x3030
    v40 = v39 + v41 & 0xffffffff;
    goto lab_0x3108;
  lab_0x317a:;
    int64_t v58 = 0;
    int64_t v59 = v10;
    int64_t v60 = 2 * v59 & 0xfffffffe; // 0x3180
    int64_t v61 = v58 + 1; // 0x3184
    while ((v59 & 0x80000) == 0) {
        // 0x3180
        v58 = v61 & 0xffffffff;
        v59 = v60;
        v60 = 2 * v59 & 0xfffffffe;
        v61 = v58 + 1;
    }
    uint32_t v62 = (int32_t)v61 % 32; // 0x3197
    uint32_t v63 = (int32_t)v13;
    int64_t v64 = v62 == 0 ? v13 : (int64_t)(v63 << v62);
    uint32_t v65 = (31 - (int32_t)v58) % 32;
    int64_t v66 = v16 - v58 & 0xffffffff; // 0x319f
    v7 = v66;
    v8 = v13 & 0xffffffff;
    v14 = v64;
    v11 = v60;
    int64_t v67 = v66; // 0x3030
    int64_t v68 = v64; // 0x3030
    int64_t v69 = v60; // 0x3030
    int64_t v70 = v63 >> v65; // 0x3030
    if (v65 == 0) {
        goto lab_dec_label_pc_unknown;
    } else {
        goto lab_dec_label_pc_unknown_2;
    }
  lab_0x306a:;
    uint64_t v71 = v15;
    int64_t v72 = v12;
    int64_t v73 = v9 % 0x100000 | 0x100000; // 0x3070
    int64_t v74 = v73; // 0x307f
    int64_t v75 = v72; // 0x307f
    if (v71 % 2 == 0) {
        // 0x3081
        v74 = 2 * v73 | (int64_t)(v72 < 0);
        v75 = 2 * v72 & 0xfffffffe;
    }
    int64_t v76 = 0; // 0x30a7
    int64_t v77 = 0;
    uint64_t v78 = 0x200000;
    int64_t v79 = 2 * v74 & 0xfffffffe | (int64_t)(v75 < 0);
    int64_t v80 = v76 + v78; // 0x30b0
    int64_t v81 = v79; // 0x30b5
    int64_t v82 = v77; // 0x30b5
    int64_t v83 = v76; // 0x30b5
    if (v79 >= (v80 & 0xffffffff)) {
        // 0x30b7
        v81 = v79 - v80 & 0xffffffff;
        v82 = v77 + v78 & 0xffffffff;
        v83 = v80 + v78 & 0xffffffff;
    }
    int64_t v84 = v82;
    int64_t v85 = 2 * (2 * v75 & 0xfffffffe) & 0xfffffffc; // 0x30c2
    int64_t v86 = 2 * v81 & 0xfffffffe;
    int32_t v87 = 21; // 0x30ca
    int64_t v88 = v85; // 0x30ce
    int64_t v89 = v78 / 2; // 0x30ce
    v76 = v83;
    int32_t v90 = v87; // 0x30ce
    v47 = v85;
    v48 = v86;
    v49 = 0x80000000;
    v50 = v83;
    v51 = 0;
    v45 = 32;
    v52 = 0;
    while (v87 != 0) {
        // 0x30b0
        v77 = v84;
        v78 = v89;
        v79 = v86;
        v80 = v76 + v78;
        v81 = v79;
        v82 = v77;
        v83 = v76;
        if (v79 >= (v80 & 0xffffffff)) {
            // 0x30b7
            v81 = v79 - v80 & 0xffffffff;
            v82 = v77 + v78 & 0xffffffff;
            v83 = v80 + v78 & 0xffffffff;
        }
        // 0x30be
        v84 = v82;
        v85 = 2 * v88 & 0xfffffffc;
        v86 = 2 * v81 & 0xfffffffe;
        v87 = v90 - 1;
        v88 = v85;
        v89 = v78 / 2;
        v76 = v83;
        v90 = v87;
        v47 = v85;
        v48 = v86;
        v49 = 0x80000000;
        v50 = v83;
        v51 = 0;
        v45 = 32;
        v52 = 0;
    }
    while (true) {
      lab_0x311e:
        // 0x311e
        v39 = v52;
        int64_t v53 = v51;
        v27 = v50;
        v41 = v49;
        v32 = v48;
        v31 = v47;
        v34 = v53 + v41;
        if (v32 > v27) {
            int64_t v54 = v34 + v41 & 0xffffffff; // 0x3126
            int32_t v55 = v34;
            v24 = v55;
            v26 = v54;
            v28 = v27;
            v23 = v55;
            v25 = v54;
            if (v55 < 0) {
                goto lab_0x31b0;
            } else {
                goto lab_0x3131;
            }
        } else {
            // 0x30e0
            v35 = v31;
            v36 = v32;
            v37 = v27;
            v38 = v53;
            v40 = v39;
            if ((int32_t)v32 != (int32_t)v27) {
                goto lab_0x3108;
            } else {
                int32_t v56 = v34;
                if (v56 > (int32_t)v31) {
                    goto lab_0x3108;
                } else {
                    int64_t v57 = v34 + v41 & 0xffffffff; // 0x30e6
                    v29 = v57;
                    v30 = v27;
                    v33 = 0;
                    v23 = v56;
                    v25 = v57;
                    if (v56 < 0) {
                        goto lab_0x31b0;
                    } else {
                        goto lab_0x3100;
                    }
                }
            }
        }
    }
  lab_0x31c8:;
    int64_t v91 = v42; // 0x31ca
    int64_t v92; // 0x3030
    int64_t v93; // 0x31ec
    int128_t v94; // 0x3206
    if ((int32_t)(v44 || v43) != 0) {
        if ((int32_t)v42 == -1) {
            // 0x31dc
            v92 = 0;
            uint64_t v95 = v84 + 1 & 0xffffffff;
            v93 = v95 % 2 != 0 ? v92 | 0x80000000 : v92;
            v94 = __asm_movq_5(0x100000000 * ((0x80000 * v71 + 0xe0080000 & 0xfff00000) + 0x3fe00000 + (int64_t)((int32_t)v95 >> 1)) | v93);
            return (int64_t)v94;
        }
        // 0x31d2
        v91 = v42 + 1 & 0xffffffff;
    }
    // 0x31dc
    v92 = v91 / 2 % 0x80000000;
    v93 = v84 % 2 != 0 ? v92 | 0x80000000 : v92;
    v94 = __asm_movq_5(0x100000000 * ((0x80000 * v71 + 0xe0080000 & 0xfff00000) + 0x3fe00000 + (int64_t)((int32_t)v84 >> 1)) | v93);
    return (int64_t)v94;
  lab_dec_label_pc_unknown:
    v67 = v7;
    v68 = v14;
    v69 = v11;
    v70 = v8;
    goto lab_dec_label_pc_unknown_2;
  lab_dec_label_pc_unknown_2:
    v9 = v70 | v69;
    v12 = v68;
    v15 = v67;
    goto lab_0x306a;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_strlen.c
// Address range: 0x3240 - 0x326b
// Line range:    5 - 15
int64_t libmin_strlen(char * str) {
    int64_t v1 = (int64_t)str;
    if (str == NULL || (char)v1 == 0) {
        // 0x3268
        return 0;
    }
    int64_t v2 = v1; // 0x3247
    v2++;
    while (*(char *)v2 != 0) {
        // 0x3258
        v2++;
    }
    // 0x3261
    return v2 - v1;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_success.c
// Address range: 0x3270 - 0x3279
// Line range:    5 - 7
void libmin_success(void) {
    // 0x3270
    libtarg_success();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_ctype.c
// Address range: 0x3280 - 0x32a2
// Line range:    140 - 146
int32_t _isctype(uint32_t c, int32_t mask) {
    int32_t result = 0; // 0x328f
    if (c < 256) {
        uint16_t v1 = *(int16_t *)((0x100000000 * (int64_t)c >> 31) + (int64_t)g6); // 0x329b
        result = (int32_t)v1 & mask;
    }
    // 0x32a1
    return result;
}

// Address range: 0x32a4 - 0x32b1
int64_t _fini(void) {
    // 0x32a4
    int64_t result; // 0x32a4
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 45

