//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;
typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int32_t _isctype(uint32_t c, int32_t mask);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t cointoss(void);
int64_t deregister_tm_clones(void);
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args);
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags);
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags);
int64_t frame_dummy(void);
void function_1070(int64_t * d);
void function_1080(void);
int32_t function_1090(int32_t c, struct _IO_FILE * stream);
int64_t * function_10a0(int64_t delta);
void function_10b0(int32_t status);
int64_t function_2bdd(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2be8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2bf3(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2bfe(void);
int64_t function_2c05(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int32_t libmin_atoi(char * s);
int64_t libmin_atol(char * s);
void libmin_fail(uint32_t code);
int32_t libmin_printf(char * fmt, ...);
int32_t libmin_rand(void);
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...);
int64_t libmin_srand(void);
int64_t libmin_strlen(char * str);
void libmin_success(void);
void libtarg_fail(int32_t code);
void libtarg_putc(char c);
char * libtarg_sbrk(int64_t inc);
void libtarg_success(void);
int64_t my_modf_isra_0(int64_t a1);
int64_t play_c(int64_t a1);
int64_t play_s(void);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int32_t argc = 6; // 0x7010
char * argv[6] = {
    "\x15\x43",
    "\x1e\x43",
    "!C",
    "$C",
    "'C",
    "\x92\x42"
}; // 0x7020
int32_t * g1 = (int32_t *)0x1000000004; // 0x38c
int32_t * g2 = (int32_t *)0x100000010; // 0x390
int32_t g3 = 0; // 0x3e8
int32_t g4 = 0; // 0x400
int32_t g5 = -0x2cf4; // 0x432c
int128_t g6; // 0x4450
int128_t g7; // 0x4458
int128_t g8; // 0x4460
int64_t g9 = -0x1fec00001e49; // 0x4520
int64_t g10 = -0x213c00001f99; // 0x4670
int64_t g11 = -0x228c000020e9; // 0x47c0
int64_t g12 = -0x66f74f2100000000; // 0x4960
int64_t g13 = 0x20002000200020; // 0x7062
struct _IO_FILE * g15 = NULL; // 0x7280
char g16 = 0; // 0x7288
int64_t g17 = 0; // 0x762c
int32_t g18 = 0; // 0x78d0
int32_t g19 = 0; // 0x7c5c
int64_t g20 = 0; // 0x7c60
int32_t mt[625]; // 0x72a0
int32_t mt_initialized = 0; // 0x7c64
int32_t mti = 625; // 0x7270
int32_t g21;
int64_t * g14 = &g13; // 0x7268

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x6fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g21;
    }
    // 0x1016
    return result;
}

// Address range: 0x1070 - 0x107b
void function_1070(int64_t * d) {
    // 0x1070
    __cxa_finalize(d);
}

// Address range: 0x1080 - 0x108b
void function_1080(void) {
    // 0x1080
    __stack_chk_fail();
}

// Address range: 0x1090 - 0x109b
int32_t function_1090(int32_t c, struct _IO_FILE * stream) {
    // 0x1090
    return fputc(c, stream);
}

// Address range: 0x10a0 - 0x10ab
int64_t * function_10a0(int64_t delta) {
    // 0x10a0
    return sbrk(delta);
}

// Address range: 0x10b0 - 0x10bb
void function_10b0(int32_t status) {
    // 0x10b0
    exit(status);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/parrondo/parrondo.c
// Address range: 0x10c0 - 0x1670
// Line range:    124 - 260
int main() {
    int64_t site_visits[3]; // bp-96, 0x10c0
    int64_t v1[3]; // 0x1134
    int64_t v2[3]; // 0x1585
    // 0x10c0
    int128_t v3; // 0x10c0
    int128_t v4 = v3;
    int128_t v5 = v3;
    __readfsqword(40);
    if (argc >= 2) {
        int128_t v6 = __asm_movsd(0x3fe0000000000000); // 0x10f1
        __asm_movsd_1(v6);
        int64_t v7 = __asm_movsd_1(__asm_pxor(v6, v6)); // 0x1134
        v1[0] = v7;
        site_visits = v1;
        int64_t v8 = *(int64_t *)((int64_t)&argv + 8); // 0x1143
        if (*(char *)v8 != 45) {
            // 0x1180
            libmin_printf((char *)(int64_t)"%s\n", (char *)(int64_t)"parrondo [ -s number -t number -m number -1 -2 -h -v]");
            libmin_fail(1);
            // UNREACHABLE
        }
        int64_t v9 = (int64_t)*(char *)(v8 + 1) + 0xffffffcf; // 0x1154
        if ((char)v9 < 70) {
            int32_t v10 = *(int32_t *)((4 * v9 & 1020) + (int64_t)&g5); // 0x1165
            return v10 + (int32_t)&g5;
        }
        // 0x1180
        libmin_printf((char *)(int64_t)"parrondo: unkown option %s\n", (char *)v8);
        libmin_fail(1);
        // UNREACHABLE
    }
    int128_t v11 = __asm_pxor(v4, v4); // 0x156e
    int128_t v12 = __asm_movsd(0x3fe0000000000000); // 0x1572
    int64_t v13 = __asm_movsd_1(v11); // 0x1585
    v2[0] = v13;
    site_visits = v2;
    int64_t v14 = __asm_movsd_1(v12); // 0x158b
    libmin_printf("Using seed = %d\n", 3445);
    libmin_srand();
    libmin_printf("Simulating %d trials ...\n", (int64_t)&g3);
    int64_t v15 = __asm_movsd_1(__asm_movsd(site_visits[0]));
    int64_t v16 = v15; // 0x11f7
    int32_t v17 = 0; // 0x11f7
    if ((int32_t)&g3 >= 1) {
        // 0x1230
        int128_t v18; // 0x10c0
        int128_t v19 = v18;
        libmin_rand();
        libmin_srand();
        uint32_t v20 = libmin_rand(); // 0x12a3
        __asm_pxor(v19, v19);
        int128_t v21 = __asm_divsd(__asm_cvtsi2sd((int64_t)v20), 0x41dfffffffc00000); // 0x12b3
        __asm_comisd(v21, (int128_t)v14);
        uint32_t v22 = libmin_rand(); // 0x1230
        __asm_pxor(v21, v21);
        int128_t v23 = __asm_divsd(__asm_cvtsi2sd((int64_t)v22), 0x41dfffffffc00000); // 0x1240
        __asm_comisd(v23, g6);
        __asm_pxor(v23, v23);
        int128_t v24 = __asm_addsd(__asm_cvtsi2sd(1), v15); // 0x1328
        int64_t v25 = 1; // 0x132e
        int64_t v26 = __asm_movsd_1(v24); // 0x1332
        int64_t v27 = v25 & 0xffffffff; // 0x133b
        v16 = v26;
        v17 = &g3;
        while ((int32_t)v25 != (int32_t)&g3) {
            // 0x1230
            v19 = v24;
            libmin_rand();
            libmin_srand();
            v20 = libmin_rand();
            __asm_pxor(v19, v19);
            v21 = __asm_divsd(__asm_cvtsi2sd((int64_t)v20), 0x41dfffffffc00000);
            __asm_comisd(v21, (int128_t)v14);
            v22 = libmin_rand();
            __asm_pxor(v21, v21);
            v23 = __asm_divsd(__asm_cvtsi2sd((int64_t)v22), 0x41dfffffffc00000);
            __asm_comisd(v23, g6);
            __asm_pxor(v23, v23);
            v24 = __asm_addsd(__asm_cvtsi2sd(1), v26);
            v25 = v27 + 1;
            v26 = __asm_movsd_1(v24);
            v27 = v25 & 0xffffffff;
            v16 = v26;
            v17 = &g3;
        }
    }
    // 0x1341
    __asm_pxor(v5, v5);
    int128_t v28 = __asm_cvtsi2sd_2(v17); // 0x1350
    int64_t v29 = __asm_movsd_1(__asm_divsd_3(__asm_movsd(v16), v28)); // 0x136e
    libmin_printf("%d wins, %d losses, %d draws\n");
    libmin_printf("(Win/loss = %d/-%d, draw = no win/loss in %ld plays.)\n", 50, 50, 0xf4240);
    int128_t v30 = __asm_movsd(v29); // 0x138f
    libmin_printf("Average trial length = %lf\n", (float64_t)(int64_t)v30);
    __asm_pxor(v11, v11);
    __asm_pxor(v28, v28);
    __asm_pxor(v30, v30);
    int128_t v31 = __asm_cvtsi2sd(0); // 0x13b1
    int128_t v32 = __asm_movsd(0x4059000000000000); // 0x13b8
    int128_t v33 = __asm_movsd(v16); // 0x13c0
    int128_t v34 = __asm_cvtsi2sd(0); // 0x13cd
    int128_t v35 = __asm_cvtsi2sd(0); // 0x13d9
    int128_t v36 = __asm_mulsd(v31, v32); // 0x13e0
    int128_t v37 = __asm_mulsd(v34, v32); // 0x13e4
    int128_t v38 = __asm_mulsd(v35, v32); // 0x13e8
    __asm_divsd_3(v36, v33);
    __asm_divsd_3(v38, v33);
    __asm_divsd_3(v37, v33);
    libmin_printf("Site occupancy: 0 mod 3: %lf%%, 1 mod 3: %lf%%, 2 mod 3: %lf%%\n");
    libmin_success();
    // UNREACHABLE
}

// Address range: 0x1670 - 0x1696
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1670
    int64_t v1; // 0x1670
    __libc_start_main(0x10c0, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x16a0 - 0x16c9
int64_t deregister_tm_clones(void) {
    // 0x16a0
    return 0x7278;
}

// Address range: 0x16d0 - 0x1709
int64_t register_tm_clones(void) {
    // 0x16d0
    return 0;
}

// Address range: 0x1710 - 0x1749
int64_t __do_global_dtors_aux(void) {
    // 0x1710
    if (g16 != 0) {
        // 0x1748
        int64_t result; // 0x1710
        return result;
    }
    // 0x171d
    if (*(int64_t *)0x6ff8 != 0) {
        // 0x172b
        __cxa_finalize((int64_t *)*(int64_t *)0x7008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1737
    g16 = 1;
    return result2;
}

// Address range: 0x1750 - 0x1759
int64_t frame_dummy(void) {
    // 0x1750
    return register_tm_clones();
}

// Address range: 0x1760 - 0x1799
int64_t cointoss(void) {
    // 0x1760
    int128_t v1; // 0x1760
    int128_t v2 = v1;
    int64_t v3 = __asm_movsd_1(v2); // 0x1768
    uint32_t v4 = libmin_rand(); // 0x176e
    __asm_pxor(v2, v2);
    __asm_comisd(__asm_divsd(__asm_cvtsi2sd((int64_t)v4), 0x41dfffffffc00000), (int128_t)v3);
    int64_t v5; // 0x1760
    return (uint64_t)v5 < 24 ? 1 : 0xffffffff;
}

// Address range: 0x17a0 - 0x17d5
int64_t play_s(void) {
    // 0x17a0
    int128_t v1; // 0x17a0
    int128_t v2 = v1;
    uint32_t v3 = libmin_rand(); // 0x17a8
    __asm_pxor(v2, v2);
    __asm_comisd(__asm_divsd(__asm_cvtsi2sd((int64_t)v3), 0x41dfffffffc00000), g6);
    int64_t v4; // 0x17a0
    return (uint64_t)v4 < 8 ? 1 : 0xffffffff;
}

// Address range: 0x17e0 - 0x185c
int64_t play_c(int64_t a1) {
    // 0x17e0
    int128_t v1; // 0x17e0
    int128_t v2 = v1;
    uint32_t v3 = -0x55555555 * (int32_t)a1 + 0x2aaaaaaa; // 0x17ee
    uint32_t v4 = libmin_rand();
    __asm_pxor(v2, v2);
    int128_t v5 = __asm_divsd(__asm_cvtsi2sd((int64_t)v4), 0x41dfffffffc00000);
    if (v3 < 0x55555555) {
        // 0x17fc
        __asm_comisd(v5, g8);
        if (v3 != 0x55555554) {
            // 0x181e
            return 1;
        }
    } else {
        // 0x1830
        __asm_comisd(v5, g7);
    }
    // 0x181e
    return 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1860 - 0x1871
// Line range:    124 - 127
void libtarg_success(void) {
    // 0x1860
    exit(0);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1880 - 0x188f
// Line range:    162 - 165
void libtarg_fail(int32_t code) {
    // 0x1880
    exit(code);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1890 - 0x18a4
// Line range:    188 - 191
void libtarg_putc(char c) {
    // 0x1890
    fputc((int32_t)c, g15);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x18b0 - 0x18b9
// Line range:    230 - 236
char * libtarg_sbrk(int64_t inc) {
    // 0x18b0
    return (char *)sbrk(inc);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_atoi.c
// Address range: 0x18c0 - 0x1946
// Line range:    6 - 18
int32_t libmin_atoi(char * s) {
    int64_t v1 = (int64_t)s;
    int64_t v2 = (int64_t)g14; // 0x18c8
    int64_t v3 = v1; // 0x18d6
    int64_t v4 = v1; // 0x18d6
    char v5 = v1; // 0x18d6
    if ((*(char *)((0x100000000000000 * v1 >> 55) + v2) & 8) != 0) {
        v3++;
        char v6 = *(char *)v3; // 0x18e0
        v4 = v3;
        v5 = v6;
        while ((*(char *)(2 * (int64_t)v6 + v2) & 8) != 0) {
            // 0x18e0
            v3++;
            v6 = *(char *)v3;
            v4 = v3;
            v5 = v6;
        }
    }
    int32_t v7 = 0; // 0x18f7
    int64_t v8; // 0x18c0
    int32_t v9; // 0x18c0
    if (v5 == 43) {
        goto lab_0x1903;
    } else {
        // 0x18f9
        v7 = 1;
        v8 = v4;
        v9 = 0;
        if (v5 != 45) {
            goto lab_0x1907;
        } else {
            goto lab_0x1903;
        }
    }
  lab_0x1903:
    // 0x1903
    v8 = v4 + 1;
    v9 = v7;
    goto lab_0x1907;
  lab_0x1907:;
    int64_t v10 = (int64_t)*(char *)v8; // 0x1907
    int32_t v11; // 0x18c0
    if ((*(char *)(2 * v10 + v2) & 4) == 0) {
        // 0x193b
        v11 = 0;
        return v9 == 0 ? -v11 : v11;
    }
    int64_t v12 = v8 + 1; // 0x1926
    int64_t v13 = 48 - v10; // 0x192c
    int64_t v14 = (int64_t)*(char *)v12; // 0x192e
    int64_t v15 = v12; // 0x1939
    int64_t v16 = v13 & 0xffffffff; // 0x1939
    while ((*(char *)(2 * v14 + v2) & 4) != 0) {
        // 0x1920
        v12 = v15 + 1;
        v13 = 48 - v14 + 10 * v16;
        v14 = (int64_t)*(char *)v12;
        v15 = v12;
        v16 = v13 & 0xffffffff;
    }
    // 0x193b
    v11 = v13;
    return v9 == 0 ? -v11 : v11;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_atol.c
// Address range: 0x1950 - 0x19df
// Line range:    5 - 18
int64_t libmin_atol(char * s) {
    int64_t v1 = (int64_t)s;
    int64_t v2 = (int64_t)g14; // 0x1958
    int64_t v3 = v1; // 0x1966
    int64_t v4 = v1; // 0x1966
    char v5 = v1; // 0x1966
    if ((*(char *)((0x100000000000000 * v1 >> 55) + v2) & 8) != 0) {
        v3++;
        char v6 = *(char *)v3; // 0x1970
        v4 = v3;
        v5 = v6;
        while ((*(char *)(2 * (int64_t)v6 + v2) & 8) != 0) {
            // 0x1970
            v3++;
            v6 = *(char *)v3;
            v4 = v3;
            v5 = v6;
        }
    }
    int32_t v7 = 0; // 0x1987
    int64_t v8; // 0x1950
    int32_t v9; // 0x1950
    if (v5 == 43) {
        goto lab_0x1993;
    } else {
        // 0x1989
        v7 = 1;
        v8 = v4;
        v9 = 0;
        if (v5 != 45) {
            goto lab_0x1997;
        } else {
            goto lab_0x1993;
        }
    }
  lab_0x1993:
    // 0x1993
    v8 = v4 + 1;
    v9 = v7;
    goto lab_0x1997;
  lab_0x1997:;
    int64_t v10 = (int64_t)*(char *)v8; // 0x1997
    int64_t v11; // 0x1950
    if ((*(char *)(2 * v10 + v2) & 4) == 0) {
        // 0x19d1
        v11 = 0;
        return v9 == 0 ? -v11 : v11;
    }
    int64_t v12 = v8 + 1; // 0x19b7
    int64_t v13 = -((0x100000000 * v10 - 0x3000000000 >> 32)); // 0x19c1
    int64_t v14 = (int64_t)*(char *)v12; // 0x19c4
    int64_t v15 = v12; // 0x19cf
    int64_t v16 = v13; // 0x19cf
    while ((*(char *)(2 * v14 + v2) & 4) != 0) {
        // 0x19b0
        v12 = v15 + 1;
        v13 = 10 * v16 - (0x100000000 * v14 - 0x3000000000 >> 32);
        v14 = (int64_t)*(char *)v12;
        v15 = v12;
        v16 = v13;
    }
    // 0x19d1
    v11 = v13;
    return v9 == 0 ? -v11 : v11;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_ctype.c
// Address range: 0x19e0 - 0x1a02
// Line range:    140 - 146
int32_t _isctype(uint32_t c, int32_t mask) {
    int32_t result = 0; // 0x19ef
    if (c < 256) {
        uint16_t v1 = *(int16_t *)((0x100000000 * (int64_t)c >> 31) + (int64_t)g14); // 0x19fb
        result = (int32_t)v1 & mask;
    }
    // 0x1a01
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fail.c
// Address range: 0x1a10 - 0x1a2f
// Line range:    5 - 8
void libmin_fail(uint32_t code) {
    // 0x1a10
    libmin_printf("ERROR: failure with termination code `%d'\n", (int64_t)code);
    libtarg_fail(code);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1a30 - 0x1c78
// Line range:    426 - 483
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags) {
    int64_t v1 = flags; // 0x1a3f
    int64_t v2 = value; // 0x1a5f
    int64_t v3 = 0; // 0x1a5f
    int32_t v4 = 0; // 0x1a5f
    if ((flags & 64) == 0) {
        if (value < 0) {
            // 0x1c40
            v2 = -value;
            v3 = 45;
            v4 = -1;
        } else {
            // 0x1a6a
            v2 = value;
            v3 = 43;
            v4 = -1;
            if ((v1 & 2) == 0) {
                uint32_t v5 = 8 * flags & 32; // 0x1c63
                v2 = value;
                v3 = v5;
                v4 = v5 != 0;
            }
        }
    }
    int64_t v6 = (int64_t)currlen;
    int64_t v7 = (int64_t)buffer;
    uint32_t v8 = max > 0 ? max : 0; // 0x1a57
    uint64_t v9 = (int64_t)base; // 0x1a92
    int64_t v10; // bp-89, 0x1a30
    int64_t v11 = &v10; // 0x1a95
    int64_t v12 = (v1 & 32) == 0 ? (int64_t)"0123456789abcdef" : (int64_t)"0123456789ABCDEF"; // 0x1aad
    uint64_t v13 = v2; // 0x1ab1
    int64_t v14 = 1;
    *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
    int32_t v15 = v14;
    int32_t v16 = v15 - 19; // 0x1ad8
    int64_t v17 = v14 + 1; // 0x1ae4
    while (v13 >= v9 == (v16 == 0 || v16 < 0 != (18 - v15 & v15) < 0)) {
        // 0x1ab8
        v13 /= v9;
        v14 = v17;
        *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
        v15 = v14;
        v16 = v15 - 19;
        v17 = v14 + 1;
    }
    int64_t v18 = v15 == 20 ? 19 : v14 & 0xffffffff; // 0x1af6
    int32_t v19 = v18; // 0x1afa
    int32_t v20 = v8 - v19; // 0x1afa
    int64_t v21 = 0x100000000 * v18 >> 32; // 0x1b00
    int64_t v22; // bp-48, 0x1a30
    int64_t v23 = (int64_t)&v22 - 40 + v21; // 0x1b07
    *(char *)v23 = 0;
    uint32_t v24 = min - (int32_t)(v20 < 0 == (v20 & v19) < 0 ? (int64_t)v8 : v18) + v4; // 0x1b13
    uint32_t v25 = v20 > 0 ? v20 : 0; // 0x1b19
    int64_t v26 = v25; // 0x1b19
    int64_t v27 = v24 >= 0 ? (int64_t)v24 : 0; // 0x1b25
    int64_t v28; // 0x1a30
    int64_t v29; // 0x1a30
    int64_t v30; // 0x1a30
    if ((v1 & 16) == 0) {
        if (flags % 2 != 0) {
            // 0x1c20
            v29 = v6;
            v30 = -v27 & 0xffffffff;
            v28 = v26;
        } else {
            // 0x1be4
            v29 = v6;
            v30 = v27;
            v28 = v26;
            if (v24 >= 1) {
                if (v6 < maxlen) {
                    // 0x1bf5
                    *(char *)(v6 + v7) = 32;
                }
                int64_t v31 = v6 + 1; // 0x1bfc
                *currlen = v31;
                uint32_t v32 = (int32_t)v27 - 1; // 0x1c03
                int64_t v33 = v32; // 0x1c06
                while (v32 != 0) {
                    int64_t v34 = v31;
                    int64_t v35 = v34; // 0x1bf3
                    if (v34 < maxlen) {
                        // 0x1bf5
                        *(char *)(v34 + v7) = 32;
                        v35 = v6;
                    }
                    // 0x1bfc
                    v31 = v35 + 1;
                    *currlen = v31;
                    v32 = (int32_t)v33 - 1;
                    v33 = v32;
                }
                int32_t v36 = v27; // 0x1c08
                v29 = v31;
                v30 = v27 - (v36 >= 0 == (v36 != 0) ? v27 : 1) & 0xffffffff;
                v28 = v26;
            }
        }
    } else {
        int32_t v37 = v27; // 0x1b36
        int32_t v38 = v25 - v37; // 0x1b36
        v29 = v6;
        v30 = 0;
        v28 = v38 < 0 == (v38 & v37) < 0 ? v26 : v27;
    }
    int64_t v39 = v29; // 0x1b42
    if (v3 != 0) {
        int64_t v40 = v29; // 0x1b47
        if (v29 < maxlen) {
            // 0x1c30
            *(char *)(v29 + v7) = (char)v3;
            v40 = v6;
        }
        // 0x1b4d
        v39 = v40 + 1;
        *currlen = v39;
    }
    int64_t v41 = v39; // 0x1b57
    uint32_t v42 = v28; // 0x1b57
    if ((int32_t)v28 != 0) {
        int64_t v43 = v39; // 0x1bc3
        if (v39 < maxlen) {
            // 0x1bc5
            *(char *)(v39 + v7) = 48;
            v43 = v6;
        }
        int64_t v44 = v43 + 1; // 0x1bcc
        *currlen = v44;
        v41 = v44;
        while (v42 != 0) {
            // 0x1bc0
            v42 = (int64_t)v42;
            int64_t v45 = v44;
            v43 = v45;
            if (v45 < maxlen) {
                // 0x1bc5
                *(char *)(v45 + v7) = 48;
                v43 = v6;
            }
            // 0x1bcc
            v44 = v43 + 1;
            *currlen = v44;
            v41 = v44;
        }
    }
    int64_t v46 = v23; // 0x1b68
    v46--;
    int64_t v47 = v41; // 0x1b73
    if (v41 < maxlen) {
        // 0x1b75
        *(char *)(v41 + v7) = *(char *)v46;
        v47 = v6;
    }
    int64_t v48 = v47 + 1; // 0x1b80
    *currlen = v48;
    while (v21 + v11 - (v18 + 0xffffffff & 0xffffffff) != v46) {
        int64_t v49 = v48;
        v46--;
        v47 = v49;
        if (v49 < maxlen) {
            // 0x1b75
            *(char *)(v49 + v7) = *(char *)v46;
            v47 = v6;
        }
        // 0x1b80
        v48 = v47 + 1;
        *currlen = v48;
    }
    // 0x1b90
    if (v30 == 0) {
        // 0x1bb0
        return;
    }
    uint32_t v50 = v30; // 0x1b92
    int64_t v51 = v48; // 0x1b9b
    if (v48 < maxlen) {
        // 0x1b9d
        *(char *)(v48 + v7) = 32;
        v51 = v6;
    }
    int64_t v52 = v51 + 1; // 0x1ba4
    *currlen = v52;
    while (v50 != 0) {
        // 0x1b98
        v50 = (int64_t)v50;
        int64_t v53 = v52;
        v51 = v53;
        if (v53 < maxlen) {
            // 0x1b9d
            *(char *)(v53 + v7) = 32;
            v51 = v6;
        }
        // 0x1ba4
        v52 = v51 + 1;
        *currlen = v52;
    }
}

// Address range: 0x1c80 - 0x1d33
int64_t my_modf_isra_0(int64_t a1) {
    // 0x1c80
    int128_t v1; // 0x1c80
    int128_t v2 = __asm_movapd(v1); // 0x1c81
    int128_t v3 = __asm_movsd(0x3ff0000000000000); // 0x1c8e
    int128_t v4 = __asm_movsd(0x3fb999999999999a); // 0x1c96
    int128_t v5 = __asm_movsd(0x4024000000000000); // 0x1c9e
    int128_t v6 = __asm_movapd(v3); // 0x1ca6
    int64_t v7; // bp-8, 0x1c80
    bool v8 = &v7 < (int64_t *)32; // 0x1caa
    int64_t result2 = 0;
    int128_t v9 = v6;
    int128_t v10; // 0x1c80
    int128_t v11 = v10;
    int128_t v12 = v2;
    int64_t v13 = __asm_cvttsd2si_5(v12); // 0x1cc0
    __asm_pxor(v11, v11);
    int128_t v14 = __asm_addsd_4(__asm_movapd(v12), v3); // 0x1ccd
    int128_t v15 = __asm_cvtsi2sd(v13); // 0x1cd1
    __asm_comisd(v14, v15);
    while (v8) {
        int64_t v16 = result2 + 1; // 0x1cb4
        int64_t result = v16 & 0xffffffff; // 0x1cb4
        uint32_t v17 = (int32_t)v16; // 0x1cbb
        v8 = v17 < 100;
        int128_t v18 = __asm_mulsd(v12, v4); // 0x1cbe
        int128_t v19 = __asm_mulsd(v9, v5); // 0x1cbe
        if (v17 == 100) {
            // 0x1cf8
            *(int64_t *)a1 = 0;
            return result;
        }
        result2 = result;
        v9 = v19;
        v11 = v15;
        v12 = v18;
        v13 = __asm_cvttsd2si_5(v12);
        __asm_pxor(v11, v11);
        v14 = __asm_addsd_4(__asm_movapd(v12), v3);
        v15 = __asm_cvtsi2sd(v13);
        __asm_comisd(v14, v15);
    }
    // 0x1cdc
    __asm_comisd(v15, __asm_subsd(__asm_movapd(v12), v3));
    if (result2 == 0) {
        // 0x1cee
        *(int64_t *)a1 = __asm_movsd_1(v15);
        return result2;
    }
    int128_t v20 = __asm_mulsd(v15, v9); // 0x1d05
    __asm_subsd(v1, v20);
    int64_t v21 = __asm_movsd_1(v20); // 0x1d12
    int64_t v22; // bp-16, 0x1c80
    int64_t result3 = my_modf_isra_0((int64_t)&v22); // 0x1d18
    *(int64_t *)a1 = __asm_movsd_1(__asm_addsd(__asm_movsd(v21), v22));
    return result3;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1d40 - 0x22c0
// Line range:    586 - 525
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags) {
    char iconvert[311]; // bp-704, 0x1d40
    char v1[311]; // 0x1d40
    char v2[311]; // 0x22a8
    char v3[311]; // 0x21e2
    char v4[311]; // 0x1e43
    char v5[311]; // 0x21bc
    // 0x1d40
    int128_t v6; // 0x1d40
    int128_t v7 = v6;
    int128_t v8 = v6;
    int128_t v9 = v6;
    int3_t v10; // 0x1d40
    int3_t v11 = v10 - 1;
    float80_t v12; // 0x1d40
    __frontend_reg_store_fpr(v11, v12);
    int32_t v13 = 6; // 0x1d65
    int64_t v14 = 6; // 0x1d65
    if (max >= 0) {
        int32_t v15 = max - 16; // 0x1d71
        v14 = v15 == 0 | v15 < 0 != (15 - max & max) < 0 ? (int64_t)max : 16;
        v13 = max;
    }
    uint64_t v16 = (int64_t)flags;
    int3_t v17 = v10 - 2; // 0x1d78
    __frontend_reg_store_fpr(v17, 0.0L);
    float80_t v18 = __frontend_reg_load_fpr(v17); // 0x1d7a
    float80_t v19 = __frontend_reg_load_fpr(v11); // 0x1d7a
    float80_t v20 = __frontend_reg_load_fpr(v11);
    int32_t v21; // 0x1d40
    int32_t v22; // 0x1d40
    float64_t v23; // bp-744, 0x1d40
    int128_t v24; // 0x1d40
    if (v18 > v19) {
        // 0x21f0
        __frontend_reg_store_fpr(v11, -v20);
        float64_t v25 = __frontend_reg_load_fpr(v11); // 0x21fa
        v23 = v25;
        v22 = 45;
        v21 = 1;
        v24 = __asm_movsd((int64_t)v25);
    } else {
        float64_t v26 = v20; // 0x1d82
        v23 = v26;
        int128_t v27 = __asm_movsd((int64_t)v26); // 0x1d85
        v22 = 43;
        v21 = 1;
        v24 = v27;
        if ((v16 & 2) == 0) {
            int32_t v28 = 8 * flags & 32; // 0x1d9d
            v22 = v28;
            v21 = v28 != 0;
            v24 = v27;
        }
    }
    // 0x1dae
    __asm_movapd(v24);
    float64_t fracpart; // bp-712, 0x1d40
    int64_t v29 = &fracpart; // 0x1db8
    my_modf_isra_0(v29);
    bool v30; // 0x1d40
    bool v31; // 0x1d40
    int128_t v32; // 0x1d40
    int128_t v33; // 0x1d40
    int128_t v34; // 0x1d40
    bool v35; // 0x1d40
    bool v36; // 0x1d40
    if (v13 == 0) {
        int128_t v37 = __asm_movsd((int64_t)fracpart); // 0x2254
        int128_t v38 = __asm_subsd(v24, v37); // 0x225a
        int64_t v39 = __asm_cvttsd2si_5(v38); // 0x225f
        v23 = __asm_movsd_1(v38);
        __frontend_reg_store_fpr(v11, (float80_t)v39);
        __frontend_reg_store_fpr(v11, (float80_t)v23 - __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v17, 0.5L);
        float80_t v40 = __frontend_reg_load_fpr(v17); // 0x227c
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v40);
        float80_t v41 = __frontend_reg_load_fpr(v17); // 0x227e
        float80_t v42 = __frontend_reg_load_fpr(v11); // 0x227e
        bool v43 = false; // 0x227e
        bool v44 = false; // 0x227e
        bool v45 = false; // 0x227e
        if (v41 <= v42) {
            v43 = true;
            v44 = false;
            v45 = false;
            if (v41 >= v42) {
                v43 = v41 != v42;
                v44 = v41 != v42;
                v45 = true;
            }
        }
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
        bool v46 = true; // 0x2282
        bool v47 = v44; // 0x2282
        bool v48 = v45; // 0x2282
        int64_t v49 = v39; // 0x2282
        if (!v43) {
            // 0x2284
            v49 = v39 + 1;
            v46 = v39 == -1;
            v47 = llvm_ctpop_i8((char)v49) % 2 == 0;
            v48 = v49 == 0;
        }
        // 0x2288
        __asm_pxor(v7, v7);
        int128_t v50 = __asm_movsd(0x3ff0000000000000); // 0x228d
        int128_t v51 = __asm_cvtsi2sd(v49); // 0x2295
        v23 = __asm_movsd_1(v51);
        __asm_comisd(v51, v50);
        __frontend_reg_store_fpr(v11, (float80_t)v23);
        int64_t v52 = __asm_movsd_1(v51); // 0x22a8
        v2[0] = v52;
        iconvert = v2;
        if (v46) {
            // 0x1e70
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v47;
            v35 = v48;
            v32 = v37;
            v34 = v51;
            goto lab_0x1e78;
        } else {
            int128_t v53 = __asm_addsd_4(v37, v50); // 0x22b5
            __frontend_reg_store_fpr(v17, 1.0L);
            v31 = v47;
            v36 = v48;
            v33 = v53;
            goto lab_0x21ab;
        }
    } else {
        // 0x1dc9
        __frontend_reg_store_fpr(v11, 1.0L);
        __frontend_reg_store_fpr(v17, 10.0L);
        int64_t v54 = v14 & 0xffffffff; // 0x1dd1
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
        uint32_t v55 = (int32_t)v54 - 1; // 0x1dda
        int64_t v56 = v55; // 0x1ddd
        while (v55 != 0) {
            // 0x1dd8
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
            v55 = (int32_t)v56 - 1;
            v56 = v55;
        }
        float80_t v57 = __frontend_reg_load_fpr(v17); // 0x1ddf
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v57);
        int128_t v58 = __asm_movsd((int64_t)fracpart); // 0x1de5
        v23 = __asm_movsd_1(__asm_subsd(v24, v58));
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) * (float80_t)v23);
        int3_t v59 = v10 - 3;
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        float80_t v60 = __frontend_reg_load_fpr(v59); // 0x1e0c
        v23 = v60;
        __frontend_reg_store_fpr(v59, v60);
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) - __frontend_reg_load_fpr(v59));
        __frontend_reg_store_fpr(v59, 0.5L);
        float80_t v61 = __frontend_reg_load_fpr(v59); // 0x1e1e
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v61);
        float80_t v62 = __frontend_reg_load_fpr(v59); // 0x1e20
        float80_t v63 = __frontend_reg_load_fpr(v17); // 0x1e20
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
        if (v62 < v63) {
            // 0x21d0
            __asm_pxor(v9, v9);
            int128_t v64 = __asm_cvtsi2sd((int64_t)v23); // 0x21d4
            int64_t v65 = __asm_movsd_1(v64); // 0x21da
            v23 = v65;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v65);
            int64_t v66 = __asm_movsd_1(v64); // 0x21e2
            v3[0] = v66;
            v1 = v3;
        } else {
            // 0x1e2a
            __asm_pxor(v9, v9);
            int128_t v67 = __asm_cvtsi2sd((int64_t)v23 + 1); // 0x1e36
            int64_t v68 = __asm_movsd_1(v67); // 0x1e3b
            v23 = v68;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v68);
            int64_t v69 = __asm_movsd_1(v67); // 0x1e43
            v4[0] = v69;
            v1 = v4;
        }
        // 0x1e49
        iconvert = v1;
        __frontend_reg_store_fpr(v59, 1.0L);
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
        uint32_t v70 = (int32_t)v54 - 1; // 0x1e52
        int64_t v71 = v70; // 0x1e55
        while (v70 != 0) {
            // 0x1e50
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            v70 = (int32_t)v71 - 1;
            v71 = v70;
        }
        float80_t v72 = __frontend_reg_load_fpr(v59); // 0x1e57
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v72);
        float80_t v73 = __frontend_reg_load_fpr(v59); // 0x1e59
        float80_t v74 = __frontend_reg_load_fpr(v17); // 0x1e59
        bool v75 = false; // 0x1e59
        bool v76 = false; // 0x1e59
        bool v77 = false; // 0x1e59
        if (v73 <= v74) {
            v75 = true;
            v76 = false;
            v77 = false;
            if (v73 >= v74) {
                v75 = v73 != v74;
                v76 = v73 != v74;
                v77 = true;
            }
        }
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v59));
        if (!v75) {
            int128_t v78 = __asm_addsd(v58, 0x3ff0000000000000); // 0x2190
            __frontend_reg_store_fpr(v59, 1.0L);
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            uint32_t v79 = (int32_t)v54 - 1; // 0x21a2
            int64_t v80 = v79; // 0x21a5
            while (v79 != 0) {
                // 0x21a0
                __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
                v79 = (int32_t)v80 - 1;
                v80 = v79;
            }
            unsigned char v81 = llvm_ctpop_i8((char)v79); // 0x21a2
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v59));
            float80_t v82 = __frontend_reg_load_fpr(v17); // 0x21a9
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
            __frontend_reg_store_fpr(v11, v82);
            v31 = v81 % 2 == 0;
            v36 = true;
            v33 = v78;
            goto lab_0x21ab;
        } else {
            // 0x1e63
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v76;
            v35 = v77;
            v32 = v58;
            v34 = __asm_movsd(*(int64_t *)&iconvert);
            goto lab_0x1e78;
        }
    }
  lab_0x1e78:;
    int64_t v83 = (int64_t)currlen;
    int64_t v84 = (int64_t)buffer;
    int64_t v85 = &v23; // 0x1d50
    int64_t v86; // bp-697, 0x1d40
    int64_t v87 = &v86; // 0x1e7d
    int128_t v88 = __asm_pxor(v8, v8); // 0x1e82
    int128_t v89 = __asm_movsd(0x3fb999999999999a); // 0x1e87
    int128_t v90 = __asm_movsd(0x3fa999999999999a); // 0x1e90
    int128_t v91 = __asm_movsd(0x4024000000000000); // 0x1ea0
    bool v92 = v30; // 0x1ea9
    bool v93 = v35; // 0x1ea9
    int64_t v94 = 1;
    int128_t v95 = __asm_movapd(__asm_mulsd(v32, v89)); // 0x1ecc
    my_modf_isra_0(v29);
    int128_t v96 = __asm_movsd((int64_t)fracpart); // 0x1ed6
    int128_t v97 = __asm_subsd(v95, v96); // 0x1edc
    __asm_ucomisd(v96, v88);
    int32_t v98 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd_4(v97, v90), v91)); // 0x1ef0
    char v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef"); // 0x1ef7
    *(char *)(v94 + v87) = v99;
    bool v100; // 0x1d40
    int64_t v101; // 0x1d40
    bool v102; // 0x1d40
    while (v92 || !v93) {
        int64_t v103 = v94 - 311; // 0x1eb4
        unsigned char v104 = llvm_ctpop_i8((char)v103); // 0x1eb4
        v92 = v104 % 2 == 0;
        v93 = false;
        v100 = v104 % 2 == 0;
        v102 = true;
        v101 = 310;
        if (v103 == 0) {
            goto lab_0x1f13;
        }
        v94++;
        v95 = __asm_movapd(__asm_mulsd(v96, v89));
        my_modf_isra_0(v29);
        v96 = __asm_movsd((int64_t)fracpart);
        v97 = __asm_subsd(v95, v96);
        __asm_ucomisd(v96, v88);
        v98 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd_4(v97, v90), v91));
        v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef");
        *(char *)(v94 + v87) = v99;
    }
    int32_t v105 = (int32_t)v94 - 311; // 0x1f04
    v100 = llvm_ctpop_i8((char)v105) % 2 == 0;
    v102 = v105 == 0;
    v101 = v105 == 0 ? 310 : v94 & 0xffffffff;
  lab_0x1f13:
    // 0x1f13
    __asm_ucomisd(v34, v88);
    int64_t v106 = 0x100000000 * v101 >> 32; // 0x1f18
    v23 = v106;
    int64_t v107 = v85 + 48; // 0x1f1f
    *(char *)(v106 + v107) = 0;
    int64_t v108 = v14; // 0x1f24
    int64_t v109 = 0; // 0x1f24
    if (v100 || !v102) {
        bool v110 = v100; // 0x1f3e
        bool v111 = v102; // 0x1f3e
        int64_t v112 = 1;
        int128_t v113 = __asm_mulsd(v34, v89); // 0x1f51
        __asm_movapd(v113);
        int128_t v114 = __asm_movapd(v113); // 0x1f5e
        my_modf_isra_0((int64_t)&iconvert);
        int128_t v115 = __asm_movsd(*(int64_t *)&iconvert); // 0x1f68
        int128_t v116 = __asm_subsd(v114, v115); // 0x1f71
        __asm_ucomisd(v115, v88);
        int32_t v117 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd_4(v116, v90), v91)); // 0x1f85
        char v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef"); // 0x1f8c
        int64_t v119; // bp-377, 0x1d40
        *(char *)(v112 + (int64_t)&v119) = v118;
        while (v110 || !v111) {
            int64_t v120 = v112 - 311; // 0x1f44
            v110 = llvm_ctpop_i8((char)v120) % 2 == 0;
            v111 = false;
            if (v120 == 0) {
                goto lab_0x2238;
            }
            v112++;
            v113 = __asm_mulsd(v115, v89);
            __asm_movapd(v113);
            v114 = __asm_movapd(v113);
            my_modf_isra_0((int64_t)&iconvert);
            v115 = __asm_movsd(*(int64_t *)&iconvert);
            v116 = __asm_subsd(v114, v115);
            __asm_ucomisd(v115, v88);
            v117 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd_4(v116, v90), v91));
            v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef");
            *(char *)(v112 + (int64_t)&v119) = v118;
        }
        if ((int32_t)v112 == 311) {
          lab_0x2238:
            // 0x2238
            v108 = v14 + 0xfffffeca;
            v109 = 310;
        } else {
            // 0x1fa5
            v108 = v14 - v112;
            v109 = v112 & 0xffffffff;
        }
    }
    int64_t v121 = (0x100000000 * v109 >> 32) + v85;
    int64_t v122 = v121 + 368; // 0x1fb5
    *(char *)v122 = 0;
    int32_t v123 = -1 - (int32_t)v14 + (int32_t)(float32_t)(float64_t)(int64_t)min - v21 - (int32_t)v101; // 0x1fcd
    int64_t v124 = v123 >= 0 ? (int64_t)v123 : 0; // 0x1fd2
    int64_t v125; // 0x1d40
    int64_t v126; // 0x1d40
    int64_t v127; // 0x1d40
    int64_t v128; // 0x1d40
    int64_t v129; // 0x1d40
    int64_t v130; // 0x1d40
    if (v16 % 2 == 0) {
        if ((v16 & 16) == 0) {
            // 0x2150
            v129 = v83;
            v125 = v124;
            if (v123 >= 1) {
                if (v83 < maxlen) {
                    // 0x2165
                    *(char *)(v83 + v84) = 32;
                }
                int64_t v131 = v83 + 1; // 0x216c
                *currlen = v131;
                uint32_t v132 = (int32_t)v124 - 1; // 0x2173
                int64_t v133 = v132; // 0x2177
                while (v132 != 0) {
                    int64_t v134 = v131;
                    int64_t v135 = v134; // 0x2163
                    if (v134 < maxlen) {
                        // 0x2165
                        *(char *)(v134 + v84) = 32;
                        v135 = v83;
                    }
                    // 0x216c
                    v131 = v135 + 1;
                    *currlen = v131;
                    v132 = (int32_t)v133 - 1;
                    v133 = v132;
                }
                int32_t v136 = v124; // 0x2179
                v129 = v131;
                v125 = v124 - (v136 >= 0 == (v136 != 0) ? v124 : 1) & 0xffffffff;
            }
            goto lab_0x1fe3;
        } else {
            // 0x210e
            v129 = v83;
            v125 = v124;
            if (v123 < 1) {
                goto lab_0x1fe3;
            } else {
                // 0x2117
                v130 = v83;
                v126 = v124;
                if (v22 != 0) {
                    // 0x2221
                    v128 = v83;
                    v127 = v124;
                    if (v83 < maxlen) {
                        // 0x222a
                        *(char *)(v83 + v84) = (char)v22;
                        v128 = v83;
                        v127 = v124;
                    }
                    goto lab_0x2134;
                } else {
                    goto lab_0x2128;
                }
            }
        }
    } else {
        // 0x1fe0
        v129 = v83;
        v125 = -v124 & 0xffffffff;
        goto lab_0x1fe3;
    }
  lab_0x21ab:
    // 0x21ab
    __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) - __frontend_reg_load_fpr(v17));
    fracpart = __asm_movsd_1(v33);
    float64_t v137 = __frontend_reg_load_fpr(v11); // 0x21b3
    v23 = v137;
    int128_t v138 = __asm_movsd((int64_t)v137); // 0x21b6
    int64_t v139 = __asm_movsd_1(v138); // 0x21bc
    v5[0] = v139;
    iconvert = v5;
    v30 = v31;
    v35 = v36;
    v32 = v33;
    v34 = v138;
    goto lab_0x1e78;
  lab_0x1fe3:;
    int64_t v140 = v129; // 0x1fe9
    int64_t v141 = v125; // 0x1fe9
    if (v22 != 0) {
        int64_t v142 = v129; // 0x1fee
        if (v129 < maxlen) {
            // 0x1ff0
            *(char *)(v129 + v84) = (char)v22;
            v142 = v83;
        }
        int64_t v143 = v142 + 1; // 0x1ff6
        *currlen = v143;
        v140 = v143;
        v141 = v125;
    }
    goto lab_0x1ffd;
  lab_0x1ffd:;
    int64_t v144 = v107 + (int64_t)v23 - 1;
    int64_t v145; // 0x1d40
    if (v140 < maxlen) {
        // 0x2015
        *(char *)(v145 + v84) = *(char *)v144;
    }
    int64_t v146 = v140 + 1; // 0x2020
    *currlen = v146;
    int64_t v147 = v146; // 0x202e
    int64_t v148 = v144; // 0x202e
    while (v87 - (v101 + 0xffffffff & 0xffffffff) + (int64_t)v23 != v144) {
        // 0x2010
        v144 = v148 - 1;
        if (v147 < maxlen) {
            // 0x2015
            *(char *)(v145 + v84) = *(char *)v144;
        }
        // 0x2020
        v146 = v147 + 1;
        *currlen = v146;
        v147 = v146;
        v148 = v144;
    }
    if (v13 != 0) {
        int64_t v149 = v146; // 0x2038
        if (v146 < maxlen) {
            // 0x203a
            *(char *)(v146 + v84) = 46;
            v149 = v83;
        }
        int64_t v150 = v149 + 1; // 0x2041
        *currlen = v150;
        int64_t v151 = v150; // 0x204a
        if ((int32_t)v108 >= 1) {
            int64_t v152 = v151;
            int64_t v153 = v152; // 0x2053
            if (v152 < maxlen) {
                // 0x2055
                *(char *)(v152 + v84) = 48;
                v153 = v83;
            }
            int64_t v154 = v153 + 1; // 0x205c
            *currlen = v154;
            uint32_t v155 = (int32_t)(v108 & 0xffffffff) - 1; // 0x2063
            int64_t v156 = v155; // 0x2066
            while (v155 != 0) {
                // 0x2050
                v152 = v154;
                v153 = v152;
                if (v152 < maxlen) {
                    // 0x2055
                    *(char *)(v152 + v84) = 48;
                    v153 = v83;
                }
                // 0x205c
                v154 = v153 + 1;
                *currlen = v154;
                v155 = (int32_t)v156 - 1;
                v156 = v155;
            }
        }
        if (v109 != 0) {
            int64_t v157 = v122 - 1;
            if (v83 < maxlen) {
                // 0x208d
                *(char *)(v83 + v84) = *(char *)v157;
            }
            int64_t v158 = v83 + 1; // 0x2098
            *currlen = v158;
            int64_t v159 = v157; // 0x20a6
            while (367 - (v109 + 0xffffffff & 0xffffffff) + v121 != v157) {
                int64_t v160 = v158;
                v157 = v159 - 1;
                int64_t v161 = v160; // 0x208b
                if (v160 < maxlen) {
                    // 0x208d
                    *(char *)(v160 + v84) = *(char *)v157;
                    v161 = v83;
                }
                // 0x2098
                v158 = v161 + 1;
                *currlen = v158;
                v159 = v157;
            }
        }
    }
    // 0x20a8
    if ((int32_t)v141 == 0) {
        // 0x20c9
        return;
    }
    if (v83 < maxlen) {
        // 0x20b5
        *(char *)(v83 + v84) = 32;
    }
    int64_t v162 = v83 + 1; // 0x20bc
    *currlen = v162;
    uint32_t v163 = (int32_t)v141 + 1; // 0x20c3
    int64_t v164 = v163; // 0x20c7
    while (v163 != 0) {
        int64_t v165 = v162;
        int64_t v166 = v165; // 0x20b3
        if (v165 < maxlen) {
            // 0x20b5
            *(char *)(v165 + v84) = 32;
            v166 = v83;
        }
        // 0x20bc
        v162 = v166 + 1;
        *currlen = v162;
        v163 = (int32_t)v164 + 1;
        v164 = v163;
    }
  lab_0x2128:;
    int64_t v167 = v126;
    int64_t v168 = v130;
    v128 = v168;
    v127 = v167;
    if (v168 < maxlen) {
        // 0x212d
        *(char *)(v168 + v84) = 48;
        v128 = v83;
        v127 = v167;
    }
    goto lab_0x2134;
  lab_0x2134:;
    int64_t v169 = v128 + 1; // 0x2134
    *currlen = v169;
    uint32_t v170 = (int32_t)v127 - 1; // 0x213b
    int64_t v171 = v170; // 0x213b
    v140 = v169;
    v141 = v171;
    v130 = v169;
    v126 = v171;
    if (v170 != 0) {
        goto lab_0x2128;
    } else {
        goto lab_0x1ffd;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x22c0 - 0x2bdd
// Line range:    130 - 290
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args) {
    // 0x22c0
    int64_t v1; // 0x22c0
    uint64_t v2 = v1;
    int64_t v3 = (int64_t)buffer;
    int64_t v4 = (int64_t)format + 1; // 0x22d3
    int64_t v5 = v4; // 0x22d3
    int64_t result2 = 0; // 0x22e9
    int64_t v6; // 0x22c0
    int64_t v7; // 0x22c0
    int64_t v8; // 0x22c0
    int64_t v9; // 0x22c0
    char v10; // 0x22c0
    int64_t v11; // 0x22c0
    int64_t v12; // 0x22c0
    if ((char)v2 != 0) {
        int64_t v13 = (int64_t)args;
        int64_t * v14 = (int64_t *)(v13 + 8);
        v6 = v4;
        v7 = v2 % 256;
        v12 = 0;
        while (true) {
          lab_0x233e:;
            char v15 = v7; // 0x2345
            int64_t v16 = v6; // 0x2348
            char v17 = v15; // 0x2348
            int64_t v18 = v12; // 0x2348
            int64_t v19 = v6; // 0x2348
            int64_t v20 = v12; // 0x2348
            if (v15 != 37) {
                while (true) {
                  lab_0x234a:;
                    uint64_t v21 = v18;
                    int64_t v22 = v16; // 0x234d
                    if (v21 < maxlen) {
                        // 0x234f
                        *(char *)(v21 + v3) = v17;
                        v22 = v5;
                    }
                    char v23 = *(char *)v22; // 0x2353
                    int64_t v24 = v22 + 1; // 0x2356
                    v5 = v24;
                    int64_t v25 = v21 + 1; // 0x235a
                    result2 = v25;
                    v16 = v24;
                    v17 = v23;
                    v18 = v25;
                    v19 = v24;
                    v20 = v25;
                    switch (v23) {
                        case 0: {
                            goto lab_0x22f0_3;
                        }
                        case 37: {
                            goto lab_0x2369;
                        }
                        default: {
                            goto lab_0x234a;
                        }
                    }
                }
            }
          lab_0x2369:
            // 0x2369
            v11 = v20;
            unsigned char v26 = *(char *)v19; // 0x2373
            result2 = v11;
            if (v26 == 0) {
                // break -> 0x22f0
                break;
            }
            int64_t v27 = v26; // 0x2373
            int64_t result = v27; // 0x238b
            if (v26 < 49) {
                // 0x2303
                return result;
            }
            int64_t v28 = v19 + 1; // 0x237e
            int64_t v29 = (int64_t)g14; // 0x239a
            v5 = 0;
            int64_t v30 = v27; // 0x23aa
            int64_t v31 = v28; // 0x23aa
            int32_t v32 = 0; // 0x23aa
            int64_t v33 = v27; // 0x23aa
            int64_t v34 = v28; // 0x23aa
            if ((*(char *)(2 * v27 + v29) & 4) != 0) {
                int64_t v35 = 0xffffffd0 + (0x100000000000000 * v30 >> 56); // 0x23b6
                int64_t v36 = v35 & 0xffffffff; // 0x23b6
                v5 = v36;
                unsigned char v37 = *(char *)v31; // 0x23ba
                result2 = v11;
                if (v37 == 0) {
                    // break (via goto) -> 0x22f0
                    goto lab_0x22f0_3;
                }
                int64_t v38 = v31 + 1; // 0x23b2
                int64_t v39 = v37; // 0x23ba
                v31 = v38;
                while ((*(char *)(2 * v39 + v29) & 4) != 0) {
                    // 0x23ac
                    v35 = 10 * v36 + 0xffffffd0 + (0x100000000000000 * v39 >> 56);
                    v36 = v35 & 0xffffffff;
                    v5 = v36;
                    v37 = *(char *)v31;
                    result2 = v11;
                    if (v37 == 0) {
                        // break (via goto) -> 0x22f0
                        goto lab_0x22f0_3;
                    }
                    // 0x23c6
                    v38 = v31 + 1;
                    v39 = v37;
                    v31 = v38;
                }
                // 0x23d2
                v32 = v35;
                v33 = v39;
                v34 = v38;
            }
            int64_t v40 = v34;
            int64_t v41 = v33; // 0x23d4
            int64_t v42 = v40; // 0x23d4
            if (v33 == 42) {
                uint32_t v43 = v32; // 0x2908
                if (v43 < 48) {
                    // 0x290f
                    v5 = *(int64_t *)(v13 + 16) + (int64_t)v43;
                    *args = v43 + 8;
                } else {
                    int64_t v44 = *v14; // 0x2963
                    v5 = v44;
                    *v14 = v44 + 8;
                }
                unsigned char v45 = *(char *)v40; // 0x291a
                result2 = v11;
                if (v45 == 0) {
                    // break -> 0x22f0
                    break;
                }
                // 0x292c
                v41 = v45;
                v42 = v40 + 1;
            }
            int64_t v46 = v42;
            int64_t v47 = v41; // 0x23e2
            int64_t v48 = v46; // 0x23e2
            if ((char)v41 == 46) {
                char v49 = *(char *)v46; // 0x2498
                result2 = v11;
                if (v49 == 0) {
                    // break -> 0x22f0
                    break;
                }
                int64_t v50 = v46;
                unsigned char v51 = v49;
                int64_t v52 = v50 + 1;
                int64_t v53 = v51;
                while ((*(char *)(2 * v53 + v29) & 4) != 0) {
                    char v54 = *(char *)v52; // 0x24cc
                    result2 = v11;
                    if (v54 == 0) {
                        // break (via goto) -> 0x22f0
                        goto lab_0x22f0_3;
                    }
                    v50 = v52;
                    v51 = v54;
                    v52 = v50 + 1;
                    v53 = v51;
                }
                // 0x2850
                v47 = v53;
                v48 = v52;
                if (v51 == 42) {
                    uint32_t v55 = *(int32_t *)&v5; // 0x2858
                    if (v55 < 48) {
                        // 0x2863
                        *args = v55 + 8;
                    } else {
                        // 0x2934
                        *v14 = *v14 + 8;
                    }
                    unsigned char v56 = *(char *)v52; // 0x286e
                    result2 = v11;
                    if (v56 == 0) {
                        // break -> 0x22f0
                        break;
                    }
                    // 0x2881
                    v47 = v56;
                    v48 = v50 + 2;
                }
            }
            int64_t v57 = v48;
            int64_t v58 = v47;
            switch ((char)v58) {
                case 104: {
                    char v59 = *(char *)v57; // 0x28ee
                    v10 = v59;
                    v9 = v57 + 1;
                    if (v59 == 0) {
                        // break -> 0x22f0
                        break;
                    }
                    goto lab_0x28a6;
                }
                case 108: {
                    char v60 = *(char *)v57; // 0x2889
                    int64_t v61 = v57 + 1;
                    result2 = v11;
                    v10 = v60;
                    v9 = v61;
                    switch (v60) {
                        case 108: {
                            char v62 = *(char *)v61; // 0x2945
                            v10 = v62;
                            v9 = v57 + 2;
                            if (v62 == 0) {
                                // break -> 0x22f0
                                break;
                            }
                            goto lab_0x28a6;
                        }
                        case 0: {
                            goto lab_0x22f0_3;
                        }
                        default: {
                            goto lab_0x28a6;
                        }
                    }
                }
                case 76: {
                    unsigned char v63 = *(char *)v57; // 0x28bf
                    if (v63 == 0) {
                        // break -> 0x22f0
                        break;
                    }
                    int64_t v64 = (int64_t)v63 + 0xffffffdb; // 0x28cb
                    v8 = v57 + 1;
                    if ((char)v64 < 84) {
                        int32_t v65 = *(int32_t *)((4 * v64 & 1020) + (int64_t)&g11); // 0x28e4
                        return (int64_t)v65 + (int64_t)&g11;
                    }
                    goto lab_0x2533;
                }
                default: {
                    // 0x2400
                    v8 = v57;
                    if ((char)(v58 + 0xffffffdb) < 84) {
                        // 0x240b
                        int64_t v66; // 0x2400
                        int32_t v67 = *(int32_t *)((4 * v66 & 1020) + (int64_t)&g9); // 0x2415
                        return (int64_t)v67 + (int64_t)&g9;
                    }
                    goto lab_0x2533;
                }
            }
        }
    }
  lab_0x22f0_3:
    // 0x22f0
    if (maxlen == 0) {
        // 0x2303
        return result2;
    }
    uint64_t v68 = maxlen - 1;
    if (v68 > result2) {
        // 0x22fe
        *(char *)(result2 + v3) = 0;
        // 0x2303
        return result2;
    }
    // 0x2318
    *(char *)(v68 + v3) = 0;
    return result2;
  lab_0x2533:;
    unsigned char v69 = *(char *)v8; // 0x2533
    int64_t v70 = v8 + 1; // 0x2537
    v5 = v70;
    result2 = v11;
    v6 = v70;
    v7 = v69;
    v12 = v11;
    if (v69 == 0) {
        // break -> 0x22f0
        goto lab_0x22f0_3;
    }
    goto lab_0x233e;
  lab_0x28a6:;
    int64_t v71 = (int64_t)v10 + 0xffffffdb; // 0x28a6
    v8 = v9;
    if ((char)v71 < 84) {
        int32_t v72 = *(int32_t *)((4 * v71 & 1020) + (int64_t)&g10); // 0x28b4
        return (int64_t)v72 + (int64_t)&g10;
    }
    goto lab_0x2533;
}

// Address range: 0x2bdd - 0x2be8
int64_t function_2bdd(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2bdd
    int64_t v1; // 0x2bdd
    return v1 & 0xffffffff;
}

// Address range: 0x2be8 - 0x2bf3
int64_t function_2be8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2be8
    int64_t v1; // 0x2be8
    return v1 & 0xffffffff;
}

// Address range: 0x2bf3 - 0x2bfe
int64_t function_2bf3(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2bf3
    int64_t v1; // 0x2bf3
    return v1 & 0xffffffff;
}

// Address range: 0x2bfe - 0x2c05
int64_t function_2bfe(void) {
    // 0x2bfe
    int64_t v1; // 0x2bfe
    return v1 & 0xffffffff;
}

// Address range: 0x2c05 - 0x2c10
int64_t function_2c05(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2c05
    int64_t v1; // 0x2c05
    return v1 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2c10 - 0x2d1c
// Line range:    751 - 769
int32_t libmin_printf(char * fmt, ...) {
    // 0x2c10
    int64_t v1; // 0x2c10
    if ((char)v1 != 0) {
        // 0x2c4c
        int128_t v2; // 0x2c10
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 8; // bp-1248, 0x2cb6
    char v4; // bp-1224, 0x2c10
    dopr(&v4, (int64_t)&g4, fmt, (int32_t *)&v3);
    if (v4 == 0) {
        // 0x2d10
        return 0;
    }
    int64_t v5 = &v4;
    libtarg_putc(v4);
    int64_t v6 = v5 + 1; // 0x2cf9
    char v7 = *(char *)v6; // 0x2cf9
    while (v7 != 0) {
        // 0x2cf0
        v5 = v6;
        libtarg_putc(v7);
        v6 = v5 + 1;
        v7 = *(char *)v6;
    }
    // 0x2d06
    int64_t v8; // bp+1225, 0x2c10
    return v5 + (int64_t)&v8;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2d20 - 0x2dcb
// Line range:    772 - 782
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...) {
    // 0x2d20
    int64_t v1; // 0x2d20
    if ((char)v1 != 0) {
        // 0x2d46
        int128_t v2; // 0x2d20
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 24; // bp-224, 0x2d9a
    dopr(s, size, fmt, (int32_t *)&v3);
    *(char *)((int64_t)s - 1 + size) = 0;
    return libmin_strlen(s);
}

// Address range: 0x2dd0 - 0x2e23
int64_t libmin_srand(void) {
    // 0x2dd0
    mt_initialized = 1;
    int64_t v1 = (int64_t)&mt;
    int64_t v2 = v1 + 4; // 0x2df9
    int64_t v3; // 0x2dd0
    int64_t v4 = 0x10dcd * v3 + 1; // 0x2dfd
    int64_t v5 = 0x10dcd * v4; // 0x2e02
    *(int32_t *)v1 = (int32_t)v4 / 0x10000 | (int32_t)v3 & -0x10000;
    v3 = v5 + 1 & 0xffffffff;
    while (v2 != (int64_t)&g20) {
        // 0x2df0
        v1 = v2;
        v2 = v1 + 4;
        v4 = 0x10dcd * v3 + 1;
        v5 = 0x10dcd * v4;
        *(int32_t *)v1 = (int32_t)v4 / 0x10000 | (int32_t)v3 & -0x10000;
        v3 = v5 + 1 & 0xffffffff;
    }
    // 0x2e18
    mti = 624;
    return v5 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_rand.c
// Address range: 0x2e30 - 0x2fd5
// Line range:    42 - 30
int32_t libmin_rand(void) {
    // 0x2e30
    if (mt_initialized == 0) {
        // 0x2f68
        libmin_printf("ERROR: rng is not initialized, call mysrand()!\n");
        libmin_fail(1);
        // UNREACHABLE
    }
    int32_t v1 = mti; // 0x2e46
    int32_t v2; // 0x2e30
    int32_t v3; // 0x2e30
    if (v1 > 623) {
        if (v1 == 625) {
            // 0x2f85
            mt_initialized = 1;
            int64_t v4 = 0x1105; // 0x2fa2
            int64_t v5 = (int64_t)&mt;
            int64_t v6 = v5 + 4; // 0x2fb1
            int64_t v7 = 0x10dcd * v4 + 1; // 0x2fb5
            *(int32_t *)v5 = (int32_t)v7 / 0x10000 | (int32_t)v4 & -0x10000;
            v4 = 0x10dcd * v7 + 1 & 0xffffffff;
            while (v6 != (int64_t)&g20) {
                // 0x2fa8
                v5 = v6;
                v6 = v5 + 4;
                v7 = 0x10dcd * v4 + 1;
                *(int32_t *)v5 = (int32_t)v7 / 0x10000 | (int32_t)v4 & -0x10000;
                v4 = 0x10dcd * v7 + 1 & 0xffffffff;
            }
        }
        int64_t v8 = (int64_t)&mt;
        int32_t * v9 = (int32_t *)v8; // 0x2ec0
        int64_t v10 = v8 + 4; // 0x2ec2
        int32_t v11 = *(int32_t *)v10; // 0x2ec2
        int32_t v12 = *(int32_t *)(v8 + 1588); // 0x2edd
        int32_t v13 = *(int32_t *)((int64_t)(4 * v11 & 4) | (int64_t)&g12); // 0x2ee3
        *v9 = v13 ^ v12 ^ (v11 & 0x7ffffffe | *v9 & -0x80000000) / 2;
        int64_t v14 = (int64_t)&mt; // 0x2eec
        while (v10 != (int64_t)&g17) {
            // 0x2ec0
            v8 = v10;
            v9 = (int32_t *)v8;
            v10 = v8 + 4;
            v11 = *(int32_t *)v10;
            v12 = *(int32_t *)(v8 + 1588);
            v13 = *(int32_t *)((int64_t)(4 * v11 & 4) | (int64_t)&g12);
            *v9 = v13 ^ v12 ^ (v11 & 0x7ffffffe | *v9 & -0x80000000) / 2;
            v14 = (int64_t)&mt;
        }
        int32_t v15 = *(int32_t *)(v14 + (int64_t)&g1); // 0x2ef8
        int32_t v16 = *(int32_t *)(v14 + (int64_t)&g2); // 0x2efe
        int64_t v17 = v14 + 4; // 0x2f04
        int32_t v18 = *(int32_t *)v14; // 0x2f1c
        int32_t v19 = *(int32_t *)((int64_t)(4 * v16 & 4) | (int64_t)&g12); // 0x2f1f
        *(int32_t *)(v14 + 908) = v19 ^ v18 ^ (v16 & 0x7ffffffe | v15 & -0x80000000) / 2;
        v14 = v17;
        while (v17 != (int64_t)&g18) {
            // 0x2ef8
            v15 = *(int32_t *)(v14 + (int64_t)&g1);
            v16 = *(int32_t *)(v14 + (int64_t)&g2);
            v17 = v14 + 4;
            v18 = *(int32_t *)v14;
            v19 = *(int32_t *)((int64_t)(4 * v16 & 4) | (int64_t)&g12);
            *(int32_t *)(v14 + 908) = v19 ^ v18 ^ (v16 & 0x7ffffffe | v15 & -0x80000000) / 2;
            v14 = v17;
        }
        int32_t v20 = mt[0]; // 0x2f2d
        int32_t v21 = *(int32_t *)((int64_t)(4 * v20 & 4) | (int64_t)&g12); // 0x2f55
        g19 = v21 ^ g18 ^ (g19 & -0x80000000 | v20 & 0x7ffffffe) / 2;
        v2 = v20;
        v3 = 1;
    } else {
        // 0x2e54
        v2 = *(int32_t *)(4 * (int64_t)v1 + (int64_t)&mt);
        v3 = v1 + 1;
    }
    uint32_t v22 = v2;
    mti = v3;
    int32_t v23 = v22 / 2048 ^ v22; // 0x2e70
    int32_t v24 = 128 * v23 & -0x62d3a980 ^ v23; // 0x2e7c
    uint32_t v25 = 0x8000 * v24 & -0x103a0000 ^ v24; // 0x2e89
    return v25 / 0x40000 ^ v25 % 0x80000000;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_strlen.c
// Address range: 0x2fe0 - 0x300b
// Line range:    5 - 15
int64_t libmin_strlen(char * str) {
    int64_t v1 = (int64_t)str;
    if (str == NULL || (char)v1 == 0) {
        // 0x3008
        return 0;
    }
    int64_t v2 = v1; // 0x2fe7
    v2++;
    while (*(char *)v2 != 0) {
        // 0x2ff8
        v2++;
    }
    // 0x3001
    return v2 - v1;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_success.c
// Address range: 0x3010 - 0x3019
// Line range:    5 - 7
void libmin_success(void) {
    // 0x3010
    libtarg_success();
}

// Address range: 0x301c - 0x3029
int64_t _fini(void) {
    // 0x301c
    int64_t result; // 0x301c
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 39

