//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;
typedef int64_t int128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int32_t _isctype(uint32_t c, int32_t mask);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t badCharHeuristic(int64_t a1, int64_t a2, int64_t a3);
int64_t deregister_tm_clones(void);
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args);
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags);
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags);
int64_t frame_dummy(void);
void function_1090(int64_t * d);
void function_10a0(void);
int64_t * function_10b0(int64_t * s, int32_t c, int32_t n);
int32_t function_10c0(int32_t c, struct _IO_FILE * stream);
int64_t * function_10d0(int64_t delta);
int64_t * function_10e0(int64_t * dest, int64_t * src, int32_t n);
void function_10f0(int32_t status);
int64_t function_292d(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2938(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2943(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_294e(void);
int64_t function_2955(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int32_t libmin_printf(char * fmt, ...);
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...);
int64_t libmin_strlen(char * str);
void libmin_success(void);
void libtarg_fail(int32_t code);
void libtarg_putc(char c);
char * libtarg_sbrk(int64_t inc);
void libtarg_success(void);
int64_t my_modf_isra_0(int64_t a1);
int64_t register_tm_clones(void);
void search(char * txt, uint32_t n, char * pat, uint32_t m, int32_t * ret);

// --------------------- Global Variables ---------------------

int64_t g1 = -0xe1c00000c79; // 0x30a0
int64_t g2 = -0xf6c00000dc9; // 0x31f0
int64_t g3 = -0x10bc00000f19; // 0x3340
int64_t g4 = 0; // 0x3f8
int32_t g5 = 0; // 0x400
int64_t g6 = 0x20002000200020; // 0x5342
struct _IO_FILE * g8 = NULL; // 0x5550
char g9 = 0; // 0x5558
int32_t g10;
int64_t * g7 = &g6; // 0x5548

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g10;
    }
    // 0x1016
    return result;
}

// Address range: 0x1090 - 0x109b
void function_1090(int64_t * d) {
    // 0x1090
    __cxa_finalize(d);
}

// Address range: 0x10a0 - 0x10ab
void function_10a0(void) {
    // 0x10a0
    __stack_chk_fail();
}

// Address range: 0x10b0 - 0x10bb
int64_t * function_10b0(int64_t * s, int32_t c, int32_t n) {
    // 0x10b0
    return memset(s, c, n);
}

// Address range: 0x10c0 - 0x10cb
int32_t function_10c0(int32_t c, struct _IO_FILE * stream) {
    // 0x10c0
    return fputc(c, stream);
}

// Address range: 0x10d0 - 0x10db
int64_t * function_10d0(int64_t delta) {
    // 0x10d0
    return sbrk(delta);
}

// Address range: 0x10e0 - 0x10eb
int64_t * function_10e0(int64_t * dest, int64_t * src, int32_t n) {
    // 0x10e0
    return memcpy(dest, src, n);
}

// Address range: 0x10f0 - 0x10fb
void function_10f0(int32_t status) {
    // 0x10f0
    exit(status);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/boyer-moore-search/boyer-moore-search.c
// Address range: 0x1100 - 0x149a
// Line range:    108 - 123
int main() {
    // 0x1100
    int64_t v1; // bp-104, 0x1100
    int64_t v2 = &v1; // 0x1122
    __readfsqword(40);
    int64_t v3 = libmin_strlen("zJfMus2WzLnMr82T4bmuzKTNjcylzYfNiGjMssyBZc2PzZPMvMyXzJnMvMyjzZQgzYfMnMyxzKDNk82NzZVOzZXNoGXMl8yxesyYzJ3MnMy6zZlwzKTMusy5zY3Mr82aZcygzLvMoM2ccsyozKTNjcy6zJbNlMyWzJZkzKDMn8ytzKzMnc2facymzZbMqc2TzZTMpGHMoMyXzKzNicyZbs2azZwgzLvMnsywzZrNhWjMtc2JacyzzJ52zKLNh+G4mc2OzZ8t0onMrcypzLzNlG3MpMytzKtpzZXNh8ydzKZuzJfNmeG4jcyfIMyvzLLNlc2ex6vMn8yvzLDMss2ZzLvMnWYgzKrMsMywzJfMlsytzJjNmGPMps2NzLLMns2NzKnMmeG4pc2aYcyuzY7Mn8yZzZzGocypzLnNjnPMpC7MncydINKJWsyhzJbMnM2WzLDMo82JzJxhzqwerty42ZbMsM2ZzKzNoWzMssyrzLPNjcypZ8yhzJ/MvMyxzZrMnsyszYVvzJfNnC7Mnw==zKZIzKzMpMyXzKTNnWXNnCDMnMylzJ3Mu82NzJ/MgXfMlWjMlsyvzZNvzJ3NmcyWzY7MscyuINKJzLrMmcyezJ/NiFfMt8y8zK1hzLrMqs2NxK/NiM2VzK3NmcyvzJx0zLbMvMyuc8yYzZnNlsyVIMygnMyWIMywzYnMqc2HzZnMss2ezYVUzZbMvM2TzKrNomjNj82TzK7Mu2XMrMydzJ/NhSDMpMy5zJ1X"); // 0x1135
    int64_t v4 = libmin_strlen("NzZVOzZXNoGXMl8yxesyY"); // 0x1144
    libmin_printf("n = %d, m = %d\n", v3 & 0xffffffff, v4 & 0xffffffff);
    int64_t v5 = 0x100000000 * v3;
    int64_t v6 = (v5 >> 32) + 15; // 0x1173
    int64_t v7 = v6 & -0x1000; // 0x117a
    int64_t v8 = v2; // 0x118a
    int64_t v9 = v2; // 0x118a
    if (v7 != 0) {
        v8 -= 0x1000;
        v9 = v8;
        while (v8 != v2 - v7) {
            // 0x118c
            v8 -= 0x1000;
            v9 = v8;
        }
    }
    int64_t v10 = v9 - (v6 & 4080); // 0x11a7
    char * v11 = (char *)v10; // 0x11b3
    int32_t v12 = v3; // 0x11b7
    if (v12 < 1) {
        int64_t v13 = (0x100000000 * v4 >> 32) + 15; // 0x1271
        int64_t v14 = v10 - (v13 & -0x1000) - (v13 & 4080); // 0x12a2
        uint32_t v15 = (int32_t)v4; // 0x12b3
        if (v15 >= 1) {
            // 0x12bc
            memcpy((int64_t *)v14, (int64_t *)"NzZVOzZXNoGXMl8yxesyY", v15);
        }
        // 0x13c6
        search(v11, v12, (char *)v14, v15, (int32_t *)(v14 - ((v5 >> 30) + 15 & -16)));
        // 0x1389
        libmin_success();
        // UNREACHABLE
    }
    int64_t v16 = v3 + 0xffffffff; // 0x11bf
    int32_t v17 = v16;
    memcpy((int64_t *)v10, (int64_t *)"zJfMus2WzLnMr82T4bmuzKTNjcylzYfNiGjMssyBZc2PzZPMvMyXzJnMvMyjzZQgzYfMnMyxzKDNk82NzZVOzZXNoGXMl8yxesyYzJ3MnMy6zZlwzKTMusy5zY3Mr82aZcygzLvMoM2ccsyozKTNjcy6zJbNlMyWzJZkzKDMn8ytzKzMnc2facymzZbMqc2TzZTMpGHMoMyXzKzNicyZbs2azZwgzLvMnsywzZrNhWjMtc2JacyzzJ52zKLNh+G4mc2OzZ8t0onMrcypzLzNlG3MpMytzKtpzZXNh8ydzKZuzJfNmeG4jcyfIMyvzLLNlc2ex6vMn8yvzLDMss2ZzLvMnWYgzKrMsMywzJfMlsytzJjNmGPMps2NzLLMns2NzKnMmeG4pc2aYcyuzY7Mn8yZzZzGocypzLnNjnPMpC7MncydINKJWsyhzJbMnM2WzLDMo82JzJxhzqwerty42ZbMsM2ZzKzNoWzMssyrzLPNjcypZ8yhzJ/MvMyxzZrMnsyszYVvzJfNnC7Mnw==zKZIzKzMpMyXzKTNnWXNnCDMnMylzJ3Mu82NzJ/MgXfMlWjMlsyvzZNvzJ3NmcyWzY7MscyuINKJzLrMmcyezJ/NiFfMt8y8zK1hzLrMqs2NxK/NiM2VzK3NmcyvzJx0zLbMvMyuc8yYzZnNlsyVIMygnMyWIMywzYnMqc2HzZnMss2ezYVUzZbMvM2TzKrNomjNj82TzK7Mu2XMrMydzJ/NhSDMpMy5zJ1X", v17 + 1);
    int64_t v18 = (0x100000000 * v4 >> 32) + 15; // 0x11dd
    int64_t v19 = v10 - (v18 & -0x1000) - (v18 & 4080); // 0x120e
    int32_t v20 = v4; // 0x1219
    if (v20 >= 0 == (v20 != 0)) {
        // 0x1425
        memcpy((int64_t *)v19, (int64_t *)"NzZVOzZXNoGXMl8yxesyY", v20);
    }
    int64_t v21 = v16 & 0xffffffff; // 0x11da
    int64_t v22 = v19 - ((v5 >> 30) + 15 & -16);
    memset((int64_t *)v22, 0, 4 * v17 + 4);
    search(v11, v12, (char *)v19, v20, (int32_t *)v22);
    int64_t v23 = 0; // 0x135c
    while (true) {
        int64_t v24 = v23;
        if (*(int32_t *)(4 * v24 + v22) == 0) {
            if (v21 == v24) {
                // break -> 0x1389
                break;
            }
        } else {
            // 0x1376
            libmin_printf("pattern occurs at shift = %d\n", v24 & 0xffffffff);
            if (v21 == v24) {
                // break -> 0x1389
                break;
            }
        }
        // 0x1369
        v23 = v24 + 1;
    }
    // 0x1389
    libmin_success();
    // UNREACHABLE
}

// Address range: 0x14a0 - 0x14c6
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x14a0
    int64_t v1; // 0x14a0
    __libc_start_main(0x1100, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x14d0 - 0x14f9
int64_t deregister_tm_clones(void) {
    // 0x14d0
    return (int64_t)&g8;
}

// Address range: 0x1500 - 0x1539
int64_t register_tm_clones(void) {
    // 0x1500
    return 0;
}

// Address range: 0x1540 - 0x1579
int64_t __do_global_dtors_aux(void) {
    // 0x1540
    if (g9 != 0) {
        // 0x1578
        int64_t result; // 0x1540
        return result;
    }
    // 0x154d
    if (*(int64_t *)0x4ff8 != 0) {
        // 0x155b
        __cxa_finalize((int64_t *)*(int64_t *)0x5008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1567
    g9 = 1;
    return result2;
}

// Address range: 0x1580 - 0x1589
int64_t frame_dummy(void) {
    // 0x1580
    return register_tm_clones();
}

// Address range: 0x1590 - 0x15ea
int64_t badCharHeuristic(int64_t a1, int64_t a2, int64_t a3) {
    int64_t v1 = a3 + 8 & -8; // 0x15a5
    *(int64_t *)a3 = -1;
    *(int64_t *)(a3 + (int64_t)&g4) = -1;
    __asm_rep_stosq_memset((char *)v1, -1, (a3 + (int64_t)(int32_t)&g5 - v1) / 8 % 0x20000000);
    if ((int32_t)a2 < 1) {
        // 0x15e9
        return -1;
    }
    int64_t result = 0; // 0x15d3
    char v2 = *(char *)(result + a1); // 0x15d8
    *(int32_t *)(4 * (int64_t)v2 + a3) = (int32_t)result;
    result++;
    while (0x100000000 * a2 >> 32 != result) {
        // 0x15d8
        v2 = *(char *)(result + a1);
        *(int32_t *)(4 * (int64_t)v2 + a3) = (int32_t)result;
        result++;
    }
    // 0x15e9
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/boyer-moore-search/boyer-moore-search.c
// Address range: 0x15f0 - 0x1720
// Line range:    62 - 104
void search(char * txt, uint32_t n, char * pat, uint32_t m, int32_t * ret) {
    int64_t v1 = (int64_t)pat;
    int64_t v2; // bp-1080, 0x15f0
    int64_t v3 = &v2; // 0x160c
    int64_t v4 = __readfsqword(40); // 0x1613
    __asm_rep_stosq_memset((char *)&v2, -1, 128);
    int64_t v5 = 0; // 0x163d
    if (m >= 1) {
        char v6 = *(char *)(v5 + v1); // 0x1640
        *(int32_t *)(4 * (int64_t)v6 + v3) = (int32_t)v5;
        v5++;
        while (v5 != (int64_t)m) {
            // 0x1640
            v6 = *(char *)(v5 + v1);
            *(int32_t *)(4 * (int64_t)v6 + v3) = (int32_t)v5;
            v5++;
        }
    }
    uint32_t v7 = n - m; // 0x1654
    if (v7 >= 0) {
        int64_t v8 = (int64_t)txt;
        int32_t v9 = m - 1;
        int64_t v10 = 0;
        int64_t v11 = 0x100000000 * v10;
        int64_t v12; // 0x15f0
        int64_t v13; // 0x15f0
        int64_t v14; // 0x15f0
        int64_t v15; // 0x16e0
        char v16; // 0x1704
        char v17; // 0x1688
        int64_t v18; // 0x1680
        int32_t v19; // 0x1694
        if (v9 < 0) {
            // 0x16e0
            v15 = v10 + (int64_t)m;
            *(int32_t *)((v11 >> 30) + (int64_t)ret) = 1;
            v13 = 1;
            if ((v15 & 0xffffffff) < (int64_t)n) {
                // 0x1700
                v16 = *(char *)((0x100000000 * v15 >> 32) + v8);
                v13 = (int64_t)(m - *(int32_t *)(4 * (int64_t)v16 + v3));
            }
            // 0x16f6
            v14 = v13 + v10 & 0xffffffff;
        } else {
            // 0x1670
            v12 = v9;
            v17 = *(char *)((v11 >> 32) + v8 + v12);
            while (*(char *)(v12 + v1) == v17) {
                // 0x1680
                v18 = v12 - 1;
                if ((int32_t)v18 < 0) {
                    goto lab_0x16e0;
                }
                v12 = v18;
                v17 = *(char *)((v11 >> 32) + v8 + v12);
            }
            // 0x1694
            v19 = (int32_t)v12 - *(int32_t *)(4 * (int64_t)v17 + v3);
            v14 = (v19 > 1 ? v19 : 1) + (int32_t)v10;
        }
        int64_t v20 = v14;
        int64_t v21 = 1; // 0x16a4
        int32_t v22 = v20; // 0x16a7
        int32_t v23 = v22 - (int32_t)v21; // 0x16a7
        int64_t v24 = v23 < 0 == ((v23 ^ v22) & (int32_t)(v20 ^ v21)) < 0 ? v20 : v21;
        int64_t v25 = v21 & 0xffffffff; // 0x16b3
        while ((v24 & 0xffffffff) <= (int64_t)v7) {
            // 0x1668
            v10 = v20;
            v11 = 0x100000000 * v10;
            if (v9 < 0) {
                // 0x16e0
                v15 = v10 + (int64_t)m;
                *(int32_t *)((v11 >> 30) + (int64_t)ret) = 1;
                v13 = 1;
                if ((v15 & 0xffffffff) < (int64_t)n) {
                    // 0x1700
                    v16 = *(char *)((0x100000000 * v15 >> 32) + v8);
                    v13 = (int64_t)(m - *(int32_t *)(4 * (int64_t)v16 + v3));
                }
                // 0x16f6
                v14 = v13 + v10 & 0xffffffff;
            } else {
                // 0x1670
                v12 = v9;
                v17 = *(char *)((v11 >> 32) + v8 + v12);
                while (*(char *)(v12 + v1) == v17) {
                    // 0x1680
                    v18 = v12 - 1;
                    if ((int32_t)v18 < 0) {
                        goto lab_0x16e0;
                    }
                    v12 = v18;
                    v17 = *(char *)((v11 >> 32) + v8 + v12);
                }
                // 0x1694
                v19 = (int32_t)v12 - *(int32_t *)(4 * (int64_t)v17 + v3);
                v14 = (v19 > 1 ? v19 : 1) + (int32_t)v10;
            }
            // 0x16a4
            v20 = v14;
            v21 = v25 + 1;
            v22 = v20;
            v23 = v22 - (int32_t)v21;
            v24 = v23 < 0 == ((v23 ^ v22) & (int32_t)(v20 ^ v21)) < 0 ? v20 : v21;
            v25 = v21 & 0xffffffff;
        }
    }
    // 0x16b5
    if (v4 == __readfsqword(40)) {
        // 0x16c8
        return;
    }
    // 0x1710
    __stack_chk_fail();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1720 - 0x1731
// Line range:    124 - 127
void libtarg_success(void) {
    // 0x1720
    exit(0);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1740 - 0x174f
// Line range:    162 - 165
void libtarg_fail(int32_t code) {
    // 0x1740
    exit(code);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1750 - 0x1764
// Line range:    188 - 191
void libtarg_putc(char c) {
    // 0x1750
    fputc((int32_t)c, g8);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1770 - 0x1779
// Line range:    230 - 236
char * libtarg_sbrk(int64_t inc) {
    // 0x1770
    return (char *)sbrk(inc);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1780 - 0x19c8
// Line range:    426 - 483
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags) {
    int64_t v1 = flags; // 0x178f
    int64_t v2 = value; // 0x17af
    int64_t v3 = 0; // 0x17af
    int32_t v4 = 0; // 0x17af
    if ((flags & 64) == 0) {
        if (value < 0) {
            // 0x1990
            v2 = -value;
            v3 = 45;
            v4 = -1;
        } else {
            // 0x17ba
            v2 = value;
            v3 = 43;
            v4 = -1;
            if ((v1 & 2) == 0) {
                uint32_t v5 = 8 * flags & 32; // 0x19b3
                v2 = value;
                v3 = v5;
                v4 = v5 != 0;
            }
        }
    }
    int64_t v6 = (int64_t)currlen;
    int64_t v7 = (int64_t)buffer;
    uint32_t v8 = max > 0 ? max : 0; // 0x17a7
    uint64_t v9 = (int64_t)base; // 0x17e2
    int64_t v10; // bp-89, 0x1780
    int64_t v11 = &v10; // 0x17e5
    int64_t v12 = (v1 & 32) == 0 ? (int64_t)"0123456789abcdef" : (int64_t)"0123456789ABCDEF"; // 0x17fd
    uint64_t v13 = v2; // 0x1801
    int64_t v14 = 1;
    *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
    int32_t v15 = v14;
    int32_t v16 = v15 - 19; // 0x1828
    int64_t v17 = v14 + 1; // 0x1834
    while (v13 >= v9 == (v16 == 0 || v16 < 0 != (18 - v15 & v15) < 0)) {
        // 0x1808
        v13 /= v9;
        v14 = v17;
        *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
        v15 = v14;
        v16 = v15 - 19;
        v17 = v14 + 1;
    }
    int64_t v18 = v15 == 20 ? 19 : v14 & 0xffffffff; // 0x1846
    int32_t v19 = v18; // 0x184a
    int32_t v20 = v8 - v19; // 0x184a
    int64_t v21 = 0x100000000 * v18 >> 32; // 0x1850
    int64_t v22; // bp-48, 0x1780
    int64_t v23 = (int64_t)&v22 - 40 + v21; // 0x1857
    *(char *)v23 = 0;
    uint32_t v24 = min - (int32_t)(v20 < 0 == (v20 & v19) < 0 ? (int64_t)v8 : v18) + v4; // 0x1863
    uint32_t v25 = v20 > 0 ? v20 : 0; // 0x1869
    int64_t v26 = v25; // 0x1869
    int64_t v27 = v24 >= 0 ? (int64_t)v24 : 0; // 0x1875
    int64_t v28; // 0x1780
    int64_t v29; // 0x1780
    int64_t v30; // 0x1780
    if ((v1 & 16) == 0) {
        if (flags % 2 != 0) {
            // 0x1970
            v29 = v6;
            v30 = -v27 & 0xffffffff;
            v28 = v26;
        } else {
            // 0x1934
            v29 = v6;
            v30 = v27;
            v28 = v26;
            if (v24 >= 1) {
                if (v6 < maxlen) {
                    // 0x1945
                    *(char *)(v6 + v7) = 32;
                }
                int64_t v31 = v6 + 1; // 0x194c
                *currlen = v31;
                uint32_t v32 = (int32_t)v27 - 1; // 0x1953
                int64_t v33 = v32; // 0x1956
                while (v32 != 0) {
                    int64_t v34 = v31;
                    int64_t v35 = v34; // 0x1943
                    if (v34 < maxlen) {
                        // 0x1945
                        *(char *)(v34 + v7) = 32;
                        v35 = v6;
                    }
                    // 0x194c
                    v31 = v35 + 1;
                    *currlen = v31;
                    v32 = (int32_t)v33 - 1;
                    v33 = v32;
                }
                int32_t v36 = v27; // 0x1958
                v29 = v31;
                v30 = v27 - (v36 >= 0 == (v36 != 0) ? v27 : 1) & 0xffffffff;
                v28 = v26;
            }
        }
    } else {
        int32_t v37 = v27; // 0x1886
        int32_t v38 = v25 - v37; // 0x1886
        v29 = v6;
        v30 = 0;
        v28 = v38 < 0 == (v38 & v37) < 0 ? v26 : v27;
    }
    int64_t v39 = v29; // 0x1892
    if (v3 != 0) {
        int64_t v40 = v29; // 0x1897
        if (v29 < maxlen) {
            // 0x1980
            *(char *)(v29 + v7) = (char)v3;
            v40 = v6;
        }
        // 0x189d
        v39 = v40 + 1;
        *currlen = v39;
    }
    int64_t v41 = v39; // 0x18a7
    uint32_t v42 = v28; // 0x18a7
    if ((int32_t)v28 != 0) {
        int64_t v43 = v39; // 0x1913
        if (v39 < maxlen) {
            // 0x1915
            *(char *)(v39 + v7) = 48;
            v43 = v6;
        }
        int64_t v44 = v43 + 1; // 0x191c
        *currlen = v44;
        v41 = v44;
        while (v42 != 0) {
            // 0x1910
            v42 = (int64_t)v42;
            int64_t v45 = v44;
            v43 = v45;
            if (v45 < maxlen) {
                // 0x1915
                *(char *)(v45 + v7) = 48;
                v43 = v6;
            }
            // 0x191c
            v44 = v43 + 1;
            *currlen = v44;
            v41 = v44;
        }
    }
    int64_t v46 = v23; // 0x18b8
    v46--;
    int64_t v47 = v41; // 0x18c3
    if (v41 < maxlen) {
        // 0x18c5
        *(char *)(v41 + v7) = *(char *)v46;
        v47 = v6;
    }
    int64_t v48 = v47 + 1; // 0x18d0
    *currlen = v48;
    while (v21 + v11 - (v18 + 0xffffffff & 0xffffffff) != v46) {
        int64_t v49 = v48;
        v46--;
        v47 = v49;
        if (v49 < maxlen) {
            // 0x18c5
            *(char *)(v49 + v7) = *(char *)v46;
            v47 = v6;
        }
        // 0x18d0
        v48 = v47 + 1;
        *currlen = v48;
    }
    // 0x18e0
    if (v30 == 0) {
        // 0x1900
        return;
    }
    uint32_t v50 = v30; // 0x18e2
    int64_t v51 = v48; // 0x18eb
    if (v48 < maxlen) {
        // 0x18ed
        *(char *)(v48 + v7) = 32;
        v51 = v6;
    }
    int64_t v52 = v51 + 1; // 0x18f4
    *currlen = v52;
    while (v50 != 0) {
        // 0x18e8
        v50 = (int64_t)v50;
        int64_t v53 = v52;
        v51 = v53;
        if (v53 < maxlen) {
            // 0x18ed
            *(char *)(v53 + v7) = 32;
            v51 = v6;
        }
        // 0x18f4
        v52 = v51 + 1;
        *currlen = v52;
    }
}

// Address range: 0x19d0 - 0x1a83
int64_t my_modf_isra_0(int64_t a1) {
    // 0x19d0
    int128_t v1; // 0x19d0
    int128_t v2 = __asm_movapd(v1); // 0x19d1
    int128_t v3 = __asm_movsd(0x3ff0000000000000); // 0x19de
    int128_t v4 = __asm_movsd(0x3fb999999999999a); // 0x19e6
    int128_t v5 = __asm_movsd(0x4024000000000000); // 0x19ee
    int128_t v6 = __asm_movapd(v3); // 0x19f6
    int64_t v7; // bp-8, 0x19d0
    bool v8 = &v7 < (int64_t *)32; // 0x19fa
    int64_t result2 = 0;
    int128_t v9 = v6;
    int128_t v10; // 0x19d0
    int128_t v11 = v10;
    int128_t v12 = v2;
    int64_t v13 = __asm_cvttsd2si_3(v12); // 0x1a10
    __asm_pxor(v11, v11);
    int128_t v14 = __asm_addsd(__asm_movapd(v12), v3); // 0x1a1d
    int128_t v15 = __asm_cvtsi2sd(v13); // 0x1a21
    __asm_comisd(v14, v15);
    while (v8) {
        int64_t v16 = result2 + 1; // 0x1a04
        int64_t result = v16 & 0xffffffff; // 0x1a04
        uint32_t v17 = (int32_t)v16; // 0x1a0b
        v8 = v17 < 100;
        int128_t v18 = __asm_mulsd(v12, v4); // 0x1a0e
        int128_t v19 = __asm_mulsd(v9, v5); // 0x1a0e
        if (v17 == 100) {
            // 0x1a48
            *(int64_t *)a1 = 0;
            return result;
        }
        result2 = result;
        v9 = v19;
        v11 = v15;
        v12 = v18;
        v13 = __asm_cvttsd2si_3(v12);
        __asm_pxor(v11, v11);
        v14 = __asm_addsd(__asm_movapd(v12), v3);
        v15 = __asm_cvtsi2sd(v13);
        __asm_comisd(v14, v15);
    }
    // 0x1a2c
    __asm_comisd(v15, __asm_subsd(__asm_movapd(v12), v3));
    if (result2 == 0) {
        // 0x1a3e
        *(int64_t *)a1 = __asm_movsd_1(v15);
        return result2;
    }
    int128_t v20 = __asm_mulsd(v15, v9); // 0x1a55
    __asm_subsd(v1, v20);
    int64_t v21 = __asm_movsd_1(v20); // 0x1a62
    int64_t v22; // bp-16, 0x19d0
    int64_t result3 = my_modf_isra_0((int64_t)&v22); // 0x1a68
    *(int64_t *)a1 = __asm_movsd_1(__asm_addsd_2(__asm_movsd(v21), v22));
    return result3;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1a90 - 0x2010
// Line range:    586 - 525
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags) {
    char iconvert[311]; // bp-704, 0x1a90
    char v1[311]; // 0x1a90
    char v2[311]; // 0x1ff8
    char v3[311]; // 0x1f32
    char v4[311]; // 0x1b93
    char v5[311]; // 0x1f0c
    // 0x1a90
    int128_t v6; // 0x1a90
    int128_t v7 = v6;
    int128_t v8 = v6;
    int128_t v9 = v6;
    int3_t v10; // 0x1a90
    int3_t v11 = v10 - 1;
    float80_t v12; // 0x1a90
    __frontend_reg_store_fpr(v11, v12);
    int32_t v13 = 6; // 0x1ab5
    int64_t v14 = 6; // 0x1ab5
    if (max >= 0) {
        int32_t v15 = max - 16; // 0x1ac1
        v14 = v15 == 0 | v15 < 0 != (15 - max & max) < 0 ? (int64_t)max : 16;
        v13 = max;
    }
    uint64_t v16 = (int64_t)flags;
    int3_t v17 = v10 - 2; // 0x1ac8
    __frontend_reg_store_fpr(v17, 0.0L);
    float80_t v18 = __frontend_reg_load_fpr(v17); // 0x1aca
    float80_t v19 = __frontend_reg_load_fpr(v11); // 0x1aca
    float80_t v20 = __frontend_reg_load_fpr(v11);
    int32_t v21; // 0x1a90
    int32_t v22; // 0x1a90
    float64_t v23; // bp-744, 0x1a90
    int128_t v24; // 0x1a90
    if (v18 > v19) {
        // 0x1f40
        __frontend_reg_store_fpr(v11, -v20);
        float64_t v25 = __frontend_reg_load_fpr(v11); // 0x1f4a
        v23 = v25;
        v22 = 45;
        v21 = 1;
        v24 = __asm_movsd((int64_t)v25);
    } else {
        float64_t v26 = v20; // 0x1ad2
        v23 = v26;
        int128_t v27 = __asm_movsd((int64_t)v26); // 0x1ad5
        v22 = 43;
        v21 = 1;
        v24 = v27;
        if ((v16 & 2) == 0) {
            int32_t v28 = 8 * flags & 32; // 0x1aed
            v22 = v28;
            v21 = v28 != 0;
            v24 = v27;
        }
    }
    // 0x1afe
    __asm_movapd(v24);
    float64_t fracpart; // bp-712, 0x1a90
    int64_t v29 = &fracpart; // 0x1b08
    my_modf_isra_0(v29);
    bool v30; // 0x1a90
    bool v31; // 0x1a90
    int128_t v32; // 0x1a90
    int128_t v33; // 0x1a90
    int128_t v34; // 0x1a90
    bool v35; // 0x1a90
    bool v36; // 0x1a90
    if (v13 == 0) {
        int128_t v37 = __asm_movsd((int64_t)fracpart); // 0x1fa4
        int128_t v38 = __asm_subsd(v24, v37); // 0x1faa
        int64_t v39 = __asm_cvttsd2si_3(v38); // 0x1faf
        v23 = __asm_movsd_1(v38);
        __frontend_reg_store_fpr(v11, (float80_t)v39);
        __frontend_reg_store_fpr(v11, (float80_t)v23 - __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v17, 0.5L);
        float80_t v40 = __frontend_reg_load_fpr(v17); // 0x1fcc
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v40);
        float80_t v41 = __frontend_reg_load_fpr(v17); // 0x1fce
        float80_t v42 = __frontend_reg_load_fpr(v11); // 0x1fce
        bool v43 = false; // 0x1fce
        bool v44 = false; // 0x1fce
        bool v45 = false; // 0x1fce
        if (v41 <= v42) {
            v43 = true;
            v44 = false;
            v45 = false;
            if (v41 >= v42) {
                v43 = v41 != v42;
                v44 = v41 != v42;
                v45 = true;
            }
        }
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
        bool v46 = true; // 0x1fd2
        bool v47 = v44; // 0x1fd2
        bool v48 = v45; // 0x1fd2
        int64_t v49 = v39; // 0x1fd2
        if (!v43) {
            // 0x1fd4
            v49 = v39 + 1;
            v46 = v39 == -1;
            v47 = llvm_ctpop_i8((char)v49) % 2 == 0;
            v48 = v49 == 0;
        }
        // 0x1fd8
        __asm_pxor(v7, v7);
        int128_t v50 = __asm_movsd(0x3ff0000000000000); // 0x1fdd
        int128_t v51 = __asm_cvtsi2sd(v49); // 0x1fe5
        v23 = __asm_movsd_1(v51);
        __asm_comisd(v51, v50);
        __frontend_reg_store_fpr(v11, (float80_t)v23);
        int64_t v52 = __asm_movsd_1(v51); // 0x1ff8
        v2[0] = v52;
        iconvert = v2;
        if (v46) {
            // 0x1bc0
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v47;
            v35 = v48;
            v32 = v37;
            v34 = v51;
            goto lab_0x1bc8;
        } else {
            int128_t v53 = __asm_addsd(v37, v50); // 0x2005
            __frontend_reg_store_fpr(v17, 1.0L);
            v31 = v47;
            v36 = v48;
            v33 = v53;
            goto lab_0x1efb;
        }
    } else {
        // 0x1b19
        __frontend_reg_store_fpr(v11, 1.0L);
        __frontend_reg_store_fpr(v17, 10.0L);
        int64_t v54 = v14 & 0xffffffff; // 0x1b21
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
        uint32_t v55 = (int32_t)v54 - 1; // 0x1b2a
        int64_t v56 = v55; // 0x1b2d
        while (v55 != 0) {
            // 0x1b28
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
            v55 = (int32_t)v56 - 1;
            v56 = v55;
        }
        float80_t v57 = __frontend_reg_load_fpr(v17); // 0x1b2f
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v57);
        int128_t v58 = __asm_movsd((int64_t)fracpart); // 0x1b35
        v23 = __asm_movsd_1(__asm_subsd(v24, v58));
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) * (float80_t)v23);
        int3_t v59 = v10 - 3;
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        float80_t v60 = __frontend_reg_load_fpr(v59); // 0x1b5c
        v23 = v60;
        __frontend_reg_store_fpr(v59, v60);
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) - __frontend_reg_load_fpr(v59));
        __frontend_reg_store_fpr(v59, (float80_t)*(float32_t *)0x34b4);
        float80_t v61 = __frontend_reg_load_fpr(v59); // 0x1b6e
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v61);
        float80_t v62 = __frontend_reg_load_fpr(v59); // 0x1b70
        float80_t v63 = __frontend_reg_load_fpr(v17); // 0x1b70
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
        if (v62 < v63) {
            // 0x1f20
            __asm_pxor(v9, v9);
            int128_t v64 = __asm_cvtsi2sd((int64_t)v23); // 0x1f24
            int64_t v65 = __asm_movsd_1(v64); // 0x1f2a
            v23 = v65;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v65);
            int64_t v66 = __asm_movsd_1(v64); // 0x1f32
            v3[0] = v66;
            v1 = v3;
        } else {
            // 0x1b7a
            __asm_pxor(v9, v9);
            int128_t v67 = __asm_cvtsi2sd((int64_t)v23 + 1); // 0x1b86
            int64_t v68 = __asm_movsd_1(v67); // 0x1b8b
            v23 = v68;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v68);
            int64_t v69 = __asm_movsd_1(v67); // 0x1b93
            v4[0] = v69;
            v1 = v4;
        }
        // 0x1b99
        iconvert = v1;
        __frontend_reg_store_fpr(v59, 1.0L);
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
        uint32_t v70 = (int32_t)v54 - 1; // 0x1ba2
        int64_t v71 = v70; // 0x1ba5
        while (v70 != 0) {
            // 0x1ba0
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            v70 = (int32_t)v71 - 1;
            v71 = v70;
        }
        float80_t v72 = __frontend_reg_load_fpr(v59); // 0x1ba7
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v72);
        float80_t v73 = __frontend_reg_load_fpr(v59); // 0x1ba9
        float80_t v74 = __frontend_reg_load_fpr(v17); // 0x1ba9
        bool v75 = false; // 0x1ba9
        bool v76 = false; // 0x1ba9
        bool v77 = false; // 0x1ba9
        if (v73 <= v74) {
            v75 = true;
            v76 = false;
            v77 = false;
            if (v73 >= v74) {
                v75 = v73 != v74;
                v76 = v73 != v74;
                v77 = true;
            }
        }
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v59));
        if (!v75) {
            int128_t v78 = __asm_addsd_2(v58, 0x3ff0000000000000); // 0x1ee0
            __frontend_reg_store_fpr(v59, 1.0L);
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            uint32_t v79 = (int32_t)v54 - 1; // 0x1ef2
            int64_t v80 = v79; // 0x1ef5
            while (v79 != 0) {
                // 0x1ef0
                __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
                v79 = (int32_t)v80 - 1;
                v80 = v79;
            }
            unsigned char v81 = llvm_ctpop_i8((char)v79); // 0x1ef2
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v59));
            float80_t v82 = __frontend_reg_load_fpr(v17); // 0x1ef9
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
            __frontend_reg_store_fpr(v11, v82);
            v31 = v81 % 2 == 0;
            v36 = true;
            v33 = v78;
            goto lab_0x1efb;
        } else {
            // 0x1bb3
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v76;
            v35 = v77;
            v32 = v58;
            v34 = __asm_movsd(*(int64_t *)&iconvert);
            goto lab_0x1bc8;
        }
    }
  lab_0x1bc8:;
    int64_t v83 = (int64_t)currlen;
    int64_t v84 = (int64_t)buffer;
    int64_t v85 = &v23; // 0x1aa0
    int64_t v86; // bp-697, 0x1a90
    int64_t v87 = &v86; // 0x1bcd
    int128_t v88 = __asm_pxor(v8, v8); // 0x1bd2
    int128_t v89 = __asm_movsd(0x3fb999999999999a); // 0x1bd7
    int128_t v90 = __asm_movsd(0x3fa999999999999a); // 0x1be0
    int128_t v91 = __asm_movsd(0x4024000000000000); // 0x1bf0
    bool v92 = v30; // 0x1bf9
    bool v93 = v35; // 0x1bf9
    int64_t v94 = 1;
    int128_t v95 = __asm_movapd(__asm_mulsd(v32, v89)); // 0x1c1c
    my_modf_isra_0(v29);
    int128_t v96 = __asm_movsd((int64_t)fracpart); // 0x1c26
    int128_t v97 = __asm_subsd(v95, v96); // 0x1c2c
    __asm_ucomisd(v96, v88);
    int32_t v98 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v97, v90), v91)); // 0x1c40
    char v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef"); // 0x1c47
    *(char *)(v94 + v87) = v99;
    bool v100; // 0x1a90
    int64_t v101; // 0x1a90
    bool v102; // 0x1a90
    while (v92 || !v93) {
        int64_t v103 = v94 - 311; // 0x1c04
        unsigned char v104 = llvm_ctpop_i8((char)v103); // 0x1c04
        v92 = v104 % 2 == 0;
        v93 = false;
        v100 = v104 % 2 == 0;
        v102 = true;
        v101 = 310;
        if (v103 == 0) {
            goto lab_0x1c63;
        }
        v94++;
        v95 = __asm_movapd(__asm_mulsd(v96, v89));
        my_modf_isra_0(v29);
        v96 = __asm_movsd((int64_t)fracpart);
        v97 = __asm_subsd(v95, v96);
        __asm_ucomisd(v96, v88);
        v98 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v97, v90), v91));
        v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef");
        *(char *)(v94 + v87) = v99;
    }
    int32_t v105 = (int32_t)v94 - 311; // 0x1c54
    v100 = llvm_ctpop_i8((char)v105) % 2 == 0;
    v102 = v105 == 0;
    v101 = v105 == 0 ? 310 : v94 & 0xffffffff;
  lab_0x1c63:
    // 0x1c63
    __asm_ucomisd(v34, v88);
    int64_t v106 = 0x100000000 * v101 >> 32; // 0x1c68
    v23 = v106;
    int64_t v107 = v85 + 48; // 0x1c6f
    *(char *)(v106 + v107) = 0;
    int64_t v108 = v14; // 0x1c74
    int64_t v109 = 0; // 0x1c74
    if (v100 || !v102) {
        bool v110 = v100; // 0x1c8e
        bool v111 = v102; // 0x1c8e
        int64_t v112 = 1;
        int128_t v113 = __asm_mulsd(v34, v89); // 0x1ca1
        __asm_movapd(v113);
        int128_t v114 = __asm_movapd(v113); // 0x1cae
        my_modf_isra_0((int64_t)&iconvert);
        int128_t v115 = __asm_movsd(*(int64_t *)&iconvert); // 0x1cb8
        int128_t v116 = __asm_subsd(v114, v115); // 0x1cc1
        __asm_ucomisd(v115, v88);
        int32_t v117 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v116, v90), v91)); // 0x1cd5
        char v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef"); // 0x1cdc
        int64_t v119; // bp-377, 0x1a90
        *(char *)(v112 + (int64_t)&v119) = v118;
        while (v110 || !v111) {
            int64_t v120 = v112 - 311; // 0x1c94
            v110 = llvm_ctpop_i8((char)v120) % 2 == 0;
            v111 = false;
            if (v120 == 0) {
                goto lab_0x1f88;
            }
            v112++;
            v113 = __asm_mulsd(v115, v89);
            __asm_movapd(v113);
            v114 = __asm_movapd(v113);
            my_modf_isra_0((int64_t)&iconvert);
            v115 = __asm_movsd(*(int64_t *)&iconvert);
            v116 = __asm_subsd(v114, v115);
            __asm_ucomisd(v115, v88);
            v117 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v116, v90), v91));
            v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef");
            *(char *)(v112 + (int64_t)&v119) = v118;
        }
        if ((int32_t)v112 == 311) {
          lab_0x1f88:
            // 0x1f88
            v108 = v14 + 0xfffffeca;
            v109 = 310;
        } else {
            // 0x1cf5
            v108 = v14 - v112;
            v109 = v112 & 0xffffffff;
        }
    }
    int64_t v121 = (0x100000000 * v109 >> 32) + v85;
    int64_t v122 = v121 + 368; // 0x1d05
    *(char *)v122 = 0;
    int32_t v123 = -1 - (int32_t)v14 + (int32_t)(float32_t)(float64_t)(int64_t)min - v21 - (int32_t)v101; // 0x1d1d
    int64_t v124 = v123 >= 0 ? (int64_t)v123 : 0; // 0x1d22
    int64_t v125; // 0x1a90
    int64_t v126; // 0x1a90
    int64_t v127; // 0x1a90
    int64_t v128; // 0x1a90
    int64_t v129; // 0x1a90
    int64_t v130; // 0x1a90
    if (v16 % 2 == 0) {
        if ((v16 & 16) == 0) {
            // 0x1ea0
            v129 = v83;
            v125 = v124;
            if (v123 >= 1) {
                if (v83 < maxlen) {
                    // 0x1eb5
                    *(char *)(v83 + v84) = 32;
                }
                int64_t v131 = v83 + 1; // 0x1ebc
                *currlen = v131;
                uint32_t v132 = (int32_t)v124 - 1; // 0x1ec3
                int64_t v133 = v132; // 0x1ec7
                while (v132 != 0) {
                    int64_t v134 = v131;
                    int64_t v135 = v134; // 0x1eb3
                    if (v134 < maxlen) {
                        // 0x1eb5
                        *(char *)(v134 + v84) = 32;
                        v135 = v83;
                    }
                    // 0x1ebc
                    v131 = v135 + 1;
                    *currlen = v131;
                    v132 = (int32_t)v133 - 1;
                    v133 = v132;
                }
                int32_t v136 = v124; // 0x1ec9
                v129 = v131;
                v125 = v124 - (v136 >= 0 == (v136 != 0) ? v124 : 1) & 0xffffffff;
            }
            goto lab_0x1d33;
        } else {
            // 0x1e5e
            v129 = v83;
            v125 = v124;
            if (v123 < 1) {
                goto lab_0x1d33;
            } else {
                // 0x1e67
                v130 = v83;
                v126 = v124;
                if (v22 != 0) {
                    // 0x1f71
                    v128 = v83;
                    v127 = v124;
                    if (v83 < maxlen) {
                        // 0x1f7a
                        *(char *)(v83 + v84) = (char)v22;
                        v128 = v83;
                        v127 = v124;
                    }
                    goto lab_0x1e84;
                } else {
                    goto lab_0x1e78;
                }
            }
        }
    } else {
        // 0x1d30
        v129 = v83;
        v125 = -v124 & 0xffffffff;
        goto lab_0x1d33;
    }
  lab_0x1efb:
    // 0x1efb
    __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) - __frontend_reg_load_fpr(v17));
    fracpart = __asm_movsd_1(v33);
    float64_t v137 = __frontend_reg_load_fpr(v11); // 0x1f03
    v23 = v137;
    int128_t v138 = __asm_movsd((int64_t)v137); // 0x1f06
    int64_t v139 = __asm_movsd_1(v138); // 0x1f0c
    v5[0] = v139;
    iconvert = v5;
    v30 = v31;
    v35 = v36;
    v32 = v33;
    v34 = v138;
    goto lab_0x1bc8;
  lab_0x1d33:;
    int64_t v140 = v129; // 0x1d39
    int64_t v141 = v125; // 0x1d39
    if (v22 != 0) {
        int64_t v142 = v129; // 0x1d3e
        if (v129 < maxlen) {
            // 0x1d40
            *(char *)(v129 + v84) = (char)v22;
            v142 = v83;
        }
        int64_t v143 = v142 + 1; // 0x1d46
        *currlen = v143;
        v140 = v143;
        v141 = v125;
    }
    goto lab_0x1d4d;
  lab_0x1d4d:;
    int64_t v144 = v107 + (int64_t)v23 - 1;
    int64_t v145; // 0x1a90
    if (v140 < maxlen) {
        // 0x1d65
        *(char *)(v145 + v84) = *(char *)v144;
    }
    int64_t v146 = v140 + 1; // 0x1d70
    *currlen = v146;
    int64_t v147 = v146; // 0x1d7e
    int64_t v148 = v144; // 0x1d7e
    while (v87 - (v101 + 0xffffffff & 0xffffffff) + (int64_t)v23 != v144) {
        // 0x1d60
        v144 = v148 - 1;
        if (v147 < maxlen) {
            // 0x1d65
            *(char *)(v145 + v84) = *(char *)v144;
        }
        // 0x1d70
        v146 = v147 + 1;
        *currlen = v146;
        v147 = v146;
        v148 = v144;
    }
    if (v13 != 0) {
        int64_t v149 = v146; // 0x1d88
        if (v146 < maxlen) {
            // 0x1d8a
            *(char *)(v146 + v84) = 46;
            v149 = v83;
        }
        int64_t v150 = v149 + 1; // 0x1d91
        *currlen = v150;
        int64_t v151 = v150; // 0x1d9a
        if ((int32_t)v108 >= 1) {
            int64_t v152 = v151;
            int64_t v153 = v152; // 0x1da3
            if (v152 < maxlen) {
                // 0x1da5
                *(char *)(v152 + v84) = 48;
                v153 = v83;
            }
            int64_t v154 = v153 + 1; // 0x1dac
            *currlen = v154;
            uint32_t v155 = (int32_t)(v108 & 0xffffffff) - 1; // 0x1db3
            int64_t v156 = v155; // 0x1db6
            while (v155 != 0) {
                // 0x1da0
                v152 = v154;
                v153 = v152;
                if (v152 < maxlen) {
                    // 0x1da5
                    *(char *)(v152 + v84) = 48;
                    v153 = v83;
                }
                // 0x1dac
                v154 = v153 + 1;
                *currlen = v154;
                v155 = (int32_t)v156 - 1;
                v156 = v155;
            }
        }
        if (v109 != 0) {
            int64_t v157 = v122 - 1;
            if (v83 < maxlen) {
                // 0x1ddd
                *(char *)(v83 + v84) = *(char *)v157;
            }
            int64_t v158 = v83 + 1; // 0x1de8
            *currlen = v158;
            int64_t v159 = v157; // 0x1df6
            while (367 - (v109 + 0xffffffff & 0xffffffff) + v121 != v157) {
                int64_t v160 = v158;
                v157 = v159 - 1;
                int64_t v161 = v160; // 0x1ddb
                if (v160 < maxlen) {
                    // 0x1ddd
                    *(char *)(v160 + v84) = *(char *)v157;
                    v161 = v83;
                }
                // 0x1de8
                v158 = v161 + 1;
                *currlen = v158;
                v159 = v157;
            }
        }
    }
    // 0x1df8
    if ((int32_t)v141 == 0) {
        // 0x1e19
        return;
    }
    if (v83 < maxlen) {
        // 0x1e05
        *(char *)(v83 + v84) = 32;
    }
    int64_t v162 = v83 + 1; // 0x1e0c
    *currlen = v162;
    uint32_t v163 = (int32_t)v141 + 1; // 0x1e13
    int64_t v164 = v163; // 0x1e17
    while (v163 != 0) {
        int64_t v165 = v162;
        int64_t v166 = v165; // 0x1e03
        if (v165 < maxlen) {
            // 0x1e05
            *(char *)(v165 + v84) = 32;
            v166 = v83;
        }
        // 0x1e0c
        v162 = v166 + 1;
        *currlen = v162;
        v163 = (int32_t)v164 + 1;
        v164 = v163;
    }
  lab_0x1e78:;
    int64_t v167 = v126;
    int64_t v168 = v130;
    v128 = v168;
    v127 = v167;
    if (v168 < maxlen) {
        // 0x1e7d
        *(char *)(v168 + v84) = 48;
        v128 = v83;
        v127 = v167;
    }
    goto lab_0x1e84;
  lab_0x1e84:;
    int64_t v169 = v128 + 1; // 0x1e84
    *currlen = v169;
    uint32_t v170 = (int32_t)v127 - 1; // 0x1e8b
    int64_t v171 = v170; // 0x1e8b
    v140 = v169;
    v141 = v171;
    v130 = v169;
    v126 = v171;
    if (v170 != 0) {
        goto lab_0x1e78;
    } else {
        goto lab_0x1d4d;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2010 - 0x292d
// Line range:    130 - 290
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args) {
    // 0x2010
    int64_t v1; // 0x2010
    uint64_t v2 = v1;
    int64_t v3 = (int64_t)buffer;
    int64_t v4 = (int64_t)format + 1; // 0x2023
    int64_t v5 = v4; // 0x2023
    int64_t result2 = 0; // 0x2039
    int64_t v6; // 0x2010
    int64_t v7; // 0x2010
    int64_t v8; // 0x2010
    int64_t v9; // 0x2010
    char v10; // 0x2010
    int64_t v11; // 0x2010
    int64_t v12; // 0x2010
    if ((char)v2 != 0) {
        int64_t v13 = (int64_t)args;
        int64_t * v14 = (int64_t *)(v13 + 8);
        v6 = v4;
        v7 = v2 % 256;
        v12 = 0;
        while (true) {
          lab_0x208e:;
            char v15 = v7; // 0x2095
            int64_t v16 = v6; // 0x2098
            char v17 = v15; // 0x2098
            int64_t v18 = v12; // 0x2098
            int64_t v19 = v6; // 0x2098
            int64_t v20 = v12; // 0x2098
            if (v15 != 37) {
                while (true) {
                  lab_0x209a:;
                    uint64_t v21 = v18;
                    int64_t v22 = v16; // 0x209d
                    if (v21 < maxlen) {
                        // 0x209f
                        *(char *)(v21 + v3) = v17;
                        v22 = v5;
                    }
                    char v23 = *(char *)v22; // 0x20a3
                    int64_t v24 = v22 + 1; // 0x20a6
                    v5 = v24;
                    int64_t v25 = v21 + 1; // 0x20aa
                    result2 = v25;
                    v16 = v24;
                    v17 = v23;
                    v18 = v25;
                    v19 = v24;
                    v20 = v25;
                    switch (v23) {
                        case 0: {
                            goto lab_0x2040_3;
                        }
                        case 37: {
                            goto lab_0x20b9;
                        }
                        default: {
                            goto lab_0x209a;
                        }
                    }
                }
            }
          lab_0x20b9:
            // 0x20b9
            v11 = v20;
            unsigned char v26 = *(char *)v19; // 0x20c3
            result2 = v11;
            if (v26 == 0) {
                // break -> 0x2040
                break;
            }
            int64_t v27 = v26; // 0x20c3
            int64_t result = v27; // 0x20db
            if (v26 < 49) {
                // 0x2053
                return result;
            }
            int64_t v28 = v19 + 1; // 0x20ce
            int64_t v29 = (int64_t)g7; // 0x20ea
            v5 = 0;
            int64_t v30 = v27; // 0x20fa
            int64_t v31 = v28; // 0x20fa
            int32_t v32 = 0; // 0x20fa
            int64_t v33 = v27; // 0x20fa
            int64_t v34 = v28; // 0x20fa
            if ((*(char *)(2 * v27 + v29) & 4) != 0) {
                int64_t v35 = 0xffffffd0 + (0x100000000000000 * v30 >> 56); // 0x2106
                int64_t v36 = v35 & 0xffffffff; // 0x2106
                v5 = v36;
                unsigned char v37 = *(char *)v31; // 0x210a
                result2 = v11;
                if (v37 == 0) {
                    // break (via goto) -> 0x2040
                    goto lab_0x2040_3;
                }
                int64_t v38 = v31 + 1; // 0x2102
                int64_t v39 = v37; // 0x210a
                v31 = v38;
                while ((*(char *)(2 * v39 + v29) & 4) != 0) {
                    // 0x20fc
                    v35 = 10 * v36 + 0xffffffd0 + (0x100000000000000 * v39 >> 56);
                    v36 = v35 & 0xffffffff;
                    v5 = v36;
                    v37 = *(char *)v31;
                    result2 = v11;
                    if (v37 == 0) {
                        // break (via goto) -> 0x2040
                        goto lab_0x2040_3;
                    }
                    // 0x2116
                    v38 = v31 + 1;
                    v39 = v37;
                    v31 = v38;
                }
                // 0x2122
                v32 = v35;
                v33 = v39;
                v34 = v38;
            }
            int64_t v40 = v34;
            int64_t v41 = v33; // 0x2124
            int64_t v42 = v40; // 0x2124
            if (v33 == 42) {
                uint32_t v43 = v32; // 0x2658
                if (v43 < 48) {
                    // 0x265f
                    v5 = *(int64_t *)(v13 + 16) + (int64_t)v43;
                    *args = v43 + 8;
                } else {
                    int64_t v44 = *v14; // 0x26b3
                    v5 = v44;
                    *v14 = v44 + 8;
                }
                unsigned char v45 = *(char *)v40; // 0x266a
                result2 = v11;
                if (v45 == 0) {
                    // break -> 0x2040
                    break;
                }
                // 0x267c
                v41 = v45;
                v42 = v40 + 1;
            }
            int64_t v46 = v42;
            int64_t v47 = v41; // 0x2132
            int64_t v48 = v46; // 0x2132
            if ((char)v41 == 46) {
                char v49 = *(char *)v46; // 0x21e8
                result2 = v11;
                if (v49 == 0) {
                    // break -> 0x2040
                    break;
                }
                int64_t v50 = v46;
                unsigned char v51 = v49;
                int64_t v52 = v50 + 1;
                int64_t v53 = v51;
                while ((*(char *)(2 * v53 + v29) & 4) != 0) {
                    char v54 = *(char *)v52; // 0x221c
                    result2 = v11;
                    if (v54 == 0) {
                        // break (via goto) -> 0x2040
                        goto lab_0x2040_3;
                    }
                    v50 = v52;
                    v51 = v54;
                    v52 = v50 + 1;
                    v53 = v51;
                }
                // 0x25a0
                v47 = v53;
                v48 = v52;
                if (v51 == 42) {
                    uint32_t v55 = *(int32_t *)&v5; // 0x25a8
                    if (v55 < 48) {
                        // 0x25b3
                        *args = v55 + 8;
                    } else {
                        // 0x2684
                        *v14 = *v14 + 8;
                    }
                    unsigned char v56 = *(char *)v52; // 0x25be
                    result2 = v11;
                    if (v56 == 0) {
                        // break -> 0x2040
                        break;
                    }
                    // 0x25d1
                    v47 = v56;
                    v48 = v50 + 2;
                }
            }
            int64_t v57 = v48;
            int64_t v58 = v47;
            switch ((char)v58) {
                case 104: {
                    char v59 = *(char *)v57; // 0x263e
                    v10 = v59;
                    v9 = v57 + 1;
                    if (v59 == 0) {
                        // break -> 0x2040
                        break;
                    }
                    goto lab_0x25f6;
                }
                case 108: {
                    char v60 = *(char *)v57; // 0x25d9
                    int64_t v61 = v57 + 1;
                    result2 = v11;
                    v10 = v60;
                    v9 = v61;
                    switch (v60) {
                        case 108: {
                            char v62 = *(char *)v61; // 0x2695
                            v10 = v62;
                            v9 = v57 + 2;
                            if (v62 == 0) {
                                // break -> 0x2040
                                break;
                            }
                            goto lab_0x25f6;
                        }
                        case 0: {
                            goto lab_0x2040_3;
                        }
                        default: {
                            goto lab_0x25f6;
                        }
                    }
                }
                case 76: {
                    unsigned char v63 = *(char *)v57; // 0x260f
                    if (v63 == 0) {
                        // break -> 0x2040
                        break;
                    }
                    int64_t v64 = (int64_t)v63 + 0xffffffdb; // 0x261b
                    v8 = v57 + 1;
                    if ((char)v64 < 84) {
                        int32_t v65 = *(int32_t *)((4 * v64 & 1020) + (int64_t)&g3); // 0x2634
                        return (int64_t)v65 + (int64_t)&g3;
                    }
                    goto lab_0x2283;
                }
                default: {
                    // 0x2150
                    v8 = v57;
                    if ((char)(v58 + 0xffffffdb) < 84) {
                        // 0x215b
                        int64_t v66; // 0x2150
                        int32_t v67 = *(int32_t *)((4 * v66 & 1020) + (int64_t)&g1); // 0x2165
                        return (int64_t)v67 + (int64_t)&g1;
                    }
                    goto lab_0x2283;
                }
            }
        }
    }
  lab_0x2040_3:
    // 0x2040
    if (maxlen == 0) {
        // 0x2053
        return result2;
    }
    uint64_t v68 = maxlen - 1;
    if (v68 > result2) {
        // 0x204e
        *(char *)(result2 + v3) = 0;
        // 0x2053
        return result2;
    }
    // 0x2068
    *(char *)(v68 + v3) = 0;
    return result2;
  lab_0x2283:;
    unsigned char v69 = *(char *)v8; // 0x2283
    int64_t v70 = v8 + 1; // 0x2287
    v5 = v70;
    result2 = v11;
    v6 = v70;
    v7 = v69;
    v12 = v11;
    if (v69 == 0) {
        // break -> 0x2040
        goto lab_0x2040_3;
    }
    goto lab_0x208e;
  lab_0x25f6:;
    int64_t v71 = (int64_t)v10 + 0xffffffdb; // 0x25f6
    v8 = v9;
    if ((char)v71 < 84) {
        int32_t v72 = *(int32_t *)((4 * v71 & 1020) + (int64_t)&g2); // 0x2604
        return (int64_t)v72 + (int64_t)&g2;
    }
    goto lab_0x2283;
}

// Address range: 0x292d - 0x2938
int64_t function_292d(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x292d
    int64_t v1; // 0x292d
    return v1 & 0xffffffff;
}

// Address range: 0x2938 - 0x2943
int64_t function_2938(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2938
    int64_t v1; // 0x2938
    return v1 & 0xffffffff;
}

// Address range: 0x2943 - 0x294e
int64_t function_2943(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2943
    int64_t v1; // 0x2943
    return v1 & 0xffffffff;
}

// Address range: 0x294e - 0x2955
int64_t function_294e(void) {
    // 0x294e
    int64_t v1; // 0x294e
    return v1 & 0xffffffff;
}

// Address range: 0x2955 - 0x2960
int64_t function_2955(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2955
    int64_t v1; // 0x2955
    return v1 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2960 - 0x2a6c
// Line range:    751 - 769
int32_t libmin_printf(char * fmt, ...) {
    // 0x2960
    int64_t v1; // 0x2960
    if ((char)v1 != 0) {
        // 0x299c
        int128_t v2; // 0x2960
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 8; // bp-1248, 0x2a06
    char v4; // bp-1224, 0x2960
    dopr(&v4, (int64_t)&g5, fmt, (int32_t *)&v3);
    if (v4 == 0) {
        // 0x2a60
        return 0;
    }
    int64_t v5 = &v4;
    libtarg_putc(v4);
    int64_t v6 = v5 + 1; // 0x2a49
    char v7 = *(char *)v6; // 0x2a49
    while (v7 != 0) {
        // 0x2a40
        v5 = v6;
        libtarg_putc(v7);
        v6 = v5 + 1;
        v7 = *(char *)v6;
    }
    // 0x2a56
    int64_t v8; // bp+1225, 0x2960
    return v5 + (int64_t)&v8;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2a70 - 0x2b1b
// Line range:    772 - 782
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...) {
    // 0x2a70
    int64_t v1; // 0x2a70
    if ((char)v1 != 0) {
        // 0x2a96
        int128_t v2; // 0x2a70
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 24; // bp-224, 0x2aea
    dopr(s, size, fmt, (int32_t *)&v3);
    *(char *)((int64_t)s - 1 + size) = 0;
    return libmin_strlen(s);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_strlen.c
// Address range: 0x2b20 - 0x2b4b
// Line range:    5 - 15
int64_t libmin_strlen(char * str) {
    int64_t v1 = (int64_t)str;
    if (str == NULL || (char)v1 == 0) {
        // 0x2b48
        return 0;
    }
    int64_t v2 = v1; // 0x2b27
    v2++;
    while (*(char *)v2 != 0) {
        // 0x2b38
        v2++;
    }
    // 0x2b41
    return v2 - v1;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_success.c
// Address range: 0x2b50 - 0x2b59
// Line range:    5 - 7
void libmin_success(void) {
    // 0x2b50
    libtarg_success();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_ctype.c
// Address range: 0x2b60 - 0x2b82
// Line range:    140 - 146
int32_t _isctype(uint32_t c, int32_t mask) {
    int32_t result = 0; // 0x2b6f
    if (c < 256) {
        uint16_t v1 = *(int16_t *)((0x100000000 * (int64_t)c >> 31) + (int64_t)g7); // 0x2b7b
        result = (int32_t)v1 & mask;
    }
    // 0x2b81
    return result;
}

// Address range: 0x2b84 - 0x2b91
int64_t _fini(void) {
    // 0x2b84
    int64_t result; // 0x2b84
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 35

