//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int8_t int3_t;
typedef int64_t int128_t;
typedef uint64_t uint128_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __popcountdi2(uint64_t a1);
int64_t _fini(void);
int64_t _init(void);
int32_t _isctype(uint32_t c, int32_t mask);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t count_bits_builtin(int64_t a1);
int64_t count_bits_kernighan(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5);
int64_t count_bits_naive(int64_t a1);
int64_t count_bits_parallel(uint64_t a1);
int64_t count_bits_table(uint64_t a1);
int64_t deregister_tm_clones(void);
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args);
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags);
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags);
int64_t frame_dummy(void);
void function_1070(int64_t * d);
int64_t * function_1080(int64_t * s, int32_t c, int32_t n);
int32_t function_1090(int32_t c, struct _IO_FILE * stream);
int64_t * function_10a0(int64_t delta);
void function_10b0(int32_t status);
int64_t function_2aad(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2ab8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2ac3(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_2ace(void);
int64_t function_2ad5(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void init_popcount_table(void);
char * libmin_calloc(uint64_t num, uint64_t nsize);
void libmin_fail(uint32_t code);
int64_t libmin_free(int64_t a1);
int64_t libmin_free_part_0(int64_t a1);
int64_t libmin_malloc(uint64_t a1);
char * libmin_memcpy(char * dest, int32_t * src, int64_t n);
char * libmin_memset(char * dest, uint32_t c, uint64_t n);
int32_t libmin_printf(char * fmt, ...);
int32_t libmin_rand(void);
char * libmin_realloc(char * block, uint64_t size);
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...);
int64_t libmin_srand(void);
int64_t libmin_strlen(char * str);
void libmin_success(void);
void libtarg_fail(int32_t code);
void libtarg_putc(char c);
char * libtarg_sbrk(int64_t inc);
void libtarg_success(void);
int64_t my_modf_isra_0(int64_t a1);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = -0xdd400000c31; // 0x31d8
int64_t g2 = -0xf2400000d81; // 0x3328
int64_t g3 = -0x107400000ed1; // 0x3478
int64_t g4 = -0x66f74f2100000000; // 0x3620
int32_t * g5 = (int32_t *)0x1000000004; // 0x38c
int32_t * g6 = (int32_t *)0x100000010; // 0x390
int32_t g7 = 0; // 0x400
int64_t g8 = 0x20002000200020; // 0x5022
struct _IO_FILE * g10 = NULL; // 0x5240
char g11 = 0; // 0x5248
int64_t g12 = 0; // 0x5670
int64_t g13 = 0; // 0x5a0c
int32_t g14 = 0; // 0x5cb0
int32_t g15 = 0; // 0x603c
int64_t g16 = 0; // 0x6040
int32_t * head = NULL; // 0x5668
int32_t mt[625]; // 0x5680
int32_t mt_initialized = 0; // 0x6044
int32_t mti = 625; // 0x5010
int32_t popcount_table[256]; // 0x5260
int32_t * tail = NULL; // 0x5660
int32_t g17;
int64_t * g9 = &g8; // 0x5228

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g17;
    }
    // 0x1016
    return result;
}

// Address range: 0x1070 - 0x107b
void function_1070(int64_t * d) {
    // 0x1070
    __cxa_finalize(d);
}

// Address range: 0x1080 - 0x108b
int64_t * function_1080(int64_t * s, int32_t c, int32_t n) {
    // 0x1080
    return memset(s, c, n);
}

// Address range: 0x1090 - 0x109b
int32_t function_1090(int32_t c, struct _IO_FILE * stream) {
    // 0x1090
    return fputc(c, stream);
}

// Address range: 0x10a0 - 0x10ab
int64_t * function_10a0(int64_t delta) {
    // 0x10a0
    return sbrk(delta);
}

// Address range: 0x10b0 - 0x10bb
void function_10b0(int32_t status) {
    // 0x10b0
    exit(status);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/bit-kernels/bit-kernels.c
// Address range: 0x10c0 - 0x1395
// Line range:    81 - 92
int main() {
    // 0x10c0
    libmin_srand();
    init_popcount_table();
    int64_t v1 = libmin_malloc(400); // 0x10e8
    if (v1 == 0) {
        // 0x137f
        libmin_printf("ERROR: Memory allocation error!\n");
        return 1;
    }
    // 0x1108
    int64_t v2; // bp-120, 0x10c0
    int64_t v3 = &v2; // 0x10d3
    int64_t v4 = v1;
    int32_t v5 = libmin_rand(); // 0x1108
    *(int32_t *)v4 = libmin_rand() % 0x10000 | 0x10000 * v5;
    while (v1 + 396 != v4) {
        // 0x1108
        v4 += 4;
        v5 = libmin_rand();
        *(int32_t *)v4 = libmin_rand() % 0x10000 | 0x10000 * v5;
    }
    int64_t * v6 = (int64_t *)(v3 + 16);
    int64_t v7 = v3 + 8;
    char * v8 = (char *)v7;
    int64_t * v9 = (int64_t *)(v3 + 48);
    int64_t * v10 = (int64_t *)(v3 + 56);
    int64_t * v11 = (int64_t *)(v3 - 16);
    int32_t * v12 = (int32_t *)v7;
    int64_t * v13 = (int64_t *)(v3 + 24);
    int64_t * v14 = (int64_t *)(v3 + 32);
    int64_t * v15 = (int64_t *)(v3 + 40);
    int64_t * v16 = (int64_t *)v7;
    int64_t v17 = 0; // 0x10c0
    int64_t v18; // 0x10c0
    int64_t v19; // 0x10c0
    int64_t v20; // 0x10c0
    int32_t v21; // 0x10c0
    uint32_t v22; // 0x1168
    uint64_t v23; // 0x1168
    int64_t v24; // 0x1186
    int64_t v25; // 0x1186
    while (true) {
      lab_0x1160:
        // 0x1160
        v22 = *(int32_t *)(*v6 + 4 * v17);
        v23 = (int64_t)v22;
        int64_t v26 = v23; // 0x116e
        int64_t v27 = 0; // 0x116e
        if (v22 == 0) {
            // 0x1340
            *v8 = 0;
            v19 = 0;
            v20 = 0;
            goto lab_0x11b3;
        } else {
            while (true) {
                // 0x1180
                v24 = v26 % 2 + v27;
                v25 = v24 & 0xffffffff;
                uint32_t v28 = (int32_t)v26; // 0x1189
                int64_t v29 = v28 / 2; // 0x1189
                v26 = v29;
                v27 = v25;
                v21 = v22;
                v18 = v29;
                if (v28 < 2) {
                    goto lab_0x1190;
                }
            }
            goto lab_0x119b;
        }
    }
  lab_0x1274:
    // 0x1274
    libmin_printf("\nTotal bit count over %d numbers:\n", 100);
    libmin_printf("Naive         : %llu\n", *v9);
    libmin_printf("Kernighan     : %llu\n", *v10);
    libmin_printf("Built-in      : %llu\n", *v13);
    libmin_printf("Table Lookup  : %llu\n", *v14);
    libmin_printf("Parallel      : %llu\n", *v15);
    libmin_free(*v6);
    libmin_success();
    // UNREACHABLE
  lab_0x1190:;
    int32_t v30 = v21;
    int64_t v31 = v18 + 1; // 0x1193
    int64_t v32 = v31 & 0xffffffff; // 0x1193
    int32_t v33 = v30 - 1 & v30; // 0x1197
    v21 = v33;
    v18 = v32;
    if (v33 != 0) {
        goto lab_0x1190;
    } else {
        goto lab_0x119b;
    }
  lab_0x11b3:;
    int64_t v34 = v19;
    int64_t v35 = __popcountdi2(v23); // 0x11b5
    int32_t v36 = *(int32_t *)((v23 / 0x400000 & 1020) + (int64_t)&popcount_table); // 0x11cc
    int32_t v37 = *(int32_t *)((4 * v23 & 1020) + (int64_t)&popcount_table); // 0x11d0
    int32_t v38 = *(int32_t *)((v23 / 64 & 1020) + (int64_t)&popcount_table); // 0x11dd
    int32_t v39 = *(int32_t *)((v23 / 0x4000 & 1020) + (int64_t)&popcount_table); // 0x11ef
    uint32_t v40 = v37 + v36 + v38 + v39; // 0x11ef
    uint64_t v41 = v23 - (v23 / 2 & 0x55555555); // 0x11f5
    uint32_t v42 = (int32_t)((v41 / 4 & 0x33333333) + (v41 & 0x33333333)); // 0x1209
    uint32_t v43 = 0x1010101 * (v42 / 16 + v42 & 0xf0f0f0f) / 0x1000000; // 0x121c
    int64_t v44 = v43; // 0x121c
    int32_t v45 = v35; // 0x121f
    int32_t v46 = v20; // 0x121f
    int64_t v47; // 0x10c0
    if (v45 != v46) {
        goto lab_0x1310;
    } else {
        // 0x1228
        v47 = v35 & 0xffffffff;
        if (v43 == v46 == v40 == v46 == *v8 == 0) {
            goto lab_0x1245;
        } else {
            goto lab_0x1310;
        }
    }
  lab_0x119b:
    // 0x119b
    *v8 = (char)((int32_t)v31 != (int32_t)v24);
    *v9 = *v9 + v25;
    *v10 = *v10 + v32;
    v19 = v32;
    v20 = v25;
    goto lab_0x11b3;
  lab_0x1310:
    // 0x1310
    *v11 = v44;
    *v12 = v45;
    libmin_printf("Mismatch for value 0x%08X: naive=%u, kernighan=%u, builtin=%u, table=%u, parallel=%u\n", v22, v46, (int32_t)v34, v45, v40);
    v47 = (int64_t)*v12;
    goto lab_0x1245;
  lab_0x1245:;
    int64_t v48 = v47;
    int64_t v49 = v17 + 1; // 0x1248
    *v13 = (0x100000000 * v48 >> 32) + *v13;
    *v14 = *v14 + (int64_t)v40;
    *v15 = *v15 + v44;
    if (v17 < 5) {
        // 0x1350
        *v16 = v49;
        *v11 = v44;
        libmin_printf("Value 0x%08X: naive=%2u, kernighan=%2u, builtin=%2u, table=%2u, parallel=%2u\n", v22, v46, (int32_t)v34, (int32_t)v48, v40);
        v17 = *v16;
    } else {
        // 0x126a
        v17 = v49;
        if (v49 == 100) {
            // break -> 0x1274
            goto lab_0x1274;
        }
    }
    // 0x1160
    goto lab_0x1160;
}

// Address range: 0x13a0 - 0x13c6
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x13a0
    int64_t v1; // 0x13a0
    __libc_start_main(0x10c0, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x13d0 - 0x13f9
int64_t deregister_tm_clones(void) {
    // 0x13d0
    return 0x5230;
}

// Address range: 0x1400 - 0x1439
int64_t register_tm_clones(void) {
    // 0x1400
    return 0;
}

// Address range: 0x1440 - 0x1479
int64_t __do_global_dtors_aux(void) {
    // 0x1440
    if (g11 != 0) {
        // 0x1478
        int64_t result; // 0x1440
        return result;
    }
    // 0x144d
    if (*(int64_t *)0x4ff8 != 0) {
        // 0x145b
        __cxa_finalize((int64_t *)*(int64_t *)0x5008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1467
    g11 = 1;
    return result2;
}

// Address range: 0x1480 - 0x1489
int64_t frame_dummy(void) {
    // 0x1480
    return register_tm_clones();
}

// Address range: 0x1490 - 0x14b1
int64_t count_bits_naive(int64_t a1) {
    int64_t result = 0; // 0x1498
    if ((int32_t)a1 == 0) {
        // 0x14ab
        return 0;
    }
    result = a1 % 2 + result & 0xffffffff;
    uint32_t v1 = (int32_t)a1; // 0x14a7
    int64_t v2 = v1 / 2; // 0x14a9
    while (v1 >= 2) {
        // 0x14a0
        result = v2 % 2 + result & 0xffffffff;
        v1 = (int32_t)v2;
        v2 = v1 / 2;
    }
    // 0x14ab
    return result;
}

// Address range: 0x14c0 - 0x14df
int64_t count_bits_kernighan(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    // 0x14c0
    if ((int32_t)a1 == 0) {
        // 0x14db
        return 0;
    }
    int64_t result = 0; // 0x14c9
    int32_t v1 = a1;
    result = result + 1 & 0xffffffff;
    uint32_t v2 = v1 - 1 & v1; // 0x14d7
    while (v2 != 0) {
        // 0x14d0
        v1 = v2;
        result = result + 1 & 0xffffffff;
        v2 = v1 - 1 & v1;
    }
    // 0x14db
    return result;
}

// Address range: 0x14e0 - 0x14f4
int64_t count_bits_builtin(int64_t a1) {
    // 0x14e0
    return __popcountdi2(a1 & 0xffffffff);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/bit-kernels/bit-kernels.c
// Address range: 0x1500 - 0x1551
// Line range:    44 - 45
void init_popcount_table(void) {
    // 0x1500
    while (true) {
        // 0x1544
        popcount_table[0] = 0;
    }
  lab_0x1550:;
}

// Address range: 0x1560 - 0x158e
int64_t count_bits_table(uint64_t a1) {
    int32_t v1 = *(int32_t *)((a1 / 0x400000 & 1020) + (int64_t)&popcount_table); // 0x1576
    int32_t v2 = *(int32_t *)((4 * a1 & 1020) + (int64_t)&popcount_table); // 0x1579
    int32_t v3 = *(int32_t *)((a1 / 64 & 1020) + (int64_t)&popcount_table); // 0x1587
    int32_t v4 = *(int32_t *)((a1 / 0x4000 & 1020) + (int64_t)&popcount_table); // 0x158a
    return v2 + v1 + v3 + v4;
}

// Address range: 0x1590 - 0x15c8
int64_t count_bits_parallel(uint64_t a1) {
    uint64_t v1 = a1 - (a1 / 2 & 0x55555555); // 0x159d
    uint32_t v2 = (int32_t)((v1 / 4 & 0x33333333) + (v1 & 0x33333333)); // 0x15b2
    return 0x1010101 * (v2 / 16 + v2 & 0xf0f0f0f) / 0x1000000;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x15d0 - 0x15e1
// Line range:    124 - 127
void libtarg_success(void) {
    // 0x15d0
    exit(0);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x15f0 - 0x15ff
// Line range:    162 - 165
void libtarg_fail(int32_t code) {
    // 0x15f0
    exit(code);
    // UNREACHABLE
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1600 - 0x1614
// Line range:    188 - 191
void libtarg_putc(char c) {
    // 0x1600
    fputc((int32_t)c, g10);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libtarg.c
// Address range: 0x1620 - 0x1629
// Line range:    230 - 236
char * libtarg_sbrk(int64_t inc) {
    // 0x1620
    return (char *)sbrk(inc);
}

// Address range: 0x1630 - 0x16b8
int64_t libmin_free_part_0(int64_t a1) {
    char * v1 = libtarg_sbrk(0); // 0x1636
    int64_t v2 = *(int64_t *)(a1 - 24); // 0x163b
    int64_t result = v2 + a1; // 0x1642
    if (result != (int64_t)v1) {
        // 0x164b
        *(int32_t *)(a1 - 16) = 1;
        return result;
    }
    // 0x1658
    if (head == tail) {
        // 0x16a0
        *(int64_t *)&tail = 0;
        *(int64_t *)&head = 0;
        // 0x1690
        return (int64_t)libtarg_sbrk(-24 - v2);
    }
    int64_t v3 = (int64_t)head;
    while (v3 != 0) {
        int64_t * v4 = (int64_t *)(v3 + 16);
        int64_t v5 = *v4; // 0x1678
        if (v5 == (int64_t)tail) {
            // 0x1681
            *v4 = 0;
            *(int64_t *)&tail = v3;
            return (int64_t)libtarg_sbrk(-24 - v2);
        }
        v3 = v5;
    }
  lab_0x1690:
    // 0x1690
    return (int64_t)libtarg_sbrk(-24 - v2);
}

// Address range: 0x16c0 - 0x1764
int64_t libmin_malloc(uint64_t a1) {
    if (a1 == 0) {
        // 0x173d
        return 0;
    }
    // 0x16cd
    if (head != NULL) {
        int64_t v1 = (int64_t)head;
        int32_t * v2 = (int32_t *)(v1 + 8);
        if (*v2 != 0) {
            // 0x16e7
            if (*(int64_t *)v1 >= a1) {
                // 0x1748
                *v2 = 0;
                return v1 + 24;
            }
        }
        int64_t v3 = *(int64_t *)(v1 + 16); // 0x16ec
        while (v3 != 0) {
            // 0x16e0
            v1 = v3;
            v2 = (int32_t *)(v1 + 8);
            if (*v2 != 0) {
                // 0x16e7
                if (*(int64_t *)v1 >= a1) {
                    // 0x1748
                    *v2 = 0;
                    return v1 + 24;
                }
            }
            // 0x16ec
            v3 = *(int64_t *)(v1 + 16);
        }
    }
    char * v4 = libtarg_sbrk(a1 + 24); // 0x16f9
    if (v4 == (char *)-1) {
        // 0x173d
        return 0;
    }
    int64_t v5 = (int64_t)v4; // 0x16f9
    *(int64_t *)v4 = a1;
    *(int32_t *)(v5 + 8) = 0;
    *(int64_t *)(v5 + 16) = 0;
    if (head == NULL) {
        // 0x175b
        *(int64_t *)&head = v5;
    }
    // 0x1720
    if (tail != NULL) {
        // 0x172c
        g12 = v5;
    }
    // 0x1730
    *(int64_t *)&tail = v5;
    return v5 + 24;
}

// Address range: 0x1770 - 0x1781
int64_t libmin_free(int64_t a1) {
    // 0x1770
    if (a1 == 0) {
        // 0x1780
        int64_t result; // 0x1770
        return result;
    }
    // 0x1779
    return libmin_free_part_0(a1);
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_malloc.c
// Address range: 0x1790 - 0x17ef
// Line range:    102 - 117
char * libmin_calloc(uint64_t num, uint64_t nsize) {
    // 0x1790
    if (num == 0 || nsize == 0) {
        // 0x17ce
        return NULL;
    }
    uint128_t v1 = (int128_t)nsize * (int128_t)num; // 0x17a9
    if (v1 > 0xffffffffffffffff) {
        // 0x17ce
        return NULL;
    }
    int64_t v2 = v1; // 0x17a9
    int64_t v3 = libmin_malloc(v2); // 0x17b4
    char * result = (char *)v3;
    if (v3 != 0) {
        // 0x17c1
        libmin_memset(result, 0, v2);
    }
    // 0x17ce
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_malloc.c
// Address range: 0x17f0 - 0x185c
// Line range:    120 - 123
char * libmin_realloc(char * block, uint64_t size) {
    if (block == NULL || size == 0) {
        // 0x1850
        return (char *)libmin_malloc(size);
    }
    int64_t v1 = (int64_t)block;
    int64_t * v2 = (int64_t *)(v1 - 24); // 0x180e
    if (*v2 >= size) {
        // 0x1814
        return (char *)v1;
    }
    int64_t v3 = libmin_malloc(size); // 0x1820
    if (v3 == 0) {
        // 0x1814
        return (char *)0;
    }
    char * result = (char *)v3; // 0x1837
    libmin_memcpy(result, (int32_t *)block, *v2);
    libmin_free_part_0(v1);
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_memcpy.c
// Address range: 0x1860 - 0x1883
// Line range:    5 - 11
char * libmin_memcpy(char * dest, int32_t * src, int64_t n) {
    // 0x1860
    if (n == 0) {
        // 0x1882
        return dest;
    }
    int64_t v1 = 0; // 0x186a
    char v2 = *(char *)(v1 + (int64_t)src); // 0x1870
    *(char *)(v1 + (int64_t)dest) = v2;
    v1++;
    while (v1 != n) {
        // 0x1870
        v2 = *(char *)(v1 + (int64_t)src);
        *(char *)(v1 + (int64_t)dest) = v2;
        v1++;
    }
    // 0x1882
    return dest;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_memset.c
// Address range: 0x1890 - 0x18f2
// Line range:    5 - 37
char * libmin_memset(char * dest, uint32_t c, uint64_t n) {
    if (n == 0) {
        // 0x18ec
        return dest;
    }
    int64_t v1 = (int64_t)dest;
    char v2 = c; // 0x189e
    int64_t v3 = v1 + n;
    *(char *)(v3 - 1) = v2;
    *dest = v2;
    if (n < 3) {
        // 0x18ec
        return dest;
    }
    // 0x18ac
    *(char *)(v3 - 2) = v2;
    *(char *)(v1 + 1) = v2;
    *(char *)(v3 - 3) = v2;
    *(char *)(v1 + 2) = v2;
    if (n < 7) {
        // 0x18ec
        return dest;
    }
    // 0x18c4
    *(char *)(v3 - 4) = v2;
    *(char *)(v1 + 3) = v2;
    if (n >= 9) {
        uint64_t v4 = -v1 % 4; // 0x18da
        memset((int64_t *)(v4 + v1), c % 256, (int32_t)(n - v4) & -4);
    }
    // 0x18ec
    return dest;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1900 - 0x1b48
// Line range:    426 - 483
void fmtint(char * buffer, int64_t * currlen, uint64_t maxlen, int64_t value, int32_t base, int32_t min, int32_t max, uint32_t flags) {
    int64_t v1 = flags; // 0x190f
    int64_t v2 = value; // 0x192f
    int64_t v3 = 0; // 0x192f
    int32_t v4 = 0; // 0x192f
    if ((flags & 64) == 0) {
        if (value < 0) {
            // 0x1b10
            v2 = -value;
            v3 = 45;
            v4 = -1;
        } else {
            // 0x193a
            v2 = value;
            v3 = 43;
            v4 = -1;
            if ((v1 & 2) == 0) {
                uint32_t v5 = 8 * flags & 32; // 0x1b33
                v2 = value;
                v3 = v5;
                v4 = v5 != 0;
            }
        }
    }
    int64_t v6 = (int64_t)currlen;
    int64_t v7 = (int64_t)buffer;
    uint32_t v8 = max > 0 ? max : 0; // 0x1927
    uint64_t v9 = (int64_t)base; // 0x1962
    int64_t v10; // bp-89, 0x1900
    int64_t v11 = &v10; // 0x1965
    int64_t v12 = (v1 & 32) == 0 ? (int64_t)"0123456789abcdef" : (int64_t)"0123456789ABCDEF"; // 0x197d
    uint64_t v13 = v2; // 0x1981
    int64_t v14 = 1;
    *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
    int32_t v15 = v14;
    int32_t v16 = v15 - 19; // 0x19a8
    int64_t v17 = v14 + 1; // 0x19b4
    while (v13 >= v9 == (v16 == 0 || v16 < 0 != (18 - v15 & v15) < 0)) {
        // 0x1988
        v13 /= v9;
        v14 = v17;
        *(char *)(v14 + v11) = *(char *)(v13 % v9 + v12);
        v15 = v14;
        v16 = v15 - 19;
        v17 = v14 + 1;
    }
    int64_t v18 = v15 == 20 ? 19 : v14 & 0xffffffff; // 0x19c6
    int32_t v19 = v18; // 0x19ca
    int32_t v20 = v8 - v19; // 0x19ca
    int64_t v21 = 0x100000000 * v18 >> 32; // 0x19d0
    int64_t v22; // bp-48, 0x1900
    int64_t v23 = (int64_t)&v22 - 40 + v21; // 0x19d7
    *(char *)v23 = 0;
    uint32_t v24 = min - (int32_t)(v20 < 0 == (v20 & v19) < 0 ? (int64_t)v8 : v18) + v4; // 0x19e3
    uint32_t v25 = v20 > 0 ? v20 : 0; // 0x19e9
    int64_t v26 = v25; // 0x19e9
    int64_t v27 = v24 >= 0 ? (int64_t)v24 : 0; // 0x19f5
    int64_t v28; // 0x1900
    int64_t v29; // 0x1900
    int64_t v30; // 0x1900
    if ((v1 & 16) == 0) {
        if (flags % 2 != 0) {
            // 0x1af0
            v29 = v6;
            v30 = -v27 & 0xffffffff;
            v28 = v26;
        } else {
            // 0x1ab4
            v29 = v6;
            v30 = v27;
            v28 = v26;
            if (v24 >= 1) {
                if (v6 < maxlen) {
                    // 0x1ac5
                    *(char *)(v6 + v7) = 32;
                }
                int64_t v31 = v6 + 1; // 0x1acc
                *currlen = v31;
                uint32_t v32 = (int32_t)v27 - 1; // 0x1ad3
                int64_t v33 = v32; // 0x1ad6
                while (v32 != 0) {
                    int64_t v34 = v31;
                    int64_t v35 = v34; // 0x1ac3
                    if (v34 < maxlen) {
                        // 0x1ac5
                        *(char *)(v34 + v7) = 32;
                        v35 = v6;
                    }
                    // 0x1acc
                    v31 = v35 + 1;
                    *currlen = v31;
                    v32 = (int32_t)v33 - 1;
                    v33 = v32;
                }
                int32_t v36 = v27; // 0x1ad8
                v29 = v31;
                v30 = v27 - (v36 >= 0 == (v36 != 0) ? v27 : 1) & 0xffffffff;
                v28 = v26;
            }
        }
    } else {
        int32_t v37 = v27; // 0x1a06
        int32_t v38 = v25 - v37; // 0x1a06
        v29 = v6;
        v30 = 0;
        v28 = v38 < 0 == (v38 & v37) < 0 ? v26 : v27;
    }
    int64_t v39 = v29; // 0x1a12
    if (v3 != 0) {
        int64_t v40 = v29; // 0x1a17
        if (v29 < maxlen) {
            // 0x1b00
            *(char *)(v29 + v7) = (char)v3;
            v40 = v6;
        }
        // 0x1a1d
        v39 = v40 + 1;
        *currlen = v39;
    }
    int64_t v41 = v39; // 0x1a27
    uint32_t v42 = v28; // 0x1a27
    if ((int32_t)v28 != 0) {
        int64_t v43 = v39; // 0x1a93
        if (v39 < maxlen) {
            // 0x1a95
            *(char *)(v39 + v7) = 48;
            v43 = v6;
        }
        int64_t v44 = v43 + 1; // 0x1a9c
        *currlen = v44;
        v41 = v44;
        while (v42 != 0) {
            // 0x1a90
            v42 = (int64_t)v42;
            int64_t v45 = v44;
            v43 = v45;
            if (v45 < maxlen) {
                // 0x1a95
                *(char *)(v45 + v7) = 48;
                v43 = v6;
            }
            // 0x1a9c
            v44 = v43 + 1;
            *currlen = v44;
            v41 = v44;
        }
    }
    int64_t v46 = v23; // 0x1a38
    v46--;
    int64_t v47 = v41; // 0x1a43
    if (v41 < maxlen) {
        // 0x1a45
        *(char *)(v41 + v7) = *(char *)v46;
        v47 = v6;
    }
    int64_t v48 = v47 + 1; // 0x1a50
    *currlen = v48;
    while (v21 + v11 - (v18 + 0xffffffff & 0xffffffff) != v46) {
        int64_t v49 = v48;
        v46--;
        v47 = v49;
        if (v49 < maxlen) {
            // 0x1a45
            *(char *)(v49 + v7) = *(char *)v46;
            v47 = v6;
        }
        // 0x1a50
        v48 = v47 + 1;
        *currlen = v48;
    }
    // 0x1a60
    if (v30 == 0) {
        // 0x1a80
        return;
    }
    uint32_t v50 = v30; // 0x1a62
    int64_t v51 = v48; // 0x1a6b
    if (v48 < maxlen) {
        // 0x1a6d
        *(char *)(v48 + v7) = 32;
        v51 = v6;
    }
    int64_t v52 = v51 + 1; // 0x1a74
    *currlen = v52;
    while (v50 != 0) {
        // 0x1a68
        v50 = (int64_t)v50;
        int64_t v53 = v52;
        v51 = v53;
        if (v53 < maxlen) {
            // 0x1a6d
            *(char *)(v53 + v7) = 32;
            v51 = v6;
        }
        // 0x1a74
        v52 = v51 + 1;
        *currlen = v52;
    }
}

// Address range: 0x1b50 - 0x1c03
int64_t my_modf_isra_0(int64_t a1) {
    // 0x1b50
    int128_t v1; // 0x1b50
    int128_t v2 = __asm_movapd(v1); // 0x1b51
    int128_t v3 = __asm_movsd(0x3ff0000000000000); // 0x1b5e
    int128_t v4 = __asm_movsd(0x3fb999999999999a); // 0x1b66
    int128_t v5 = __asm_movsd(0x4024000000000000); // 0x1b6e
    int128_t v6 = __asm_movapd(v3); // 0x1b76
    int64_t v7; // bp-8, 0x1b50
    bool v8 = &v7 < (int64_t *)32; // 0x1b7a
    int64_t result2 = 0;
    int128_t v9 = v6;
    int128_t v10; // 0x1b50
    int128_t v11 = v10;
    int128_t v12 = v2;
    int64_t v13 = __asm_cvttsd2si_3(v12); // 0x1b90
    __asm_pxor(v11, v11);
    int128_t v14 = __asm_addsd(__asm_movapd(v12), v3); // 0x1b9d
    int128_t v15 = __asm_cvtsi2sd(v13); // 0x1ba1
    __asm_comisd(v14, v15);
    while (v8) {
        int64_t v16 = result2 + 1; // 0x1b84
        int64_t result = v16 & 0xffffffff; // 0x1b84
        uint32_t v17 = (int32_t)v16; // 0x1b8b
        v8 = v17 < 100;
        int128_t v18 = __asm_mulsd(v12, v4); // 0x1b8e
        int128_t v19 = __asm_mulsd(v9, v5); // 0x1b8e
        if (v17 == 100) {
            // 0x1bc8
            *(int64_t *)a1 = 0;
            return result;
        }
        result2 = result;
        v9 = v19;
        v11 = v15;
        v12 = v18;
        v13 = __asm_cvttsd2si_3(v12);
        __asm_pxor(v11, v11);
        v14 = __asm_addsd(__asm_movapd(v12), v3);
        v15 = __asm_cvtsi2sd(v13);
        __asm_comisd(v14, v15);
    }
    // 0x1bac
    __asm_comisd(v15, __asm_subsd(__asm_movapd(v12), v3));
    if (result2 == 0) {
        // 0x1bbe
        *(int64_t *)a1 = __asm_movsd_1(v15);
        return result2;
    }
    int128_t v20 = __asm_mulsd(v15, v9); // 0x1bd5
    __asm_subsd(v1, v20);
    int64_t v21 = __asm_movsd_1(v20); // 0x1be2
    int64_t v22; // bp-16, 0x1b50
    int64_t result3 = my_modf_isra_0((int64_t)&v22); // 0x1be8
    *(int64_t *)a1 = __asm_movsd_1(__asm_addsd_2(__asm_movsd(v21), v22));
    return result3;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x1c10 - 0x2190
// Line range:    586 - 525
void fmtfp(char * buffer, int64_t * currlen, uint64_t maxlen, float128_t fvalue, int32_t min, uint32_t max, int32_t flags) {
    char iconvert[311]; // bp-704, 0x1c10
    char v1[311]; // 0x1c10
    char v2[311]; // 0x2178
    char v3[311]; // 0x20b2
    char v4[311]; // 0x1d13
    char v5[311]; // 0x208c
    // 0x1c10
    int128_t v6; // 0x1c10
    int128_t v7 = v6;
    int128_t v8 = v6;
    int128_t v9 = v6;
    int3_t v10; // 0x1c10
    int3_t v11 = v10 - 1;
    float80_t v12; // 0x1c10
    __frontend_reg_store_fpr(v11, v12);
    int32_t v13 = 6; // 0x1c35
    int64_t v14 = 6; // 0x1c35
    if (max >= 0) {
        int32_t v15 = max - 16; // 0x1c41
        v14 = v15 == 0 | v15 < 0 != (15 - max & max) < 0 ? (int64_t)max : 16;
        v13 = max;
    }
    uint64_t v16 = (int64_t)flags;
    int3_t v17 = v10 - 2; // 0x1c48
    __frontend_reg_store_fpr(v17, 0.0L);
    float80_t v18 = __frontend_reg_load_fpr(v17); // 0x1c4a
    float80_t v19 = __frontend_reg_load_fpr(v11); // 0x1c4a
    float80_t v20 = __frontend_reg_load_fpr(v11);
    int32_t v21; // 0x1c10
    int32_t v22; // 0x1c10
    float64_t v23; // bp-744, 0x1c10
    int128_t v24; // 0x1c10
    if (v18 > v19) {
        // 0x20c0
        __frontend_reg_store_fpr(v11, -v20);
        float64_t v25 = __frontend_reg_load_fpr(v11); // 0x20ca
        v23 = v25;
        v22 = 45;
        v21 = 1;
        v24 = __asm_movsd((int64_t)v25);
    } else {
        float64_t v26 = v20; // 0x1c52
        v23 = v26;
        int128_t v27 = __asm_movsd((int64_t)v26); // 0x1c55
        v22 = 43;
        v21 = 1;
        v24 = v27;
        if ((v16 & 2) == 0) {
            int32_t v28 = 8 * flags & 32; // 0x1c6d
            v22 = v28;
            v21 = v28 != 0;
            v24 = v27;
        }
    }
    // 0x1c7e
    __asm_movapd(v24);
    float64_t fracpart; // bp-712, 0x1c10
    int64_t v29 = &fracpart; // 0x1c88
    my_modf_isra_0(v29);
    bool v30; // 0x1c10
    bool v31; // 0x1c10
    int128_t v32; // 0x1c10
    int128_t v33; // 0x1c10
    int128_t v34; // 0x1c10
    bool v35; // 0x1c10
    bool v36; // 0x1c10
    if (v13 == 0) {
        int128_t v37 = __asm_movsd((int64_t)fracpart); // 0x2124
        int128_t v38 = __asm_subsd(v24, v37); // 0x212a
        int64_t v39 = __asm_cvttsd2si_3(v38); // 0x212f
        v23 = __asm_movsd_1(v38);
        __frontend_reg_store_fpr(v11, (float80_t)v39);
        __frontend_reg_store_fpr(v11, (float80_t)v23 - __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v17, 0.5L);
        float80_t v40 = __frontend_reg_load_fpr(v17); // 0x214c
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v40);
        float80_t v41 = __frontend_reg_load_fpr(v17); // 0x214e
        float80_t v42 = __frontend_reg_load_fpr(v11); // 0x214e
        bool v43 = false; // 0x214e
        bool v44 = false; // 0x214e
        bool v45 = false; // 0x214e
        if (v41 <= v42) {
            v43 = true;
            v44 = false;
            v45 = false;
            if (v41 >= v42) {
                v43 = v41 != v42;
                v44 = v41 != v42;
                v45 = true;
            }
        }
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
        bool v46 = true; // 0x2152
        bool v47 = v44; // 0x2152
        bool v48 = v45; // 0x2152
        int64_t v49 = v39; // 0x2152
        if (!v43) {
            // 0x2154
            v49 = v39 + 1;
            v46 = v39 == -1;
            v47 = llvm_ctpop_i8((char)v49) % 2 == 0;
            v48 = v49 == 0;
        }
        // 0x2158
        __asm_pxor(v7, v7);
        int128_t v50 = __asm_movsd(0x3ff0000000000000); // 0x215d
        int128_t v51 = __asm_cvtsi2sd(v49); // 0x2165
        v23 = __asm_movsd_1(v51);
        __asm_comisd(v51, v50);
        __frontend_reg_store_fpr(v11, (float80_t)v23);
        int64_t v52 = __asm_movsd_1(v51); // 0x2178
        v2[0] = v52;
        iconvert = v2;
        if (v46) {
            // 0x1d40
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v47;
            v35 = v48;
            v32 = v37;
            v34 = v51;
            goto lab_0x1d48;
        } else {
            int128_t v53 = __asm_addsd(v37, v50); // 0x2185
            __frontend_reg_store_fpr(v17, 1.0L);
            v31 = v47;
            v36 = v48;
            v33 = v53;
            goto lab_0x207b;
        }
    } else {
        // 0x1c99
        __frontend_reg_store_fpr(v11, 1.0L);
        __frontend_reg_store_fpr(v17, 10.0L);
        int64_t v54 = v14 & 0xffffffff; // 0x1ca1
        __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
        uint32_t v55 = (int32_t)v54 - 1; // 0x1caa
        int64_t v56 = v55; // 0x1cad
        while (v55 != 0) {
            // 0x1ca8
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) * __frontend_reg_load_fpr(v17));
            v55 = (int32_t)v56 - 1;
            v56 = v55;
        }
        float80_t v57 = __frontend_reg_load_fpr(v17); // 0x1caf
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
        __frontend_reg_store_fpr(v11, v57);
        int128_t v58 = __asm_movsd((int64_t)fracpart); // 0x1cb5
        v23 = __asm_movsd_1(__asm_subsd(v24, v58));
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) * (float80_t)v23);
        int3_t v59 = v10 - 3;
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        float80_t v60 = __frontend_reg_load_fpr(v59); // 0x1cdc
        v23 = v60;
        __frontend_reg_store_fpr(v59, v60);
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17) - __frontend_reg_load_fpr(v59));
        __frontend_reg_store_fpr(v59, 0.5L);
        float80_t v61 = __frontend_reg_load_fpr(v59); // 0x1cee
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v61);
        float80_t v62 = __frontend_reg_load_fpr(v59); // 0x1cf0
        float80_t v63 = __frontend_reg_load_fpr(v17); // 0x1cf0
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
        if (v62 < v63) {
            // 0x20a0
            __asm_pxor(v9, v9);
            int128_t v64 = __asm_cvtsi2sd((int64_t)v23); // 0x20a4
            int64_t v65 = __asm_movsd_1(v64); // 0x20aa
            v23 = v65;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v65);
            int64_t v66 = __asm_movsd_1(v64); // 0x20b2
            v3[0] = v66;
            v1 = v3;
        } else {
            // 0x1cfa
            __asm_pxor(v9, v9);
            int128_t v67 = __asm_cvtsi2sd((int64_t)v23 + 1); // 0x1d06
            int64_t v68 = __asm_movsd_1(v67); // 0x1d0b
            v23 = v68;
            __frontend_reg_store_fpr(v17, (float80_t)(float64_t)v68);
            int64_t v69 = __asm_movsd_1(v67); // 0x1d13
            v4[0] = v69;
            v1 = v4;
        }
        // 0x1d19
        iconvert = v1;
        __frontend_reg_store_fpr(v59, 1.0L);
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
        uint32_t v70 = (int32_t)v54 - 1; // 0x1d22
        int64_t v71 = v70; // 0x1d25
        while (v70 != 0) {
            // 0x1d20
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            v70 = (int32_t)v71 - 1;
            v71 = v70;
        }
        float80_t v72 = __frontend_reg_load_fpr(v59); // 0x1d27
        __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v17));
        __frontend_reg_store_fpr(v17, v72);
        float80_t v73 = __frontend_reg_load_fpr(v59); // 0x1d29
        float80_t v74 = __frontend_reg_load_fpr(v17); // 0x1d29
        bool v75 = false; // 0x1d29
        bool v76 = false; // 0x1d29
        bool v77 = false; // 0x1d29
        if (v73 <= v74) {
            v75 = true;
            v76 = false;
            v77 = false;
            if (v73 >= v74) {
                v75 = v73 != v74;
                v76 = v73 != v74;
                v77 = true;
            }
        }
        __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v59));
        if (!v75) {
            int128_t v78 = __asm_addsd_2(v58, 0x3ff0000000000000); // 0x2060
            __frontend_reg_store_fpr(v59, 1.0L);
            __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
            uint32_t v79 = (int32_t)v54 - 1; // 0x2072
            int64_t v80 = v79; // 0x2075
            while (v79 != 0) {
                // 0x2070
                __frontend_reg_store_fpr(v59, __frontend_reg_load_fpr(v59) * __frontend_reg_load_fpr(v11));
                v79 = (int32_t)v80 - 1;
                v80 = v79;
            }
            unsigned char v81 = llvm_ctpop_i8((char)v79); // 0x2072
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v59));
            float80_t v82 = __frontend_reg_load_fpr(v17); // 0x2079
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v11));
            __frontend_reg_store_fpr(v11, v82);
            v31 = v81 % 2 == 0;
            v36 = true;
            v33 = v78;
            goto lab_0x207b;
        } else {
            // 0x1d33
            __frontend_reg_store_fpr(v17, __frontend_reg_load_fpr(v17));
            __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11));
            v30 = v76;
            v35 = v77;
            v32 = v58;
            v34 = __asm_movsd(*(int64_t *)&iconvert);
            goto lab_0x1d48;
        }
    }
  lab_0x1d48:;
    int64_t v83 = (int64_t)currlen;
    int64_t v84 = (int64_t)buffer;
    int64_t v85 = &v23; // 0x1c20
    int64_t v86; // bp-697, 0x1c10
    int64_t v87 = &v86; // 0x1d4d
    int128_t v88 = __asm_pxor(v8, v8); // 0x1d52
    int128_t v89 = __asm_movsd(0x3fb999999999999a); // 0x1d57
    int128_t v90 = __asm_movsd(0x3fa999999999999a); // 0x1d60
    int128_t v91 = __asm_movsd(0x4024000000000000); // 0x1d70
    bool v92 = v30; // 0x1d79
    bool v93 = v35; // 0x1d79
    int64_t v94 = 1;
    int128_t v95 = __asm_movapd(__asm_mulsd(v32, v89)); // 0x1d9c
    my_modf_isra_0(v29);
    int128_t v96 = __asm_movsd((int64_t)fracpart); // 0x1da6
    int128_t v97 = __asm_subsd(v95, v96); // 0x1dac
    __asm_ucomisd(v96, v88);
    int32_t v98 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v97, v90), v91)); // 0x1dc0
    char v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef"); // 0x1dc7
    *(char *)(v94 + v87) = v99;
    bool v100; // 0x1c10
    int64_t v101; // 0x1c10
    bool v102; // 0x1c10
    while (v92 || !v93) {
        int64_t v103 = v94 - 311; // 0x1d84
        unsigned char v104 = llvm_ctpop_i8((char)v103); // 0x1d84
        v92 = v104 % 2 == 0;
        v93 = false;
        v100 = v104 % 2 == 0;
        v102 = true;
        v101 = 310;
        if (v103 == 0) {
            goto lab_0x1de3;
        }
        v94++;
        v95 = __asm_movapd(__asm_mulsd(v96, v89));
        my_modf_isra_0(v29);
        v96 = __asm_movsd((int64_t)fracpart);
        v97 = __asm_subsd(v95, v96);
        __asm_ucomisd(v96, v88);
        v98 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v97, v90), v91));
        v99 = *(char *)((int64_t)v98 + (int64_t)"0123456789abcdef");
        *(char *)(v94 + v87) = v99;
    }
    int32_t v105 = (int32_t)v94 - 311; // 0x1dd4
    v100 = llvm_ctpop_i8((char)v105) % 2 == 0;
    v102 = v105 == 0;
    v101 = v105 == 0 ? 310 : v94 & 0xffffffff;
  lab_0x1de3:
    // 0x1de3
    __asm_ucomisd(v34, v88);
    int64_t v106 = 0x100000000 * v101 >> 32; // 0x1de8
    v23 = v106;
    int64_t v107 = v85 + 48; // 0x1def
    *(char *)(v106 + v107) = 0;
    int64_t v108 = v14; // 0x1df4
    int64_t v109 = 0; // 0x1df4
    if (v100 || !v102) {
        bool v110 = v100; // 0x1e0e
        bool v111 = v102; // 0x1e0e
        int64_t v112 = 1;
        int128_t v113 = __asm_mulsd(v34, v89); // 0x1e21
        __asm_movapd(v113);
        int128_t v114 = __asm_movapd(v113); // 0x1e2e
        my_modf_isra_0((int64_t)&iconvert);
        int128_t v115 = __asm_movsd(*(int64_t *)&iconvert); // 0x1e38
        int128_t v116 = __asm_subsd(v114, v115); // 0x1e41
        __asm_ucomisd(v115, v88);
        int32_t v117 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v116, v90), v91)); // 0x1e55
        char v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef"); // 0x1e5c
        int64_t v119; // bp-377, 0x1c10
        *(char *)(v112 + (int64_t)&v119) = v118;
        while (v110 || !v111) {
            int64_t v120 = v112 - 311; // 0x1e14
            v110 = llvm_ctpop_i8((char)v120) % 2 == 0;
            v111 = false;
            if (v120 == 0) {
                goto lab_0x2108;
            }
            v112++;
            v113 = __asm_mulsd(v115, v89);
            __asm_movapd(v113);
            v114 = __asm_movapd(v113);
            my_modf_isra_0((int64_t)&iconvert);
            v115 = __asm_movsd(*(int64_t *)&iconvert);
            v116 = __asm_subsd(v114, v115);
            __asm_ucomisd(v115, v88);
            v117 = __asm_cvttsd2si(__asm_mulsd(__asm_addsd(v116, v90), v91));
            v118 = *(char *)((int64_t)v117 + (int64_t)"0123456789abcdef");
            *(char *)(v112 + (int64_t)&v119) = v118;
        }
        if ((int32_t)v112 == 311) {
          lab_0x2108:
            // 0x2108
            v108 = v14 + 0xfffffeca;
            v109 = 310;
        } else {
            // 0x1e75
            v108 = v14 - v112;
            v109 = v112 & 0xffffffff;
        }
    }
    int64_t v121 = (0x100000000 * v109 >> 32) + v85;
    int64_t v122 = v121 + 368; // 0x1e85
    *(char *)v122 = 0;
    int32_t v123 = -1 - (int32_t)v14 + (int32_t)(float32_t)(float64_t)(int64_t)min - v21 - (int32_t)v101; // 0x1e9d
    int64_t v124 = v123 >= 0 ? (int64_t)v123 : 0; // 0x1ea2
    int64_t v125; // 0x1c10
    int64_t v126; // 0x1c10
    int64_t v127; // 0x1c10
    int64_t v128; // 0x1c10
    int64_t v129; // 0x1c10
    int64_t v130; // 0x1c10
    if (v16 % 2 == 0) {
        if ((v16 & 16) == 0) {
            // 0x2020
            v129 = v83;
            v125 = v124;
            if (v123 >= 1) {
                if (v83 < maxlen) {
                    // 0x2035
                    *(char *)(v83 + v84) = 32;
                }
                int64_t v131 = v83 + 1; // 0x203c
                *currlen = v131;
                uint32_t v132 = (int32_t)v124 - 1; // 0x2043
                int64_t v133 = v132; // 0x2047
                while (v132 != 0) {
                    int64_t v134 = v131;
                    int64_t v135 = v134; // 0x2033
                    if (v134 < maxlen) {
                        // 0x2035
                        *(char *)(v134 + v84) = 32;
                        v135 = v83;
                    }
                    // 0x203c
                    v131 = v135 + 1;
                    *currlen = v131;
                    v132 = (int32_t)v133 - 1;
                    v133 = v132;
                }
                int32_t v136 = v124; // 0x2049
                v129 = v131;
                v125 = v124 - (v136 >= 0 == (v136 != 0) ? v124 : 1) & 0xffffffff;
            }
            goto lab_0x1eb3;
        } else {
            // 0x1fde
            v129 = v83;
            v125 = v124;
            if (v123 < 1) {
                goto lab_0x1eb3;
            } else {
                // 0x1fe7
                v130 = v83;
                v126 = v124;
                if (v22 != 0) {
                    // 0x20f1
                    v128 = v83;
                    v127 = v124;
                    if (v83 < maxlen) {
                        // 0x20fa
                        *(char *)(v83 + v84) = (char)v22;
                        v128 = v83;
                        v127 = v124;
                    }
                    goto lab_0x2004;
                } else {
                    goto lab_0x1ff8;
                }
            }
        }
    } else {
        // 0x1eb0
        v129 = v83;
        v125 = -v124 & 0xffffffff;
        goto lab_0x1eb3;
    }
  lab_0x207b:
    // 0x207b
    __frontend_reg_store_fpr(v11, __frontend_reg_load_fpr(v11) - __frontend_reg_load_fpr(v17));
    fracpart = __asm_movsd_1(v33);
    float64_t v137 = __frontend_reg_load_fpr(v11); // 0x2083
    v23 = v137;
    int128_t v138 = __asm_movsd((int64_t)v137); // 0x2086
    int64_t v139 = __asm_movsd_1(v138); // 0x208c
    v5[0] = v139;
    iconvert = v5;
    v30 = v31;
    v35 = v36;
    v32 = v33;
    v34 = v138;
    goto lab_0x1d48;
  lab_0x1eb3:;
    int64_t v140 = v129; // 0x1eb9
    int64_t v141 = v125; // 0x1eb9
    if (v22 != 0) {
        int64_t v142 = v129; // 0x1ebe
        if (v129 < maxlen) {
            // 0x1ec0
            *(char *)(v129 + v84) = (char)v22;
            v142 = v83;
        }
        int64_t v143 = v142 + 1; // 0x1ec6
        *currlen = v143;
        v140 = v143;
        v141 = v125;
    }
    goto lab_0x1ecd;
  lab_0x1ecd:;
    int64_t v144 = v107 + (int64_t)v23 - 1;
    int64_t v145; // 0x1c10
    if (v140 < maxlen) {
        // 0x1ee5
        *(char *)(v145 + v84) = *(char *)v144;
    }
    int64_t v146 = v140 + 1; // 0x1ef0
    *currlen = v146;
    int64_t v147 = v146; // 0x1efe
    int64_t v148 = v144; // 0x1efe
    while (v87 - (v101 + 0xffffffff & 0xffffffff) + (int64_t)v23 != v144) {
        // 0x1ee0
        v144 = v148 - 1;
        if (v147 < maxlen) {
            // 0x1ee5
            *(char *)(v145 + v84) = *(char *)v144;
        }
        // 0x1ef0
        v146 = v147 + 1;
        *currlen = v146;
        v147 = v146;
        v148 = v144;
    }
    if (v13 != 0) {
        int64_t v149 = v146; // 0x1f08
        if (v146 < maxlen) {
            // 0x1f0a
            *(char *)(v146 + v84) = 46;
            v149 = v83;
        }
        int64_t v150 = v149 + 1; // 0x1f11
        *currlen = v150;
        int64_t v151 = v150; // 0x1f1a
        if ((int32_t)v108 >= 1) {
            int64_t v152 = v151;
            int64_t v153 = v152; // 0x1f23
            if (v152 < maxlen) {
                // 0x1f25
                *(char *)(v152 + v84) = 48;
                v153 = v83;
            }
            int64_t v154 = v153 + 1; // 0x1f2c
            *currlen = v154;
            uint32_t v155 = (int32_t)(v108 & 0xffffffff) - 1; // 0x1f33
            int64_t v156 = v155; // 0x1f36
            while (v155 != 0) {
                // 0x1f20
                v152 = v154;
                v153 = v152;
                if (v152 < maxlen) {
                    // 0x1f25
                    *(char *)(v152 + v84) = 48;
                    v153 = v83;
                }
                // 0x1f2c
                v154 = v153 + 1;
                *currlen = v154;
                v155 = (int32_t)v156 - 1;
                v156 = v155;
            }
        }
        if (v109 != 0) {
            int64_t v157 = v122 - 1;
            if (v83 < maxlen) {
                // 0x1f5d
                *(char *)(v83 + v84) = *(char *)v157;
            }
            int64_t v158 = v83 + 1; // 0x1f68
            *currlen = v158;
            int64_t v159 = v157; // 0x1f76
            while (367 - (v109 + 0xffffffff & 0xffffffff) + v121 != v157) {
                int64_t v160 = v158;
                v157 = v159 - 1;
                int64_t v161 = v160; // 0x1f5b
                if (v160 < maxlen) {
                    // 0x1f5d
                    *(char *)(v160 + v84) = *(char *)v157;
                    v161 = v83;
                }
                // 0x1f68
                v158 = v161 + 1;
                *currlen = v158;
                v159 = v157;
            }
        }
    }
    // 0x1f78
    if ((int32_t)v141 == 0) {
        // 0x1f99
        return;
    }
    if (v83 < maxlen) {
        // 0x1f85
        *(char *)(v83 + v84) = 32;
    }
    int64_t v162 = v83 + 1; // 0x1f8c
    *currlen = v162;
    uint32_t v163 = (int32_t)v141 + 1; // 0x1f93
    int64_t v164 = v163; // 0x1f97
    while (v163 != 0) {
        int64_t v165 = v162;
        int64_t v166 = v165; // 0x1f83
        if (v165 < maxlen) {
            // 0x1f85
            *(char *)(v165 + v84) = 32;
            v166 = v83;
        }
        // 0x1f8c
        v162 = v166 + 1;
        *currlen = v162;
        v163 = (int32_t)v164 + 1;
        v164 = v163;
    }
  lab_0x1ff8:;
    int64_t v167 = v126;
    int64_t v168 = v130;
    v128 = v168;
    v127 = v167;
    if (v168 < maxlen) {
        // 0x1ffd
        *(char *)(v168 + v84) = 48;
        v128 = v83;
        v127 = v167;
    }
    goto lab_0x2004;
  lab_0x2004:;
    int64_t v169 = v128 + 1; // 0x2004
    *currlen = v169;
    uint32_t v170 = (int32_t)v127 - 1; // 0x200b
    int64_t v171 = v170; // 0x200b
    v140 = v169;
    v141 = v171;
    v130 = v169;
    v126 = v171;
    if (v170 != 0) {
        goto lab_0x1ff8;
    } else {
        goto lab_0x1ecd;
    }
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2190 - 0x2aad
// Line range:    130 - 290
int64_t dopr(char * buffer, uint64_t maxlen, char * format, int32_t * args) {
    // 0x2190
    int64_t v1; // 0x2190
    uint64_t v2 = v1;
    int64_t v3 = (int64_t)buffer;
    int64_t v4 = (int64_t)format + 1; // 0x21a3
    int64_t v5 = v4; // 0x21a3
    int64_t result2 = 0; // 0x21b9
    int64_t v6; // 0x2190
    int64_t v7; // 0x2190
    int64_t v8; // 0x2190
    int64_t v9; // 0x2190
    char v10; // 0x2190
    int64_t v11; // 0x2190
    int64_t v12; // 0x2190
    if ((char)v2 != 0) {
        int64_t v13 = (int64_t)args;
        int64_t * v14 = (int64_t *)(v13 + 8);
        v6 = v4;
        v7 = v2 % 256;
        v12 = 0;
        while (true) {
          lab_0x220e:;
            char v15 = v7; // 0x2215
            int64_t v16 = v6; // 0x2218
            char v17 = v15; // 0x2218
            int64_t v18 = v12; // 0x2218
            int64_t v19 = v6; // 0x2218
            int64_t v20 = v12; // 0x2218
            if (v15 != 37) {
                while (true) {
                  lab_0x221a:;
                    uint64_t v21 = v18;
                    int64_t v22 = v16; // 0x221d
                    if (v21 < maxlen) {
                        // 0x221f
                        *(char *)(v21 + v3) = v17;
                        v22 = v5;
                    }
                    char v23 = *(char *)v22; // 0x2223
                    int64_t v24 = v22 + 1; // 0x2226
                    v5 = v24;
                    int64_t v25 = v21 + 1; // 0x222a
                    result2 = v25;
                    v16 = v24;
                    v17 = v23;
                    v18 = v25;
                    v19 = v24;
                    v20 = v25;
                    switch (v23) {
                        case 0: {
                            goto lab_0x21c0_3;
                        }
                        case 37: {
                            goto lab_0x2239;
                        }
                        default: {
                            goto lab_0x221a;
                        }
                    }
                }
            }
          lab_0x2239:
            // 0x2239
            v11 = v20;
            unsigned char v26 = *(char *)v19; // 0x2243
            result2 = v11;
            if (v26 == 0) {
                // break -> 0x21c0
                break;
            }
            int64_t v27 = v26; // 0x2243
            int64_t result = v27; // 0x225b
            if (v26 < 49) {
                // 0x21d3
                return result;
            }
            int64_t v28 = v19 + 1; // 0x224e
            int64_t v29 = (int64_t)g9; // 0x226a
            v5 = 0;
            int64_t v30 = v27; // 0x227a
            int64_t v31 = v28; // 0x227a
            int32_t v32 = 0; // 0x227a
            int64_t v33 = v27; // 0x227a
            int64_t v34 = v28; // 0x227a
            if ((*(char *)(2 * v27 + v29) & 4) != 0) {
                int64_t v35 = 0xffffffd0 + (0x100000000000000 * v30 >> 56); // 0x2286
                int64_t v36 = v35 & 0xffffffff; // 0x2286
                v5 = v36;
                unsigned char v37 = *(char *)v31; // 0x228a
                result2 = v11;
                if (v37 == 0) {
                    // break (via goto) -> 0x21c0
                    goto lab_0x21c0_3;
                }
                int64_t v38 = v31 + 1; // 0x2282
                int64_t v39 = v37; // 0x228a
                v31 = v38;
                while ((*(char *)(2 * v39 + v29) & 4) != 0) {
                    // 0x227c
                    v35 = 10 * v36 + 0xffffffd0 + (0x100000000000000 * v39 >> 56);
                    v36 = v35 & 0xffffffff;
                    v5 = v36;
                    v37 = *(char *)v31;
                    result2 = v11;
                    if (v37 == 0) {
                        // break (via goto) -> 0x21c0
                        goto lab_0x21c0_3;
                    }
                    // 0x2296
                    v38 = v31 + 1;
                    v39 = v37;
                    v31 = v38;
                }
                // 0x22a2
                v32 = v35;
                v33 = v39;
                v34 = v38;
            }
            int64_t v40 = v34;
            int64_t v41 = v33; // 0x22a4
            int64_t v42 = v40; // 0x22a4
            if (v33 == 42) {
                uint32_t v43 = v32; // 0x27d8
                if (v43 < 48) {
                    // 0x27df
                    v5 = *(int64_t *)(v13 + 16) + (int64_t)v43;
                    *args = v43 + 8;
                } else {
                    int64_t v44 = *v14; // 0x2833
                    v5 = v44;
                    *v14 = v44 + 8;
                }
                unsigned char v45 = *(char *)v40; // 0x27ea
                result2 = v11;
                if (v45 == 0) {
                    // break -> 0x21c0
                    break;
                }
                // 0x27fc
                v41 = v45;
                v42 = v40 + 1;
            }
            int64_t v46 = v42;
            int64_t v47 = v41; // 0x22b2
            int64_t v48 = v46; // 0x22b2
            if ((char)v41 == 46) {
                char v49 = *(char *)v46; // 0x2368
                result2 = v11;
                if (v49 == 0) {
                    // break -> 0x21c0
                    break;
                }
                int64_t v50 = v46;
                unsigned char v51 = v49;
                int64_t v52 = v50 + 1;
                int64_t v53 = v51;
                while ((*(char *)(2 * v53 + v29) & 4) != 0) {
                    char v54 = *(char *)v52; // 0x239c
                    result2 = v11;
                    if (v54 == 0) {
                        // break (via goto) -> 0x21c0
                        goto lab_0x21c0_3;
                    }
                    v50 = v52;
                    v51 = v54;
                    v52 = v50 + 1;
                    v53 = v51;
                }
                // 0x2720
                v47 = v53;
                v48 = v52;
                if (v51 == 42) {
                    uint32_t v55 = *(int32_t *)&v5; // 0x2728
                    if (v55 < 48) {
                        // 0x2733
                        *args = v55 + 8;
                    } else {
                        // 0x2804
                        *v14 = *v14 + 8;
                    }
                    unsigned char v56 = *(char *)v52; // 0x273e
                    result2 = v11;
                    if (v56 == 0) {
                        // break -> 0x21c0
                        break;
                    }
                    // 0x2751
                    v47 = v56;
                    v48 = v50 + 2;
                }
            }
            int64_t v57 = v48;
            int64_t v58 = v47;
            switch ((char)v58) {
                case 104: {
                    char v59 = *(char *)v57; // 0x27be
                    v10 = v59;
                    v9 = v57 + 1;
                    if (v59 == 0) {
                        // break -> 0x21c0
                        break;
                    }
                    goto lab_0x2776;
                }
                case 108: {
                    char v60 = *(char *)v57; // 0x2759
                    int64_t v61 = v57 + 1;
                    result2 = v11;
                    v10 = v60;
                    v9 = v61;
                    switch (v60) {
                        case 108: {
                            char v62 = *(char *)v61; // 0x2815
                            v10 = v62;
                            v9 = v57 + 2;
                            if (v62 == 0) {
                                // break -> 0x21c0
                                break;
                            }
                            goto lab_0x2776;
                        }
                        case 0: {
                            goto lab_0x21c0_3;
                        }
                        default: {
                            goto lab_0x2776;
                        }
                    }
                }
                case 76: {
                    unsigned char v63 = *(char *)v57; // 0x278f
                    if (v63 == 0) {
                        // break -> 0x21c0
                        break;
                    }
                    int64_t v64 = (int64_t)v63 + 0xffffffdb; // 0x279b
                    v8 = v57 + 1;
                    if ((char)v64 < 84) {
                        int32_t v65 = *(int32_t *)((4 * v64 & 1020) + (int64_t)&g3); // 0x27b4
                        return (int64_t)v65 + (int64_t)&g3;
                    }
                    goto lab_0x2403;
                }
                default: {
                    // 0x22d0
                    v8 = v57;
                    if ((char)(v58 + 0xffffffdb) < 84) {
                        // 0x22db
                        int64_t v66; // 0x22d0
                        int32_t v67 = *(int32_t *)((4 * v66 & 1020) + (int64_t)&g1); // 0x22e5
                        return (int64_t)v67 + (int64_t)&g1;
                    }
                    goto lab_0x2403;
                }
            }
        }
    }
  lab_0x21c0_3:
    // 0x21c0
    if (maxlen == 0) {
        // 0x21d3
        return result2;
    }
    uint64_t v68 = maxlen - 1;
    if (v68 > result2) {
        // 0x21ce
        *(char *)(result2 + v3) = 0;
        // 0x21d3
        return result2;
    }
    // 0x21e8
    *(char *)(v68 + v3) = 0;
    return result2;
  lab_0x2403:;
    unsigned char v69 = *(char *)v8; // 0x2403
    int64_t v70 = v8 + 1; // 0x2407
    v5 = v70;
    result2 = v11;
    v6 = v70;
    v7 = v69;
    v12 = v11;
    if (v69 == 0) {
        // break -> 0x21c0
        goto lab_0x21c0_3;
    }
    goto lab_0x220e;
  lab_0x2776:;
    int64_t v71 = (int64_t)v10 + 0xffffffdb; // 0x2776
    v8 = v9;
    if ((char)v71 < 84) {
        int32_t v72 = *(int32_t *)((4 * v71 & 1020) + (int64_t)&g2); // 0x2784
        return (int64_t)v72 + (int64_t)&g2;
    }
    goto lab_0x2403;
}

// Address range: 0x2aad - 0x2ab8
int64_t function_2aad(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2aad
    int64_t v1; // 0x2aad
    return v1 & 0xffffffff;
}

// Address range: 0x2ab8 - 0x2ac3
int64_t function_2ab8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2ab8
    int64_t v1; // 0x2ab8
    return v1 & 0xffffffff;
}

// Address range: 0x2ac3 - 0x2ace
int64_t function_2ac3(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2ac3
    int64_t v1; // 0x2ac3
    return v1 & 0xffffffff;
}

// Address range: 0x2ace - 0x2ad5
int64_t function_2ace(void) {
    // 0x2ace
    int64_t v1; // 0x2ace
    return v1 & 0xffffffff;
}

// Address range: 0x2ad5 - 0x2ae0
int64_t function_2ad5(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x2ad5
    int64_t v1; // 0x2ad5
    return v1 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2ae0 - 0x2bec
// Line range:    751 - 769
int32_t libmin_printf(char * fmt, ...) {
    // 0x2ae0
    int64_t v1; // 0x2ae0
    if ((char)v1 != 0) {
        // 0x2b1c
        int128_t v2; // 0x2ae0
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 8; // bp-1248, 0x2b86
    char v4; // bp-1224, 0x2ae0
    dopr(&v4, (int64_t)&g7, fmt, (int32_t *)&v3);
    if (v4 == 0) {
        // 0x2be0
        return 0;
    }
    int64_t v5 = &v4;
    libtarg_putc(v4);
    int64_t v6 = v5 + 1; // 0x2bc9
    char v7 = *(char *)v6; // 0x2bc9
    while (v7 != 0) {
        // 0x2bc0
        v5 = v6;
        libtarg_putc(v7);
        v6 = v5 + 1;
        v7 = *(char *)v6;
    }
    // 0x2bd6
    int64_t v8; // bp+1225, 0x2ae0
    return v5 + (int64_t)&v8;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_printf.c
// Address range: 0x2bf0 - 0x2c9b
// Line range:    772 - 782
int32_t libmin_snprintf(char * s, int64_t size, char * fmt, ...) {
    // 0x2bf0
    int64_t v1; // 0x2bf0
    if ((char)v1 != 0) {
        // 0x2c16
        int128_t v2; // 0x2bf0
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
        __asm_movaps(v2);
    }
    int64_t v3 = 24; // bp-224, 0x2c6a
    dopr(s, size, fmt, (int32_t *)&v3);
    *(char *)((int64_t)s - 1 + size) = 0;
    return libmin_strlen(s);
}

// Address range: 0x2ca0 - 0x2cf3
int64_t libmin_srand(void) {
    // 0x2ca0
    mt_initialized = 1;
    int64_t v1 = (int64_t)&mt;
    int64_t v2 = v1 + 4; // 0x2cc9
    int64_t v3; // 0x2ca0
    int64_t v4 = 0x10dcd * v3 + 1; // 0x2ccd
    int64_t v5 = 0x10dcd * v4; // 0x2cd2
    *(int32_t *)v1 = (int32_t)v4 / 0x10000 | (int32_t)v3 & -0x10000;
    v3 = v5 + 1 & 0xffffffff;
    while (v2 != (int64_t)&g16) {
        // 0x2cc0
        v1 = v2;
        v2 = v1 + 4;
        v4 = 0x10dcd * v3 + 1;
        v5 = 0x10dcd * v4;
        *(int32_t *)v1 = (int32_t)v4 / 0x10000 | (int32_t)v3 & -0x10000;
        v3 = v5 + 1 & 0xffffffff;
    }
    // 0x2ce8
    mti = 624;
    return v5 & 0xffffffff;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_rand.c
// Address range: 0x2d00 - 0x2ea5
// Line range:    42 - 30
int32_t libmin_rand(void) {
    // 0x2d00
    if (mt_initialized == 0) {
        // 0x2e38
        libmin_printf("ERROR: rng is not initialized, call mysrand()!\n");
        libmin_fail(1);
        // UNREACHABLE
    }
    int32_t v1 = mti; // 0x2d16
    int32_t v2; // 0x2d00
    int32_t v3; // 0x2d00
    if (v1 > 623) {
        if (v1 == 625) {
            // 0x2e55
            mt_initialized = 1;
            int64_t v4 = 0x1105; // 0x2e72
            int64_t v5 = (int64_t)&mt;
            int64_t v6 = v5 + 4; // 0x2e81
            int64_t v7 = 0x10dcd * v4 + 1; // 0x2e85
            *(int32_t *)v5 = (int32_t)v7 / 0x10000 | (int32_t)v4 & -0x10000;
            v4 = 0x10dcd * v7 + 1 & 0xffffffff;
            while (v6 != (int64_t)&g16) {
                // 0x2e78
                v5 = v6;
                v6 = v5 + 4;
                v7 = 0x10dcd * v4 + 1;
                *(int32_t *)v5 = (int32_t)v7 / 0x10000 | (int32_t)v4 & -0x10000;
                v4 = 0x10dcd * v7 + 1 & 0xffffffff;
            }
        }
        int64_t v8 = (int64_t)&mt;
        int32_t * v9 = (int32_t *)v8; // 0x2d90
        int64_t v10 = v8 + 4; // 0x2d92
        int32_t v11 = *(int32_t *)v10; // 0x2d92
        int32_t v12 = *(int32_t *)(v8 + 1588); // 0x2dad
        int32_t v13 = *(int32_t *)((int64_t)(4 * v11 & 4) | (int64_t)&g4); // 0x2db3
        *v9 = v13 ^ v12 ^ (v11 & 0x7ffffffe | *v9 & -0x80000000) / 2;
        int64_t v14 = (int64_t)&mt; // 0x2dbc
        while (v10 != (int64_t)&g13) {
            // 0x2d90
            v8 = v10;
            v9 = (int32_t *)v8;
            v10 = v8 + 4;
            v11 = *(int32_t *)v10;
            v12 = *(int32_t *)(v8 + 1588);
            v13 = *(int32_t *)((int64_t)(4 * v11 & 4) | (int64_t)&g4);
            *v9 = v13 ^ v12 ^ (v11 & 0x7ffffffe | *v9 & -0x80000000) / 2;
            v14 = (int64_t)&mt;
        }
        int32_t v15 = *(int32_t *)(v14 + (int64_t)&g5); // 0x2dc8
        int32_t v16 = *(int32_t *)(v14 + (int64_t)&g6); // 0x2dce
        int64_t v17 = v14 + 4; // 0x2dd4
        int32_t v18 = *(int32_t *)v14; // 0x2dec
        int32_t v19 = *(int32_t *)((int64_t)(4 * v16 & 4) | (int64_t)&g4); // 0x2def
        *(int32_t *)(v14 + 908) = v19 ^ v18 ^ (v16 & 0x7ffffffe | v15 & -0x80000000) / 2;
        v14 = v17;
        while (v17 != (int64_t)&g14) {
            // 0x2dc8
            v15 = *(int32_t *)(v14 + (int64_t)&g5);
            v16 = *(int32_t *)(v14 + (int64_t)&g6);
            v17 = v14 + 4;
            v18 = *(int32_t *)v14;
            v19 = *(int32_t *)((int64_t)(4 * v16 & 4) | (int64_t)&g4);
            *(int32_t *)(v14 + 908) = v19 ^ v18 ^ (v16 & 0x7ffffffe | v15 & -0x80000000) / 2;
            v14 = v17;
        }
        int32_t v20 = mt[0]; // 0x2dfd
        int32_t v21 = *(int32_t *)((int64_t)(4 * v20 & 4) | (int64_t)&g4); // 0x2e25
        g15 = v21 ^ g14 ^ (g15 & -0x80000000 | v20 & 0x7ffffffe) / 2;
        v2 = v20;
        v3 = 1;
    } else {
        // 0x2d24
        v2 = *(int32_t *)(4 * (int64_t)v1 + (int64_t)&mt);
        v3 = v1 + 1;
    }
    uint32_t v22 = v2;
    mti = v3;
    int32_t v23 = v22 / 2048 ^ v22; // 0x2d40
    int32_t v24 = 128 * v23 & -0x62d3a980 ^ v23; // 0x2d4c
    uint32_t v25 = 0x8000 * v24 & -0x103a0000 ^ v24; // 0x2d59
    return v25 / 0x40000 ^ v25 % 0x80000000;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_strlen.c
// Address range: 0x2eb0 - 0x2edb
// Line range:    5 - 15
int64_t libmin_strlen(char * str) {
    int64_t v1 = (int64_t)str;
    if (str == NULL || (char)v1 == 0) {
        // 0x2ed8
        return 0;
    }
    int64_t v2 = v1; // 0x2eb7
    v2++;
    while (*(char *)v2 != 0) {
        // 0x2ec8
        v2++;
    }
    // 0x2ed1
    return v2 - v1;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_success.c
// Address range: 0x2ee0 - 0x2ee9
// Line range:    5 - 7
void libmin_success(void) {
    // 0x2ee0
    libtarg_success();
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_ctype.c
// Address range: 0x2ef0 - 0x2f12
// Line range:    140 - 146
int32_t _isctype(uint32_t c, int32_t mask) {
    int32_t result = 0; // 0x2eff
    if (c < 256) {
        uint16_t v1 = *(int16_t *)((0x100000000 * (int64_t)c >> 31) + (int64_t)g9); // 0x2f0b
        result = (int32_t)v1 & mask;
    }
    // 0x2f11
    return result;
}

// From module:   /home/jad/asm-to-asm/bringup-bench/ackermann/libmin_fail.c
// Address range: 0x2f20 - 0x2f3f
// Line range:    5 - 8
void libmin_fail(uint32_t code) {
    // 0x2f20
    libmin_printf("ERROR: failure with termination code `%d'\n", (int64_t)code);
    libtarg_fail(code);
}

// Address range: 0x2f40 - 0x2f9e
int64_t __popcountdi2(uint64_t a1) {
    uint64_t v1 = a1 - (a1 / 2 & 0x5555555555555555); // 0x2f57
    uint64_t v2 = (v1 / 4 & 0x3333333333333333) + (v1 & 0x3333333333333333); // 0x2f71
    return 0x101010101010101 * (v2 / 16 + v2 & 0xf0f0f0f0f0f0f0f) / 0x100000000000000;
}

// Address range: 0x2fa0 - 0x2fad
int64_t _fini(void) {
    // 0x2fa0
    int64_t result; // 0x2fa0
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 48

